In [435]:
import json, re
import pandas as pd
import numpy as np
from get_electronic import get_electronic_dipole, get_electronic_quadrupole, get_stddev
from os import path
from pathlib import Path
from numpy import sign

In [377]:
with open('output.json') as f:
    data = json.load(f)

In [4]:
with open('jacob_ladder.json') as f:
    ladder = json.load(f)

In [5]:
data

{'AlF': [{'name': 'AlF',
   'method': 'BLYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-16.0501, -16.0501, -22.7295],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [-0.0, 0.0, -1.4687, 1.4687],
   'quadrupoles_elec': [-21.5879248908169,
    -21.5879248908169,
    -55.20529701953551],
   'dipoles_elec': [-0.0, 0.0, -15.467431081610002, 15.467431081610002],
   'std_dev': [0.9905903861934812, 0.9905903861934812, 1.4195179531622888],
   'spin_polarized': 0}],
 'Ar': [{'name': 'Ar',
   'method': 'B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-11.7543, -11.7543, -11.7543],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-15.8099292555267,
    -15.8099292555267,
    -15.8099292555267],
   'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
   'std_dev': [0.9371922978155639, 0.9371922978155639, 0.9371922978155639],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'B3LYP5',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-11.7593, -11.7593, -11.7593],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-15.8166544238717,
    -15.8166544238717,
    -15.8166544238717],
   'dipoles_elec': [-0.0, 0.0, -0.0, 0.0],
   'std_dev': [0.9373916062929237, 0.9373916062929237, 0.9373916062929237],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'BLYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.8321, -11.8321, -11.8321],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-15.914572874974901,
    -15.914572874974901,
    -15.914572874974901],
   'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.9402887521919028, 0.9402887521919028, 0.9402887521919028],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'BPBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.695, -11.695, -11.695],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-15.730168758955001,
    -15.730168758955001,
    -15.730168758955001],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [0.9348252587443222, 0.9348252587443222, 0.9348252587443222],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'mBEEF',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-11.5602, -11.5602, -11.5602],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-15.5488582203738,
    -15.5488582203738,
    -15.5488582203738],
   'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.9294221089943112, 0.9294221089943112, 0.9294221089943112],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'mPW91',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.7286, -11.7286, -11.7286],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [-0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-15.7753618902334,
    -15.7753618902334,
    -15.7753618902334],
   'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.936167182666566, 0.936167182666566, 0.936167182666566],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'TPSS',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-11.6976, -11.6976, -11.6976],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-15.733665846494398,
    -15.733665846494398,
    -15.733665846494398],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [0.9349291668503377, 0.9349291668503377, 0.9349291668503377],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'wB97X-V',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-11.7107, -11.7107, -11.7107],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-15.751285787558299,
    -15.751285787558299,
    -15.751285787558299],
   'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
   'std_dev': [0.9354525282675373, 0.9354525282675373, 0.9354525282675373],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcV5Zp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-11.63857633767873,
    -11.63857633767873,
    -11.63857633767873],
   'quadrupoles_mp2': [-11.656129027221297,
    -11.656129027221297,
    -11.656129027221297],
   'quadrupoles_ccsd': [-11.624722491366455,
    -11.624722491366455,
    -11.624722491366455],
   'quadrupoles_hf': [-11.6741, -11.6741, -11.6741],
   'dipoles_ccsdt': [0, 0, 0, 0],
   'dipoles_mp2': [0, 0, 0, 0],
   'dipoles_ccsd': [0, 0, 0, 0],
   'dipoles_hf': [0.0, -0.0, -0.0, 0.0],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVQZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-11.656801543824729,
    -11.656801543824729,
    -11.656801543824729],
   'quadrupoles_mp2': [-11.673547213290263,
    -11.673547213290263,
    -11.673547213290263],
   'quadrupoles_ccsd': [-11.64200617319726,
    -11.64200617319726,
    -11.64200617319726],
   'quadrupoles_hf': [-11.6767, -11.6767, -11.6767],
   'dipoles_ccsdt': [0, 0, 0, 0],
   'dipoles_mp2': [0, 0, 0, 0],
   'dipoles_ccsd': [0, 0, 0, 0],
   'dipoles_hf': [0.0, -0.0, -0.0, 0.0],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVTZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-11.709997625582261,
    -11.709997625582261,
    -11.709997625582261],
   'quadrupoles_mp2': [-11.715445011675651,
    -11.715445011675651,
    -11.715445011675651],
   'quadrupoles_ccsd': [-11.694327983905522,
    -11.694327983905522,
    -11.694327983905522],
   'quadrupoles_hf': [-11.6875, -11.6875, -11.6875],
   'dipoles_ccsdt': [0, 0, 0, 0],
   'dipoles_mp2': [0, 0, 0, 0],
   'dipoles_ccsd': [0, 0, 0, 0],
   'dipoles_hf': [0.0, 0.0, 0.0, 0.0],
   'spin_polarized': 0}],
 'Be': [{'name': 'Be',
   'method': 'PBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-7.5237, -7.5237, -7.5237],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-10.1196298154553,
    -10.1196298154553,
    -10.1196298154553],
   'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
   'std_dev': [1.5905682801639875, 1.5905682801639875, 1.5905682801639875],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'B97-D3',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-7.6035, -7.6035, -7.6035],
   'quadrupoles_off_diag': [0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-10.2269635022415,
    -10.2269635022415,
    -10.2269635022415],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [1.5989811992516907, 1.5989811992516907, 1.5989811992516907],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'CAM-B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-7.5393, -7.5393, -7.5393],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-10.1406123406917,
    -10.1406123406917,
    -10.1406123406917],
   'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
   'std_dev': [1.5922164065141788, 1.5922164065141788, 1.5922164065141788],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'M06-2X',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-7.454, -7.454, -7.454],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-10.025880968726, -10.025880968726, -10.025880968726],
   'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
   'std_dev': [1.583183578168211, 1.583183578168211, 1.583183578168211],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'M06-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.4636, -7.4636, -7.4636],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.0, 0.0],
   'quadrupoles_elec': [-10.0387932919484,
    -10.0387932919484,
    -10.0387932919484],
   'dipoles_elec': [0.0, -0.0, 0.0, 0.0],
   'std_dev': [1.584202740493495, 1.584202740493495, 1.584202740493495],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'MGGA_MS2',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.4472, -7.4472, -7.4472],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-10.0167347397768,
    -10.0167347397768,
    -10.0167347397768],
   'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
   'std_dev': [1.582461274390056, 1.582461274390056, 1.582461274390056],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'MN15',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 5,
   'quadrupoles': [-7.7815, -7.7815, -7.7815],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [-0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-10.4663794953235,
    -10.4663794953235,
    -10.4663794953235],
   'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
   'std_dev': [1.6175892166526318, 1.6175892166526318, 1.6175892166526318],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'MN15-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.9746, -7.9746, -7.9746],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, 0.0, 0.0],
   'quadrupoles_elec': [-10.7261054968074,
    -10.7261054968074,
    -10.7261054968074],
   'dipoles_elec': [-0.0, -0.0, 0.0, 0.0],
   'std_dev': [1.6375366787348153, 1.6375366787348153, 1.6375366787348153],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'revM06-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.5653, -7.5653, -7.5653],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-10.1755832160857,
    -10.1755832160857,
    -10.1755832160857],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [1.5949594991790308, 1.5949594991790308, 1.5949594991790308],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'Slater',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 1,
   'quadrupoles': [-8.0362, -8.0362, -8.0362],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, 0.0, 0.0],
   'quadrupoles_elec': [-10.808959570817798,
    -10.808959570817798,
    -10.808959570817798],
   'dipoles_elec': [-0.0, -0.0, 0.0, 0.0],
   'std_dev': [1.6438491088614093, 1.6438491088614093, 1.6438491088614093],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVQZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-7.291763778065563,
    -7.292032784797728,
    -7.292032784797728],
   'quadrupoles_mp2': [-6.1426342629446555,
    -8.443919618941246,
    -8.443919618941246],
   'quadrupoles_ccsd': [-7.288132187157441,
    -7.308173188823205,
    -7.308173188823205],
   'quadrupoles_hf': [-7.5774, -8.0435, -7.5774],
   'dipoles_ccsdt': [0, 0, 0, 0],
   'dipoles_mp2': [0, 0, 0, 0],
   'dipoles_ccsd': [0, 0, 0, 0],
   'dipoles_hf': [0.0, 0.0, -0.0, 0.0],
   'spin_polarized': 1},
  {'name': 'Be',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVTZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-7.309854480917156,
    -7.310526997747569,
    -7.310526997747569],
   'quadrupoles_mp2': [-6.190181203147525,
    -8.450981045702394,
    -8.450981045702394],
   'quadrupoles_ccsd': [-7.305348618123525,
    -7.323035810876871,
    -7.323035810876871],
   'quadrupoles_hf': [-7.9957, -7.5817, -7.6276],
   'dipoles_ccsdt': [0, 0, 0, 0],
   'dipoles_mp2': [0, 0, 0, 0],
   'dipoles_ccsd': [0, 0, 0, 0],
   'dipoles_hf': [0.0, 0.0, -0.0, 0.0],
   'spin_polarized': 1}],
 'BeH': [{'name': 'BeH',
   'method': 'B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-6.7621, -6.7621, -10.1264],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.3051, 0.3051],
   'quadrupoles_elec': [-9.0952521731449, -9.0952521731449, -20.8306479857616],
   'dipoles_elec': [-0.0, 0.0, -5.25036441547, 5.25036441547],
   'std_dev': [1.3487217780658025, 1.3487217780658025, 1.75027898843098],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'B3LYP5',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-6.7758, -6.7758, -10.1462],
   'quadrupoles_off_diag': [0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.3008, 0.3008],
   'quadrupoles_elec': [-9.1136791344102, -9.1136791344102, -20.8572796524078],
   'dipoles_elec': [0.0, -0.0, -5.25205616576, 5.25205616576],
   'std_dev': [1.3500873404643272, 1.3500873404643272, 1.7515970346371494],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'BLYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-6.8576, -6.8576, -10.1165],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [-0.0, -0.0, 0.3047, 0.3047],
   'quadrupoles_elec': [-9.2237028885344, -9.2237028885344, -20.8173321524385],
   'dipoles_elec': [-0.0, -0.0, -5.25052178759, 5.25052178759],
   'std_dev': [1.358212272697784, 1.358212272697784, 1.74949914798762],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'BPBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-6.7704, -6.7704, -10.0953],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, 0.2743, 0.2743],
   'quadrupoles_elec': [-9.106415952597601,
    -9.106415952597601,
    -20.7888174386557],
   'dipoles_elec': [0.0, 0.0, -5.26248206871, 5.26248206871],
   'std_dev': [1.3495492545733632, 1.3495492545733632, 1.7464291530982208],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'mBEEF',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-6.6953, -6.6953, -10.1219],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, 0.3205, 0.3205],
   'quadrupoles_elec': [-9.005403924055699,
    -9.005403924055699,
    -20.8245953342511],
   'dipoles_elec': [-0.0, -0.0, -5.24430558885, 5.24430558885],
   'std_dev': [1.3420435107742, 1.3420435107742, 1.7506597106463855],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'mPW91',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-6.8165, -6.8165, -10.1366],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.2666, 0.2666],
   'quadrupoles_elec': [-9.168422004738499,
    -9.168422004738499,
    -20.8443673291854],
   'dipoles_elec': [0.0, -0.0, -5.26551148202, 5.26551148202],
   'std_dev': [1.3541360348752631, 1.3541360348752631, 1.7492424129164321],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'TPSS',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-6.7357, -6.7357, -10.2449],
   'quadrupoles_off_diag': [0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.1885, 0.1885],
   'quadrupoles_elec': [-9.0597432842833, -9.0597432842833, -20.9900344755381],
   'dipoles_elec': [-0.0, 0.0, -5.29623838845, 5.29623838845],
   'std_dev': [1.346086422506616, 1.346086422506616, 1.7538532585185003],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'wB97X-V',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-6.7379, -6.7379, -10.52],
   'quadrupoles_off_diag': [0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.2334, 0.2334],
   'quadrupoles_elec': [-9.0627023583551, -9.0627023583551, -21.36005323788],
   'dipoles_elec': [-0.0, 0.0, -5.27857336798, 5.27857336798],
   'std_dev': [1.3463062325009938, 1.3463062325009938, 1.776929141955326],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'B97-D3',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-6.8874, -6.8874, -10.6129],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, 0.0744, 0.0744],
   'quadrupoles_elec': [-9.2637848918706, -9.2637848918706, -21.4850068657301],
   'dipoles_elec': [0.0, 0.0, -5.3411287856800005, 5.3411287856800005],
   'std_dev': [1.3611601589725288, 1.3611601589725288, 1.7764839163181971],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'CAM-B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-6.7598, -6.7598, -10.2436],
   'quadrupoles_off_diag': [0.0, -0.0, 0.0],
   'dipoles': [-0.0, -0.0, 0.2799, 0.2799],
   'quadrupoles_elec': [-9.0921585957062,
    -9.0921585957062,
    -20.988285931768402],
   'dipoles_elec': [-0.0, -0.0, -5.2602788590300005, 5.2602788590300005],
   'std_dev': [1.348492387498439, 1.348492387498439, 1.758077313249722],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'M06-2X',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-6.8179, -6.8179, -10.1027],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [-0.0, -0.0, 0.2513, 0.2513],
   'quadrupoles_elec': [-9.1703050518751, -9.1703050518751, -20.7987706878063],
   'dipoles_elec': [-0.0, -0.0, -5.27153096561, 5.27153096561],
   'std_dev': [1.3542750866699942, 1.3542750866699942, 1.7459073826253944],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'M06-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-6.5112, -6.5112, -10.4318],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.0918, 0.0918],
   'quadrupoles_elec': [-8.7577832255928,
    -8.7577832255928,
    -21.241421268274202],
   'dipoles_elec': [0.0, -0.0, -5.33428309846, 5.33428309846],
   'std_dev': [1.3234638813048734, 1.3234638813048734, 1.763547903141335],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'MGGA_MS2',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-6.6589, -6.6589, -10.1564],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [0.0, -0.0, 0.2607, 0.2607],
   'quadrupoles_elec': [-8.9564446985041, -8.9564446985041, -20.8709989958316],
   'dipoles_elec': [0.0, -0.0, -5.26783272079, 5.26783272079],
   'std_dev': [1.3383904287243016, 1.3383904287243016, 1.7504848860236666],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'MN15',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 5,
   'quadrupoles': [-7.1747, -7.1747, -9.8023],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.5052, 0.5052],
   'quadrupoles_elec': [-9.650213064974299,
    -9.650213064974299,
    -20.3947225736387],
   'dipoles_elec': [0.0, -0.0, -5.17163901244, 5.17163901244],
   'std_dev': [1.3892597356127687, 1.3892597356127687, 1.7346787920903641],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'MN15-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.0314, -7.0314, -10.5284],
   'quadrupoles_off_diag': [0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.4055, 0.4055],
   'quadrupoles_elec': [-9.4574697402066,
    -9.4574697402066,
    -21.371351520699598],
   'dipoles_elec': [0.0, -0.0, -5.21086401335, 5.21086401335],
   'std_dev': [1.3753159448073449, 1.3753159448073449, 1.785538057145486],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'revM06-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-6.7011, -6.7011, -10.5707],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.2853, 0.2853],
   'quadrupoles_elec': [-9.0132051193359, -9.0132051193359, -21.4282464448983],
   'dipoles_elec': [0.0, -0.0, -5.25815433541, 5.25815433541],

In [6]:
def search(key, value, molecule):
    result = []
    for d in data[molecule]:
        if d[key] == value:
            result.append(d)
    return result

In [7]:
def load():
    global data
    with open('output.json') as f:
        data = json.load(f)

In [8]:
def save(data):
    with open("output.json", 'w') as outfile:
        json.dump(data, outfile)
    print('File saved!')

In [9]:
def save_as(data, name):
    with open(name, 'w') as outfile:
        json.dump(data, outfile)
    print('File saved as {0}!'.format(name))

In [10]:
search('name', 'BeH', 'BeH')

[{'name': 'BeH',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.7621, -6.7621, -10.1264],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.3051, 0.3051],
  'quadrupoles_elec': [-9.0952521731449, -9.0952521731449, -20.8306479857616],
  'dipoles_elec': [-0.0, 0.0, -5.25036441547, 5.25036441547],
  'std_dev': [1.3487217780658025, 1.3487217780658025, 1.75027898843098],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'B3LYP5',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.7758, -6.7758, -10.1462],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.3008, 0.3008],
  'quadrupoles_elec': [-9.1136791344102, -9.1136791344102, -20.8572796524078],
  'dipoles_elec': [0.0, -0.0, -5.25205616576, 5.25205616576],
  'std_dev': [1.3500873404643272, 1.3500873404643272, 1.7515970346371494],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8576, -6.8576, -10.1165],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.3047, 0.3047],
  'quadrupoles_elec': [-9.2237028885344, -9.2237028885344, -20.8173321524385],
  'dipoles_elec': [-0.0, -0.0, -5.25052178759, 5.25052178759],
  'std_dev': [1.358212272697784, 1.358212272697784, 1.74949914798762],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'BPBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.7704, -6.7704, -10.0953],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.2743, 0.2743],
  'quadrupoles_elec': [-9.106415952597601,
   -9.106415952597601,
   -20.7888174386557],
  'dipoles_elec': [0.0, 0.0, -5.26248206871, 5.26248206871],
  'std_dev': [1.3495492545733632, 1.3495492545733632, 1.7464291530982208],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'mBEEF',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.6953, -6.6953, -10.1219],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.3205, 0.3205],
  'quadrupoles_elec': [-9.005403924055699,
   -9.005403924055699,
   -20.8245953342511],
  'dipoles_elec': [-0.0, -0.0, -5.24430558885, 5.24430558885],
  'std_dev': [1.3420435107742, 1.3420435107742, 1.7506597106463855],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'mPW91',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8165, -6.8165, -10.1366],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.2666, 0.2666],
  'quadrupoles_elec': [-9.168422004738499,
   -9.168422004738499,
   -20.8443673291854],
  'dipoles_elec': [0.0, -0.0, -5.26551148202, 5.26551148202],
  'std_dev': [1.3541360348752631, 1.3541360348752631, 1.7492424129164321],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.7357, -6.7357, -10.2449],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.1885, 0.1885],
  'quadrupoles_elec': [-9.0597432842833, -9.0597432842833, -20.9900344755381],
  'dipoles_elec': [-0.0, 0.0, -5.29623838845, 5.29623838845],
  'std_dev': [1.346086422506616, 1.346086422506616, 1.7538532585185003],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.7379, -6.7379, -10.52],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.2334, 0.2334],
  'quadrupoles_elec': [-9.0627023583551, -9.0627023583551, -21.36005323788],
  'dipoles_elec': [-0.0, 0.0, -5.27857336798, 5.27857336798],
  'std_dev': [1.3463062325009938, 1.3463062325009938, 1.776929141955326],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8874, -6.8874, -10.6129],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0744, 0.0744],
  'quadrupoles_elec': [-9.2637848918706, -9.2637848918706, -21.4850068657301],
  'dipoles_elec': [0.0, 0.0, -5.3411287856800005, 5.3411287856800005],
  'std_dev': [1.3611601589725288, 1.3611601589725288, 1.7764839163181971],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.7598, -6.7598, -10.2436],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.2799, 0.2799],
  'quadrupoles_elec': [-9.0921585957062,
   -9.0921585957062,
   -20.988285931768402],
  'dipoles_elec': [-0.0, -0.0, -5.2602788590300005, 5.2602788590300005],
  'std_dev': [1.348492387498439, 1.348492387498439, 1.758077313249722],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.8179, -6.8179, -10.1027],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.2513, 0.2513],
  'quadrupoles_elec': [-9.1703050518751, -9.1703050518751, -20.7987706878063],
  'dipoles_elec': [-0.0, -0.0, -5.27153096561, 5.27153096561],
  'std_dev': [1.3542750866699942, 1.3542750866699942, 1.7459073826253944],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.5112, -6.5112, -10.4318],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0918, 0.0918],
  'quadrupoles_elec': [-8.7577832255928,
   -8.7577832255928,
   -21.241421268274202],
  'dipoles_elec': [0.0, -0.0, -5.33428309846, 5.33428309846],
  'std_dev': [1.3234638813048734, 1.3234638813048734, 1.763547903141335],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.6589, -6.6589, -10.1564],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, 0.2607, 0.2607],
  'quadrupoles_elec': [-8.9564446985041, -8.9564446985041, -20.8709989958316],
  'dipoles_elec': [0.0, -0.0, -5.26783272079, 5.26783272079],
  'std_dev': [1.3383904287243016, 1.3383904287243016, 1.7504848860236666],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-7.1747, -7.1747, -9.8023],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.5052, 0.5052],
  'quadrupoles_elec': [-9.650213064974299,
   -9.650213064974299,
   -20.3947225736387],
  'dipoles_elec': [0.0, -0.0, -5.17163901244, 5.17163901244],
  'std_dev': [1.3892597356127687, 1.3892597356127687, 1.7346787920903641],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.0314, -7.0314, -10.5284],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.4055, 0.4055],
  'quadrupoles_elec': [-9.4574697402066,
   -9.4574697402066,
   -21.371351520699598],
  'dipoles_elec': [0.0, -0.0, -5.21086401335, 5.21086401335],
  'std_dev': [1.3753159448073449, 1.3753159448073449, 1.785538057145486],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.7011, -6.7011, -10.5707],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.2853, 0.2853],
  'quadrupoles_elec': [-9.0132051193359, -9.0132051193359, -21.4282464448983],
  'dipoles_elec': [0.0, -0.0, -5.25815433541, 5.25815433541],
  'std_dev': [1.342624677215185, 1.342624677215185, 1.783177447249718],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-7.269, -7.269, -11.0095],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.1611, 0.1611],
  'quadrupoles_elec': [-9.777049739961, -9.777049739961, -22.0184472188555],
  'dipoles_elec': [-0.0, -0.0, -5.3070183786700005, 5.3070183786700005],
  'std_dev': [1.398359734829418, 1.398359734829418, 1.8102794482922941],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.647223643879551,
   -6.647223643879551,
   -10.375522470984151],
  'quadrupoles_mp2': [-6.596583126244836,
   -6.596583126244836,
   -10.484066688069824],
  'quadrupoles_ccsd': [-6.635387347604554,
   -6.635387347604554,
   -10.393613173835746],
  'quadrupoles_hf': [-6.5797, -6.5797, -10.7231],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [0.0, 0.0, 0.2749, 0.2749],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.669752957835762,
   -6.669752957835762,
   -10.425624975154536],
  'quadrupoles_mp2': [-6.617094889697863,
   -6.617094889697863,
   -10.537061014628902],
  'quadrupoles_ccsd': [-6.657983913225887,
   -6.657983913225887,
   -10.441294617392751],
  'quadrupoles_hf': [-6.5849, -6.5849, -10.7454],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [-0.0, -0.0, 0.2712, 0.2712],
  'spin_polarized': 1}]

In [261]:
def retrieve(molecule, method, basis):
    d = data[molecule]
    for m in d:
        if m['method'] == method and m['basis'] == basis:
            return m
    return {}

In [326]:
def get_dft_species():
    result = []
    for v in data.values():
        for d in v:
            if d['method_type'] == 'dft':
                result.append(d['name'])
                break
    return result
def get_wft_species():
    result = []
    for v in data.values():
        for d in v:
            if d['method_type'] == 'wft':
                result.append(d['name'])
                break
    return result

In [264]:
retrieve('BeH', 'ccsdT', 'aug-cc-pcVTZp')

{'name': 'BeH',
 'method': 'ccsdT',
 'basis': 'aug-cc-pcVTZp',
 'method_type': 'wft',
 'quadrupoles_ccsdt': [-6.669752957835762,
  -6.669752957835762,
  -10.425624975154536],
 'quadrupoles_mp2': [-6.617094889697863,
  -6.617094889697863,
  -10.537061014628902],
 'quadrupoles_ccsd': [-6.657983913225887,
  -6.657983913225887,
  -10.441294617392751],
 'quadrupoles_hf': [-6.5849, -6.5849, -10.7454],
 'dipoles_ccsdt': [0, 0, 0.2297, 0.2297],
 'dipoles_mp2': [0, 0, 0.2824, 0.2824],
 'dipoles_ccsd': [0, 0, 0.2331, 0.2331],
 'dipoles_hf': [-0.0, -0.0, 0.2712, 0.2712],
 'spin_polarized': 1}

In [379]:
print(data.keys())

dict_keys(['AlF', 'Ar', 'Be', 'BeH', 'BeH2', 'BF', 'BH2', 'BH2F', 'BH3', 'BO', 'BS', 'C2H', 'C2H2', 'C2H3', 'CH2BH', 'CH2F', 'CH2NH', 'CH2-t', 'CH3', 'CH3BH2', 'CH3O', 'CH4', 'ClF', 'CN', 'CO', 'CO2', 'F2', 'FCN', 'FCO', 'H', 'H2', 'H2CN', 'H2O', 'HBO', 'HCCF', 'HCN', 'HCO', 'He', 'HF', 'HNC', 'HNO', 'HNS', 'HO2', 'LiBH4', 'Mg', 'Mg2', 'N', 'N2', 'N2H2', 'N2H4', 'Na', 'Na2', 'NaCl', 'Ne', 'NH2', 'NH2Cl', 'NH2F', 'NH2OH', 'NH3', 'NH3O', 'O2', 'O3', 'OF', 'OH', 'P', 'S2H2', 'SF', 'SH', 'HCl', 'NH', 'PH', 'SiO', 'LiH'])

In [13]:
def get_functionals():
    functionals = []
    for v in data.values():
        for n in v:
            if n['method_type'] == 'dft':
                functionals.append(n['method'])
    functionals = np.unique(functionals)
    return functionals

In [14]:
get_functionals()

array(['B3LYP', 'B3LYP5', 'B97-D3', 'B97M-V', 'B97M-rV', 'BLYP', 'BPBE',
       'CAM-B3LYP', 'M06-2X', 'M06-L', 'M08-HX', 'MGGA_MS2', 'MN15',
       'MN15-L', 'PBE', 'PBE0', 'SCAN', 'SCAN0', 'SPW92', 'Slater',
       'TPSS', 'mBEEF', 'mPW91', 'revM06-L', 'wB97M-V', 'wB97X-D',
       'wB97X-V'], dtype='<U9')

In [15]:
def delete(molecule, method, basis):
    for c, d in enumerate(data[molecule]):
        if d.get('method') == method and d.get('basis') == basis:
            data[molecule].pop(c)
    return

def pop(molecule, method, basis, key):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d.pop(key, None)
    return

def modify(molecule, method, basis, old, new):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d[old] = new
    return

def add(molecule, method, basis, key, value):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d[key] = value

In [16]:
from pymatgen.core.periodic_table import Element

In [17]:
def count_e(name):
    if name == 'CH2-t':
        return 8
    l = [a for a in re.split(r'([A-Z][a-z]*)', name) if a]
    c = 0
    e = 0
    prev = ''
    while c < len(l):
        if l[c].isnumeric():
            e -= Element(prev).Z
            e += Element(prev).Z * int(l[c])
        else:
            e += Element(l[c]).Z
            prev = l[c]
        c += 1
    return e

In [28]:
def get_leq20():
    leq_20 = []
    for k in data.keys():
        if count_e(k) <= 20:
            if data[k][0]['method_type'] == 'dft':
                leq_20.append(data[k][0])
    return leq_20

In [29]:
#find electron count less than 20:
leq_20 = get_leq20()

In [30]:
leq_20

[{'name': 'Ar',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-11.7543, -11.7543, -11.7543],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-15.8099292555267,
   -15.8099292555267,
   -15.8099292555267],
  'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
  'std_dev': [0.9371922978155639, 0.9371922978155639, 0.9371922978155639],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.5237, -7.5237, -7.5237],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.1196298154553,
   -10.1196298154553,
   -10.1196298154553],
  'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
  'std_dev': [1.5905682801639875, 1.5905682801639875, 1.5905682801639875],
  'spin_polarized': 0},
 {'name': 'BeH',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.7621, -6.7621, -10.1264],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.3051, 0.3051],
  'quadrupoles_elec': [-9.0952521731449, -9.0952521731449, -20.8306479857616],
  'dipoles_elec': [-0.0, 0.0, -5.25036441547, 5.25036441547],
  'std_dev': [1.3487217780658025, 1.3487217780658025, 1.75027898843098],
  'spin_polarized': 1},
 {'name': 'BeH2',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.7659, -6.7659, -11.9572],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-9.1003633010871, -9.1003633010871, -19.6015105069668],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.231554796526671, 1.231554796526671, 1.8074618717493878],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.8268, -10.8268, -12.6137],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 1.0097, 1.0097],
  'quadrupoles_elec': [-14.5624105275292,
   -14.5624105275292,
   -31.411171680665298],
  'dipoles_elec': [-0.0, -0.0, -11.00485342609, 11.00485342609],
  'std_dev': [1.0198883176788527, 1.0198883176788527, 1.275054229738255],
  'spin_polarized': 0},
 {'name': 'BH2',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8136, -9.5373, -8.4481],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.4878, -0.0, 0.4878],
  'quadrupoles_elec': [-9.1645214070984, -13.3062316113537, -13.6699309390789],
  'dipoles_elec': [0.0, -0.7860846996599999, -0.0, 0.7860846996599999],
  'std_dev': [1.144210358225794, 1.3741468011500613, 1.397443121207898],
  'spin_polarized': 1},
 {'name': 'BH2F',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0907, -12.8078, -14.0274],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.6118, 0.6118],
  'quadrupoles_elec': [-14.9173649127783,
   -19.4736982458182,
   -35.06719891853061],
  'dipoles_elec': [-0.0, -0.0, -10.968200657539999, 10.968200657539999],
  'std_dev': [0.9655751172480802, 1.1032253352618573, 1.3121632857262564],
  'spin_polarized': 0},
 {'name': 'BH3',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-9.3862, -9.3862, -7.2026],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec': [-14.749027743967801,
   -14.7489050239678,
   -9.687739504339401],
  'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
  'std_dev': [1.357802808951276, 1.3577971601074939, 1.1004396567020043],
  'spin_polarized': 0},
 {'name': 'BO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.5253, -10.5253, -13.6658],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.1838, 2.1838],
  'quadrupoles_elec': [-14.1568828763257,
   -14.1568828763257,
   -29.987523113820203],
  'dipoles_elec': [0.0, 0.0, -10.49517308914, 10.49517308914],
  'std_dev': [1.04354731109164, 1.04354731109164, 1.2864545616167182],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'B97M-rV',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.9131, -12.9131, -9.012],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, 0.7621, 0.7621],
  'quadrupoles_elec': [-17.3685542711639,
   -17.3685542711639,
   -22.095839175027997],
  'dipoles_elec': [0.0, 0.0, 6.55233323163, 6.55233323163],
  'std_dev': [1.1558731055973994, 1.1558731055973994, 1.2023469123408719],
  'spin_polarized': 1},
 {'name': 'C2H2',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-13.7879, -13.7879, -7.4406],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-18.545189724805102,
   -18.545189724805102,
   -19.8870525175614],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.150937187215119, 1.150937187215119, 1.191848879369522],
  'spin_polarized': 0},
 {'name': 'C2H3',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.648, -11.7986, -15.0047],
  'quadrupoles_off_diag': [-1.1888, -0.0, 0.0],
  'dipoles': [-0.6115, -0.3728, -0.0, 0.7162],
  'quadrupoles_elec': [-19.224254985512, -26.1068616070634, -20.1818266932443],
  'dipoles_elec': [-0.24018262845000007,
   -0.1460708158400001,
   -0.0,
   0.2811127500653679],
  'std_dev': [1.1319720002184406, 1.3192280359238897, 1.1599375469752469],
  'spin_polarized': 1},
 {'name': 'CH2BH',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-16.2715, -11.8421, -11.7112],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, -0.509, 0.509],
  'quadrupoles_elec': [-21.885715345133498,
   -17.6109017916649,
   -27.5462574443928],
  'dipoles_elec': [0.0, 0.0, -0.2000560227000007, 0.2000560227000007],
  'std_dev': [1.2503061152354848, 1.1215710216243522, 1.4026352417773915],
  'spin_polarized': 0},
 {'name': 'CH2F',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.7679, -11.9532, -10.9089],
  'quadrupoles_off_diag': [0.4934, -0.0, 0.0],
  'dipoles': [0.4286, 1.0942, 0.0, 1.1752],
  'quadrupoles_elec': [-17.278060732425097,
   -25.2723608622908,
   -16.4679713117541],
  'dipoles_elec': [0.16912422658, 0.4303914342599994, 0.0, 0.4624281465272876],
  'std_dev': [1.0080959980774788, 1.2190030782357777, 0.9842277149161492],
  'spin_polarized': 1},
 {'name': 'CH2NH',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.8913, -13.7771, -13.007],
  'quadrupoles_off_diag': [0.0, 2.1021, -0.0],
  'dipoles': [-1.3146, -0.0, 1.4334, 1.9449],
  'quadrupoles_elec': [-18.5868675381797, -18.5306633611799, -26.633103392683],
  'dipoles_elec': [-0.51770347238,
   -0.0,
   0.5635429920199994,
   0.7652434835849061],
  'std_dev': [1.0773264501431181, 1.0761814252595814, 1.2897009003711886],
  'spin_polarized': 0},
 {'name': 'CH2-t',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-8.4761, -5.9565, -7.9487],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.5897, 0.5897],
  'quadrupoles_elec': [-11.400639881810902,
   -10.028528329398501,
   -10.9444040847803],
  'dipoles_elec': [-0.0, -0.0, -0.23200584791, 0.23200584791],
  'std_dev': [1.1937671402858945, 1.119627635053196, 1.169277327326437],
  'spin_polarized': 1},
 {'name': 'CH3',
  'method': 'B3LYP5',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-7.3267, -7.3268, -9.1826],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-11.601019682662299,
   -11.600999406029201,
   -12.350906168959401],
  'dipoles_elec': [-0.0, 0.0, -0.0, 0.0],
  'std_dev': [1.1353423214883156, 1.1353413292940782, 1.1714618677798077],
  'spin_polarized': 1},
 {'name': 'CH3BH2',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-13.837, -16.559, -15.7637],
  'quadrupoles_off_diag': [-0.1929, -0.0, -0.0],
  'dipoles': [0.0997, -0.7191, 0.0, 0.726],
  'quadrupoles_elec': [-20.101880243046285,
   -36.791836181041774,
   -24.88929674448142],
  'dipoles_elec': [0.048500556209999914,
   -0.28182743123000026,
   6.819000000213293e-07,
   0.2859702868251261],
  'std_dev': [1.1208739119557907, 1.51630455409339, 1.2472293480070484],
  'spin_polarized': 0},
 {'name': 'CH3O',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-13.1049, -11.732, -13.7156],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.288],
  'dipoles': [0.0, 0.1715, -2.1155, 2.1225],
  'quadrupoles_elec': [-19.2364674088781, -17.389879004708, -28.8138552505364],
  'dipoles_elec': [0.0,
   0.06747329645000001,
   -0.8323017996500006,
   0.8350322936476525],
  'std_dev': [1.06374663637757, 1.0113942386631662, 1.3009748979242945],
  'spin_polarized': 1},
 {'name': 'CH4',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-8.4815, -8.4815, -8.4815],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-12.983430103623501,
   -12.983430103623501,
   -12.983430103623501],
  'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
  'std_dev': [1.139448555382098, 1.139448555382098, 1.139448555382098],
  'spin_polarized': 0},
 {'name': 'CN',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-11.0789, -11.0789, -9.0071],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.3668, 1.3668],
  'quadrupoles_elec': [-14.9014935154841,
   -14.9014935154841,
   -20.3535442000499],
  'dipoles_elec': [0.0, -0.0, -6.493059465959999, 6.493059465959999],
  'std_dev': [1.0706394033288311, 1.0706394033288311, 1.147253611175817],
  'spin_polarized': 1},
 {'name': 'CO',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.3071, -10.3071, -12.222],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0872, 0.0872],
  'quadrupoles_elec': [-13.8633965297499,
   -13.8633965297499,
   -26.621683422518004],
  'dipoles_elec': [0.0, 0.0, -8.991292877840001, 8.991292877840001],
  'std_dev': [0.9951093453826318, 0.9951093453826318, 1.2202797862102968],
  'spin_polarized': 0},
 {'name': 'F2',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-9.8209, -9.8209, -8.9373],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-13.2094411598821,
   -13.2094411598821,
   -29.9621238999537],
  'dipoles_elec': [-0.0, 0.0, -12.707099999999999, 12.707099999999999],
  'std_dev': [0.8566550310455617, 0.8566550310455617, 1.0799060312760165],
  'spin_polarized': 0},
 {'name': 'H',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-1.4216, -1.4216, -1.4216],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-1.9120998638503999,
   -1.9120998638503999,
   -1.9120998638503999],
  'dipoles_elec': [0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.3827869914959425, 1.3827869914959425, 1.3827869914959425],
  'spin_polarized': 1},
 {'name': 'H2',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-2.1053, -2.1053, -1.514],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-2.8316993833457,
   -2.8316993833457,
   -2.5860549348659996],
  'dipoles_elec': [0.0, -0.0, -0.7414, 0.7414],
  'std_dev': [1.1898948237860563, 1.1898948237860563, 1.074992547617424],
  'spin_polarized': 0},
 {'name': 'H2CN',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.8266, -11.1734, -13.1315],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, -2.4665, 2.4665],
  'quadrupoles_elec': [-17.2522088587954,
   -16.7740584772046,
   -24.9968387844735],
  'dipoles_elec': [0.0, 0.0, -0.9705958349500005, 0.9705958349500005],
  'std_dev': [1.0724491863268053, 1.0574831275944658, 1.2892901156015708],
  'spin_polarized': 1},
 {'name': 'H2O',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.8655, -4.5551, -6.5422],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, -1.7955, 1.7955],
  'quadrupoles_elec': [-10.5793623235195,
   -7.2734665456619005,
   -9.3498508693318],
  'dipoles_elec': [-0.0, 0.0, -0.7064041036500001, 0.7064041036500001],
  'std_dev': [1.0285602716185134, 0.8528462080388176, 0.9643624937525538],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0978, -11.0978, -19.9502],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-14.926914651828199,
   -14.926914651828199,
   -78.41511870328381],
  'dipoles_elec': [-0.0, 0.0, -25.775214040650003, 25.775214040650003],
  'std_dev': [1.0325735757883308, 1.0325735757883308, 1.4871044372089655],
  'spin_polarized': 0},
 {'name': 'HCN',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.8099, -11.8099, -12.8787],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, 2.9427, 2.9427],
  'quadrupoles_elec': [-15.884713127523101,
   -15.884713127523101,
   -27.8087331129503],
  'dipoles_elec': [0.0, 0.0, 8.185747343809998, 8.185747343809998],
  'std_dev': [1.0651865405888539, 1.0651865405888539, 1.2823682730708177],
  'spin_polarized': 0},
 {'name': 'HCO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.3297, -13.407, -11.0841],
  'quadrupoles_off_diag': [0.5232, -0.0, -0.0],
  'dipoles': [1.4642, -0.52, -0.0, 1.5538],
  'quadrupoles_elec': [-19.1890840396693,
   -26.730652720282997,
   -14.908487690562898],
  'dipoles_elec': [4.21526064526, -8.546183756, -0.0, 9.52920138830091],
  'std_dev': [1.0955827232574793, 1.2072420985460606, 0.996944922937501],
  'spin_polarized': 1},
 {'name': 'He',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-1.125, -1.125, -1.125],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-1.513162877625, -1.513162877625, -1.513162877625],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [0.8698168995900804, 0.8698168995900804, 0.8698168995900804],
  'spin_polarized': 0},
 {'name': 'HF',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-5.9524, -5.9524, -3.5354],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 1.7456, 1.7456],
  'quadrupoles_elec': [-8.0061784113556, -8.0061784113556, -5.5957542733826],
  'dipoles_elec': [0.0, 0.0, -0.2300280683199999, 0.2300280683199999],
  'std_dev': [0.8947725080351765, 0.8947725080351765, 0.7476939870134771],
  'spin_polarized': 0},
 {'name': 'HNC',
  'method': 'B3LYP5',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-12.1493, -12.1493, -10.5746],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 3.0058, 3.0058],
  'quadrupoles_elec': [-16.3412175547817,
   -16.3412175547817,
   -20.8317822962074],
  'dipoles_elec': [-0.0, 0.0, 1.1825727957400007, 1.1825727957400007],
  'std_dev': [1.0803841100930494, 1.0803841100930494, 1.2169015390587974],
  'spin_polarized': 0},
 {'name': 'HNO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.806, -11.2922, -12.1186],
  'quadrupoles_off_diag': [0.0, 0.0, -1.2948],
  'dipoles': [0.0, -1.2816, 0.7755, 1.4979],
  'quadrupoles_elec': [-14.534433827213999,
   -16.1957700370818,
   -22.6618420311434],
  'dipoles_elec': [0.0,
   -0.50442027248,
   0.3050051976500002,
   0.5894641480890191],
  'std_dev': [0.9531013137127001, 1.0056051520376998, 1.1899587117438493],
  'spin_polarized': 1},
 {'name': 'HO2',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.0634, -11.1131, -11.1327],
  'quadrupoles_off_diag': [1.6368, 0.0, 0.0],
  'dipoles': [-1.6687, -1.4033, -0.0, 2.1803],
  'quadrupoles_elec': [-14.3682973546146,
   -22.827771746963897,
   -14.9738563268763],
  'dipoles_elec': [-0.6560171416100001,
   -0.5521007399900002,
   -0.0,
   0.8574227179073697],
  'std_dev': [0.9185340670397977, 1.15834165028863, 0.9385174894755809],
  'spin_polarized': 1},
 {'name': 'LiBH4',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-14.1406, -14.1408, -4.5924],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0001, -6.0899, 6.0899],
  'quadrupoles_elec': [-20.9706856798614,
   -20.9708484365952,
   -16.4736666015156],
  'dipoles_elec': [0.0,
   -0.00013934302999998898,
   -2.3959511839700007,
   2.3959511880219364],
  'std_dev': [1.3219520187920777, 1.3219571486681267, 1.1545303793408694],
  'spin_polarized': 0},
 {'name': 'Mg',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-12.6256, -12.6256, -12.6256],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-16.9818570913264,
   -16.9818570913264,
   -16.9818570913264],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.1896027730341474, 1.1896027730341474, 1.1896027730341474],
  'spin_polarized': 0},
 {'name': 'N',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-5.5748, -5.5748, -5.5748],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-7.498293697941199,
   -7.498293697941199,
   -7.498293697941199],
  'dipoles_elec': [0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.0349805862872983, 1.0349805862872983, 1.0349805862872983],
  'spin_polarized': 1},
 {'name': 'N2',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.3096, -10.3096, -11.8471],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-13.866759113922399,
   -13.866759113922399,
   -20.151288540009897],
  'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
  'std_dev': [0.9952300205739374, 0.9952300205739374, 1.1997407023427396],
  'spin_polarized': 0},
 {'name': 'N2H2',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-11.3241, -12.364, -12.6142],
  'quadrupoles_off_diag': [-0.0, 1.836, 0.0],
  'dipoles': [1.0445, -0.0, 2.6466, 2.8452],
  'quadrupoles_elec': [-28.231719421032725,
   -16.629996283516,
   -19.6021075435635],
  'dipoles_elec': [-9.61474216605,
   -0.0,
   2.9303808381800005,
   10.051387902990928],
  'std_dev': [1.1846416979026952, 1.0194973112861798, 1.0915989362660632],
  'spin_polarized': 0},
 {'name': 'N2H4',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.7179, -14.2517, -14.5796],
  'quadrupoles_off_diag': [1.9827, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 2.6368, 2.6368],
  'quadrupoles_elec': [-18.0280594099751,
   -30.512060780487303,
   -20.932099840552397],

In [31]:
asymmetrics = []
symmetrics = []
for m in leq_20:
    if abs(m['quadrupoles'][0] - m['quadrupoles'][1]) > 0.001:
        asymmetrics.append(m)
    elif all([v == 0 for v in m['quadrupoles_off_diag']]):
        symmetrics.append(m)

In [32]:
[x['name'] for x in asymmetrics]

['BH2',
 'BH2F',
 'C2H3',
 'CH2BH',
 'CH2F',
 'CH2NH',
 'CH2-t',
 'CH3BH2',
 'CH3O',
 'H2CN',
 'H2O',
 'HCO',
 'HNO',
 'HO2',
 'N2H2',
 'N2H4',
 'NH2',
 'NH2F',
 'NH2OH',
 'OF',
 'OH',
 'SH']

In [33]:
[x['name'] for x in leq_20]

['Ar',
 'Be',
 'BeH',
 'BeH2',
 'BF',
 'BH2',
 'BH2F',
 'BH3',
 'BO',
 'C2H',
 'C2H2',
 'C2H3',
 'CH2BH',
 'CH2F',
 'CH2NH',
 'CH2-t',
 'CH3',
 'CH3BH2',
 'CH3O',
 'CH4',
 'CN',
 'CO',
 'F2',
 'H',
 'H2',
 'H2CN',
 'H2O',
 'HBO',
 'HCN',
 'HCO',
 'He',
 'HF',
 'HNC',
 'HNO',
 'HO2',
 'LiBH4',
 'Mg',
 'N',
 'N2',
 'N2H2',
 'N2H4',
 'Na',
 'Ne',
 'NH2',
 'NH2F',
 'NH2OH',
 'NH3',
 'NH3O',
 'O2',
 'OF',
 'OH',
 'P',
 'SH',
 'LiH']

In [34]:
[x['name'] for x in symmetrics]

['Ar',
 'Be',
 'BeH',
 'BeH2',
 'BF',
 'BH3',
 'BO',
 'C2H',
 'C2H2',
 'CH3',
 'CH4',
 'CN',
 'CO',
 'F2',
 'H',
 'H2',
 'HBO',
 'HCN',
 'He',
 'HF',
 'HNC',
 'LiBH4',
 'Mg',
 'N',
 'N2',
 'Na',
 'Ne',
 'NH3',
 'NH3O',
 'O2',
 'P',
 'LiH']

In [378]:
functionals_sorted = sorted(sorted(get_functionals(), key=lambda v: v.upper()), key=lambda x: ladder[x])
functionals_sorted

['Slater',
 'SPW92',
 'B97-D3',
 'BLYP',
 'BPBE',
 'mPW91',
 'PBE',
 'B97M-rV',
 'B97M-V',
 'M06-L',
 'mBEEF',
 'MGGA_MS2',
 'MN15-L',
 'revM06-L',
 'SCAN',
 'TPSS',
 'B3LYP',
 'B3LYP5',
 'M06-2X',
 'PBE0',
 'M08-HX',
 'MN15',
 'SCAN0',
 'CAM-B3LYP',
 'wB97X-D',
 'wB97X-V',
 'wB97M-V']

In [399]:
def make_dft_table(key, domain=data.keys()):
    """
    Makes a table of molecules in DOMAIN of desired KEY.
    """
    values = []
    index = pd.MultiIndex.from_product([domain], names=['molecule'])
    columns = pd.MultiIndex.from_product([functionals_sorted, ['XX','YY','ZZ']], names=['method', 'component'])
    for d in domain:
        value = data[d]
        temp = [[0, 0, 0] for i in range(len(functionals_sorted))]
        for i in value:
            if i['method_type'] == 'dft':
                method = i['method']
                ind = functionals_sorted.index(method)
                temp[ind] = i[key]
        values.append(np.ravel(temp).tolist())
    df = pd.DataFrame(values, index=index, columns=columns)
    return df

In [400]:
quadrupoles_table = make_dft_table('quadrupoles')

In [38]:
quadrupoles_table.loc[[x['name'] for x in symmetrics]]

method      Slater                      SPW92                     B97-D3  \
component       XX       YY       ZZ       XX       YY       ZZ       XX
molecule
Ar          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
Be         -8.0362  -8.0362  -8.0362   0.0000   0.0000   0.0000  -7.6035
BeH        -7.2690  -7.2690 -11.0095   0.0000   0.0000   0.0000  -6.8874
BeH2       -7.2404  -7.2404 -12.0233   0.0000   0.0000   0.0000  -6.7053
BF        -11.2366 -11.2366 -12.7018   0.0000   0.0000   0.0000 -10.6846
BH3        -9.7252  -9.7252  -7.6537   0.0000   0.0000   0.0000  -9.3741
BO        -10.8295 -10.8295 -14.0397   0.0000   0.0000   0.0000 -10.4443
C2H       -13.3165 -13.3165  -9.4623 -12.9556 -12.9556  -9.1745 -12.8255
C2H2      -14.1931 -14.1931  -7.5291   0.0000   0.0000   0.0000 -13.6475
CH3         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
CH4        -8.8456  -8.8456  -8.8456  -8.5448  -8.5448  -8.5448  -8.4336
CN        -11.3633 -11.3633  -9.4595 -11.0994 -11.0994  -9.4022 -10.9856
CO        -10.6552 -10.6552 -12.3091   0.0000   0.0000   0.0000 -10.2501
F2        -10.0467 -10.0467  -9.1387   0.0000   0.0000   0.0000  -9.6886
H          -1.5691  -1.5691  -1.5691   0.0000   0.0000   0.0000  -1.4188
H2         -2.2623  -2.2623  -1.6805   0.0000   0.0000   0.0000  -2.0771
HBO       -11.4667 -11.4667 -20.1273   0.0000   0.0000   0.0000 -11.0084
HCN         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
He         -1.1903  -1.1903  -1.1903   0.0000   0.0000   0.0000  -1.1055
HF         -6.1204  -6.1204  -3.6541  -5.9767  -5.9767  -3.5143  -5.8656
HNC       -12.5552 -12.5552 -11.0358   0.0000   0.0000   0.0000 -12.0576
LiBH4       0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
Mg          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
N          -5.7938  -5.7938  -5.7938   0.0000   0.0000   0.0000  -5.5141
N2        -10.5945 -10.5945 -12.1545 -10.3594 -10.3594 -11.8892 -10.2319
Na          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
Ne         -4.4996  -4.4996  -4.4996   0.0000   0.0000   0.0000  -4.3389
NH3         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
NH3O        0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
O2        -10.3854 -10.3854 -10.8805   0.0000   0.0000   0.0000 -10.0220
P           0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
LiH         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000

method                          BLYP  ... CAM-B3LYP  wB97X-D           \
component       YY       ZZ       XX  ...        ZZ       XX       YY
molecule                              ...
Ar          0.0000   0.0000 -11.8321  ...    0.0000   0.0000   0.0000
Be         -7.6035  -7.6035   0.0000  ...   -7.5393   0.0000   0.0000
BeH        -6.8874 -10.6129  -6.8576  ...  -10.2436   0.0000   0.0000
BeH2       -6.7053 -11.9638  -6.7659  ...  -11.9598   0.0000   0.0000
BF        -10.6846 -12.5204 -10.8268  ...  -12.7801   0.0000   0.0000
BH3        -9.3741  -7.1752  -9.4663  ...   -7.2560   0.0000   0.0000
BO        -10.4443 -13.5331   0.0000  ...  -14.0268   0.0000   0.0000
C2H       -12.8255  -9.1380   0.0000  ...   -9.0487 -12.8571 -12.8571
C2H2      -13.6475  -7.2100 -13.7879  ...   -7.0897   0.0000   0.0000
CH3         0.0000   0.0000  -7.4255  ...    0.0000  -7.1862  -7.1864
CH4        -8.4336  -8.4336   0.0000  ...   -8.5012   0.0000   0.0000
CN        -10.9856  -9.1731   0.0000  ...   -8.7796 -10.9962 -10.9962
CO        -10.2501 -12.0613   0.0000  ...  -12.2810 -10.2096 -10.2096
F2         -9.6886  -8.8209   0.0000  ...   -8.9595   0.0000   0.0000
H          -1.4188  -1.4188  -1.4483  ...   -1.4396   0.0000   0.0000
H2         -2.0771  -1.5018  -2.1214  ...   -1.5270   0.0000   0.0000
HBO       -11.0084 -20.1871   0.0000  ...  -20.9574   0.0000   0.0000
HCN         0.0000   0.0000   0.0000  ...    0.0000   0.0000   0.0000
He         -1.1055  -1.1055   0.0000  ...   -1.1210   0.0000   0.0000
HF         -5.8656  -3.4548   0.0000  ...   -3.4477   0.0000   0.0000
HNC       -12.0576 -10.5643 -12.2036  ...  -10.5487   0.0000   0.0000
LiBH4       0.0000   0.0000   0.0000  ...    0.0000   0.0000   0.0000
Mg          0.0000   0.0000 -12.6376  ...    0.0000   0.0000   0.0000
N          -5.5141  -5.5141   0.0000  ...   -5.5865   0.0000   0.0000
N2        -10.2319 -11.7609   0.0000  ...  -11.8279   0.0000   0.0000
Na          0.0000   0.0000   0.0000  ...    0.0000   0.0000   0.0000
Ne         -4.3389  -4.3389   0.0000  ...   -4.3763   0.0000   0.0000
NH3         0.0000   0.0000   0.0000  ...    0.0000   0.0000   0.0000
NH3O        0.0000   0.0000   0.0000  ...    0.0000   0.0000   0.0000
O2        -10.0220 -10.4846   0.0000  ...  -10.5785   0.0000   0.0000
P           0.0000   0.0000   0.0000  ...    0.0000   0.0000   0.0000
LiH         0.0000   0.0000   0.0000  ...    0.0000   0.0000   0.0000

method              wB97X-V                    wB97M-V
component       ZZ       XX       YY       ZZ       XX       YY       ZZ
molecule
Ar          0.0000 -11.7107 -11.7107 -11.7107   0.0000   0.0000   0.0000
Be          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
BeH         0.0000  -6.7379  -6.7379 -10.5200   0.0000   0.0000   0.0000
BeH2        0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
BF          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
BH3         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
BO          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
C2H        -8.8602 -12.9553 -12.9553  -8.9946 -13.0659 -13.0659  -9.1022
C2H2        0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
CH3        -9.0736   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
CH4         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
CN         -8.6203 -11.0999 -11.0999  -8.7630 -11.1850 -11.1850  -8.7858
CO        -12.0847 -10.3119 -10.3119 -12.2139 -10.3778 -10.3778 -12.2395
F2          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
H           0.0000  -1.4344  -1.4344  -1.4344   0.0000   0.0000   0.0000
H2          0.0000  -2.1073  -2.1073  -1.4906   0.0000   0.0000   0.0000
HBO         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
HCN         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
He          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
HF          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
HNC         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
LiBH4       0.0000 -14.1406 -14.1408  -4.5924   0.0000   0.0000   0.0000
Mg          0.0000 -12.7250 -12.7250 -12.7250   0.0000   0.0000   0.0000
N           0.0000  -5.5845  -5.5845  -5.5845   0.0000   0.0000   0.0000
N2          0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
Na          0.0000 -11.7820 -11.7820 -11.7820   0.0000   0.0000   0.0000
Ne          0.0000  -4.3610  -4.3610  -4.3610   0.0000   0.0000   0.0000
NH3         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
NH3O        0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000
O2          0.0000 -10.1137 -10.1137 -10.5182   0.0000   0.0000   0.0000
P           0.0000 -13.5362 -13.5362 -13.5362   0.0000   0.0000   0.0000
LiH         0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000

[32 rows x 81 columns]

In [265]:
make_dft_table('std_dev').loc['He']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
He         0.894705  0.894705  0.894705   0.0  0.0  0.0  0.862246  0.862246

method              BLYP  ... CAM-B3LYP wB97X-D           wB97X-V            \
component        ZZ   XX  ...        ZZ      XX   YY   ZZ      XX   YY   ZZ
molecule                  ...
He         0.862246  0.0  ...  0.868269     0.0  0.0  0.0     0.0  0.0  0.0

method    wB97M-V
component      XX   YY   ZZ
molecule
He            0.0  0.0  0.0

[1 rows x 81 columns]

In [382]:
make_dft_table('std_dev').loc['BeH2']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
BeH2       0.947195  0.947195  1.893168   0.0  0.0  0.0  0.911522  0.911522

method                  BLYP  ... CAM-B3LYP wB97X-D           wB97X-V       \
component       ZZ        XX  ...        ZZ      XX   YY   ZZ      XX   YY
molecule                      ...
BeH2       1.89122  0.915632  ...  1.891089     0.0  0.0  0.0     0.0  0.0

method         wB97M-V
component   ZZ      XX   YY   ZZ
molecule
BeH2       0.0     0.0  0.0  0.0

[1 rows x 81 columns]

In [267]:
make_dft_table('std_dev').loc['Ne']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
Ne         0.777953  0.777953  0.777953   0.0  0.0  0.0  0.763935  0.763935

method              BLYP  ... CAM-B3LYP wB97X-D             wB97X-V            \
component        ZZ   XX  ...        ZZ      XX   YY   ZZ        XX        YY
molecule                  ...
Ne         0.763935  0.0  ...   0.76722     0.0  0.0  0.0  0.765878  0.765878

method              wB97M-V
component        ZZ      XX   YY   ZZ
molecule
Ne         0.765878     0.0  0.0  0.0

[1 rows x 81 columns]

In [268]:
make_dft_table('std_dev').loc['Be']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
Be         1.643849  1.643849  1.643849   0.0  0.0  0.0  1.598981  1.598981

method              BLYP  ... CAM-B3LYP wB97X-D           wB97X-V            \
component        ZZ   XX  ...        ZZ      XX   YY   ZZ      XX   YY   ZZ
molecule                  ...
Be         1.598981  0.0  ...  1.592216     0.0  0.0  0.0     0.0  0.0  0.0

method    wB97M-V
component      XX   YY   ZZ
molecule
Be            0.0  0.0  0.0

[1 rows x 81 columns]

In [269]:
make_dft_table('std_dev').loc['N']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
N          1.055114  1.055114  1.055114   0.0  0.0  0.0  1.029331  1.029331

method              BLYP  ... CAM-B3LYP wB97X-D             wB97X-V            \
component        ZZ   XX  ...        ZZ      XX   YY   ZZ        XX        YY
molecule                  ...
N          1.029331  0.0  ...  1.036066     0.0  0.0  0.0  1.035881  1.035881

method              wB97M-V
component        ZZ      XX   YY   ZZ
molecule
N          1.035881     0.0  0.0  0.0

[1 rows x 81 columns]

In [39]:
wft_method = ['hf', 'MP2', 'CCSD', 'CCSD\(T\)']
wft_basis = ['aug-cc-pcV5Zp', 'aug-cc-pcVQZp', 'aug-cc-pcVTZp', 'CBS']

In [332]:
def make_table_wft_extrap(domain=data.keys()):
    """
    Makes a table of DOMAIN of wft method of desired KEY.
    """
    values = np.array([])
    index = pd.MultiIndex.from_product([domain, ['5Z', 'QZ', 'TZ', 'CBS']], names=['molecule', 'basis'])
    columns = pd.MultiIndex.from_product([wft_method, ['XX','YY','ZZ']], names=['method', 'component'])
    for d in domain:
        m_name = d
        for b in wft_basis:
            temp = [[0, 0, 0] for k in range(len(wft_method))]
            info = search('basis', b, m_name)
            if info != []:
                temp[0] = info[0]['std_dev_hf']
                temp[1] = info[0]['std_dev_mp2']
                temp[2] = info[0]['std_dev_ccsd']
                temp[3] = info[0]['std_dev_ccsdt']
            temp = np.ravel(temp)
            values = np.vstack((values, temp)) if values.size else temp
    df = pd.DataFrame(values, index=index, columns=columns)
    return df

In [433]:
wft_table = make_table_wft_extrap(get_wft_species())

In [434]:
wft_table.loc['HBO']

method           hf                           MP2                      \
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
QZ         0.761014  0.761014  1.596252  0.766903  0.766903  1.598887
TZ         0.761262  0.761262  1.596361  0.768257  0.768257  1.599782
CBS        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

method         CCSD                     CCSD\(T\)
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
QZ         0.763161  0.763161  1.596700  0.764286  0.764286  1.597599
TZ         0.764681  0.764681  1.597664  0.765833  0.765833  1.598608
CBS        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

In [44]:
wft_table[wft_table.index.get_level_values('basis') == '5Z']

method               hf                          MP2                        \
component            XX       YY       ZZ         XX         YY         ZZ
molecule basis
AlF      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
Ar       5Z    -11.6741 -11.6741 -11.6741 -11.656129 -11.656129 -11.656129
Be       5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
BeH      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
BeH2     5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
...                 ...      ...      ...        ...        ...        ...
HCl      5Z    -14.0726 -14.0726 -10.2180 -14.012628 -14.012628 -10.243776
NH       5Z     -6.2690  -6.2690  -5.4578  -6.372837  -5.470655   0.836409
PH       5Z    -14.4015 -14.4015 -15.4878 -14.363615 -15.049447  -0.236188
SiO      5Z    -16.0826 -16.0826 -25.3663 -16.569470 -16.569470 -23.618388
LiH      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000

method               CCSD                        CCSD\(T\)             \
component              XX         YY         ZZ         XX         YY
molecule basis
AlF      5Z      0.000000   0.000000   0.000000   0.000000   0.000000
Ar       5Z    -11.624722 -11.624722 -11.624722 -11.638576 -11.638576
Be       5Z      0.000000   0.000000   0.000000   0.000000   0.000000
BeH      5Z      0.000000   0.000000   0.000000   0.000000   0.000000
BeH2     5Z      0.000000   0.000000   0.000000   0.000000   0.000000
...                   ...        ...        ...        ...        ...
HCl      5Z    -13.947865 -13.947865 -10.236849 -13.963534 -13.963534
NH       5Z     -6.347012  -5.482626   0.822085  -6.365237  -5.506568
PH       5Z    -14.302954 -15.020933  -0.233700 -14.315261 -14.995915
SiO      5Z    -16.259103 -16.259103 -24.055255 -16.382039 -16.382039
LiH      5Z      0.000000   0.000000   0.000000   0.000000   0.000000

method
component              ZZ
molecule basis
AlF      5Z      0.000000
Ar       5Z    -11.638576
Be       5Z      0.000000
BeH      5Z      0.000000
BeH2     5Z      0.000000
...                   ...
HCl      5Z    -10.266440
NH       5Z      0.814889
PH       5Z     -0.229194
SiO      5Z    -23.702654
LiH      5Z      0.000000

[73 rows x 12 columns]

In [340]:
data['Be']

[{'name': 'Be',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.5237, -7.5237, -7.5237],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.1196298154553,
   -10.1196298154553,
   -10.1196298154553],
  'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
  'std_dev': [1.5905682801639875, 1.5905682801639875, 1.5905682801639875],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.6035, -7.6035, -7.6035],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.2269635022415,
   -10.2269635022415,
   -10.2269635022415],
  'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.5989811992516907, 1.5989811992516907, 1.5989811992516907],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-7.5393, -7.5393, -7.5393],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.1406123406917,
   -10.1406123406917,
   -10.1406123406917],
  'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
  'std_dev': [1.5922164065141788, 1.5922164065141788, 1.5922164065141788],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-7.454, -7.454, -7.454],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.025880968726, -10.025880968726, -10.025880968726],
  'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
  'std_dev': [1.583183578168211, 1.583183578168211, 1.583183578168211],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.4636, -7.4636, -7.4636],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.0387932919484,
   -10.0387932919484,
   -10.0387932919484],
  'dipoles_elec': [0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.584202740493495, 1.584202740493495, 1.584202740493495],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.4472, -7.4472, -7.4472],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.0167347397768,
   -10.0167347397768,
   -10.0167347397768],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.582461274390056, 1.582461274390056, 1.582461274390056],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-7.7815, -7.7815, -7.7815],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.4663794953235,
   -10.4663794953235,
   -10.4663794953235],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.6175892166526318, 1.6175892166526318, 1.6175892166526318],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.9746, -7.9746, -7.9746],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.7261054968074,
   -10.7261054968074,
   -10.7261054968074],
  'dipoles_elec': [-0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.6375366787348153, 1.6375366787348153, 1.6375366787348153],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.5653, -7.5653, -7.5653],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.1755832160857,
   -10.1755832160857,
   -10.1755832160857],
  'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.5949594991790308, 1.5949594991790308, 1.5949594991790308],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-8.0362, -8.0362, -8.0362],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.808959570817798,
   -10.808959570817798,
   -10.808959570817798],
  'dipoles_elec': [-0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.6438491088614093, 1.6438491088614093, 1.6438491088614093],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-7.291763778065563,
   -7.292032784797728,
   -7.292032784797728],
  'quadrupoles_mp2': [-6.1426342629446555,
   -8.443919618941246,
   -8.443919618941246],
  'quadrupoles_ccsd': [-7.288132187157441,
   -7.308173188823205,
   -7.308173188823205],
  'quadrupoles_hf': [-7.5774, -8.0435, -7.5774],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [0.0, 0.0, -0.0, 0.0],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, 0.0, -0.0, 0.0],
  'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
  'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
  'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec_hf': [-10.1918581234806,
   -10.8187783166015,
   -10.1918581234806],
  'quadrupoles_elec_mp2': [-8.26204990001356,
   -11.357356185805626,
   -11.357356185805626],
  'quadrupoles_elec_ccsd': [-9.802783175849367,
   -9.829738997850304,
   -9.829738997850304],
  'quadrupoles_elec_ccsdt': [-9.807667787892825,
   -9.808029611004775,
   -9.808029611004775],
  'std_dev_hf': [1.5962344849269954, 1.6445955670469183, 1.5962344849269954],
  'std_dev_mp2': [1.437189088117284, 1.6850338413371426, 1.6850338413371426],
  'std_dev_ccsd': [1.5654698316998452, 1.5676207288316188, 1.5676207288316188],
  'std_dev_ccsdt': [1.5658598107663426,
   1.5658886942408115,
   1.5658886942408115]},
 {'name': 'Be',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-7.309854480917156,
   -7.310526997747569,
   -7.310526997747569],
  'quadrupoles_mp2': [-6.190181203147525,
   -8.450981045702394,
   -8.450981045702394],
  'quadrupoles_ccsd': [-7.305348618123525,
   -7.323035810876871,
   -7.323035810876871],
  'quadrupoles_hf': [-7.9957, -7.5817, -7.6276],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [0.0, 0.0, -0.0, 0.0],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, 0.0, -0.0, 0.0],
  'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
  'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
  'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec_hf': [-10.754485707223301,
   -10.197641768257299,
   -10.2593788136644],
  'quadrupoles_elec_mp2': [-8.32600213544435,
   -11.366854042550546,
   -11.366854042550546],
  'quadrupoles_elec_ccsd': [-9.825939855158765,
   -9.849729724922108,
   -9.849729724922108],
  'quadrupoles_elec_ccsdt': [-9.832000392324094,
   -9.832904950103968,
   -9.832904950103968],
  'std_dev_hf': [1.6397016273718292, 1.5966873338460241, 1.6015132542118096],
  'std_dev_mp2': [1.4427406329139993, 1.6857382687231244, 1.6857382687231244],
  'std_dev_ccsd': [1.567317760950118, 1.5692139532997171, 1.5692139532997171],
  'std_dev_ccsdt': [1.5678010390610868,
   1.5678731573459608,
   1.5678731573459608]}]

In [341]:
save(data)

File saved!

In [45]:
data['BeH']

[{'name': 'BeH',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.7621, -6.7621, -10.1264],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.3051, 0.3051],
  'quadrupoles_elec': [-9.0952521731449, -9.0952521731449, -20.8306479857616],
  'dipoles_elec': [-0.0, 0.0, -5.25036441547, 5.25036441547],
  'std_dev': [1.3487217780658025, 1.3487217780658025, 1.75027898843098],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'B3LYP5',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.7758, -6.7758, -10.1462],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.3008, 0.3008],
  'quadrupoles_elec': [-9.1136791344102, -9.1136791344102, -20.8572796524078],
  'dipoles_elec': [0.0, -0.0, -5.25205616576, 5.25205616576],
  'std_dev': [1.3500873404643272, 1.3500873404643272, 1.7515970346371494],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8576, -6.8576, -10.1165],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.3047, 0.3047],
  'quadrupoles_elec': [-9.2237028885344, -9.2237028885344, -20.8173321524385],
  'dipoles_elec': [-0.0, -0.0, -5.25052178759, 5.25052178759],
  'std_dev': [1.358212272697784, 1.358212272697784, 1.74949914798762],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'BPBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.7704, -6.7704, -10.0953],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.2743, 0.2743],
  'quadrupoles_elec': [-9.106415952597601,
   -9.106415952597601,
   -20.7888174386557],
  'dipoles_elec': [0.0, 0.0, -5.26248206871, 5.26248206871],
  'std_dev': [1.3495492545733632, 1.3495492545733632, 1.7464291530982208],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'mBEEF',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.6953, -6.6953, -10.1219],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.3205, 0.3205],
  'quadrupoles_elec': [-9.005403924055699,
   -9.005403924055699,
   -20.8245953342511],
  'dipoles_elec': [-0.0, -0.0, -5.24430558885, 5.24430558885],
  'std_dev': [1.3420435107742, 1.3420435107742, 1.7506597106463855],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'mPW91',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8165, -6.8165, -10.1366],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.2666, 0.2666],
  'quadrupoles_elec': [-9.168422004738499,
   -9.168422004738499,
   -20.8443673291854],
  'dipoles_elec': [0.0, -0.0, -5.26551148202, 5.26551148202],
  'std_dev': [1.3541360348752631, 1.3541360348752631, 1.7492424129164321],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.7357, -6.7357, -10.2449],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.1885, 0.1885],
  'quadrupoles_elec': [-9.0597432842833, -9.0597432842833, -20.9900344755381],
  'dipoles_elec': [-0.0, 0.0, -5.29623838845, 5.29623838845],
  'std_dev': [1.346086422506616, 1.346086422506616, 1.7538532585185003],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.7379, -6.7379, -10.52],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.2334, 0.2334],
  'quadrupoles_elec': [-9.0627023583551, -9.0627023583551, -21.36005323788],
  'dipoles_elec': [-0.0, 0.0, -5.27857336798, 5.27857336798],
  'std_dev': [1.3463062325009938, 1.3463062325009938, 1.776929141955326],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8874, -6.8874, -10.6129],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0744, 0.0744],
  'quadrupoles_elec': [-9.2637848918706, -9.2637848918706, -21.4850068657301],
  'dipoles_elec': [0.0, 0.0, -5.3411287856800005, 5.3411287856800005],
  'std_dev': [1.3611601589725288, 1.3611601589725288, 1.7764839163181971],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.7598, -6.7598, -10.2436],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.2799, 0.2799],
  'quadrupoles_elec': [-9.0921585957062,
   -9.0921585957062,
   -20.988285931768402],
  'dipoles_elec': [-0.0, -0.0, -5.2602788590300005, 5.2602788590300005],
  'std_dev': [1.348492387498439, 1.348492387498439, 1.758077313249722],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.8179, -6.8179, -10.1027],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.2513, 0.2513],
  'quadrupoles_elec': [-9.1703050518751, -9.1703050518751, -20.7987706878063],
  'dipoles_elec': [-0.0, -0.0, -5.27153096561, 5.27153096561],
  'std_dev': [1.3542750866699942, 1.3542750866699942, 1.7459073826253944],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.5112, -6.5112, -10.4318],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0918, 0.0918],
  'quadrupoles_elec': [-8.7577832255928,
   -8.7577832255928,
   -21.241421268274202],
  'dipoles_elec': [0.0, -0.0, -5.33428309846, 5.33428309846],
  'std_dev': [1.3234638813048734, 1.3234638813048734, 1.763547903141335],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.6589, -6.6589, -10.1564],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, 0.2607, 0.2607],
  'quadrupoles_elec': [-8.9564446985041, -8.9564446985041, -20.8709989958316],
  'dipoles_elec': [0.0, -0.0, -5.26783272079, 5.26783272079],
  'std_dev': [1.3383904287243016, 1.3383904287243016, 1.7504848860236666],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-7.1747, -7.1747, -9.8023],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.5052, 0.5052],
  'quadrupoles_elec': [-9.650213064974299,
   -9.650213064974299,
   -20.3947225736387],
  'dipoles_elec': [0.0, -0.0, -5.17163901244, 5.17163901244],
  'std_dev': [1.3892597356127687, 1.3892597356127687, 1.7346787920903641],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.0314, -7.0314, -10.5284],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.4055, 0.4055],
  'quadrupoles_elec': [-9.4574697402066,
   -9.4574697402066,
   -21.371351520699598],
  'dipoles_elec': [0.0, -0.0, -5.21086401335, 5.21086401335],
  'std_dev': [1.3753159448073449, 1.3753159448073449, 1.785538057145486],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.7011, -6.7011, -10.5707],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.2853, 0.2853],
  'quadrupoles_elec': [-9.0132051193359, -9.0132051193359, -21.4282464448983],
  'dipoles_elec': [0.0, -0.0, -5.25815433541, 5.25815433541],
  'std_dev': [1.342624677215185, 1.342624677215185, 1.783177447249718],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-7.269, -7.269, -11.0095],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.1611, 0.1611],
  'quadrupoles_elec': [-9.777049739961, -9.777049739961, -22.0184472188555],
  'dipoles_elec': [-0.0, -0.0, -5.3070183786700005, 5.3070183786700005],
  'std_dev': [1.398359734829418, 1.398359734829418, 1.8102794482922941],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.647223643879551,
   -6.647223643879551,
   -10.375522470984151],
  'quadrupoles_mp2': [-6.596583126244836,
   -6.596583126244836,
   -10.484066688069824],
  'quadrupoles_ccsd': [-6.635387347604554,
   -6.635387347604554,
   -10.393613173835746],
  'quadrupoles_hf': [-6.5797, -6.5797, -10.7231],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [0.0, 0.0, 0.2749, 0.2749],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.669752957835762,
   -6.669752957835762,
   -10.425624975154536],
  'quadrupoles_mp2': [-6.617094889697863,
   -6.617094889697863,
   -10.537061014628902],
  'quadrupoles_ccsd': [-6.657983913225887,
   -6.657983913225887,
   -10.441294617392751],
  'quadrupoles_hf': [-6.5849, -6.5849, -10.7454],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [-0.0, -0.0, 0.2712, 0.2712],
  'spin_polarized': 1}]

In [162]:
quadrupoles_table.loc['CO', 'Slater']

component       XX       YY       ZZ
molecule
CO        -10.6552 -10.6552 -12.3091

In [425]:
data['HBO']

[{'name': 'HBO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0978, -11.0978, -19.9502],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-8.2509590506, -8.2509590506, -199.033869166212],
  'dipoles_elec': [-0.0, 0.0, -47.803149380650005, 47.803149380650005],
  'std_dev': [0.7676940913541018, 0.7676940913541018, 1.599319175331429],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0084, -11.0084, -20.1871],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -2.6504, 2.6504],
  'quadrupoles_elec': [-8.1844922068, -8.1844922068, -199.209998867512],
  'dipoles_elec': [-0.0, -0.0, -47.82868300712, 47.82868300712],
  'std_dev': [0.7645957011388437, 0.7645957011388437, 1.599357437857018],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-11.0795, -11.0795, -20.9574],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.8692, 2.8692],
  'quadrupoles_elec': [-8.2373534215, -8.2373534215, -199.78269920061203],
  'dipoles_elec': [-0.0, 0.0, -47.91476555676, 47.91476555676],
  'std_dev': [0.7670608758436321, 0.7670608758436321, 1.5990000549598815],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.9943, -10.9943, -20.9452],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.9066, 2.9066],
  'quadrupoles_elec': [-8.1740091811, -8.1740091811, -199.773628781212],
  'dipoles_elec': [0.0, 0.0, -47.929479849980005, 47.929479849980005],
  'std_dev': [0.764105881831831, 0.764105881831831, 1.5965456400785158],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.7705, -10.7705, -19.8658],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-8.0076190285, -8.0076190285, -198.97111970741202],
  'dipoles_elec': [0.0, -0.0, -47.803149380650005, 47.803149380650005],
  'std_dev': [0.7562888256149234, 0.7562888256149234, 1.597917307116611],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.9448, -10.9448, -20.0411],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, -2.6413, 2.6413],
  'quadrupoles_elec': [-8.1372070696, -8.1372070696, -199.10145122551202],
  'dipoles_elec': [0.0, -0.0, -47.82510279139, 47.82510279139],
  'std_dev': [0.7623838117378936, 0.7623838117378936, 1.5974786577574538],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-10.9999, -10.9999, -20.7016],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.7898, 2.7898],
  'quadrupoles_elec': [-8.1781726523, -8.1781726523, -199.59251778401202],
  'dipoles_elec': [-0.0, 0.0, -47.88352719094, 47.88352719094],
  'std_dev': [0.7643004575754223, 0.7643004575754223, 1.5995265127382026],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-11.1407, -11.1407, -20.7911],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -2.7518, 2.7518],
  'quadrupoles_elec': [-8.2828542139, -8.2828542139, -199.659058975512],
  'dipoles_elec': [0.0, -0.0, -47.868576839540005, 47.868576839540005],
  'std_dev': [0.7691764712015052, 0.7691764712015052, 1.6032909029431675],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.8551, -10.8551, -20.3839],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.6621, 2.6621],
  'quadrupoles_elec': [-8.070517182700002,
   -8.070517182700002,
   -199.35631514111202],
  'dipoles_elec': [0.0, 0.0, -47.833286141630005, 47.833286141630005],
  'std_dev': [0.7592532601510514, 0.7592532601510514, 1.6019203222123481],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-11.4667, -11.4667, -20.1273],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, -2.5652, 2.5652],
  'quadrupoles_elec': [-8.5252277159, -8.5252277159, -199.165538942912],
  'dipoles_elec': [0.0, -0.0, -47.79516274556, 47.79516274556],
  'std_dev': [0.780349176234588, 0.780349176234588, 1.6034719398444037],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-10.99948358996839,
   -10.99948358996839,
   -20.338388612318287],
  'quadrupoles_mp2': [-11.074939978926075,
   -11.074939978926075,
   -20.21229170588119],
  'quadrupoles_ccsd': [-10.967135530276206,
   -10.967135530276206,
   -20.70746585104695],
  'quadrupoles_hf': [-10.9055, -10.9055, -22.4865],
  'dipoles_ccsdt': [0, 0, -2.7215, 2.7215],
  'dipoles_mp2': [0, 0, -2.6652, 2.6652],
  'dipoles_ccsd': [0, 0, -2.8384, 2.8384],
  'dipoles_hf': [0.0, -0.0, -3.3361, 3.3361],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -48.09845816383, 48.09845816383],
  'dipoles_elec_mp2': [0.0, 0.0, -45.73736490444, 45.73736490444],
  'dipoles_elec_ccsd': [0.0, 0.0, -45.66922277648, 45.66922277648],
  'dipoles_elec_ccsdt': [0.0, 0.0, -45.71521477855, 45.71521477855],
  'quadrupoles_elec_hf': [-8.1079884235, -8.1079884235, -200.919549881312],
  'quadrupoles_elec_mp2': [-8.233963150712022,
   -8.233963150712022,
   -199.22872832142545],
  'quadrupoles_elec_ccsd': [-8.153813022643163,
   -8.153813022643163,
   -199.59687890935086],
  'quadrupoles_elec_ccsdt': [-8.177863061018929,
   -8.177863061018929,
   -199.32247847113257],
  'std_dev_hf': [0.7610138173844152, 0.7610138173844152, 1.59625202059972],
  'std_dev_mp2': [0.7669030088941227, 0.7669030088941227, 1.8861683004554883],
  'std_dev_ccsd': [0.7631613301937429, 0.7631613301937429, 1.9015010125236143],
  'std_dev_ccsdt': [0.7642859908352804,
   0.7642859908352804,
   1.8906777700976238]},
 {'name': 'HBO',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-11.044071456105497,
   -11.044071456105497,
   -20.348476364810317],
  'quadrupoles_mp2': [-11.11408045858751,
   -11.11408045858751,
   -20.24161343990222],
  'quadrupoles_ccsd': [-11.010849124503912,
   -11.010849124503912,
   -20.70531379718963],
  'quadrupoles_hf': [-10.9126, -10.9126, -22.4967],
  'dipoles_ccsdt': [0, 0, -2.7075, 2.7075],
  'dipoles_mp2': [0, 0, -2.6584, 2.6584],
  'dipoles_ccsd': [0, 0, -2.8218, 2.8218],
  'dipoles_hf': [0.0, -0.0, -3.3371, 3.3371],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -48.098851594130004, 48.098851594130004],
  'dipoles_elec_mp2': [0.0, 0.0, -45.740040230480005, 45.740040230480005],
  'dipoles_elec_ccsd': [0.0, 0.0, -45.675753719460005, 45.675753719460005],
  'dipoles_elec_ccsdt': [0.0, 0.0, -45.720722802750004, 45.720722802750004],
  'quadrupoles_elec_hf': [-8.1132671102, -8.1132671102, -200.92713334671203],
  'quadrupoles_elec_mp2': [-8.263063197109267,
   -8.263063197109267,
   -199.2505283562702],
  'quadrupoles_elec_ccsd': [-8.186313074538795,
   -8.186313074538795,
   -199.59527890680516],
  'quadrupoles_elec_ccsdt': [-8.211013113970948,
   -8.211013113970948,
   -199.3299784830921],
  'std_dev_hf': [0.761261505200414, 0.761261505200414, 1.5963612037237105],
  'std_dev_mp2': [0.768256988118897, 0.768256988118897, 1.8862500817568768],
  'std_dev_ccsd': [0.7646807491897142, 0.7646807491897142, 1.90067043334621],
  'std_dev_ccsdt': [0.7658334915059608,
   0.7658334915059608,
   1.890139835499417]}]

In [424]:
#this cell block is used to modify dipole values
modify('HBO', 'ccsdT', 'aug-cc-pcVTZp', 'dipoles_ccsd', [0, 0, -2.8218, 2.8218])

In [426]:
save(data)

File saved!

In [207]:
func = ['B3LYP', 'B3LYP5', 'B97-D3', 'B97M-V', 'B97M-rV', 'BLYP', 'BPBE',
       'CAM-B3LYP', 'M06-2X', 'M06-L', 'M08-HX', 'MGGA_MS2', 'MN15',
       'MN15-L', 'PBE', 'PBE0', 'SCAN', 'SCAN0', 'SPW92', 'Slater',
       'TPSS', 'mBEEF', 'mPW91', 'revM06-L', 'wB97M-V', 'wB97X-D',
       'wB97X-V']
mols = ['AlF',
 'Ar',
 'Be',
 'BeH',
 'BeH2',
 'BF',
 'BH2',
 'BH2F',
 'BH3',
 'BO',
 'BS',
 'C2H',
 'C2H2',
 'C2H3',
 'CH2BH',
 'CH2F',
 'CH2NH',
 'CH2-t',
 'CH3',
 'CH3BH2',
 'CH3O',
 'CH4',
 'ClF',
 'CN',
 'CO',
 'CO2',
 'F2',
 'FCN',
 'FCO',
 'H',
 'H2',
 'H2CN',
 'H2O',
 'HBO',
 'HCCF',
 'HCN',
 'HCO',
 'He',
 'HF',
 'HNC',
 'HNO',
 'HNS',
 'HO2',
 'LiBH4',
 'Mg',
 'Mg2',
 'N',
 'N2',
 'N2H2',
 'N2H4',
 'Na',
 'Na2',
 'NaCl',
 'Ne',
 'NH2',
 'NH2Cl',
 'NH2F',
 'NH2OH',
 'NH3',
 'NH3O',
 'O2',
 'O3',
 'OF',
 'OH',
 'P',
 'S2H2',
 'SF',
 'SH',
 'HCl',
 'NH',
 'PH',
 'SiO',
 'LiH']

In [370]:
#use this cell block for electronic component calculation

input_path = Path.home() / "summer/research/geometries/geometries"
ang_to_bohr = 1.88973
ang2_to_bohr2 = 3.571079
debye_to_e = 0.3934303
ea02_to_debye_ang = 1.345033669
debye_ang_to_ea02 = 0.743477

def get_electronic_dipole(string, dipole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    x = y = z = 0
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        if len(line) == 1:
            line += [0, 0, 0]
        x += charge * float(line[1])
        y += charge * float(line[2])
        z += charge * float(line[3])
    x_elec = dipole[0] * debye_to_e - x * ang_to_bohr
    y_elec = dipole[1] * debye_to_e - y * ang_to_bohr
    z_elec = dipole[2] * debye_to_e - z * ang_to_bohr
    total_elec = np.sqrt(x_elec ** 2 + y_elec ** 2 + z_elec ** 2)
    return [x_elec, y_elec, z_elec, total_elec]

def get_electronic_quadrupole(string, quadrupole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    xx = yy = zz = 0
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        if len(line) == 1:
            line += [0, 0, 0]
        xx += charge * float(line[1]) ** 2
        yy += charge * float(line[2]) ** 2
        zz += charge * float(line[3]) ** 2
    xx_elec = quadrupole[0] * debye_ang_to_ea02 - xx * ang2_to_bohr2
    yy_elec = quadrupole[1] * debye_ang_to_ea02 - yy * ang2_to_bohr2
    zz_elec = quadrupole[2] * debye_ang_to_ea02 - zz * ang2_to_bohr2
    return [xx_elec, yy_elec, zz_elec]

def get_stddev(string, dipole, quadrupole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    tote = int(re.search('molecule\s*(\d\s\d\s)', string).group(1).splitlines()[0].split()[0])
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        tote += Element(re.sub('\d+', '', line[0])).Z
    xx_std = np.sqrt((quadrupole[0]/-tote) - (dipole[0]/-tote) ** 2)
    yy_std = np.sqrt((quadrupole[1]/-tote) - (dipole[1]/-tote) ** 2)
    zz_std = np.sqrt((quadrupole[2]/-tote) - (dipole[2]/-tote) ** 2)
    return [xx_std, yy_std, zz_std]

def get_electronic_for_wft(molecule, method, basis):
    filename = input_path / "{}.xyz".format(molecule)
    with open(filename, 'r') as file:
        string = file.read()
    d = retrieve(molecule, method, basis)
    if d == {}:
        print('WFT method has not been calculated!')
        return
    add(molecule, method, basis, 'dipoles_elec_hf', get_electronic_dipole(string, d['dipoles_hf']))
    add(molecule, method, basis, 'dipoles_elec_mp2', get_electronic_dipole(string, d['dipoles_mp2']))
    add(molecule, method, basis, 'dipoles_elec_ccsd', get_electronic_dipole(string, d['dipoles_ccsd']))
    add(molecule, method, basis, 'dipoles_elec_ccsdt', get_electronic_dipole(string, d['dipoles_ccsdt']))
    add(molecule, method, basis, 'quadrupoles_elec_hf', get_electronic_quadrupole(string, d['quadrupoles_hf']))
    add(molecule, method, basis, 'quadrupoles_elec_mp2', get_electronic_quadrupole(string, d['quadrupoles_mp2']))
    add(molecule, method, basis, 'quadrupoles_elec_ccsd', get_electronic_quadrupole(string, d['quadrupoles_ccsd']))
    add(molecule, method, basis, 'quadrupoles_elec_ccsdt', get_electronic_quadrupole(string, d['quadrupoles_ccsdt']))
    add(molecule, method, basis, 'std_dev_hf', get_stddev(string, d['dipoles_elec_hf'], d['quadrupoles_elec_hf']))
    add(molecule, method, basis, 'std_dev_mp2', get_stddev(string, d['dipoles_elec_mp2'], d['quadrupoles_elec_mp2']))
    add(molecule, method, basis, 'std_dev_ccsd', get_stddev(string, d['dipoles_elec_ccsd'], d['quadrupoles_elec_ccsd']))
    add(molecule, method, basis, 'std_dev_ccsdt', get_stddev(string, d['dipoles_elec_ccsdt'], d['quadrupoles_elec_ccsdt']))
    print('Electronic part successfully calculated!')
    
def get_electronic_for_dft(molecule, method, basis):
    filename = input_path / "{}.xyz".format(molecule)
    with open(filename, 'r') as file:
        string = file.read()
    d = retrieve(molecule, method, basis)
    if d == {}:
        print('DFT method has not been calculated for {0} of method {1}!'.format(molecule, method))
        return
    add(molecule, method, basis, 'dipoles_elec', get_electronic_dipole(string, d['dipoles']))
    add(molecule, method, basis, 'quadrupoles_elec', get_electronic_quadrupole(string, d['quadrupoles']))
    add(molecule, method, basis, 'std_dev', get_stddev(string, d['dipoles_elec'], d['quadrupoles_elec']))
    print('Electronic part successfully calculated for {0} of method {1}!'.format(molecule, method))

In [432]:
get_electronic_for_wft('HBO', 'ccsdT', 'aug-cc-pcVTZp')

Electronic part successfully calculated!

In [431]:
data['HBO']

[{'name': 'HBO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0978, -11.0978, -19.9502],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-8.2509590506, -8.2509590506, -199.033869166212],
  'dipoles_elec': [-0.0, 0.0, -47.803149380650005, 47.803149380650005],
  'std_dev': [0.7676940913541018, 0.7676940913541018, 1.599319175331429],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0084, -11.0084, -20.1871],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -2.6504, 2.6504],
  'quadrupoles_elec': [-8.1844922068, -8.1844922068, -199.209998867512],
  'dipoles_elec': [-0.0, -0.0, -47.82868300712, 47.82868300712],
  'std_dev': [0.7645957011388437, 0.7645957011388437, 1.599357437857018],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-11.0795, -11.0795, -20.9574],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.8692, 2.8692],
  'quadrupoles_elec': [-8.2373534215, -8.2373534215, -199.78269920061203],
  'dipoles_elec': [-0.0, 0.0, -47.91476555676, 47.91476555676],
  'std_dev': [0.7670608758436321, 0.7670608758436321, 1.5990000549598815],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.9943, -10.9943, -20.9452],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.9066, 2.9066],
  'quadrupoles_elec': [-8.1740091811, -8.1740091811, -199.773628781212],
  'dipoles_elec': [0.0, 0.0, -47.929479849980005, 47.929479849980005],
  'std_dev': [0.764105881831831, 0.764105881831831, 1.5965456400785158],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.7705, -10.7705, -19.8658],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-8.0076190285, -8.0076190285, -198.97111970741202],
  'dipoles_elec': [0.0, -0.0, -47.803149380650005, 47.803149380650005],
  'std_dev': [0.7562888256149234, 0.7562888256149234, 1.597917307116611],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.9448, -10.9448, -20.0411],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, -2.6413, 2.6413],
  'quadrupoles_elec': [-8.1372070696, -8.1372070696, -199.10145122551202],
  'dipoles_elec': [0.0, -0.0, -47.82510279139, 47.82510279139],
  'std_dev': [0.7623838117378936, 0.7623838117378936, 1.5974786577574538],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-10.9999, -10.9999, -20.7016],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.7898, 2.7898],
  'quadrupoles_elec': [-8.1781726523, -8.1781726523, -199.59251778401202],
  'dipoles_elec': [-0.0, 0.0, -47.88352719094, 47.88352719094],
  'std_dev': [0.7643004575754223, 0.7643004575754223, 1.5995265127382026],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-11.1407, -11.1407, -20.7911],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -2.7518, 2.7518],
  'quadrupoles_elec': [-8.2828542139, -8.2828542139, -199.659058975512],
  'dipoles_elec': [0.0, -0.0, -47.868576839540005, 47.868576839540005],
  'std_dev': [0.7691764712015052, 0.7691764712015052, 1.6032909029431675],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.8551, -10.8551, -20.3839],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.6621, 2.6621],
  'quadrupoles_elec': [-8.070517182700002,
   -8.070517182700002,
   -199.35631514111202],
  'dipoles_elec': [0.0, 0.0, -47.833286141630005, 47.833286141630005],
  'std_dev': [0.7592532601510514, 0.7592532601510514, 1.6019203222123481],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-11.4667, -11.4667, -20.1273],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, -2.5652, 2.5652],
  'quadrupoles_elec': [-8.5252277159, -8.5252277159, -199.165538942912],
  'dipoles_elec': [0.0, -0.0, -47.79516274556, 47.79516274556],
  'std_dev': [0.780349176234588, 0.780349176234588, 1.6034719398444037],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-10.99948358996839,
   -10.99948358996839,
   -20.338388612318287],
  'quadrupoles_mp2': [-11.074939978926075,
   -11.074939978926075,
   -20.21229170588119],
  'quadrupoles_ccsd': [-10.967135530276206,
   -10.967135530276206,
   -20.70746585104695],
  'quadrupoles_hf': [-10.9055, -10.9055, -22.4865],
  'dipoles_ccsdt': [0, 0, -2.7215, 2.7215],
  'dipoles_mp2': [0, 0, -2.6652, 2.6652],
  'dipoles_ccsd': [0, 0, -2.8384, 2.8384],
  'dipoles_hf': [0.0, -0.0, -3.3361, 3.3361],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -48.09845816383, 48.09845816383],
  'dipoles_elec_mp2': [0.0, 0.0, -47.834505775560004, 47.834505775560004],
  'dipoles_elec_ccsd': [0.0, 0.0, -47.902647903520005, 47.902647903520005],
  'dipoles_elec_ccsdt': [0.0, 0.0, -47.856655901450004, 47.856655901450004],
  'quadrupoles_elec_hf': [-8.1079884235, -8.1079884235, -200.919549881312],
  'quadrupoles_elec_mp2': [-8.233963150712022,
   -8.233963150712022,
   -199.22872832142545],
  'quadrupoles_elec_ccsd': [-8.153813022643163,
   -8.153813022643163,
   -199.59687890935086],
  'quadrupoles_elec_ccsdt': [-8.177863061018929,
   -8.177863061018929,
   -199.32247847113257],
  'std_dev_hf': [0.7610138173844152, 0.7610138173844152, 1.59625202059972],
  'std_dev_mp2': [0.7669030088941227, 0.7669030088941227, 1.5988871348341405],
  'std_dev_ccsd': [0.7631613301937429, 0.7631613301937429, 1.5967004060068248],
  'std_dev_ccsdt': [0.7642859908352804,
   0.7642859908352804,
   1.597598939042885]},
 {'name': 'HBO',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-11.044071456105497,
   -11.044071456105497,
   -20.348476364810317],
  'quadrupoles_mp2': [-11.11408045858751,
   -11.11408045858751,
   -20.24161343990222],
  'quadrupoles_ccsd': [-11.010849124503912,
   -11.010849124503912,
   -20.70531379718963],
  'quadrupoles_hf': [-10.9126, -10.9126, -22.4967],
  'dipoles_ccsdt': [0, 0, -2.7075, 2.7075],
  'dipoles_mp2': [0, 0, -2.6584, 2.6584],
  'dipoles_ccsd': [0, 0, -2.8218, 2.8218],
  'dipoles_hf': [0.0, -0.0, -3.3371, 3.3371],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -48.098851594130004, 48.098851594130004],
  'dipoles_elec_mp2': [0.0, 0.0, -45.740040230480005, 45.740040230480005],
  'dipoles_elec_ccsd': [0.0, 0.0, -45.675753719460005, 45.675753719460005],
  'dipoles_elec_ccsdt': [0.0, 0.0, -45.720722802750004, 45.720722802750004],
  'quadrupoles_elec_hf': [-8.1132671102, -8.1132671102, -200.92713334671203],
  'quadrupoles_elec_mp2': [-8.263063197109267,
   -8.263063197109267,
   -199.2505283562702],
  'quadrupoles_elec_ccsd': [-8.186313074538795,
   -8.186313074538795,
   -199.59527890680516],
  'quadrupoles_elec_ccsdt': [-8.211013113970948,
   -8.211013113970948,
   -199.3299784830921],
  'std_dev_hf': [0.761261505200414, 0.761261505200414, 1.5963612037237105],
  'std_dev_mp2': [0.768256988118897, 0.768256988118897, 1.8862500817568768],
  'std_dev_ccsd': [0.7646807491897142, 0.7646807491897142, 1.90067043334621],
  'std_dev_ccsdt': [0.7658334915059608,
   0.7658334915059608,
   1.890139835499417]}]

In [363]:
bases = ['aug-cc-pcV5Zp', 'aug-cc-pcVQZp', 'aug-cc-pcVTZp']
for m in mols:
    for b in bases:
        get_electronic_for_wft(m, 'ccsdT', b)

WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
Electronic part successfully calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!
WFT method has not been calculated!

In [369]:
functionals = get_functionals()
for m in mols:
    for f in functionals:
        get_electronic_for_dft(m, f, 'aug-pc-4p')

DFT method has not been calculated for AlF of method B3LYP!
DFT method has not been calculated for AlF of method B3LYP5!
DFT method has not been calculated for AlF of method B97-D3!
DFT method has not been calculated for AlF of method B97M-V!
DFT method has not been calculated for AlF of method B97M-rV!
Al1
F2
Electronic part successfully calculated for AlF of method BLYP!
DFT method has not been calculated for AlF of method BPBE!
DFT method has not been calculated for AlF of method CAM-B3LYP!
DFT method has not been calculated for AlF of method M06-2X!
DFT method has not been calculated for AlF of method M06-L!
DFT method has not been calculated for AlF of method M08-HX!
DFT method has not been calculated for AlF of method MGGA_MS2!
DFT method has not been calculated for AlF of method MN15!
DFT method has not been calculated for AlF of method MN15-L!
DFT method has not been calculated for AlF of method PBE!
DFT method has not been calculated for AlF of method PBE0!
DFT method has not been calculated for AlF of method SCAN!
DFT method has not been calculated for AlF of method SCAN0!
DFT method has not been calculated for AlF of method SPW92!
DFT method has not been calculated for AlF of method Slater!
DFT method has not been calculated for AlF of method TPSS!
DFT method has not been calculated for AlF of method mBEEF!
DFT method has not been calculated for AlF of method mPW91!
DFT method has not been calculated for AlF of method revM06-L!
DFT method has not been calculated for AlF of method wB97M-V!
DFT method has not been calculated for AlF of method wB97X-D!
DFT method has not been calculated for AlF of method wB97X-V!
Ar
Electronic part successfully calculated for Ar of method B3LYP!
Ar
Electronic part successfully calculated for Ar of method B3LYP5!
DFT method has not been calculated for Ar of method B97-D3!
DFT method has not been calculated for Ar of method B97M-V!
DFT method has not been calculated for Ar of method B97M-rV!
Ar
Electronic part successfully calculated for Ar of method BLYP!
Ar
Electronic part successfully calculated for Ar of method BPBE!
DFT method has not been calculated for Ar of method CAM-B3LYP!
DFT method has not been calculated for Ar of method M06-2X!
DFT method has not been calculated for Ar of method M06-L!
DFT method has not been calculated for Ar of method M08-HX!
DFT method has not been calculated for Ar of method MGGA_MS2!
DFT method has not been calculated for Ar of method MN15!
DFT method has not been calculated for Ar of method MN15-L!
DFT method has not been calculated for Ar of method PBE!
DFT method has not been calculated for Ar of method PBE0!
DFT method has not been calculated for Ar of method SCAN!
DFT method has not been calculated for Ar of method SCAN0!
DFT method has not been calculated for Ar of method SPW92!
DFT method has not been calculated for Ar of method Slater!
Ar
Electronic part successfully calculated for Ar of method TPSS!
Ar
Electronic part successfully calculated for Ar of method mBEEF!
Ar
Electronic part successfully calculated for Ar of method mPW91!
DFT method has not been calculated for Ar of method revM06-L!
DFT method has not been calculated for Ar of method wB97M-V!
DFT method has not been calculated for Ar of method wB97X-D!
Ar
Electronic part successfully calculated for Ar of method wB97X-V!
DFT method has not been calculated for Be of method B3LYP!
DFT method has not been calculated for Be of method B3LYP5!
Be
Electronic part successfully calculated for Be of method B97-D3!
DFT method has not been calculated for Be of method B97M-V!
DFT method has not been calculated for Be of method B97M-rV!
DFT method has not been calculated for Be of method BLYP!
DFT method has not been calculated for Be of method BPBE!
Be
Electronic part successfully calculated for Be of method CAM-B3LYP!
Be
Electronic part successfully calculated for Be of method M06-2X!
Be
Electronic part successfully calculated for Be of method M06-L!
DFT method has not been calculated for Be of method M08-HX!
Be
Electronic part successfully calculated for Be of method MGGA_MS2!
Be
Electronic part successfully calculated for Be of method MN15!
Be
Electronic part successfully calculated for Be of method MN15-L!
Be
Electronic part successfully calculated for Be of method PBE!
DFT method has not been calculated for Be of method PBE0!
DFT method has not been calculated for Be of method SCAN!
DFT method has not been calculated for Be of method SCAN0!
DFT method has not been calculated for Be of method SPW92!
Be
Electronic part successfully calculated for Be of method Slater!
DFT method has not been calculated for Be of method TPSS!
DFT method has not been calculated for Be of method mBEEF!
DFT method has not been calculated for Be of method mPW91!
Be
Electronic part successfully calculated for Be of method revM06-L!
DFT method has not been calculated for Be of method wB97M-V!
DFT method has not been calculated for Be of method wB97X-D!
DFT method has not been calculated for Be of method wB97X-V!
H
Be
Electronic part successfully calculated for BeH of method B3LYP!
H
Be
Electronic part successfully calculated for BeH of method B3LYP5!
H
Be
Electronic part successfully calculated for BeH of method B97-D3!
DFT method has not been calculated for BeH of method B97M-V!
DFT method has not been calculated for BeH of method B97M-rV!
H
Be
Electronic part successfully calculated for BeH of method BLYP!
H
Be
Electronic part successfully calculated for BeH of method BPBE!
H
Be
Electronic part successfully calculated for BeH of method CAM-B3LYP!
H
Be
Electronic part successfully calculated for BeH of method M06-2X!
H
Be
Electronic part successfully calculated for BeH of method M06-L!
DFT method has not been calculated for BeH of method M08-HX!
H
Be
Electronic part successfully calculated for BeH of method MGGA_MS2!
H
Be
Electronic part successfully calculated for BeH of method MN15!
H
Be
Electronic part successfully calculated for BeH of method MN15-L!
DFT method has not been calculated for BeH of method PBE!
DFT method has not been calculated for BeH of method PBE0!
DFT method has not been calculated for BeH of method SCAN!
DFT method has not been calculated for BeH of method SCAN0!
DFT method has not been calculated for BeH of method SPW92!
H
Be
Electronic part successfully calculated for BeH of method Slater!
H
Be
Electronic part successfully calculated for BeH of method TPSS!
H
Be
Electronic part successfully calculated for BeH of method mBEEF!
H
Be
Electronic part successfully calculated for BeH of method mPW91!
H
Be
Electronic part successfully calculated for BeH of method revM06-L!
DFT method has not been calculated for BeH of method wB97M-V!
DFT method has not been calculated for BeH of method wB97X-D!
H
Be
Electronic part successfully calculated for BeH of method wB97X-V!
DFT method has not been calculated for BeH2 of method B3LYP!
DFT method has not been calculated for BeH2 of method B3LYP5!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method B97-D3!
DFT method has not been calculated for BeH2 of method B97M-V!
DFT method has not been calculated for BeH2 of method B97M-rV!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method BLYP!
DFT method has not been calculated for BeH2 of method BPBE!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method CAM-B3LYP!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method M06-2X!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method M06-L!
DFT method has not been calculated for BeH2 of method M08-HX!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method MGGA_MS2!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method MN15!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method MN15-L!
DFT method has not been calculated for BeH2 of method PBE!
DFT method has not been calculated for BeH2 of method PBE0!
DFT method has not been calculated for BeH2 of method SCAN!
DFT method has not been calculated for BeH2 of method SCAN0!
DFT method has not been calculated for BeH2 of method SPW92!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method Slater!
DFT method has not been calculated for BeH2 of method TPSS!
DFT method has not been calculated for BeH2 of method mBEEF!
DFT method has not been calculated for BeH2 of method mPW91!
Be1
H2
H3
Electronic part successfully calculated for BeH2 of method revM06-L!
DFT method has not been calculated for BeH2 of method wB97M-V!
DFT method has not been calculated for BeH2 of method wB97X-D!
DFT method has not been calculated for BeH2 of method wB97X-V!
DFT method has not been calculated for BF of method B3LYP!
DFT method has not been calculated for BF of method B3LYP5!
B1
F2
Electronic part successfully calculated for BF of method B97-D3!
DFT method has not been calculated for BF of method B97M-V!
DFT method has not been calculated for BF of method B97M-rV!
B1
F2
Electronic part successfully calculated for BF of method BLYP!
DFT method has not been calculated for BF of method BPBE!
B1
F2
Electronic part successfully calculated for BF of method CAM-B3LYP!
B1
F2
Electronic part successfully calculated for BF of method M06-2X!
B1
F2
Electronic part successfully calculated for BF of method M06-L!
DFT method has not been calculated for BF of method M08-HX!
B1
F2
Electronic part successfully calculated for BF of method MGGA_MS2!
B1
F2
Electronic part successfully calculated for BF of method MN15!
B1
F2
Electronic part successfully calculated for BF of method MN15-L!
DFT method has not been calculated for BF of method PBE!
DFT method has not been calculated for BF of method PBE0!
DFT method has not been calculated for BF of method SCAN!
DFT method has not been calculated for BF of method SCAN0!
DFT method has not been calculated for BF of method SPW92!
B1
F2
Electronic part successfully calculated for BF of method Slater!
DFT method has not been calculated for BF of method TPSS!
DFT method has not been calculated for BF of method mBEEF!
DFT method has not been calculated for BF of method mPW91!
B1
F2
Electronic part successfully calculated for BF of method revM06-L!
DFT method has not been calculated for BF of method wB97M-V!
DFT method has not been calculated for BF of method wB97X-D!
DFT method has not been calculated for BF of method wB97X-V!
DFT method has not been calculated for BH2 of method B3LYP!
DFT method has not been calculated for BH2 of method B3LYP5!
DFT method has not been calculated for BH2 of method B97-D3!
DFT method has not been calculated for BH2 of method B97M-V!
DFT method has not been calculated for BH2 of method B97M-rV!
B1
H2
H3
Electronic part successfully calculated for BH2 of method BLYP!
DFT method has not been calculated for BH2 of method BPBE!
DFT method has not been calculated for BH2 of method CAM-B3LYP!
DFT method has not been calculated for BH2 of method M06-2X!
DFT method has not been calculated for BH2 of method M06-L!
DFT method has not been calculated for BH2 of method M08-HX!
DFT method has not been calculated for BH2 of method MGGA_MS2!
DFT method has not been calculated for BH2 of method MN15!
DFT method has not been calculated for BH2 of method MN15-L!
DFT method has not been calculated for BH2 of method PBE!
DFT method has not been calculated for BH2 of method PBE0!
DFT method has not been calculated for BH2 of method SCAN!
DFT method has not been calculated for BH2 of method SCAN0!
DFT method has not been calculated for BH2 of method SPW92!
DFT method has not been calculated for BH2 of method Slater!
DFT method has not been calculated for BH2 of method TPSS!
DFT method has not been calculated for BH2 of method mBEEF!
DFT method has not been calculated for BH2 of method mPW91!
DFT method has not been calculated for BH2 of method revM06-L!
DFT method has not been calculated for BH2 of method wB97M-V!
DFT method has not been calculated for BH2 of method wB97X-D!
DFT method has not been calculated for BH2 of method wB97X-V!
DFT method has not been calculated for BH2F of method B3LYP!
DFT method has not been calculated for BH2F of method B3LYP5!
DFT method has not been calculated for BH2F of method B97-D3!
DFT method has not been calculated for BH2F of method B97M-V!
DFT method has not been calculated for BH2F of method B97M-rV!
DFT method has not been calculated for BH2F of method BLYP!
DFT method has not been calculated for BH2F of method BPBE!
DFT method has not been calculated for BH2F of method CAM-B3LYP!
DFT method has not been calculated for BH2F of method M06-2X!
DFT method has not been calculated for BH2F of method M06-L!
DFT method has not been calculated for BH2F of method M08-HX!
DFT method has not been calculated for BH2F of method MGGA_MS2!
DFT method has not been calculated for BH2F of method MN15!
DFT method has not been calculated for BH2F of method MN15-L!
B
F
H
H
Electronic part successfully calculated for BH2F of method PBE!
DFT method has not been calculated for BH2F of method PBE0!
DFT method has not been calculated for BH2F of method SCAN!
DFT method has not been calculated for BH2F of method SCAN0!
DFT method has not been calculated for BH2F of method SPW92!
DFT method has not been calculated for BH2F of method Slater!
DFT method has not been calculated for BH2F of method TPSS!
DFT method has not been calculated for BH2F of method mBEEF!
DFT method has not been calculated for BH2F of method mPW91!
DFT method has not been calculated for BH2F of method revM06-L!
DFT method has not been calculated for BH2F of method wB97M-V!
DFT method has not been calculated for BH2F of method wB97X-D!
DFT method has not been calculated for BH2F of method wB97X-V!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method B3LYP!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method B3LYP5!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method B97-D3!
DFT method has not been calculated for BH3 of method B97M-V!
DFT method has not been calculated for BH3 of method B97M-rV!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method BLYP!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method BPBE!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method CAM-B3LYP!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method M06-2X!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method M06-L!
DFT method has not been calculated for BH3 of method M08-HX!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method MGGA_MS2!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method MN15!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method MN15-L!
DFT method has not been calculated for BH3 of method PBE!
DFT method has not been calculated for BH3 of method PBE0!
DFT method has not been calculated for BH3 of method SCAN!
DFT method has not been calculated for BH3 of method SCAN0!
DFT method has not been calculated for BH3 of method SPW92!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method Slater!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method TPSS!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method mBEEF!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method mPW91!
B1
H2
H3
H4
Electronic part successfully calculated for BH3 of method revM06-L!
DFT method has not been calculated for BH3 of method wB97M-V!
DFT method has not been calculated for BH3 of method wB97X-D!
DFT method has not been calculated for BH3 of method wB97X-V!
DFT method has not been calculated for BO of method B3LYP!
DFT method has not been calculated for BO of method B3LYP5!
B1
O2
Electronic part successfully calculated for BO of method B97-D3!
DFT method has not been calculated for BO of method B97M-V!
DFT method has not been calculated for BO of method B97M-rV!
DFT method has not been calculated for BO of method BLYP!
DFT method has not been calculated for BO of method BPBE!
B1
O2
Electronic part successfully calculated for BO of method CAM-B3LYP!
B1
O2
Electronic part successfully calculated for BO of method M06-2X!
B1
O2
Electronic part successfully calculated for BO of method M06-L!
DFT method has not been calculated for BO of method M08-HX!
B1
O2
Electronic part successfully calculated for BO of method MGGA_MS2!
B1
O2
Electronic part successfully calculated for BO of method MN15!
B1
O2
Electronic part successfully calculated for BO of method MN15-L!
B1
O2
Electronic part successfully calculated for BO of method PBE!
DFT method has not been calculated for BO of method PBE0!
DFT method has not been calculated for BO of method SCAN!
DFT method has not been calculated for BO of method SCAN0!
DFT method has not been calculated for BO of method SPW92!
B1
O2
Electronic part successfully calculated for BO of method Slater!
DFT method has not been calculated for BO of method TPSS!
DFT method has not been calculated for BO of method mBEEF!
DFT method has not been calculated for BO of method mPW91!
B1
O2
Electronic part successfully calculated for BO of method revM06-L!
DFT method has not been calculated for BO of method wB97M-V!
DFT method has not been calculated for BO of method wB97X-D!
DFT method has not been calculated for BO of method wB97X-V!
B1
S2
Electronic part successfully calculated for BS of method B3LYP!
B1
S2
Electronic part successfully calculated for BS of method B3LYP5!
DFT method has not been calculated for BS of method B97-D3!
DFT method has not been calculated for BS of method B97M-V!
DFT method has not been calculated for BS of method B97M-rV!
B1
S2
Electronic part successfully calculated for BS of method BLYP!
B1
S2
Electronic part successfully calculated for BS of method BPBE!
DFT method has not been calculated for BS of method CAM-B3LYP!
DFT method has not been calculated for BS of method M06-2X!
DFT method has not been calculated for BS of method M06-L!
DFT method has not been calculated for BS of method M08-HX!
DFT method has not been calculated for BS of method MGGA_MS2!
DFT method has not been calculated for BS of method MN15!
DFT method has not been calculated for BS of method MN15-L!
DFT method has not been calculated for BS of method PBE!
DFT method has not been calculated for BS of method PBE0!
DFT method has not been calculated for BS of method SCAN!
DFT method has not been calculated for BS of method SCAN0!
DFT method has not been calculated for BS of method SPW92!
DFT method has not been calculated for BS of method Slater!
B1
S2
Electronic part successfully calculated for BS of method TPSS!
B1
S2
Electronic part successfully calculated for BS of method mBEEF!
B1
S2
Electronic part successfully calculated for BS of method mPW91!
DFT method has not been calculated for BS of method revM06-L!
DFT method has not been calculated for BS of method wB97M-V!
DFT method has not been calculated for BS of method wB97X-D!
B1
S2
Electronic part successfully calculated for BS of method wB97X-V!
DFT method has not been calculated for C2H of method B3LYP!
DFT method has not been calculated for C2H of method B3LYP5!
C1
C2
H3
Electronic part successfully calculated for C2H of method B97-D3!
C1
C2
H3
Electronic part successfully calculated for C2H of method B97M-V!
C1
C2
H3
Electronic part successfully calculated for C2H of method B97M-rV!
DFT method has not been calculated for C2H of method BLYP!
DFT method has not been calculated for C2H of method BPBE!
C1
C2
H3
Electronic part successfully calculated for C2H of method CAM-B3LYP!
C1
C2
H3
Electronic part successfully calculated for C2H of method M06-2X!
C1
C2
H3
Electronic part successfully calculated for C2H of method M06-L!
C1
C2
H3
Electronic part successfully calculated for C2H of method M08-HX!
C1
C2
H3
Electronic part successfully calculated for C2H of method MGGA_MS2!
C1
C2
H3
Electronic part successfully calculated for C2H of method MN15!
C1
C2
H3

DFT method has not been calculated for CH3BH2 of method M08-HX!
DFT method has not been calculated for CH3BH2 of method MGGA_MS2!
DFT method has not been calculated for CH3BH2 of method MN15!
DFT method has not been calculated for CH3BH2 of method MN15-L!
C
B
H
H
H
H
H
Electronic part successfully calculated for CH3BH2 of method PBE!
DFT method has not been calculated for CH3BH2 of method PBE0!
DFT method has not been calculated for CH3BH2 of method SCAN!
DFT method has not been calculated for CH3BH2 of method SCAN0!
DFT method has not been calculated for CH3BH2 of method SPW92!
DFT method has not been calculated for CH3BH2 of method Slater!
DFT method has not been calculated for CH3BH2 of method TPSS!
DFT method has not been calculated for CH3BH2 of method mBEEF!
DFT method has not been calculated for CH3BH2 of method mPW91!
DFT method has not been calculated for CH3BH2 of method revM06-L!
DFT method has not been calculated for CH3BH2 of method wB97M-V!
DFT method has not been calculated for CH3BH2 of method wB97X-D!
DFT method has not been calculated for CH3BH2 of method wB97X-V!
DFT method has not been calculated for CH3O of method B3LYP!
DFT method has not been calculated for CH3O of method B3LYP5!
DFT method has not been calculated for CH3O of method B97-D3!
DFT method has not been calculated for CH3O of method B97M-V!
DFT method has not been calculated for CH3O of method B97M-rV!
DFT method has not been calculated for CH3O of method BLYP!
DFT method has not been calculated for CH3O of method BPBE!
DFT method has not been calculated for CH3O of method CAM-B3LYP!
DFT method has not been calculated for CH3O of method M06-2X!
DFT method has not been calculated for CH3O of method M06-L!
DFT method has not been calculated for CH3O of method M08-HX!
DFT method has not been calculated for CH3O of method MGGA_MS2!
DFT method has not been calculated for CH3O of method MN15!
DFT method has not been calculated for CH3O of method MN15-L!
C1
O2
H3
H4
H5
Electronic part successfully calculated for CH3O of method PBE!
DFT method has not been calculated for CH3O of method PBE0!
DFT method has not been calculated for CH3O of method SCAN!
DFT method has not been calculated for CH3O of method SCAN0!
DFT method has not been calculated for CH3O of method SPW92!
DFT method has not been calculated for CH3O of method Slater!
DFT method has not been calculated for CH3O of method TPSS!
DFT method has not been calculated for CH3O of method mBEEF!
DFT method has not been calculated for CH3O of method mPW91!
DFT method has not been calculated for CH3O of method revM06-L!
DFT method has not been calculated for CH3O of method wB97M-V!
DFT method has not been calculated for CH3O of method wB97X-D!
DFT method has not been calculated for CH3O of method wB97X-V!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method B3LYP!
DFT method has not been calculated for CH4 of method B3LYP5!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method B97-D3!
DFT method has not been calculated for CH4 of method B97M-V!
DFT method has not been calculated for CH4 of method B97M-rV!
DFT method has not been calculated for CH4 of method BLYP!
DFT method has not been calculated for CH4 of method BPBE!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method CAM-B3LYP!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method M06-2X!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method M06-L!
DFT method has not been calculated for CH4 of method M08-HX!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method MGGA_MS2!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method MN15!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method MN15-L!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method PBE!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method PBE0!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method SCAN!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method SCAN0!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method SPW92!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method Slater!
DFT method has not been calculated for CH4 of method TPSS!
DFT method has not been calculated for CH4 of method mBEEF!
DFT method has not been calculated for CH4 of method mPW91!
C1
H2
H3
H4
H5
Electronic part successfully calculated for CH4 of method revM06-L!
DFT method has not been calculated for CH4 of method wB97M-V!
DFT method has not been calculated for CH4 of method wB97X-D!
DFT method has not been calculated for CH4 of method wB97X-V!
F1
Cl2
Electronic part successfully calculated for ClF of method B3LYP!
F1
Cl2
Electronic part successfully calculated for ClF of method B3LYP5!
DFT method has not been calculated for ClF of method B97-D3!
DFT method has not been calculated for ClF of method B97M-V!
DFT method has not been calculated for ClF of method B97M-rV!
F1
Cl2
Electronic part successfully calculated for ClF of method BLYP!
F1
Cl2
Electronic part successfully calculated for ClF of method BPBE!
DFT method has not been calculated for ClF of method CAM-B3LYP!
DFT method has not been calculated for ClF of method M06-2X!
DFT method has not been calculated for ClF of method M06-L!
DFT method has not been calculated for ClF of method M08-HX!
DFT method has not been calculated for ClF of method MGGA_MS2!
DFT method has not been calculated for ClF of method MN15!
DFT method has not been calculated for ClF of method MN15-L!
DFT method has not been calculated for ClF of method PBE!
DFT method has not been calculated for ClF of method PBE0!
DFT method has not been calculated for ClF of method SCAN!
DFT method has not been calculated for ClF of method SCAN0!
DFT method has not been calculated for ClF of method SPW92!
DFT method has not been calculated for ClF of method Slater!
F1
Cl2
Electronic part successfully calculated for ClF of method TPSS!
F1
Cl2
Electronic part successfully calculated for ClF of method mBEEF!
F1
Cl2
Electronic part successfully calculated for ClF of method mPW91!
DFT method has not been calculated for ClF of method revM06-L!
DFT method has not been calculated for ClF of method wB97M-V!
DFT method has not been calculated for ClF of method wB97X-D!
F1
Cl2
Electronic part successfully calculated for ClF of method wB97X-V!
N1
C2
Electronic part successfully calculated for CN of method B3LYP!
DFT method has not been calculated for CN of method B3LYP5!
N1
C2
Electronic part successfully calculated for CN of method B97-D3!
N1
C2
Electronic part successfully calculated for CN of method B97M-V!
N1
C2
Electronic part successfully calculated for CN of method B97M-rV!
DFT method has not been calculated for CN of method BLYP!
DFT method has not been calculated for CN of method BPBE!
N1
C2
Electronic part successfully calculated for CN of method CAM-B3LYP!
N1
C2
Electronic part successfully calculated for CN of method M06-2X!
N1
C2
Electronic part successfully calculated for CN of method M06-L!
N1
C2
Electronic part successfully calculated for CN of method M08-HX!
N1
C2
Electronic part successfully calculated for CN of method MGGA_MS2!
N1
C2
Electronic part successfully calculated for CN of method MN15!
N1
C2
Electronic part successfully calculated for CN of method MN15-L!
N1
C2
Electronic part successfully calculated for CN of method PBE!
N1
C2
Electronic part successfully calculated for CN of method PBE0!
N1
C2
Electronic part successfully calculated for CN of method SCAN!
N1
C2
Electronic part successfully calculated for CN of method SCAN0!
N1
C2
Electronic part successfully calculated for CN of method SPW92!
N1
C2
Electronic part successfully calculated for CN of method Slater!
N1
C2
Electronic part successfully calculated for CN of method TPSS!
N1
C2
Electronic part successfully calculated for CN of method mBEEF!
N1
C2
Electronic part successfully calculated for CN of method mPW91!
N1
C2
Electronic part successfully calculated for CN of method revM06-L!
N1
C2
Electronic part successfully calculated for CN of method wB97M-V!
N1
C2
Electronic part successfully calculated for CN of method wB97X-D!
N1
C2
Electronic part successfully calculated for CN of method wB97X-V!
C1
O2
Electronic part successfully calculated for CO of method B3LYP!
DFT method has not been calculated for CO of method B3LYP5!
C1
O2
Electronic part successfully calculated for CO of method B97-D3!
C1
O2
Electronic part successfully calculated for CO of method B97M-V!
C1
O2
Electronic part successfully calculated for CO of method B97M-rV!
DFT method has not been calculated for CO of method BLYP!
DFT method has not been calculated for CO of method BPBE!
C1
O2
Electronic part successfully calculated for CO of method CAM-B3LYP!
C1
O2
Electronic part successfully calculated for CO of method M06-2X!
C1
O2
Electronic part successfully calculated for CO of method M06-L!
C1
O2
Electronic part successfully calculated for CO of method M08-HX!
C1
O2
Electronic part successfully calculated for CO of method MGGA_MS2!
C1
O2
Electronic part successfully calculated for CO of method MN15!
C1
O2
Electronic part successfully calculated for CO of method MN15-L!
DFT method has not been calculated for CO of method PBE!
C1
O2
Electronic part successfully calculated for CO of method PBE0!
DFT method has not been calculated for CO of method SCAN!
DFT method has not been calculated for CO of method SCAN0!
DFT method has not been calculated for CO of method SPW92!
C1
O2
Electronic part successfully calculated for CO of method Slater!
C1
O2
Electronic part successfully calculated for CO of method TPSS!
DFT method has not been calculated for CO of method mBEEF!
C1
O2
Electronic part successfully calculated for CO of method mPW91!
C1
O2
Electronic part successfully calculated for CO of method revM06-L!
C1
O2
Electronic part successfully calculated for CO of method wB97M-V!
C1
O2
Electronic part successfully calculated for CO of method wB97X-D!
C1
O2
Electronic part successfully calculated for CO of method wB97X-V!
DFT method has not been calculated for CO2 of method B3LYP!
DFT method has not been calculated for CO2 of method B3LYP5!
DFT method has not been calculated for CO2 of method B97-D3!
DFT method has not been calculated for CO2 of method B97M-V!
DFT method has not been calculated for CO2 of method B97M-rV!
DFT method has not been calculated for CO2 of method BLYP!
DFT method has not been calculated for CO2 of method BPBE!
DFT method has not been calculated for CO2 of method CAM-B3LYP!
DFT method has not been calculated for CO2 of method M06-2X!
DFT method has not been calculated for CO2 of method M06-L!
DFT method has not been calculated for CO2 of method M08-HX!
DFT method has not been calculated for CO2 of method MGGA_MS2!
DFT method has not been calculated for CO2 of method MN15!
DFT method has not been calculated for CO2 of method MN15-L!

C1
O2
O3
Electronic part successfully calculated for CO2 of method PBE!
C1
O2
O3
Electronic part successfully calculated for CO2 of method PBE0!
C1
O2
O3
Electronic part successfully calculated for CO2 of method SCAN!
C1
O2
O3
Electronic part successfully calculated for CO2 of method SCAN0!
C1
O2
O3
Electronic part successfully calculated for CO2 of method SPW92!
DFT method has not been calculated for CO2 of method Slater!
DFT method has not been calculated for CO2 of method TPSS!
DFT method has not been calculated for CO2 of method mBEEF!
DFT method has not been calculated for CO2 of method mPW91!
DFT method has not been calculated for CO2 of method revM06-L!
DFT method has not been calculated for CO2 of method wB97M-V!
DFT method has not been calculated for CO2 of method wB97X-D!
DFT method has not been calculated for CO2 of method wB97X-V!
DFT method has not been calculated for F2 of method B3LYP!
DFT method has not been calculated for F2 of method B3LYP5!
F1
F2
Electronic part successfully calculated for F2 of method B97-D3!
DFT method has not been calculated for F2 of method B97M-V!
DFT method has not been calculated for F2 of method B97M-rV!
DFT method has not been calculated for F2 of method BLYP!
DFT method has not been calculated for F2 of method BPBE!
F1
F2
Electronic part successfully calculated for F2 of method CAM-B3LYP!
F1
F2
Electronic part successfully calculated for F2 of method M06-2X!
F1
F2
Electronic part successfully calculated for F2 of method M06-L!
DFT method has not been calculated for F2 of method M08-HX!
F1
F2
Electronic part successfully calculated for F2 of method MGGA_MS2!
F1
F2
Electronic part successfully calculated for F2 of method MN15!
F1
F2
Electronic part successfully calculated for F2 of method MN15-L!
F1
F2
Electronic part successfully calculated for F2 of method PBE!
DFT method has not been calculated for F2 of method PBE0!
DFT method has not been calculated for F2 of method SCAN!
DFT method has not been calculated for F2 of method SCAN0!
DFT method has not been calculated for F2 of method SPW92!
F1
F2
Electronic part successfully calculated for F2 of method Slater!
DFT method has not been calculated for F2 of method TPSS!
DFT method has not been calculated for F2 of method mBEEF!
DFT method has not been calculated for F2 of method mPW91!
F1
F2
Electronic part successfully calculated for F2 of method revM06-L!
DFT method has not been calculated for F2 of method wB97M-V!
DFT method has not been calculated for F2 of method wB97X-D!
DFT method has not been calculated for F2 of method wB97X-V!
C1
F2
N3
Electronic part successfully calculated for FCN of method B3LYP!
DFT method has not been calculated for FCN of method B3LYP5!
DFT method has not been calculated for FCN of method B97-D3!
C1
F2
N3
Electronic part successfully calculated for FCN of method B97M-V!
DFT method has not been calculated for FCN of method B97M-rV!
DFT method has not been calculated for FCN of method BLYP!
DFT method has not been calculated for FCN of method BPBE!
DFT method has not been calculated for FCN of method CAM-B3LYP!
DFT method has not been calculated for FCN of method M06-2X!
DFT method has not been calculated for FCN of method M06-L!
C1
F2
N3
Electronic part successfully calculated for FCN of method M08-HX!
DFT method has not been calculated for FCN of method MGGA_MS2!
DFT method has not been calculated for FCN of method MN15!
DFT method has not been calculated for FCN of method MN15-L!
DFT method has not been calculated for FCN of method PBE!
DFT method has not been calculated for FCN of method PBE0!
DFT method has not been calculated for FCN of method SCAN!
DFT method has not been calculated for FCN of method SCAN0!
DFT method has not been calculated for FCN of method SPW92!
DFT method has not been calculated for FCN of method Slater!
C1
F2
N3
Electronic part successfully calculated for FCN of method TPSS!
DFT method has not been calculated for FCN of method mBEEF!
C1
F2
N3
Electronic part successfully calculated for FCN of method mPW91!
DFT method has not been calculated for FCN of method revM06-L!
C1
F2
N3
Electronic part successfully calculated for FCN of method wB97M-V!
C1
F2
N3
Electronic part successfully calculated for FCN of method wB97X-D!
C1
F2
N3
Electronic part successfully calculated for FCN of method wB97X-V!
F1
C2
O3
Electronic part successfully calculated for FCO of method B3LYP!
DFT method has not been calculated for FCO of method B3LYP5!
DFT method has not been calculated for FCO of method B97-D3!
DFT method has not been calculated for FCO of method B97M-V!
F1
C2
O3
Electronic part successfully calculated for FCO of method B97M-rV!
F1
C2
O3
Electronic part successfully calculated for FCO of method BLYP!
F1
C2
O3
Electronic part successfully calculated for FCO of method BPBE!
DFT method has not been calculated for FCO of method CAM-B3LYP!
DFT method has not been calculated for FCO of method M06-2X!
DFT method has not been calculated for FCO of method M06-L!
F1
C2
O3
Electronic part successfully calculated for FCO of method M08-HX!
DFT method has not been calculated for FCO of method MGGA_MS2!
DFT method has not been calculated for FCO of method MN15!
DFT method has not been calculated for FCO of method MN15-L!
DFT method has not been calculated for FCO of method PBE!
DFT method has not been calculated for FCO of method PBE0!
DFT method has not been calculated for FCO of method SCAN!
DFT method has not been calculated for FCO of method SCAN0!
DFT method has not been calculated for FCO of method SPW92!
DFT method has not been calculated for FCO of method Slater!
DFT method has not been calculated for FCO of method TPSS!
DFT method has not been calculated for FCO of method mBEEF!
DFT method has not been calculated for FCO of method mPW91!
DFT method has not been calculated for FCO of method revM06-L!
DFT method has not been calculated for FCO of method wB97M-V!
DFT method has not been calculated for FCO of method wB97X-D!
DFT method has not been calculated for FCO of method wB97X-V!
H
Electronic part successfully calculated for H of method B3LYP!
H
Electronic part successfully calculated for H of method B3LYP5!
H
Electronic part successfully calculated for H of method B97-D3!
DFT method has not been calculated for H of method B97M-V!
DFT method has not been calculated for H of method B97M-rV!
H
Electronic part successfully calculated for H of method BLYP!
H
Electronic part successfully calculated for H of method BPBE!
H
Electronic part successfully calculated for H of method CAM-B3LYP!
H
Electronic part successfully calculated for H of method M06-2X!
H
Electronic part successfully calculated for H of method M06-L!
DFT method has not been calculated for H of method M08-HX!
H
Electronic part successfully calculated for H of method MGGA_MS2!
H
Electronic part successfully calculated for H of method MN15!
H
Electronic part successfully calculated for H of method MN15-L!
DFT method has not been calculated for H of method PBE!
DFT method has not been calculated for H of method PBE0!
DFT method has not been calculated for H of method SCAN!
DFT method has not been calculated for H of method SCAN0!
DFT method has not been calculated for H of method SPW92!
H
Electronic part successfully calculated for H of method Slater!
H
Electronic part successfully calculated for H of method TPSS!
H
Electronic part successfully calculated for H of method mBEEF!
H
Electronic part successfully calculated for H of method mPW91!
H
Electronic part successfully calculated for H of method revM06-L!
DFT method has not been calculated for H of method wB97M-V!
DFT method has not been calculated for H of method wB97X-D!
H
Electronic part successfully calculated for H of method wB97X-V!
H1
H2
Electronic part successfully calculated for H2 of method B3LYP!
H1
H2
Electronic part successfully calculated for H2 of method B3LYP5!
H1
H2
Electronic part successfully calculated for H2 of method B97-D3!
DFT method has not been calculated for H2 of method B97M-V!
DFT method has not been calculated for H2 of method B97M-rV!
H1
H2
Electronic part successfully calculated for H2 of method BLYP!
H1
H2
Electronic part successfully calculated for H2 of method BPBE!
H1
H2
Electronic part successfully calculated for H2 of method CAM-B3LYP!
H1
H2
Electronic part successfully calculated for H2 of method M06-2X!
H1
H2
Electronic part successfully calculated for H2 of method M06-L!
DFT method has not been calculated for H2 of method M08-HX!
H1
H2
Electronic part successfully calculated for H2 of method MGGA_MS2!
H1
H2
Electronic part successfully calculated for H2 of method MN15!
H1
H2
Electronic part successfully calculated for H2 of method MN15-L!
DFT method has not been calculated for H2 of method PBE!
DFT method has not been calculated for H2 of method PBE0!
DFT method has not been calculated for H2 of method SCAN!
DFT method has not been calculated for H2 of method SCAN0!
DFT method has not been calculated for H2 of method SPW92!
H1
H2
Electronic part successfully calculated for H2 of method Slater!
H1
H2
Electronic part successfully calculated for H2 of method TPSS!
DFT method has not been calculated for H2 of method mBEEF!
H1
H2
Electronic part successfully calculated for H2 of method mPW91!
H1
H2
Electronic part successfully calculated for H2 of method revM06-L!
DFT method has not been calculated for H2 of method wB97M-V!
DFT method has not been calculated for H2 of method wB97X-D!
H1
H2
Electronic part successfully calculated for H2 of method wB97X-V!
DFT method has not been calculated for H2CN of method B3LYP!
DFT method has not been calculated for H2CN of method B3LYP5!
DFT method has not been calculated for H2CN of method B97-D3!
DFT method has not been calculated for H2CN of method B97M-V!
DFT method has not been calculated for H2CN of method B97M-rV!
DFT method has not been calculated for H2CN of method BLYP!
DFT method has not been calculated for H2CN of method BPBE!
DFT method has not been calculated for H2CN of method CAM-B3LYP!
DFT method has not been calculated for H2CN of method M06-2X!
DFT method has not been calculated for H2CN of method M06-L!
DFT method has not been calculated for H2CN of method M08-HX!
DFT method has not been calculated for H2CN of method MGGA_MS2!
DFT method has not been calculated for H2CN of method MN15!
DFT method has not been calculated for H2CN of method MN15-L!
C
N
H
H
Electronic part successfully calculated for H2CN of method PBE!
DFT method has not been calculated for H2CN of method PBE0!
DFT method has not been calculated for H2CN of method SCAN!
DFT method has not been calculated for H2CN of method SCAN0!
DFT method has not been calculated for H2CN of method SPW92!
DFT method has not been calculated for H2CN of method Slater!
DFT method has not been calculated for H2CN of method TPSS!
DFT method has not been calculated for H2CN of method mBEEF!
DFT method has not been calculated for H2CN of method mPW91!
DFT method has not been calculated for H2CN of method revM06-L!
DFT method has not been calculated for H2CN of method wB97M-V!
DFT method has not been calculated for H2CN of method wB97X-D!
DFT method has not been calculated for H2CN of method wB97X-V!
DFT method has not been calculated for H2O of method B3LYP!
DFT method has not been calculated for H2O of method B3LYP5!
DFT method has not been calculated for H2O of method B97-D3!
DFT method has not been calculated for H2O of method B97M-V!
DFT method has not been calculated for H2O of method B97M-rV!
DFT method has not been calculated for H2O of method BLYP!
DFT method has not been calculated for H2O of method BPBE!
DFT method has not been calculated for H2O of method CAM-B3LYP!
DFT method has not been calculated for H2O of method M06-2X!
DFT method has not been calculated for H2O of method M06-L!
DFT method has not been calculated for H2O of method M08-HX!
DFT method has not been calculated for H2O of method MGGA_MS2!
DFT method has not been calculated for H2O of method MN15!
DFT method has not been calculated for H2O of method MN15-L!
O
H
H
Electronic part successfully calculated for H2O of method PBE!
O
H
H
Electronic part successfully calculated for H2O of method PBE0!
O
H
H
Electronic part successfully calculated for H2O of method SCAN!
O
H
H
Electronic part successfully calculated for H2O of method SCAN0!
O
H
H
Electronic part successfully calculated for H2O of method SPW92!
DFT method has not been calculated for H2O of method Slater!
DFT method has not been calculated for H2O of method TPSS!
DFT method has not been calculated for H2O of method mBEEF!
DFT method has not been calculated for H2O of method mPW91!
DFT method has not been calculated for H2O of method revM06-L!
DFT method has not been calculated for H2O of method wB97M-V!
DFT method has not been calculated for H2O of method wB97X-D!
DFT method has not been calculated for H2O of method wB97X-V!
DFT method has not been calculated for HBO of method B3LYP!
DFT method has not been calculated for HBO of method B3LYP5!
B1
H2
O3
Electronic part successfully calculated for HBO of method B97-D3!
DFT method has not been calculated for HBO of method B97M-V!
DFT method has not been calculated for HBO of method B97M-rV!
DFT method has not been calculated for HBO of method BLYP!
DFT method has not been calculated for HBO of method BPBE!
B1
H2
O3
Electronic part successfully calculated for HBO of method CAM-B3LYP!
B1
H2
O3
Electronic part successfully calculated for HBO of method M06-2X!
B1
H2
O3
Electronic part successfully calculated for HBO of method M06-L!
DFT method has not been calculated for HBO of method M08-HX!
B1
H2
O3
Electronic part successfully calculated for HBO of method MGGA_MS2!
B1
H2
O3
Electronic part successfully calculated for HBO of method MN15!
B1
H2
O3
Electronic part successfully calculated for HBO of method MN15-L!
B1
H2
O3
Electronic part successfully calculated for HBO of method PBE!
DFT method has not been calculated for HBO of method PBE0!
DFT method has not been calculated for HBO of method SCAN!
DFT method has not been calculated for HBO of method SCAN0!
DFT method has not been calculated for HBO of method SPW92!
B1
H2
O3
Electronic part successfully calculated for HBO of method Slater!
DFT method has not been calculated for HBO of method TPSS!
DFT method has not been calculated for HBO of method mBEEF!
DFT method has not been calculated for HBO of method mPW91!
B1
H2
O3
Electronic part successfully calculated for HBO of method revM06-L!
DFT method has not been calculated for HBO of method wB97M-V!
DFT method has not been calculated for HBO of method wB97X-D!
DFT method has not been calculated for HBO of method wB97X-V!
C
C
F
H
Electronic part successfully calculated for HCCF of method B3LYP!
C
C
F
H
Electronic part successfully calculated for HCCF of method B3LYP5!
DFT method has not been calculated for HCCF of method B97-D3!
DFT method has not been calculated for HCCF of method B97M-V!
DFT method has not been calculated for HCCF of method B97M-rV!
C
C
F
H
Electronic part successfully calculated for HCCF of method BLYP!
C
C
F
H
Electronic part successfully calculated for HCCF of method BPBE!
DFT method has not been calculated for HCCF of method CAM-B3LYP!
DFT method has not been calculated for HCCF of method M06-2X!
DFT method has not been calculated for HCCF of method M06-L!
DFT method has not been calculated for HCCF of method M08-HX!
DFT method has not been calculated for HCCF of method MGGA_MS2!
DFT method has not been calculated for HCCF of method MN15!
DFT method has not been calculated for HCCF of method MN15-L!
DFT method has not been calculated for HCCF of method PBE!
DFT method has not been calculated for HCCF of method PBE0!
DFT method has not been calculated for HCCF of method SCAN!
DFT method has not been calculated for HCCF of method SCAN0!
DFT method has not been calculated for HCCF of method SPW92!
DFT method has not been calculated for HCCF of method Slater!
C
C
F
H
Electronic part successfully calculated for HCCF of method TPSS!
C
C
F
H
Electronic part successfully calculated for HCCF of method mBEEF!
C
C
F
H
Electronic part successfully calculated for HCCF of method mPW91!
DFT method has not been calculated for HCCF of method revM06-L!
DFT method has not been calculated for HCCF of method wB97M-V!
DFT method has not been calculated for HCCF of method wB97X-D!
C
C
F
H
Electronic part successfully calculated for HCCF of method wB97X-V!
DFT method has not been calculated for HCN of method B3LYP!
DFT method has not been calculated for HCN of method B3LYP5!
DFT method has not been calculated for HCN of method B97-D3!
DFT method has not been calculated for HCN of method B97M-V!
DFT method has not been calculated for HCN of method B97M-rV!
DFT method has not been calculated for HCN of method BLYP!
DFT method has not been calculated for HCN of method BPBE!
DFT method has not been calculated for HCN of method CAM-B3LYP!
DFT method has not been calculated for HCN of method M06-2X!
DFT method has not been calculated for HCN of method M06-L!
DFT method has not been calculated for HCN of method M08-HX!
DFT method has not been calculated for HCN of method MGGA_MS2!
DFT method has not been calculated for HCN of method MN15!
DFT method has not been calculated for HCN of method MN15-L!
C1
H2
N3
Electronic part successfully calculated for HCN of method PBE!
DFT method has not been calculated for HCN of method PBE0!
DFT method has not been calculated for HCN of method SCAN!
DFT method has not been calculated for HCN of method SCAN0!
DFT method has not been calculated for HCN of method SPW92!
DFT method has not been calculated for HCN of method Slater!
DFT method has not been calculated for HCN of method TPSS!
DFT method has not been calculated for HCN of method mBEEF!
DFT method has not been calculated for HCN of method mPW91!
DFT method has not been calculated for HCN of method revM06-L!
DFT method has not been calculated for HCN of method wB97M-V!
DFT method has not been calculated for HCN of method wB97X-D!
DFT method has not been calculated for HCN of method wB97X-V!
DFT method has not been calculated for HCO of method B3LYP!
DFT method has not been calculated for HCO of method B3LYP5!
DFT method has not been calculated for HCO of method B97-D3!
DFT method has not been calculated for HCO of method B97M-V!
DFT method has not been calculated for HCO of method B97M-rV!
DFT method has not been calculated for HCO of method BLYP!
DFT method has not been calculated for HCO of method BPBE!
DFT method has not been calculated for HCO of method CAM-B3LYP!
DFT method has not been calculated for HCO of method M06-2X!
DFT method has not been calculated for HCO of method M06-L!
DFT method has not been calculated for HCO of method M08-HX!
DFT method has not been calculated for HCO of method MGGA_MS2!
DFT method has not been calculated for HCO of method MN15!
DFT method has not been calculated for HCO of method MN15-L!
C1
H2
O3
Electronic part successfully calculated for HCO of method PBE!
C1
H2
O3
Electronic part successfully calculated for HCO of method PBE0!
C1
H2
O3
Electronic part successfully calculated for HCO of method SCAN!
C1
H2
O3
Electronic part successfully calculated for HCO of method SCAN0!
C1
H2
O3
Electronic part successfully calculated for HCO of method SPW92!
DFT method has not been calculated for HCO of method Slater!
DFT method has not been calculated for HCO of method TPSS!
DFT method has not been calculated for HCO of method mBEEF!
DFT method has not been calculated for HCO of method mPW91!
DFT method has not been calculated for HCO of method revM06-L!
DFT method has not been calculated for HCO of method wB97M-V!
DFT method has not been calculated for HCO of method wB97X-D!
DFT method has not been calculated for HCO of method wB97X-V!
DFT method has not been calculated for He of method B3LYP!
DFT method has not been calculated for He of method B3LYP5!
He
Electronic part successfully calculated for He of method B97-D3!

DFT method has not been calculated for Mg of method MN15-L!
DFT method has not been calculated for Mg of method PBE!
DFT method has not been calculated for Mg of method PBE0!
DFT method has not been calculated for Mg of method SCAN!
DFT method has not been calculated for Mg of method SCAN0!
DFT method has not been calculated for Mg of method SPW92!
DFT method has not been calculated for Mg of method Slater!
Mg
Electronic part successfully calculated for Mg of method TPSS!
Mg
Electronic part successfully calculated for Mg of method mBEEF!
Mg
Electronic part successfully calculated for Mg of method mPW91!
DFT method has not been calculated for Mg of method revM06-L!
DFT method has not been calculated for Mg of method wB97M-V!
DFT method has not been calculated for Mg of method wB97X-D!
Mg
Electronic part successfully calculated for Mg of method wB97X-V!
Mg1
Mg2
Electronic part successfully calculated for Mg2 of method B3LYP!
Mg1
Mg2
Electronic part successfully calculated for Mg2 of method B3LYP5!
DFT method has not been calculated for Mg2 of method B97-D3!
DFT method has not been calculated for Mg2 of method B97M-V!
DFT method has not been calculated for Mg2 of method B97M-rV!
DFT method has not been calculated for Mg2 of method BLYP!
Mg1
Mg2
Electronic part successfully calculated for Mg2 of method BPBE!
DFT method has not been calculated for Mg2 of method CAM-B3LYP!
DFT method has not been calculated for Mg2 of method M06-2X!
DFT method has not been calculated for Mg2 of method M06-L!
DFT method has not been calculated for Mg2 of method M08-HX!
DFT method has not been calculated for Mg2 of method MGGA_MS2!
DFT method has not been calculated for Mg2 of method MN15!
DFT method has not been calculated for Mg2 of method MN15-L!
DFT method has not been calculated for Mg2 of method PBE!
DFT method has not been calculated for Mg2 of method PBE0!
DFT method has not been calculated for Mg2 of method SCAN!
DFT method has not been calculated for Mg2 of method SCAN0!
DFT method has not been calculated for Mg2 of method SPW92!
DFT method has not been calculated for Mg2 of method Slater!
Mg1
Mg2
Electronic part successfully calculated for Mg2 of method TPSS!
Mg1
Mg2
Electronic part successfully calculated for Mg2 of method mBEEF!
Mg1
Mg2
Electronic part successfully calculated for Mg2 of method mPW91!
DFT method has not been calculated for Mg2 of method revM06-L!
DFT method has not been calculated for Mg2 of method wB97M-V!
DFT method has not been calculated for Mg2 of method wB97X-D!
Mg1
Mg2
Electronic part successfully calculated for Mg2 of method wB97X-V!
N
Electronic part successfully calculated for N of method B3LYP!
N
Electronic part successfully calculated for N of method B3LYP5!
N
Electronic part successfully calculated for N of method B97-D3!
DFT method has not been calculated for N of method B97M-V!
DFT method has not been calculated for N of method B97M-rV!
DFT method has not been calculated for N of method BLYP!
N
Electronic part successfully calculated for N of method BPBE!
N
Electronic part successfully calculated for N of method CAM-B3LYP!
N
Electronic part successfully calculated for N of method M06-2X!
N
Electronic part successfully calculated for N of method M06-L!
DFT method has not been calculated for N of method M08-HX!
N
Electronic part successfully calculated for N of method MGGA_MS2!
N
Electronic part successfully calculated for N of method MN15!
N
Electronic part successfully calculated for N of method MN15-L!
DFT method has not been calculated for N of method PBE!
DFT method has not been calculated for N of method PBE0!
DFT method has not been calculated for N of method SCAN!
DFT method has not been calculated for N of method SCAN0!
DFT method has not been calculated for N of method SPW92!
N
Electronic part successfully calculated for N of method Slater!
N
Electronic part successfully calculated for N of method TPSS!
N
Electronic part successfully calculated for N of method mBEEF!
N
Electronic part successfully calculated for N of method mPW91!
N
Electronic part successfully calculated for N of method revM06-L!
DFT method has not been calculated for N of method wB97M-V!
DFT method has not been calculated for N of method wB97X-D!
N
Electronic part successfully calculated for N of method wB97X-V!
DFT method has not been calculated for N2 of method B3LYP!
DFT method has not been calculated for N2 of method B3LYP5!
N1
N2
Electronic part successfully calculated for N2 of method B97-D3!
DFT method has not been calculated for N2 of method B97M-V!
DFT method has not been calculated for N2 of method B97M-rV!
DFT method has not been calculated for N2 of method BLYP!
DFT method has not been calculated for N2 of method BPBE!
N1
N2
Electronic part successfully calculated for N2 of method CAM-B3LYP!
N1
N2
Electronic part successfully calculated for N2 of method M06-2X!
N1
N2
Electronic part successfully calculated for N2 of method M06-L!
DFT method has not been calculated for N2 of method M08-HX!
N1
N2
Electronic part successfully calculated for N2 of method MGGA_MS2!
N1
N2
Electronic part successfully calculated for N2 of method MN15!
N1
N2
Electronic part successfully calculated for N2 of method MN15-L!
N1
N2
Electronic part successfully calculated for N2 of method PBE!
N1
N2
Electronic part successfully calculated for N2 of method PBE0!
N1
N2
Electronic part successfully calculated for N2 of method SCAN!
N1
N2
Electronic part successfully calculated for N2 of method SCAN0!
N1
N2
Electronic part successfully calculated for N2 of method SPW92!
N1
N2
Electronic part successfully calculated for N2 of method Slater!
DFT method has not been calculated for N2 of method TPSS!
DFT method has not been calculated for N2 of method mBEEF!
DFT method has not been calculated for N2 of method mPW91!
N1
N2
Electronic part successfully calculated for N2 of method revM06-L!
DFT method has not been calculated for N2 of method wB97M-V!
DFT method has not been calculated for N2 of method wB97X-D!
DFT method has not been calculated for N2 of method wB97X-V!
N
H
N
H
Electronic part successfully calculated for N2H2 of method B3LYP!
N
H
N
H
Electronic part successfully calculated for N2H2 of method B3LYP5!
DFT method has not been calculated for N2H2 of method B97-D3!
DFT method has not been calculated for N2H2 of method B97M-V!
DFT method has not been calculated for N2H2 of method B97M-rV!
DFT method has not been calculated for N2H2 of method BLYP!
N
H
N
H
Electronic part successfully calculated for N2H2 of method BPBE!
DFT method has not been calculated for N2H2 of method CAM-B3LYP!
DFT method has not been calculated for N2H2 of method M06-2X!
DFT method has not been calculated for N2H2 of method M06-L!
DFT method has not been calculated for N2H2 of method M08-HX!
DFT method has not been calculated for N2H2 of method MGGA_MS2!
DFT method has not been calculated for N2H2 of method MN15!
DFT method has not been calculated for N2H2 of method MN15-L!
DFT method has not been calculated for N2H2 of method PBE!
DFT method has not been calculated for N2H2 of method PBE0!
DFT method has not been calculated for N2H2 of method SCAN!
DFT method has not been calculated for N2H2 of method SCAN0!
DFT method has not been calculated for N2H2 of method SPW92!
DFT method has not been calculated for N2H2 of method Slater!
N
H
N
H
Electronic part successfully calculated for N2H2 of method TPSS!
N
H
N
H
Electronic part successfully calculated for N2H2 of method mBEEF!
N
H
N
H
Electronic part successfully calculated for N2H2 of method mPW91!
DFT method has not been calculated for N2H2 of method revM06-L!
DFT method has not been calculated for N2H2 of method wB97M-V!
DFT method has not been calculated for N2H2 of method wB97X-D!
N
H
N
H
Electronic part successfully calculated for N2H2 of method wB97X-V!
DFT method has not been calculated for N2H4 of method B3LYP!
DFT method has not been calculated for N2H4 of method B3LYP5!
DFT method has not been calculated for N2H4 of method B97-D3!
DFT method has not been calculated for N2H4 of method B97M-V!
DFT method has not been calculated for N2H4 of method B97M-rV!
DFT method has not been calculated for N2H4 of method BLYP!
DFT method has not been calculated for N2H4 of method BPBE!
DFT method has not been calculated for N2H4 of method CAM-B3LYP!
DFT method has not been calculated for N2H4 of method M06-2X!
DFT method has not been calculated for N2H4 of method M06-L!
DFT method has not been calculated for N2H4 of method M08-HX!
DFT method has not been calculated for N2H4 of method MGGA_MS2!
DFT method has not been calculated for N2H4 of method MN15!
DFT method has not been calculated for N2H4 of method MN15-L!
N1
N2
H3
H4
H5
H6
Electronic part successfully calculated for N2H4 of method PBE!
DFT method has not been calculated for N2H4 of method PBE0!
DFT method has not been calculated for N2H4 of method SCAN!
DFT method has not been calculated for N2H4 of method SCAN0!
DFT method has not been calculated for N2H4 of method SPW92!
DFT method has not been calculated for N2H4 of method Slater!
DFT method has not been calculated for N2H4 of method TPSS!
DFT method has not been calculated for N2H4 of method mBEEF!
DFT method has not been calculated for N2H4 of method mPW91!
DFT method has not been calculated for N2H4 of method revM06-L!
DFT method has not been calculated for N2H4 of method wB97M-V!
DFT method has not been calculated for N2H4 of method wB97X-D!
DFT method has not been calculated for N2H4 of method wB97X-V!
Na
Electronic part successfully calculated for Na of method B3LYP!
Na
Electronic part successfully calculated for Na of method B3LYP5!
DFT method has not been calculated for Na of method B97-D3!
DFT method has not been calculated for Na of method B97M-V!
DFT method has not been calculated for Na of method B97M-rV!
DFT method has not been calculated for Na of method BLYP!
Na
Electronic part successfully calculated for Na of method BPBE!
DFT method has not been calculated for Na of method CAM-B3LYP!
DFT method has not been calculated for Na of method M06-2X!
DFT method has not been calculated for Na of method M06-L!
DFT method has not been calculated for Na of method M08-HX!
DFT method has not been calculated for Na of method MGGA_MS2!
DFT method has not been calculated for Na of method MN15!
DFT method has not been calculated for Na of method MN15-L!
DFT method has not been calculated for Na of method PBE!
DFT method has not been calculated for Na of method PBE0!
DFT method has not been calculated for Na of method SCAN!
DFT method has not been calculated for Na of method SCAN0!
DFT method has not been calculated for Na of method SPW92!
DFT method has not been calculated for Na of method Slater!
Na
Electronic part successfully calculated for Na of method TPSS!
Na
Electronic part successfully calculated for Na of method mBEEF!
Na
Electronic part successfully calculated for Na of method mPW91!
DFT method has not been calculated for Na of method revM06-L!
DFT method has not been calculated for Na of method wB97M-V!
DFT method has not been calculated for Na of method wB97X-D!
Na
Electronic part successfully calculated for Na of method wB97X-V!
Na1
Na2
Electronic part successfully calculated for Na2 of method B3LYP!
Na1
Na2
Electronic part successfully calculated for Na2 of method B3LYP5!
DFT method has not been calculated for Na2 of method B97-D3!
DFT method has not been calculated for Na2 of method B97M-V!
DFT method has not been calculated for Na2 of method B97M-rV!
DFT method has not been calculated for Na2 of method BLYP!
Na1
Na2
Electronic part successfully calculated for Na2 of method BPBE!
DFT method has not been calculated for Na2 of method CAM-B3LYP!
DFT method has not been calculated for Na2 of method M06-2X!
DFT method has not been calculated for Na2 of method M06-L!
DFT method has not been calculated for Na2 of method M08-HX!
DFT method has not been calculated for Na2 of method MGGA_MS2!
DFT method has not been calculated for Na2 of method MN15!
DFT method has not been calculated for Na2 of method MN15-L!
DFT method has not been calculated for Na2 of method PBE!
DFT method has not been calculated for Na2 of method PBE0!
DFT method has not been calculated for Na2 of method SCAN!
DFT method has not been calculated for Na2 of method SCAN0!
DFT method has not been calculated for Na2 of method SPW92!
DFT method has not been calculated for Na2 of method Slater!
Na1
Na2
Electronic part successfully calculated for Na2 of method TPSS!
Na1
Na2
Electronic part successfully calculated for Na2 of method mBEEF!
Na1
Na2
Electronic part successfully calculated for Na2 of method mPW91!
DFT method has not been calculated for Na2 of method revM06-L!
DFT method has not been calculated for Na2 of method wB97M-V!
DFT method has not been calculated for Na2 of method wB97X-D!
Na1
Na2
Electronic part successfully calculated for Na2 of method wB97X-V!
Na1
Cl2
Electronic part successfully calculated for NaCl of method B3LYP!
Na1
Cl2
Electronic part successfully calculated for NaCl of method B3LYP5!
DFT method has not been calculated for NaCl of method B97-D3!
DFT method has not been calculated for NaCl of method B97M-V!
DFT method has not been calculated for NaCl of method B97M-rV!
DFT method has not been calculated for NaCl of method BLYP!
Na1
Cl2
Electronic part successfully calculated for NaCl of method BPBE!
DFT method has not been calculated for NaCl of method CAM-B3LYP!
DFT method has not been calculated for NaCl of method M06-2X!
DFT method has not been calculated for NaCl of method M06-L!
DFT method has not been calculated for NaCl of method M08-HX!
DFT method has not been calculated for NaCl of method MGGA_MS2!
DFT method has not been calculated for NaCl of method MN15!
DFT method has not been calculated for NaCl of method MN15-L!
DFT method has not been calculated for NaCl of method PBE!
DFT method has not been calculated for NaCl of method PBE0!
DFT method has not been calculated for NaCl of method SCAN!
DFT method has not been calculated for NaCl of method SCAN0!
DFT method has not been calculated for NaCl of method SPW92!
DFT method has not been calculated for NaCl of method Slater!
Na1
Cl2
Electronic part successfully calculated for NaCl of method TPSS!
Na1
Cl2
Electronic part successfully calculated for NaCl of method mBEEF!
Na1
Cl2
Electronic part successfully calculated for NaCl of method mPW91!
DFT method has not been calculated for NaCl of method revM06-L!
DFT method has not been calculated for NaCl of method wB97M-V!
DFT method has not been calculated for NaCl of method wB97X-D!
Na1
Cl2
Electronic part successfully calculated for NaCl of method wB97X-V!
Ne
Electronic part successfully calculated for Ne of method B3LYP!
Ne
Electronic part successfully calculated for Ne of method B3LYP5!
Ne
Electronic part successfully calculated for Ne of method B97-D3!
DFT method has not been calculated for Ne of method B97M-V!
DFT method has not been calculated for Ne of method B97M-rV!
DFT method has not been calculated for Ne of method BLYP!
Ne
Electronic part successfully calculated for Ne of method BPBE!
Ne
Electronic part successfully calculated for Ne of method CAM-B3LYP!
Ne
Electronic part successfully calculated for Ne of method M06-2X!
Ne
Electronic part successfully calculated for Ne of method M06-L!
DFT method has not been calculated for Ne of method M08-HX!
Ne
Electronic part successfully calculated for Ne of method MGGA_MS2!
Ne
Electronic part successfully calculated for Ne of method MN15!
Ne
Electronic part successfully calculated for Ne of method MN15-L!
DFT method has not been calculated for Ne of method PBE!
DFT method has not been calculated for Ne of method PBE0!
DFT method has not been calculated for Ne of method SCAN!
DFT method has not been calculated for Ne of method SCAN0!
DFT method has not been calculated for Ne of method SPW92!
Ne
Electronic part successfully calculated for Ne of method Slater!
Ne
Electronic part successfully calculated for Ne of method TPSS!
Ne
Electronic part successfully calculated for Ne of method mBEEF!
Ne
Electronic part successfully calculated for Ne of method mPW91!
Ne
Electronic part successfully calculated for Ne of method revM06-L!
DFT method has not been calculated for Ne of method wB97M-V!
DFT method has not been calculated for Ne of method wB97X-D!
Ne
Electronic part successfully calculated for Ne of method wB97X-V!
DFT method has not been calculated for NH2 of method B3LYP!
DFT method has not been calculated for NH2 of method B3LYP5!
DFT method has not been calculated for NH2 of method B97-D3!
DFT method has not been calculated for NH2 of method B97M-V!
DFT method has not been calculated for NH2 of method B97M-rV!
DFT method has not been calculated for NH2 of method BLYP!
DFT method has not been calculated for NH2 of method BPBE!
DFT method has not been calculated for NH2 of method CAM-B3LYP!
DFT method has not been calculated for NH2 of method M06-2X!
DFT method has not been calculated for NH2 of method M06-L!
DFT method has not been calculated for NH2 of method M08-HX!
DFT method has not been calculated for NH2 of method MGGA_MS2!
DFT method has not been calculated for NH2 of method MN15!
DFT method has not been calculated for NH2 of method MN15-L!
N1
H2
H3
Electronic part successfully calculated for NH2 of method PBE!
DFT method has not been calculated for NH2 of method PBE0!
DFT method has not been calculated for NH2 of method SCAN!
DFT method has not been calculated for NH2 of method SCAN0!
DFT method has not been calculated for NH2 of method SPW92!
DFT method has not been calculated for NH2 of method Slater!
DFT method has not been calculated for NH2 of method TPSS!
DFT method has not been calculated for NH2 of method mBEEF!
DFT method has not been calculated for NH2 of method mPW91!
DFT method has not been calculated for NH2 of method revM06-L!
DFT method has not been calculated for NH2 of method wB97M-V!
DFT method has not been calculated for NH2 of method wB97X-D!
DFT method has not been calculated for NH2 of method wB97X-V!
Cl
N
H
H
Electronic part successfully calculated for NH2Cl of method B3LYP!
Cl
N
H
H
Electronic part successfully calculated for NH2Cl of method B3LYP5!
DFT method has not been calculated for NH2Cl of method B97-D3!
DFT method has not been calculated for NH2Cl of method B97M-V!
DFT method has not been calculated for NH2Cl of method B97M-rV!
DFT method has not been calculated for NH2Cl of method BLYP!
Cl
N
H
H
Electronic part successfully calculated for NH2Cl of method BPBE!
DFT method has not been calculated for NH2Cl of method CAM-B3LYP!
DFT method has not been calculated for NH2Cl of method M06-2X!
DFT method has not been calculated for NH2Cl of method M06-L!
DFT method has not been calculated for NH2Cl of method M08-HX!
DFT method has not been calculated for NH2Cl of method MGGA_MS2!
DFT method has not been calculated for NH2Cl of method MN15!
DFT method has not been calculated for NH2Cl of method MN15-L!
DFT method has not been calculated for NH2Cl of method PBE!
DFT method has not been calculated for NH2Cl of method PBE0!
DFT method has not been calculated for NH2Cl of method SCAN!
DFT method has not been calculated for NH2Cl of method SCAN0!
DFT method has not been calculated for NH2Cl of method SPW92!
DFT method has not been calculated for NH2Cl of method Slater!
Cl
N
H
H
Electronic part successfully calculated for NH2Cl of method TPSS!
Cl
N
H
H
Electronic part successfully calculated for NH2Cl of method mBEEF!
Cl
N
H
H
Electronic part successfully calculated for NH2Cl of method mPW91!
DFT method has not been calculated for NH2Cl of method revM06-L!
DFT method has not been calculated for NH2Cl of method wB97M-V!
DFT method has not been calculated for NH2Cl of method wB97X-D!
Cl
N
H
H
Electronic part successfully calculated for NH2Cl of method wB97X-V!
N
H
H
F
Electronic part successfully calculated for NH2F of method B3LYP!
N
H
H
F
Electronic part successfully calculated for NH2F of method B3LYP5!

S2
H3
H4
Electronic part successfully calculated for S2H2 of method TPSS!
S1
S2
H3
H4
Electronic part successfully calculated for S2H2 of method mBEEF!
S1
S2
H3
H4
Electronic part successfully calculated for S2H2 of method mPW91!
DFT method has not been calculated for S2H2 of method revM06-L!
DFT method has not been calculated for S2H2 of method wB97M-V!
DFT method has not been calculated for S2H2 of method wB97X-D!
S1
S2
H3
H4
Electronic part successfully calculated for S2H2 of method wB97X-V!
DFT method has not been calculated for SF of method B3LYP!
DFT method has not been calculated for SF of method B3LYP5!
DFT method has not been calculated for SF of method B97-D3!
DFT method has not been calculated for SF of method B97M-V!
DFT method has not been calculated for SF of method B97M-rV!
S1
F2
Electronic part successfully calculated for SF of method BLYP!
DFT method has not been calculated for SF of method BPBE!
DFT method has not been calculated for SF of method CAM-B3LYP!
DFT method has not been calculated for SF of method M06-2X!
DFT method has not been calculated for SF of method M06-L!
DFT method has not been calculated for SF of method M08-HX!
DFT method has not been calculated for SF of method MGGA_MS2!
DFT method has not been calculated for SF of method MN15!
DFT method has not been calculated for SF of method MN15-L!
DFT method has not been calculated for SF of method PBE!
DFT method has not been calculated for SF of method PBE0!
DFT method has not been calculated for SF of method SCAN!
DFT method has not been calculated for SF of method SCAN0!
DFT method has not been calculated for SF of method SPW92!
DFT method has not been calculated for SF of method Slater!
DFT method has not been calculated for SF of method TPSS!
DFT method has not been calculated for SF of method mBEEF!
DFT method has not been calculated for SF of method mPW91!
DFT method has not been calculated for SF of method revM06-L!
DFT method has not been calculated for SF of method wB97M-V!
DFT method has not been calculated for SF of method wB97X-D!
DFT method has not been calculated for SF of method wB97X-V!
DFT method has not been calculated for SH of method B3LYP!
DFT method has not been calculated for SH of method B3LYP5!
DFT method has not been calculated for SH of method B97-D3!
DFT method has not been calculated for SH of method B97M-V!
DFT method has not been calculated for SH of method B97M-rV!
DFT method has not been calculated for SH of method BLYP!
DFT method has not been calculated for SH of method BPBE!
DFT method has not been calculated for SH of method CAM-B3LYP!
DFT method has not been calculated for SH of method M06-2X!
DFT method has not been calculated for SH of method M06-L!
DFT method has not been calculated for SH of method M08-HX!
DFT method has not been calculated for SH of method MGGA_MS2!
DFT method has not been calculated for SH of method MN15!
DFT method has not been calculated for SH of method MN15-L!
DFT method has not been calculated for SH of method PBE!
DFT method has not been calculated for SH of method PBE0!
DFT method has not been calculated for SH of method SCAN!
DFT method has not been calculated for SH of method SCAN0!
DFT method has not been calculated for SH of method SPW92!
DFT method has not been calculated for SH of method Slater!
DFT method has not been calculated for SH of method TPSS!
DFT method has not been calculated for SH of method mBEEF!
DFT method has not been calculated for SH of method mPW91!
DFT method has not been calculated for SH of method revM06-L!
DFT method has not been calculated for SH of method wB97M-V!
S1
H2
Electronic part successfully calculated for SH of method wB97X-D!
S1
H2
Electronic part successfully calculated for SH of method wB97X-V!
DFT method has not been calculated for HCl of method B3LYP!
DFT method has not been calculated for HCl of method B3LYP5!
DFT method has not been calculated for HCl of method B97-D3!
DFT method has not been calculated for HCl of method B97M-V!
DFT method has not been calculated for HCl of method B97M-rV!
DFT method has not been calculated for HCl of method BLYP!
DFT method has not been calculated for HCl of method BPBE!
DFT method has not been calculated for HCl of method CAM-B3LYP!
DFT method has not been calculated for HCl of method M06-2X!
DFT method has not been calculated for HCl of method M06-L!
DFT method has not been calculated for HCl of method M08-HX!
DFT method has not been calculated for HCl of method MGGA_MS2!
DFT method has not been calculated for HCl of method MN15!
DFT method has not been calculated for HCl of method MN15-L!
Cl1
H2
Electronic part successfully calculated for HCl of method PBE!
DFT method has not been calculated for HCl of method PBE0!
DFT method has not been calculated for HCl of method SCAN!
DFT method has not been calculated for HCl of method SCAN0!
DFT method has not been calculated for HCl of method SPW92!
DFT method has not been calculated for HCl of method Slater!
DFT method has not been calculated for HCl of method TPSS!
DFT method has not been calculated for HCl of method mBEEF!
DFT method has not been calculated for HCl of method mPW91!
DFT method has not been calculated for HCl of method revM06-L!
DFT method has not been calculated for HCl of method wB97M-V!
DFT method has not been calculated for HCl of method wB97X-D!
DFT method has not been calculated for HCl of method wB97X-V!
DFT method has not been calculated for NH of method B3LYP!
DFT method has not been calculated for NH of method B3LYP5!
DFT method has not been calculated for NH of method B97-D3!
DFT method has not been calculated for NH of method B97M-V!
DFT method has not been calculated for NH of method B97M-rV!
DFT method has not been calculated for NH of method BLYP!
DFT method has not been calculated for NH of method BPBE!
DFT method has not been calculated for NH of method CAM-B3LYP!
DFT method has not been calculated for NH of method M06-2X!
DFT method has not been calculated for NH of method M06-L!
DFT method has not been calculated for NH of method M08-HX!
DFT method has not been calculated for NH of method MGGA_MS2!
DFT method has not been calculated for NH of method MN15!
DFT method has not been calculated for NH of method MN15-L!
N
H
Electronic part successfully calculated for NH of method PBE!
DFT method has not been calculated for NH of method PBE0!
DFT method has not been calculated for NH of method SCAN!
DFT method has not been calculated for NH of method SCAN0!
DFT method has not been calculated for NH of method SPW92!
DFT method has not been calculated for NH of method Slater!
DFT method has not been calculated for NH of method TPSS!
DFT method has not been calculated for NH of method mBEEF!
DFT method has not been calculated for NH of method mPW91!
DFT method has not been calculated for NH of method revM06-L!
DFT method has not been calculated for NH of method wB97M-V!
DFT method has not been calculated for NH of method wB97X-D!
DFT method has not been calculated for NH of method wB97X-V!
DFT method has not been calculated for PH of method B3LYP!
DFT method has not been calculated for PH of method B3LYP5!
DFT method has not been calculated for PH of method B97-D3!
DFT method has not been calculated for PH of method B97M-V!
DFT method has not been calculated for PH of method B97M-rV!
DFT method has not been calculated for PH of method BLYP!
DFT method has not been calculated for PH of method BPBE!
DFT method has not been calculated for PH of method CAM-B3LYP!
DFT method has not been calculated for PH of method M06-2X!
DFT method has not been calculated for PH of method M06-L!
DFT method has not been calculated for PH of method M08-HX!
DFT method has not been calculated for PH of method MGGA_MS2!
DFT method has not been calculated for PH of method MN15!
DFT method has not been calculated for PH of method MN15-L!
DFT method has not been calculated for PH of method PBE!
DFT method has not been calculated for PH of method PBE0!
DFT method has not been calculated for PH of method SCAN!
DFT method has not been calculated for PH of method SCAN0!
DFT method has not been calculated for PH of method SPW92!
DFT method has not been calculated for PH of method Slater!
DFT method has not been calculated for PH of method TPSS!
DFT method has not been calculated for PH of method mBEEF!
DFT method has not been calculated for PH of method mPW91!
DFT method has not been calculated for PH of method revM06-L!
DFT method has not been calculated for PH of method wB97M-V!
DFT method has not been calculated for PH of method wB97X-D!
DFT method has not been calculated for PH of method wB97X-V!
DFT method has not been calculated for SiO of method B3LYP!
DFT method has not been calculated for SiO of method B3LYP5!
DFT method has not been calculated for SiO of method B97-D3!
DFT method has not been calculated for SiO of method B97M-V!
DFT method has not been calculated for SiO of method B97M-rV!
DFT method has not been calculated for SiO of method BLYP!
DFT method has not been calculated for SiO of method BPBE!
DFT method has not been calculated for SiO of method CAM-B3LYP!
DFT method has not been calculated for SiO of method M06-2X!
DFT method has not been calculated for SiO of method M06-L!
DFT method has not been calculated for SiO of method M08-HX!
DFT method has not been calculated for SiO of method MGGA_MS2!
DFT method has not been calculated for SiO of method MN15!
DFT method has not been calculated for SiO of method MN15-L!
DFT method has not been calculated for SiO of method PBE!
DFT method has not been calculated for SiO of method PBE0!
DFT method has not been calculated for SiO of method SCAN!
DFT method has not been calculated for SiO of method SCAN0!
DFT method has not been calculated for SiO of method SPW92!
DFT method has not been calculated for SiO of method Slater!
DFT method has not been calculated for SiO of method TPSS!
DFT method has not been calculated for SiO of method mBEEF!
DFT method has not been calculated for SiO of method mPW91!
DFT method has not been calculated for SiO of method revM06-L!
DFT method has not been calculated for SiO of method wB97M-V!
DFT method has not been calculated for SiO of method wB97X-D!
DFT method has not been calculated for SiO of method wB97X-V!
DFT method has not been calculated for LiH of method B3LYP!
DFT method has not been calculated for LiH of method B3LYP5!
DFT method has not been calculated for LiH of method B97-D3!
DFT method has not been calculated for LiH of method B97M-V!
DFT method has not been calculated for LiH of method B97M-rV!
DFT method has not been calculated for LiH of method BLYP!
DFT method has not been calculated for LiH of method BPBE!
DFT method has not been calculated for LiH of method CAM-B3LYP!
DFT method has not been calculated for LiH of method M06-2X!
DFT method has not been calculated for LiH of method M06-L!
DFT method has not been calculated for LiH of method M08-HX!
DFT method has not been calculated for LiH of method MGGA_MS2!
DFT method has not been calculated for LiH of method MN15!
DFT method has not been calculated for LiH of method MN15-L!
Li
H
Electronic part successfully calculated for LiH of method PBE!
DFT method has not been calculated for LiH of method PBE0!
DFT method has not been calculated for LiH of method SCAN!
DFT method has not been calculated for LiH of method SCAN0!
DFT method has not been calculated for LiH of method SPW92!
DFT method has not been calculated for LiH of method Slater!
DFT method has not been calculated for LiH of method TPSS!
DFT method has not been calculated for LiH of method mBEEF!
DFT method has not been calculated for LiH of method mPW91!
DFT method has not been calculated for LiH of method revM06-L!
DFT method has not been calculated for LiH of method wB97M-V!
DFT method has not been calculated for LiH of method wB97X-D!
DFT method has not been calculated for LiH of method wB97X-V!

In [371]:
data['LiH']

[{'name': 'LiH',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-5.6189, -5.6189, -11.6417],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, -5.6155, 5.6155],
  'quadrupoles_elec': [-4.1775229153, -4.1775229153, -17.73911130538479],
  'dipoles_elec': [-0.0, -0.0, -5.22323822665, 5.22323822665],
  'std_dev': [1.021949474692854, 1.021949474692854, 1.6521619860277266],
  'spin_polarized': 0}]

In [376]:
save(data)

File saved!

In [375]:
wft_table.to_csv('wft_table_2.csv')

In [401]:
std_dev_dft = make_dft_table('std_dev', get_wft_species())

In [403]:
std_dev_dft.to_csv('dft_table.csv')

In [402]:
std_dev_dft

method       Slater                         SPW92                      \
component        XX        YY        ZZ        XX        YY        ZZ
molecule
Ar         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
Be         1.222163  1.222163  1.222163  0.000000  0.000000  0.000000
BeH        1.039647  1.039647  1.648727  0.000000  0.000000  0.000000
BeH2       0.947195  0.947195  1.893168  0.000000  0.000000  0.000000
BF         0.772480  0.772480  1.444419  0.000000  0.000000  0.000000
BH3        1.360901  1.360881  0.843382  0.000000  0.000000  0.000000
BO         0.786985  0.786985  1.356487  0.777896  0.777896  1.349021
BS         0.834994  0.834994  1.516451  0.825257  0.825257  1.510172
C2H        0.872684  0.872684  1.554235  0.860777  0.860777  1.547621
C2H2       0.868177  0.868177  1.708740  0.000000  0.000000  0.000000
CH3        1.150866  1.150846  0.895335  1.140646  1.140626  0.879825
CH4        1.104664  1.104664  1.104664  1.094495  1.094495  1.094495
CN         0.806147  0.806147  1.356301  0.796731  0.796731  1.351023
CO         0.752230  0.752230  1.336442  0.000000  0.000000  0.000000
F2         0.644183  0.644183  1.468731  0.000000  0.000000  0.000000
H          1.080088  1.080088  1.080088  0.000000  0.000000  0.000000
H2         0.917052  0.917052  1.056143  0.898356  0.898356  1.038896
H2O        0.778713  0.872497  0.834077  0.767132  0.864488  0.824571
HBO        0.780349  0.780349  1.603472  0.000000  0.000000  0.000000
HCN        0.804185  0.804185  1.520467  0.794084  0.794084  1.514564
He         0.665192  0.665192  0.665192  0.654970  0.654970  0.654970
HF         0.674565  0.674565  0.749059  0.666599  0.666599  0.742227
HNC        0.816548  0.816548  1.504585  0.805455  0.805455  1.497646
LiBH4      1.224641  1.224633  1.833917  1.210955  1.210948  1.824402
Mg         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
N          0.784452  0.784452  0.784452  0.000000  0.000000  0.000000
N2         0.750084  0.750084  1.311874  0.741715  0.741715  1.306493
Na         0.903963  0.903963  0.903963  0.878281  0.878281  0.878281
Ne         0.578390  0.578390  0.578390  0.573070  0.573070  0.573070
NH3        0.985267  0.985263  0.921548  0.975743  0.975740  0.906757
NH3O       0.884605  0.884609  1.596591  0.874355  0.874359  1.589847
O2         0.694681  0.694681  1.344357  0.687547  0.687547  1.340376
OF         0.656111  0.690127  1.438590  0.649876  0.682573  1.435119
OH         0.000000  0.000000  0.000000  0.685500  0.761964  0.850544
P          0.833876  0.833876  0.833876  0.822360  0.822360  0.822360
SF         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
HCl        0.773235  0.773235  0.867499  0.764313  0.764313  0.860610
NH         0.790495  0.790495  1.000869  0.780677  0.780677  0.989187
PH         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
SiO        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

method       B97-D3                          BLYP  ... CAM-B3LYP   wB97X-D  \
component        XX        YY        ZZ        XX  ...        ZZ        XX
molecule                                           ...
Ar         0.000000  0.000000  0.000000  0.699083  ...  0.000000  0.000000
Be         1.188805  1.188805  1.188805  0.000000  ...  1.183775  0.000000
BeH        1.011990  1.011990  1.622270  1.009799  ...  1.625435  0.000000
BeH2       0.911522  0.911522  1.891220  0.915632  ...  1.891089  0.000000
BF         0.753267  0.753267  1.438330  0.758263  ...  1.440706  0.000000
BH3        1.348859  1.348839  0.816593  1.352032  ...  0.821178  0.000000
BO         0.772862  0.772862  1.347866  0.000000  ...  1.345646  0.000000
BS         0.000000  0.000000  0.000000  0.826029  ...  0.000000  0.000000
C2H        0.856445  0.856445  1.546506  0.000000  ...  1.545597  0.857499
C2H2       0.851327  0.851327  1.703774  0.855695  ...  1.701898  0.000000
CH3        0.000000  0.000000  0.000000  1.142953  ...  0.000000  1.134273
CH4        1.090712  1.090712  1.090712  0.000000  ...  1.093013  0.000000
CN         0.792636  0.792636  1.347520  0.000000  ...  1.346867  0.793019
CO         0.737792  0.737792  1.328568  0.000000  ...  1.330166  0.736333
F2         0.632598  0.632598  1.464255  0.000000  ...  1.466209  0.000000
H          1.027057  1.027057  1.027057  1.037679  ...  1.034558  0.000000
H2         0.878714  0.878714  1.024211  0.888035  ...  1.028774  0.000000
H2O        0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
HBO        0.764596  0.764596  1.599357  0.000000  ...  1.599000  0.000000
HCN        0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
He         0.641059  0.641059  0.641059  0.000000  ...  0.645538  0.000000
HF         0.660374  0.660374  0.739018  0.000000  ...  0.739048  0.000000
HNC        0.800203  0.800203  1.496513  0.805033  ...  1.496234  0.000000
LiBH4      0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
Mg         0.000000  0.000000  0.000000  0.884862  ...  0.000000  0.000000
N          0.765283  0.765283  0.765283  0.000000  ...  0.770291  0.000000
N2         0.737136  0.737136  1.303883  0.000000  ...  1.305247  0.000000
Na         0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
Ne         0.567968  0.567968  0.567968  0.000000  ...  0.570410  0.000000
NH3        0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
NH3O       0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
O2         0.682419  0.682419  1.337497  0.000000  ...  1.339128  0.000000
OF         0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.641688
OH         0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
P          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
SF         0.000000  0.000000  0.000000  0.710574  ...  0.000000  0.000000
HCl        0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
NH         0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
PH         0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
SiO        0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000

method                          wB97X-V                       wB97M-V  \
component        YY        ZZ        XX        YY        ZZ        XX
molecule
Ar         0.000000  0.000000  0.695487  0.695487  0.695487  0.000000
Be         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
BeH        0.000000  0.000000  1.000947  1.000947  1.633534  0.000000
BeH2       0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
BF         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
BH3        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
BO         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
BS         0.000000  0.000000  0.825305  0.825305  1.504392  0.000000
C2H        0.857499  1.542090  0.860767  0.860767  1.544249  0.864434
C2H2       0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
CH3        1.134253  0.865770  0.000000  0.000000  0.000000  0.000000
CH4        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
CN         0.793019  1.343500  0.796749  0.796749  1.345641  0.799798
CO         0.736333  1.327211  0.740013  0.740013  1.329320  0.742373
F2         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
H          0.000000  0.000000  1.032687  1.032687  1.032687  0.000000
H2         0.000000  0.000000  0.885079  0.885079  1.022177  0.000000
H2O        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
HBO        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
HCN        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
He         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
HF         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
HNC        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
LiBH4      0.000000  0.000000  1.206950  1.206942  1.819029  0.000000
Mg         0.000000  0.000000  0.887916  0.887916  0.887916  0.000000
N          0.000000  0.000000  0.770153  0.770153  0.770153  0.000000
N2         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
Na         0.000000  0.000000  0.892374  0.892374  0.892374  0.000000
Ne         0.000000  0.000000  0.569412  0.569412  0.569412  0.000000
NH3        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
NH3O       0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
O2         0.000000  0.000000  0.685534  0.685534  1.338081  0.000000
OF         0.673777  1.432480  0.645717  0.677780  1.434336  0.647074
OH         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
P          0.000000  0.000000  0.819099  0.819099  0.819099  0.000000
SF         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
HCl        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
NH         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
PH         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
SiO        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

method
component        YY        ZZ
molecule
Ar         0.000000  0.000000
Be         0.000000  0.000000
BeH        0.000000  0.000000
BeH2       0.000000  0.000000
BF         0.000000  0.000000
BH3        0.000000  0.000000
BO         0.000000  0.000000
BS         0.000000  0.000000
C2H        0.864434  1.546439
C2H2       0.000000  0.000000
CH3        0.000000  0.000000
CH4        0.000000  0.000000
CN         0.799798  1.346718
CO         0.742373  1.329327
F2         0.000000  0.000000
H          0.000000  0.000000
H2         0.000000  0.000000
H2O        0.000000  0.000000
HBO        0.000000  0.000000
HCN        0.000000  0.000000
He         0.000000  0.000000
HF         0.000000  0.000000
HNC        0.000000  0.000000
LiBH4      0.000000  0.000000
Mg         0.000000  0.000000
N          0.000000  0.000000
N2         0.000000  0.000000
Na         0.000000  0.000000
Ne         0.000000  0.000000
NH3        0.000000  0.000000
NH3O       0.000000  0.000000
O2         0.000000  0.000000
OF         0.678831  1.434756
OH         0.000000  0.000000
P          0.000000  0.000000
SF         0.000000  0.000000
HCl        0.000000  0.000000
NH         0.000000  0.000000
PH         0.000000  0.000000
SiO        0.000000  0.000000

[40 rows x 81 columns]

In [447]:
quadrupoles_table.loc['HCl']

method      Slater                      SPW92                   B97-D3       \
component       XX       YY       ZZ       XX       YY       ZZ     XX   YY
molecule
HCl       -14.4753 -14.4753 -10.7091 -14.1432 -14.1432 -10.4192    0.0  0.0

method         BLYP  ... CAM-B3LYP wB97X-D           wB97X-V            \
component   ZZ   XX  ...        ZZ      XX   YY   ZZ      XX   YY   ZZ
molecule             ...
HCl        0.0  0.0  ...       0.0     0.0  0.0  0.0     0.0  0.0  0.0

method    wB97M-V
component      XX   YY   ZZ
molecule
HCl           0.0  0.0  0.0

[1 rows x 81 columns]

In [459]:
data['H2O']

[{'name': 'H2O',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.8655, -4.5551, -6.5422],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, 0.0, -1.7955, 1.7955],
  'quadrupoles_elec': [-5.8478183435, -7.48158151357072, -6.8293956923564005],
  'dipoles_elec': [-0.0, 0.0, -0.7064041036500001, 0.7064041036500001],
  'std_dev': [0.7647102943925889, 0.8649613583028274, 0.8233768891941918],
  'spin_polarized': 0},
 {'name': 'H2O',
  'method': 'PBE0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-7.7221, -4.4151, -6.4041],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, -1.8581, 1.8581],
  'quadrupoles_elec': [-5.741203741700001,
   -7.377494733570719,
   -6.7267215186564],
  'dipoles_elec': [0.0, 0.0, -0.73103284043, 0.73103284043],
  'std_dev': [0.7577073143173425, 0.8589234385887208, 0.816901500627688],
  'spin_polarized': 0},
 {'name': 'H2O',
  'method': 'SCAN',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.7121, -4.3967, -6.3978],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, -1.8381, 1.8381],
  'quadrupoles_elec': [-5.733768971700001,
   -7.3638147567707195,
   -6.722037613556401],
  'dipoles_elec': [0.0, 0.0, -0.72316423443, 0.72316423443],
  'std_dev': [0.7572165457582131, 0.8581267247190661, 0.8166848206352636],
  'spin_polarized': 0},
 {'name': 'H2O',
  'method': 'SCAN0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-7.6444, -4.3287, -6.33],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, -1.8841, 1.8841],
  'quadrupoles_elec': [-5.6834355788, -7.31325832077072, -6.671629872956401],
  'dipoles_elec': [-0.0, -0.0, -0.7412620282300001, 0.7412620282300001],
  'std_dev': [0.7538856397889537, 0.8551759070957693, 0.8134299560199905],
  'spin_polarized': 0},
 {'name': 'H2O',
  'method': 'SPW92',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-7.9154, -4.5441, -6.5732],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, -1.8552, 1.8552],
  'quadrupoles_elec': [-5.8849178458, -7.47340326657072, -6.852443479356401],
  'dipoles_elec': [0.0, -0.0, -0.72989189256, 0.72989189256],
  'std_dev': [0.767132181947805, 0.8644884768792884, 0.8245707526873555],
  'spin_polarized': 0},
 {'name': 'H2O',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcV5Zp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-7.719618988154585,
   -4.38306121713678,
   -6.385883602004226],
  'quadrupoles_mp2': [-7.799244981448883,
   -4.3978565874775395,
   -6.4377346499814685],
  'quadrupoles_ccsd': [-7.6809492701728965,
   -4.3497716338939645,
   -6.350172958148031],
  'quadrupoles_hf': [-7.5511, -4.2371, -6.2357],
  'dipoles_ccsdt': array([-0.    , -0.    , -1.8564, -1.8564]),
  'dipoles_mp2': array([-0.    , -0.    , -1.8668, -1.8668]),
  'dipoles_ccsd': array([-0.    , -0.    , -1.8792, -1.8792]),
  'dipoles_hf': [-0.0, 0.0, -1.9814, 1.9814],
  'spin_polarized': 0,
  'dipoles_elec_hf': [-0.0, 0.0, -0.77954279642, 0.77954279642],
  'dipoles_elec_mp2': [0.0, 0.0, 0.7344556840400001, 0.7344556840400001],
  'dipoles_elec_ccsd': [0.0, 0.0, 0.73933421976, 0.73933421976],
  'dipoles_elec_ccsdt': [0.0, 0.0, 0.7303640089200001, 0.7303640089200001],
  'quadrupoles_elec_hf': [-5.6140691747, -7.24515582757072, -6.6015199918564],
  'quadrupoles_elec_mp2': [-5.798559261072672,
   -7.364674652958758,
   -6.751728107320673],
  'quadrupoles_elec_ccsd': [-5.710609120540335,
   -7.3289245959233025,
   -6.686628003361424],
  'quadrupoles_elec_ccsdt': [-5.739359166456207,
   -7.353674635403921,
   -6.713178045723696],
  'std_dev_hf': [0.7492709239454044, 0.8511848111644568, 0.8087491140465854],
  'std_dev_mp2': [0.7614827155669833, 0.8581768263568271, 0.8183999995197219],
  'std_dev_ccsd': [0.7556857230714588, 0.8560913850707355, 0.8143688657181468],
  'std_dev_ccsdt': [0.7575855837102635,
   0.8575356922836461,
   0.8160781143475866]},
 {'name': 'H2O',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-7.73044650917799,
   -4.39557003033776,
   -6.395769599476998],
  'quadrupoles_mp2': [-7.80866021705077,
   -4.410365400678519,
   -6.447284388961384],
  'quadrupoles_ccsd': [-7.691844042933101,
   -4.362011440243316,
   -6.3599244521472045],
  'quadrupoles_hf': [-7.5535, -4.2397, -6.2371],
  'dipoles_ccsdt': array([-0.    , -0.    , -1.8527, -1.8527]),
  'dipoles_mp2': array([-0.    , -0.    , -1.8631, -1.8631]),
  'dipoles_ccsd': array([-0.    , -0.    , -1.8757, -1.8757]),
  'dipoles_hf': [0.0, 0.0, -1.9812, 1.9812],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, 0.0, -0.7794641103600001, 0.7794641103600001],
  'dipoles_elec_mp2': [0.0, 0.0, 0.73299999193, 0.73299999193],
  'dipoles_elec_ccsd': [0.0, 0.0, 0.73795721371, 0.73795721371],
  'dipoles_elec_ccsdt': [0.0, 0.0, 0.72890831681, 0.72890831681],
  'quadrupoles_elec_hf': [-5.6158535195,
   -7.247088867770719,
   -6.602560859656401],
  'quadrupoles_elec_mp2': [-5.805559272192256,
   -7.373974667870983,
   -6.7588281186082435],
  'quadrupoles_elec_ccsd': [-5.718709133507773,
   -7.3380246104285,
   -6.693878014865448],
  'quadrupoles_elec_ccsdt': [-5.747409179304125,
   -7.362974650316147,
   -6.720528057466761],
  'std_dev_hf': [0.7493899865557319, 0.8512983535618238, 0.808814220307882],
  'std_dev_mp2': [0.7619422072698333, 0.8587185026462969, 0.8188467023681114],
  'std_dev_ccsd': [0.756221471098763, 0.8566227063549331, 0.814826357571893],
  'std_dev_ccsdt': [0.7581166914996744,
   0.858077773300075,
   0.8165413231450863]},
 {'name': 'H2O',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-7.758355957873074,
   -4.42953213037515,
   -6.424149809851828],
  'quadrupoles_mp2': [-7.831794796255896,
   -4.439418127847922,
   -6.471091484865513],
  'quadrupoles_ccsd': [-7.719955246551873,
   -4.395301023581702,
   -6.388304662617604],
  'quadrupoles_hf': [-7.559, -4.2447, -6.2426],
  'dipoles_ccsdt': array([-0.   , -0.   , -1.843, -1.843]),
  'dipoles_mp2': array([-0.    , -0.    , -1.8558, -1.8558]),
  'dipoles_ccsd': array([-0.    , -0.    , -1.8658, -1.8658]),
  'dipoles_hf': [0.0, 0.0, -1.9825, 1.9825],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, 0.0, -0.77997556975, 0.77997556975],
  'dipoles_elec_mp2': [0.0, 0.0, 0.73012795074, 0.73012795074],
  'dipoles_elec_ccsd': [0.0, 0.0, 0.73406225374, 0.73406225374],
  'dipoles_elec_ccsdt': [0.0, 0.0, 0.7250920429, 0.7250920429],
  'quadrupoles_elec_hf': [-5.619942643000001,
   -7.25080625277072,
   -6.606649983156401],
  'quadrupoles_elec_mp2': [-5.822759299735945,
   -7.395574702308709,
   -6.776528146849758],
  'quadrupoles_elec_ccsd': [-5.739609166840647,
   -7.362774649980173,
   -6.714978048605349],
  'quadrupoles_elec_ccsdt': [-5.7681592124916,
   -7.388224690565645,
   -6.741628091135608],
  'std_dev_hf': [0.7496627670492914, 0.8515166617730224, 0.8090620368189152],
  'std_dev_mp2': [0.7630700688492469, 0.8599752730345629, 0.8199524049848612],
  'std_dev_ccsd': [0.7576020833419511, 0.8580661192460738, 0.8161552125281542],
  'std_dev_ccsdt': [0.7594839835369539,
   0.8595478282542307,
   0.817866263154797]},
 {'name': 'H2O',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-8.1562, -4.7312, -6.783],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, -1.8255, 1.8255],
  'quadrupoles_elec': [-6.063947107400001,
   -7.61250781327072,
   -7.008424953956401],
  'dipoles_elec': [0.0, -0.0, -0.71820701265, 0.71820701265],
  'std_dev': [0.7787134972119079, 0.8724968660843843, 0.8340769042872748],
  'spin_polarized': 0}]

In [461]:
s = get_wft_species()
b = ['aug-cc-pcV5Zp', 'aug-cc-pcVQZp', 'aug-cc-pcVTZp']
to_change = ['dipoles_mp2', 'dipoles_ccsd', 'dipoles_ccsdt']
for sp in s:
    for ba in b:
        d = retrieve(sp, 'ccsdT', ba)
        if d != {}:
            for t in to_change:
                modify(sp, 'ccsdT', ba, t, np.multiply(sign(d['dipoles_hf'][2]), d[t]).tolist())