In [1]:
import json, re
import pandas as pd
import numpy as np
from get_electronic import get_electronic_dipole, get_electronic_quadrupole, get_stddev
from os import path
from pathlib import Path
from numpy import sign
import subprocess
from IPython.display import display

In [2]:
with open('output.json') as f:
    data = json.load(f)

In [3]:
with open('jacob_ladder.json') as f:
    ladder = json.load(f)

In [4]:
data

{'AlF': [{'name': 'AlF',
   'method': 'BLYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-16.0501, -16.0501, -22.7295],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [-0.0, 0.0, -1.4687, 1.4687],
   'quadrupoles_elec': [-11.932880197700001,
    -11.932880197700001,
    -104.86651449752497],
   'dipoles_elec': [-0.0, 0.0, -28.71515488961, 28.71515488961],
   'std_dev': [0.736480580429654, 0.736480580429654, 1.7501494615108055],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVQZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-15.765946654685989,
    -15.765946654685989,
    -22.819975731761097],
   'quadrupoles_mp2': [-15.832458569625961,
    -15.832458569625961,
    -22.936119389084194],
   'quadrupoles_ccsd': [-15.69775344747287,
    -15.69775344747287,
    -22.96806393845115],
   'quadrupoles_hf': [-15.7093, -15.7093, -23.7877],
   'dipoles_ccsdt': [0, 0, -1.4655, 1.4655],
   'dipoles_mp2': [0, 0, -1.4559, 1.4559],
   'dipoles_ccsd': [0, 0, -1.4688, 1.4688],
   'dipoles_hf': [-0.0, 0.0, -1.3257, 1.3257],
   'spin_polarized': 0,
   'dipoles_elec_hf': [-0.0, 0.0, -28.65889435671, 28.65889435671],
   'dipoles_elec_mp2': [0.0, 0.0, -28.71011898177, 28.71011898177],
   'dipoles_elec_ccsd': [0.0, 0.0, -28.715194232640002, 28.715194232640002],
   'dipoles_elec_ccsdt': [0.0, 0.0, -28.713895912650003, 28.713895912650003],
   'quadrupoles_elec_hf': [-11.679503236100002,
    -11.679503236100002,
    -105.65326185892498],
   'quadrupoles_elec_mp2': [-11.771068799969802,
    -11.771068799969802,
    -105.02013126106313],
   'quadrupoles_elec_ccsd': [-11.670918639866787,
    -11.670918639866787,
    -105.04388129879283],
   'quadrupoles_elec_ccsdt': [-11.721618720985976,
    -11.721618720985976,
    -104.93378112314753],
   'std_dev_hf': [0.7286195926077051, 0.7286195926077051, 1.76222971970599],
   'std_dev_mp2': [0.7314701510087812, 0.7314701510087812, 1.7523136746754397],
   'std_dev_ccsd': [0.7283517706521532,
    0.7283517706521532,
    1.7524498841911726],
   'std_dev_ccsdt': [0.72993208653539, 0.72993208653539, 1.7510654172559652]},
  {'name': 'AlF',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVTZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-15.852297815926025,
    -15.852297815926025,
    -22.919978985249855],
   'quadrupoles_mp2': [-15.917733703841767,
    -15.917733703841767,
    -23.047420925180532],
   'quadrupoles_ccsd': [-15.781750800218608,
    -15.781750800218608,
    -23.055423875360898],
   'quadrupoles_hf': [-15.7334, -15.7334, -23.8192],
   'dipoles_ccsdt': [0, 0, -1.4603, 1.4603],
   'dipoles_mp2': [0, 0, -1.4537, 1.4537],
   'dipoles_ccsd': [0, 0, -1.4669, 1.4669],
   'dipoles_hf': [0.0, 0.0, -1.336, 1.336],
   'spin_polarized': 0,
   'dipoles_elec_hf': [0.0, 0.0, -28.6629466888, 28.6629466888],
   'dipoles_elec_mp2': [0.0, 0.0, -28.70925343511, 28.70925343511],
   'dipoles_elec_ccsd': [0.0, 0.0, -28.71444671507, 28.71444671507],
   'dipoles_elec_ccsdt': [0.0, 0.0, -28.711850075090002, 28.711850075090002],
   'quadrupoles_elec_hf': [-11.697421031800001,
    -11.697421031800001,
    -105.67668138442497],
   'quadrupoles_elec_mp2': [-11.834468900931167,
    -11.834468900931167,
    -105.10288139321543],
   'quadrupoles_elec_ccsd': [-11.73336873969413,
    -11.73336873969413,
    -105.10883140260667],
   'quadrupoles_elec_ccsdt': [-11.785818823291235,
    -11.785818823291235,
    -105.00813124204159],
   'std_dev_hf': [0.7291782744918482, 0.7291782744918482, 1.7623955789783385],
   'std_dev_mp2': [0.7334373896848867, 0.7334373896848867, 1.753415885716737],
   'std_dev_ccsd': [0.730297845206577, 0.730297845206577, 1.753317304912044],
   'std_dev_ccsdt': [0.7319283007387601,
    0.7319283007387601,
    1.7520994210903864]},
  {'name': 'AlF',
   'method': 'B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-15.8582, -15.8582, -22.8759],
   'quadrupoles_off_diag': [0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, -1.494, 1.494],
   'quadrupoles_elec': [-11.790206961400001,
    -11.790206961400001,
    -104.97535953032498],
   'dipoles_elec': [-0.0, 0.0, -28.7251086762, 28.7251086762],
   'std_dev': [0.7320645451361885, 0.7320645451361885, 1.7512250972785075],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'B97-D3',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-15.9475, -15.9475, -22.5785],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, -1.3354, 1.3354],
   'quadrupoles_elec': [-11.856599457500002,
    -11.856599457500002,
    -104.75424947052497],
   'dipoles_elec': [-0.0, -0.0, -28.66271063062, 28.66271063062],
   'std_dev': [0.7341228364362962, 0.7341228364362962, 1.7504677696302324],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'B97M-V',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-15.9206, -15.9206, -22.9013],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [0.0, -0.0, -1.3122, 1.3122],
   'quadrupoles_elec': [-11.836599926200002,
    -11.836599926200002,
    -104.99424384612497],
   'dipoles_elec': [0.0, -0.0, -28.65358304766, 28.65358304766],
   'std_dev': [0.7335034215139882, 0.7335034215139882, 1.7538891513603436],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'BPBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-15.8949, -15.8949, -22.4046],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [-0.0, 0.0, -1.3274, 1.3274],
   'quadrupoles_elec': [-11.8174925673, -11.8174925673, -104.62495882022498],
   'dipoles_elec': [-0.0, 0.0, -28.65956318822, 28.65956318822],
   'std_dev': [0.732911149498417, 0.732911149498417, 1.7488948883174782],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'CAM-B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-15.8274, -15.8274, -22.9891],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, -1.488, 1.488],
   'quadrupoles_elec': [-11.767307869800002,
    -11.767307869800002,
    -105.05952112672497],
   'dipoles_elec': [0.0, 0.0, -28.7227480944, 28.7227480944],
   'std_dev': [0.7313532870271758, 0.7313532870271758, 1.7523969456581596],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'M06-2X',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-15.6868, -15.6868, -22.8742],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [-0.0, 0.0, -1.5757, 1.5757],
   'quadrupoles_elec': [-11.6627750036, -11.6627750036, -104.97409561942497],
   'dipoles_elec': [-0.0, 0.0, -28.75725193171, 28.75725193171],
   'std_dev': [0.7280976146968706, 0.7280976146968706, 1.7501183932581466],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'M06-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-15.5465, -15.5465, -22.3253],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [-0.0, -0.0, -1.2726, 1.2726],
   'quadrupoles_elec': [-11.5584651805, -11.5584651805, -104.56600109412497],
   'dipoles_elec': [-0.0, -0.0, -28.638003207780002, 28.638003207780002],
   'std_dev': [0.7248343127445183, 0.7248343127445183, 1.7488584212468357],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'M08-HX',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 5,
   'quadrupoles': [-15.8054, -15.8054, -23.122],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [0.0, 0.0, -1.4382, 1.4382],
   'quadrupoles_elec': [-11.750951375800001,
    -11.750951375800001,
    -105.15832922002497],
   'dipoles_elec': [0.0, 0.0, -28.70315526546, 28.70315526546],
   'std_dev': [0.7308448217271944, 0.7308448217271944, 1.7543406148958742],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'mBEEF',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-15.7948, -15.7948, -22.67],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [0.0, 0.0, -1.2938, 1.2938],
   'quadrupoles_elec': [-11.743070519600002,
    -11.743070519600002,
    -104.82227761602498],
   'dipoles_elec': [0.0, 0.0, -28.646343930140002, 28.646343930140002],
   'std_dev': [0.7305997075752844, 0.7305997075752844, 1.7519039742807196],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'MGGA_MS2',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-15.8565, -15.8565, -22.5287],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [-0.0, -0.0, -1.2226, 1.2226],
   'quadrupoles_elec': [-11.7889430505, -11.7889430505, -104.71722431592498],
   'dipoles_elec': [-0.0, -0.0, -28.61833169278, 28.61833169278],
   'std_dev': [0.7320253054027572, 0.7320253054027572, 1.7514869869453178],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'MN15',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 5,
   'quadrupoles': [-16.0902, -16.0902, -22.8059],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [0.0, -0.0, -1.4675, 1.4675],
   'quadrupoles_elec': [-11.9626936254, -11.9626936254, -104.92331614032497],
   'dipoles_elec': [0.0, -0.0, -28.71468277325, 28.71468277325],
   'std_dev': [0.73740002790517, 0.73740002790517, 1.7509029242780398],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'MN15-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-16.4612, -16.4612, -23.2589],
   'quadrupoles_off_diag': [0.0, -0.0, 0.0],
   'dipoles': [0.0, -0.0, -1.1293, 1.1293],
   'quadrupoles_elec': [-12.238523592400002,
    -12.238523592400002,
    -105.26011122132498],
   'dipoles_elec': [0.0, -0.0, -28.58162464579, 28.58162464579],
   'std_dev': [0.7458528855795041, 0.7458528855795041, 1.759750392867979],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'mPW91',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-15.9517, -15.9517, -22.4914],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, -1.3683, 1.3683],
   'quadrupoles_elec': [-11.859722060900001,
    -11.859722060900001,
    -104.68949262382498],
   'dipoles_elec': [-0.0, -0.0, -28.67565448749, 28.67565448749],
   'std_dev': [0.7342195008956481, 0.7342195008956481, 1.7491885234516276],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'PBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-16.0218, -16.0218, -22.5389],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [-0.0, -0.0, -1.3739, 1.3739],
   'quadrupoles_elec': [-11.9118397986, -11.9118397986, -104.72480778132498],
   'dipoles_elec': [-0.0, -0.0, -28.67785769717, 28.67785769717],
   'std_dev': [0.7358310020464803, 0.7358310020464803, 1.7495727040852576],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'PBE0',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-15.8087, -15.8087, -22.7713],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, -1.3962, 1.3962],
   'quadrupoles_elec': [-11.7534048499, -11.7534048499, -104.89759183612497],
   'dipoles_elec': [0.0, 0.0, -28.686631192860002, 28.686631192860002],
   'std_dev': [0.7309211140714534, 0.7309211140714534, 1.7515189459954332],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'revM06-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-15.7056, -15.7056, -22.9822],
   'quadrupoles_off_diag': [0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, -1.0327, 1.0327],
   'quadrupoles_elec': [-11.676752371200001,
    -11.676752371200001,
    -105.05439113542498],
   'dipoles_elec': [-0.0, 0.0, -28.543619278810002, 28.543619278810002],
   'std_dev': [0.7285337819333993, 0.7285337819333993, 1.7583674830553235],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'SCAN',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-15.8629, -15.8629, -22.5801],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [-0.0, -0.0, -1.2952, 1.2952],
   'quadrupoles_elec': [-11.7937013033, -11.7937013033, -104.75543903372497],
   'dipoles_elec': [-0.0, -0.0, -28.64689473256, 28.64689473256],
   'std_dev': [0.7321730205137184, 0.7321730205137184, 1.751018051530094],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'SCAN0',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 5,
   'quadrupoles': [-15.7386, -15.7386, -22.8153],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, -1.3681, 1.3681],
   'quadrupoles_elec': [-11.701287112200001,
    -11.701287112200001,
    -104.93030482412497],
   'dipoles_elec': [-0.0, -0.0, -28.67557580143, 28.67557580143],
   'std_dev': [0.7292987638260344, 0.7292987638260344, 1.7523172725072522],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'Slater',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 1,
   'quadrupoles': [-16.5721, -16.5721, -22.7699],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [0.0, -0.0, -1.3479, 1.3479],
   'quadrupoles_elec': [-12.3209751917, -12.3209751917, -104.89655096832497],
   'dipoles_elec': [0.0, -0.0, -28.66762850937, 28.66762850937],
   'std_dev': [0.748361093921547, 0.748361093921547, 1.7521481484732255],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'SPW92',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 1,
   'quadrupoles': [-16.0118, -16.0118, -22.4027],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [0.0, -0.0, -1.4595, 1.4595],
   'quadrupoles_elec': [-11.904405028600001,
    -11.904405028600001,
    -104.62354621392498],
   'dipoles_elec': [0.0, -0.0, -28.71153533085, 28.71153533085],
   'std_dev': [0.735601331892363, 0.735601331892363, 1.7471143597536007],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'TPSS',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-15.926, -15.926, -22.5578],
   'quadrupoles_off_diag': [0.0, 0.0, -0.0],
   'dipoles': [0.0, 0.0, -1.2602, 1.2602],
   'quadrupoles_elec': [-11.840614702000002,
    -11.840614702000002,
    -104.73885949662497],
   'dipoles_elec': [0.0, 0.0, -28.633124672060003, 28.633124672060003],
   'std_dev': [0.7336278069851349, 0.7336278069851349, 1.7512681830156718],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'wB97M-V',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 7,
   'quadrupoles': [-15.9272, -15.9272, -22.8982],
   'quadrupoles_off_diag': [0.0, -0.0, 0.0],
   'dipoles': [0.0, -0.0, -1.5462, 1.5462],
   'quadrupoles_elec': [-11.8415068744, -11.8415068744, -104.99193906742498],
   'dipoles_elec': [0.0, -0.0, -28.745645737860002, 28.745645737860002],
   'std_dev': [0.7336554453370651, 0.7336554453370651, 1.7507439449380346],
   'spin_polarized': 0},
  {'name': 'AlF',
   'method': 'wB97X-V',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-15.8375, -15.8375, -22.9766],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [0.0, 0.0, -1.3291, 1.3291],
   'quadrupoles_elec': [-11.774816987500001,
    -11.774816987500001,
    -105.05022766422498],
   'dipoles_elec': [0.0, 0.0, -28.660232019730003, 28.660232019730003],
   'std_dev': [0.7315866004631801, 0.7315866004631801, 1.7543900715394225],
   'spin_polarized': 0}],
 'Ar': [{'name': 'Ar',
   'method': 'B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-11.7543, -11.7543, -11.7543],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.739051701100001,
    -8.739051701100001,
    -8.739051701100001],
   'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
   'std_dev': [0.6967803615798406, 0.6967803615798406, 0.6967803615798406],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'BLYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.8321, -11.8321, -11.8321],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-8.796894211700002,
    -8.796894211700002,
    -8.796894211700002],
   'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.6990825023517929, 0.6990825023517929, 0.6990825023517929],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'BPBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.695, -11.695, -11.695],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.694963515000001,
    -8.694963515000001,
    -8.694963515000001],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [0.6950205238776127, 0.6950205238776127, 0.6950205238776127],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'mBEEF',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-11.5602, -11.5602, -11.5602],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-8.5947428154, -8.5947428154, -8.5947428154],
   'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.6910034095188436, 0.6910034095188436, 0.6910034095188436],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'mPW91',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.7286, -11.7286, -11.7286],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [-0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-8.719944342200002,
    -8.719944342200002,
    -8.719944342200002],
   'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.6960182126528331, 0.6960182126528331, 0.6960182126528331],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'TPSS',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-11.6976, -11.6976, -11.6976],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.6968965552, -8.6968965552, -8.6968965552],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [0.6950977771028573, 0.6950977771028573, 0.6950977771028573],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'wB97X-V',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-11.7107, -11.7107, -11.7107],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.7066361039, -8.7066361039, -8.7066361039],
   'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
   'std_dev': [0.695486883968506, 0.695486883968506, 0.695486883968506],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcV5Zp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-11.63857633767873,
    -11.63857633767873,
    -11.63857633767873],
   'quadrupoles_mp2': [-11.656129027221297,
    -11.656129027221297,
    -11.656129027221297],
   'quadrupoles_ccsd': [-11.624722491366455,
    -11.624722491366455,
    -11.624722491366455],
   'quadrupoles_hf': [-11.6741, -11.6741, -11.6741],
   'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_hf': [0.0, -0.0, -0.0, 0.0],
   'spin_polarized': 0,
   'dipoles_elec_hf': [0.0, -0.0, -0.0, 0.0],
   'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec_hf': [-8.6794248457, -8.6794248457, -8.6794248457],
   'quadrupoles_elec_mp2': [-8.66606384077141,
    -8.66606384077141,
    -8.66606384077141],
   'quadrupoles_elec_ccsd': [-8.642713803713658,
    -8.642713803713658,
    -8.642713803713658],
   'quadrupoles_elec_ccsdt': [-8.65301381980837,
    -8.65301381980837,
    -8.65301381980837],

In [4]:
def search(key, value, molecule):
    result = []
    for d in data[molecule]:
        if d[key] == value:
            result.append(d)
    return result

In [5]:
def load():
    global data
    with open('output.json') as f:
        data = json.load(f)

In [6]:
def save(data):
    with open("output.json", 'w') as outfile:
        json.dump(data, outfile)
    result = subprocess.run(['sh', 'commit.sh'], stdout=subprocess.PIPE)
    print(result.stdout)
    print('File saved!')

In [7]:
def save_as(data, name):
    with open(name, 'w') as outfile:
        json.dump(data, outfile)
    print('File saved as {0}!'.format(name))

In [8]:
def retrieve(molecule, method, basis):
    d = data[molecule]
    for m in d:
        if m['method'] == method and m['basis'] == basis:
            return m
    return {}

In [9]:
def get_dft_species():
    result = []
    for v in data.values():
        for d in v:
            if d['method_type'] == 'dft':
                result.append(d['name'])
                break
    return result
def get_wft_species():
    result = []
    for v in data.values():
        for d in v:
            if d['method_type'] == 'wft':
                result.append(d['name'])
                break
    return result

In [10]:
def get_functionals():
    functionals = []
    for v in data.values():
        for n in v:
            if n['method_type'] == 'dft':
                functionals.append(n['method'])
    functionals = np.unique(functionals)
    return functionals

In [11]:
def delete(molecule, method, basis):
    for c, d in enumerate(data[molecule]):
        if d.get('method') == method and d.get('basis') == basis:
            data[molecule].pop(c)
    return

def pop(molecule, method, basis, key):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d.pop(key, None)
    return

def modify(molecule, method, basis, old, new):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d[old] = new
    return

def add(molecule, method, basis, key, value):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d[key] = value

In [12]:
from pymatgen.core.periodic_table import Element

In [13]:
def count_e(name):
    if name == 'CH2-t':
        return 8
    l = [a for a in re.split(r'([A-Z][a-z]*)', name) if a]
    c = 0
    e = 0
    prev = ''
    while c < len(l):
        if l[c].isnumeric():
            e -= Element(prev).Z
            e += Element(prev).Z * int(l[c])
        else:
            e += Element(l[c]).Z
            prev = l[c]
        c += 1
    return e

In [14]:
functionals_sorted = sorted(sorted(get_functionals(), key=lambda v: v.upper()), key=lambda x: ladder[x])
functionals_sorted

['Slater',
 'SPW92',
 'B97-D3',
 'BLYP',
 'BPBE',
 'mPW91',
 'N12',
 'PBE',
 'SOGGA11',
 'B97M-V',
 'M06-L',
 'mBEEF',
 'MGGA_MS2',
 'MN15-L',
 'revM06-L',
 'SCAN',
 'TPSS',
 'B3LYP',
 'B97-2',
 'HFLYP',
 'M06-2X',
 'PBE0',
 'M06',
 'M08-HX',
 'MN15',
 'SCAN0',
 'TPSSh',
 'CAM-B3LYP',
 'wB97X-D',
 'wB97X-V',
 'wB97M-V',
 'wM05-D']

In [15]:
def make_dft_table(key, domain=data.keys()):
    """
    Makes a table of molecules in DOMAIN of desired KEY.
    """
    values = []
    index = pd.MultiIndex.from_product([domain], names=['molecule'])
    columns = pd.MultiIndex.from_product([functionals_sorted, ['XX','YY','ZZ']], names=['method', 'component'])
    for d in domain:
        value = data[d]
        temp = [[0, 0, 0] for i in range(len(functionals_sorted))]
        for i in value:
            if i['method_type'] == 'dft':
                method = i['method']
                ind = functionals_sorted.index(method)
                temp[ind] = i[key]
        values.append(np.ravel(temp).tolist())
    df = pd.DataFrame(values, index=index, columns=columns)
    return df

In [16]:
quadrupoles_table = make_dft_table('quadrupoles')

In [17]:
make_dft_table('std_dev').loc['He']

method       Slater                        SPW92                      B97-D3  \
component        XX        YY        ZZ       XX       YY       ZZ        XX
molecule
He         0.665192  0.665192  0.665192  0.65497  0.65497  0.65497  0.641059

method                             BLYP  ...   wB97X-D   wB97X-V            \
component        YY        ZZ        XX  ...        ZZ        XX        YY
molecule                                 ...
He         0.641059  0.641059  0.647148  ...  0.635556  0.642392  0.642392

method                wB97M-V                     wM05-D
component        ZZ        XX        YY        ZZ     XX   YY   ZZ
molecule
He         0.642392  0.643086  0.643086  0.643086    0.0  0.0  0.0

[1 rows x 96 columns]

In [21]:
make_dft_table('std_dev').loc['BeH2']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
BeH2       0.947195  0.947195  1.893168   0.0  0.0  0.0  0.911522  0.911522

method                  BLYP  ... CAM-B3LYP wB97X-D           wB97X-V       \
component       ZZ        XX  ...        ZZ      XX   YY   ZZ      XX   YY
molecule                      ...
BeH2       1.89122  0.915632  ...  1.891089     0.0  0.0  0.0     0.0  0.0

method         wB97M-V
component   ZZ      XX   YY   ZZ
molecule
BeH2       0.0     0.0  0.0  0.0

[1 rows x 81 columns]

In [22]:
make_dft_table('std_dev').loc['Ne']

method      Slater                      SPW92                      B97-D3  \
component       XX       YY       ZZ       XX       YY       ZZ        XX
molecule
Ne         0.57839  0.57839  0.57839  0.57307  0.57307  0.57307  0.567968

method                             BLYP  ... CAM-B3LYP   wB97X-D            \
component        YY        ZZ        XX  ...        ZZ        XX        YY
molecule                                 ...
Ne         0.567968  0.567968  0.573919  ...   0.57041  0.565304  0.565304

method                wB97X-V                       wB97M-V            \
component        ZZ        XX        YY        ZZ        XX        YY
molecule
Ne         0.565304  0.569412  0.569412  0.569412  0.569934  0.569934

method
component        ZZ
molecule
Ne         0.569934

[1 rows x 81 columns]

In [23]:
make_dft_table('std_dev').loc['Be']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
Be         1.222163  1.222163  1.222163   0.0  0.0  0.0  1.188805  1.188805

method              BLYP  ... CAM-B3LYP wB97X-D           wB97X-V            \
component        ZZ   XX  ...        ZZ      XX   YY   ZZ      XX   YY   ZZ
molecule                  ...
Be         1.188805  0.0  ...  1.183775     0.0  0.0  0.0     0.0  0.0  0.0

method    wB97M-V
component      XX   YY   ZZ
molecule
Be            0.0  0.0  0.0

[1 rows x 81 columns]

In [24]:
make_dft_table('std_dev').loc['N']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
N          0.784452  0.784452  0.784452   0.0  0.0  0.0  0.765283  0.765283

method                   BLYP  ... CAM-B3LYP   wB97X-D                      \
component        ZZ        XX  ...        ZZ        XX        YY        ZZ
molecule                       ...
N          0.765283  0.775054  ...  0.770291  0.764623  0.764623  0.764623

method      wB97X-V                       wB97M-V
component        XX        YY        ZZ        XX        YY        ZZ
molecule
N          0.770153  0.770153  0.770153  0.773229  0.773229  0.773229

[1 rows x 81 columns]

In [18]:
wft_method = ['hf', 'MP2', 'CCSD', 'CCSD\(T\)']
wft_basis = ['aug-cc-pcV5Zp', 'aug-cc-pcVQZp', 'aug-cc-pcVTZp', 'CBS']

In [19]:
def make_table_wft_extrap(domain=data.keys()):
    """
    Makes a table of DOMAIN of wft method of desired KEY.
    """
    values = np.array([])
    index = pd.MultiIndex.from_product([domain, ['5Z', 'QZ', 'TZ', 'CBS']], names=['molecule', 'basis'])
    columns = pd.MultiIndex.from_product([wft_method, ['XX','YY','ZZ']], names=['method', 'component'])
    for d in domain:
        m_name = d
        for b in wft_basis:
            temp = [[0, 0, 0] for k in range(len(wft_method))]
            info = search('basis', b, m_name)
            if info != []:
                temp[0] = info[0]['std_dev_hf']
                temp[1] = info[0]['std_dev_mp2']
                temp[2] = info[0]['std_dev_ccsd']
                temp[3] = info[0]['std_dev_ccsdt']
            temp = np.ravel(temp)
            values = np.vstack((values, temp)) if values.size else temp
    df = pd.DataFrame(values, index=index, columns=columns)
    return df

In [20]:
wft_table = make_table_wft_extrap(get_wft_species())

KeyError: 'std_dev_hf'

In [44]:
wft_table[wft_table.index.get_level_values('basis') == '5Z']

method               hf                          MP2                        \
component            XX       YY       ZZ         XX         YY         ZZ
molecule basis
AlF      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
Ar       5Z    -11.6741 -11.6741 -11.6741 -11.656129 -11.656129 -11.656129
Be       5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
BeH      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
BeH2     5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
...                 ...      ...      ...        ...        ...        ...
HCl      5Z    -14.0726 -14.0726 -10.2180 -14.012628 -14.012628 -10.243776
NH       5Z     -6.2690  -6.2690  -5.4578  -6.372837  -5.470655   0.836409
PH       5Z    -14.4015 -14.4015 -15.4878 -14.363615 -15.049447  -0.236188
SiO      5Z    -16.0826 -16.0826 -25.3663 -16.569470 -16.569470 -23.618388
LiH      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000

method               CCSD                        CCSD\(T\)             \
component              XX         YY         ZZ         XX         YY
molecule basis
AlF      5Z      0.000000   0.000000   0.000000   0.000000   0.000000
Ar       5Z    -11.624722 -11.624722 -11.624722 -11.638576 -11.638576
Be       5Z      0.000000   0.000000   0.000000   0.000000   0.000000
BeH      5Z      0.000000   0.000000   0.000000   0.000000   0.000000
BeH2     5Z      0.000000   0.000000   0.000000   0.000000   0.000000
...                   ...        ...        ...        ...        ...
HCl      5Z    -13.947865 -13.947865 -10.236849 -13.963534 -13.963534
NH       5Z     -6.347012  -5.482626   0.822085  -6.365237  -5.506568
PH       5Z    -14.302954 -15.020933  -0.233700 -14.315261 -14.995915
SiO      5Z    -16.259103 -16.259103 -24.055255 -16.382039 -16.382039
LiH      5Z      0.000000   0.000000   0.000000   0.000000   0.000000

method
component              ZZ
molecule basis
AlF      5Z      0.000000
Ar       5Z    -11.638576
Be       5Z      0.000000
BeH      5Z      0.000000
BeH2     5Z      0.000000
...                   ...
HCl      5Z    -10.266440
NH       5Z      0.814889
PH       5Z     -0.229194
SiO      5Z    -23.702654
LiH      5Z      0.000000

[73 rows x 12 columns]

In [494]:
wft_table.loc['C2H']

method           hf                           MP2                      \
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.860498  0.860498  1.545005 -0.000000 -0.000000  1.383428
QZ         0.860668  0.860668  1.545016  0.870421  0.870421  1.547620
TZ         0.861166  0.861166  1.544931  0.871710  0.871710  1.548739
CBS        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

method         CCSD                     CCSD\(T\)
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z        -0.000000 -0.000000  1.383428 -0.000000 -0.000000  1.383428
QZ         0.855555  0.855555  1.557354  0.855798  0.855798  1.558396
TZ         0.857163  0.857163  1.558318  0.857549  0.857549  1.559362
CBS        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

In [341]:
save(data)

File saved!

In [87]:
data['HBS']

[{'name': 'HBS',
  'method': 'B97-2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-19.6484, -19.6484, -19.341],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 1.4588, 1.4588],
  'quadrupoles_elec': [-14.6081334868, -14.6081334868, -165.44134642761856],
  'dipoles_elec': [-0.0, 0.0, 46.72643396564, 46.72643396564],
  'std_dev': [0.814865674563494, 0.814865674563494, 1.734643359076025],
  'spin_polarized': 0},
 {'name': 'HBS',
  'method': 'HFLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-19.916, -19.916, -19.9894],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, 2.0072, 2.0072],
  'quadrupoles_elec': [-14.807087932000002,
   -14.807087932000002,
   -165.92341691441857],
  'dipoles_elec': [0.0, -0.0, 46.94219114216, 46.94219114216],
  'std_dev': [0.8203959114077456, 0.8203959114077456, 1.728914209790152],
  'spin_polarized': 0},
 {'name': 'HBS',
  'method': 'M06',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-19.5807, -19.5807, -19.2654],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 1.337, 1.337],
  'quadrupoles_elec': [-14.557800093900001,
   -14.557800093900001,
   -165.38513956641856],
  'dipoles_elec': [-0.0, 0.0, 46.6785141551, 46.6785141551],
  'std_dev': [0.8134606235622986, 0.8134606235622986, 1.736571493230825],
  'spin_polarized': 0},
 {'name': 'HBS',
  'method': 'N12',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-19.5398, -19.5398, -19.4169],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, 1.4219, 1.4219],
  'quadrupoles_elec': [-14.5273918846, -14.5273918846, -165.49777633191854],
  'dipoles_elec': [0.0, 0.0, 46.71191638756999, 46.71191638756999],
  'std_dev': [0.8126106046284072, 0.8126106046284072, 1.7361898691625886],
  'spin_polarized': 0},
 {'name': 'HBS',
  'method': 'SOGGA11',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-20.6406, -20.6406, -20.2532],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, 1.4823, 1.4823],
  'quadrupoles_elec': [-15.345811366200001,
   -15.345811366200001,
   -166.11954614701855],
  'dipoles_elec': [0.0, 0.0, 46.73567957768999, 46.73567957768999],
  'std_dev': [0.8351867337798285, 0.8351867337798285, 1.7429944012358327],
  'spin_polarized': 0},
 {'name': 'HBS',
  'method': 'TPSSh',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-19.6595, -19.6595, -19.3559],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 1.4039, 1.4039],
  'quadrupoles_elec': [-14.616386081500002,
   -14.616386081500002,
   -165.45242423491857],
  'dipoles_elec': [-0.0, -0.0, 46.70483464217, 46.70483464217],
  'std_dev': [0.8150958137070312, 0.8150958137070312, 1.7359898182898792],
  'spin_polarized': 0},
 {'name': 'HBS',
  'method': 'wM05-D',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 7,
  'quadrupoles': [-19.8032, -19.8032, -19.295],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.4118, 1.4118],
  'quadrupoles_elec': [-14.7232237264, -14.7232237264, -165.40714648561857],
  'dipoles_elec': [0.0, -0.0, 46.707942741539995, 46.707942741539995],
  'std_dev': [0.8180693382037313, 0.8180693382037313, 1.7352241070023091],
  'spin_polarized': 0},
 {'name': 'HBS',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-19.751012409398303,
   -19.751012409398303,
   -19.29894659282905],
  'quadrupoles_mp2': [-19.797819580747248,
   -19.797819580747248,
   -19.33875958966734],
  'quadrupoles_ccsd': [-19.78376397884229,
   -19.78376397884229,
   -19.410584387227104],
  'quadrupoles_hf': [-20.1522, -20.1522, -20.3084],
  'dipoles_ccsdt': [],
  'dipoles_mp2': [],
  'dipoles_ccsd': [],
  'dipoles_hf': [0.0, 0.0, 2.0119, 2.0119],
  'spin_polarized': 0},
 {'name': 'HBS',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-19.837498074111938,
   -19.837498074111938,
   -19.359674862991632],
  'quadrupoles_mp2': [-19.881077164770474,
   -19.881077164770474,
   -19.4202013783261],
  'quadrupoles_ccsd': [-19.865340270974652,
   -19.865340270974652,
   -19.461830170146573],
  'quadrupoles_hf': [-20.1635, -20.1635, -20.3306],
  'dipoles_ccsdt': [],
  'dipoles_mp2': [],
  'dipoles_ccsd': [],
  'dipoles_hf': [-0.0, -0.0, 2.0199, 2.0199],
  'spin_polarized': 0}]

In [90]:
#this cell block is used to modify dipole values
modify('HBS', 'ccsdT', 'aug-cc-pcVQZp', 'dipoles_c', [0, 0, 1.4791, 1.4791])

In [501]:
save(data)

b"\x1b[0;32mSaving updates to GitHub...\x1b[0m\nOn branch master\nYour branch is up to date with 'origin/master'.\n\nChanges not staged for commit:\n\tmodified:   ../geometries/cbs_limit/LiH_ccsdT_aug-cc-pcV5Z.inp\n\tmodified:   ../geometries/cbs_limit/LiH_ccsdT_aug-cc-pcVQZ.inp\n\tmodified:   ../geometries/cbs_limit/LiH_ccsdT_aug-cc-pcVTZ.inp\n\tmodified:   ../geometries/cbs_limit/Mg_ccsdT_aug-cc-pcV5Z.inp\n\tmodified:   ../geometries/cbs_limit/Na_ccsdT_aug-cc-pcV5Z.inp\n\tmodified:   ../geometries/cbs_limit/make_input.py\n\tdeleted:    ../geometries/inputs/dft/Be_B3LYP5_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B3LYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B97-D3_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B97M-V_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_BLYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_BPBE_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_CAM-B3LYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M06-2X_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M06-L_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M08-HX_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MGGA_MS2_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MN15-L_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MN15_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_PBE0_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_PBE_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SCAN0_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SCAN_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SPW92_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_Slater_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_TPSS_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_mBEEF_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_mPW91_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_revM06-L_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_B3LYP_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_B97-D3_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_B97M-V_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_M06-2X_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_M06-L_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_M08-HX_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_MGGA_MS2_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_MN15-L_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_MN15_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_revM06-L_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_wB97M-V_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_wB97X-D_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_wB97X-V_aug-pc-4.inp\n\tmodified:   .ipynb_checkpoints/ouput-checkpoint.ipynb\n\tdeleted:    cbs_limit/20-08-03/AlF_ccsdT_aug-cc-pcVTZp.out\n\tmodified:   dft_table.csv\n\tmodified:   mp2/HF.ipynb\n\tmodified:   ouput.ipynb\n\tmodified:   output.json\n\tmodified:   output.py\n\tmodified:   wft_table_2.csv\n\nUntracked files:\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/AlF_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/BH2F_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/BO_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/C2H2_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2BH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2BH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2BH_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2NH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2NH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3O_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH3O_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH4_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CO2_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CO_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/FCN_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/FCO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/FCO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/H2CN_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/H2CN_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/H2CN_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HBO_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HCCF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HCCF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HCCF_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HCN_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HCO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HCO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HNC_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HNS_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HNS_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/LiBH4_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2Cl_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2Cl_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2OH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2OH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NaCl_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/O3_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/O3_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/hf/C2H2_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/C2H_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HBO_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HCN_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HF_ccsdT_aug-cc-pc-V5Z.inp\n\t../geometries/cbs_limit/hf/HNC_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/LiBH4_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/LiH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/hf/NH3O_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/NH3_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/O3_hf_aug-cc-pcV5Z.inp\n\t../geometries/inputs/HF_MP2_aug-cc-pcVDZ.inp\n\t../geometries/inputs/NH3-F2_TDDFT_aug-pc-2.inp\n\t../geometries/inputs/dft/BHF2_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/BHF2_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/BHF2_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/BHF2_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/BHF2_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/BHF2_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/BHF2_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/BHF2_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/BN_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/BN_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/BN_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/BN_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/BN_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/BN_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/BN_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/BN_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/C2H4_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/C2H4_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/C2H4_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/C2H4_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/C2H4_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/C2H4_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/C2H4_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/C2H4_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3Cl_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3Cl_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3Cl_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3Cl_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3Cl_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3Cl_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3Cl_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3Cl_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/CSO_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/CSO_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CSO_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/CSO_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/CSO_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/CSO_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/CSO_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/CSO_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/CS_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/CS_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CS_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/CS_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/CS_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/CS_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/CS_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/CS_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/Cl2_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/Cl2_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/Cl2_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/Cl2_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/Cl2_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/Cl2_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/Cl2_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/Cl2_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/ClCN_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/ClCN_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/ClCN_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/ClCN_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/ClCN_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/ClCN_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/ClCN_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/ClCN_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HBS_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/HBS_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HBS_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/HBS_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/HBS_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/HBS_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/HBS_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/HBS_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCCCl_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCCCl_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCCCl_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/HCCCl_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/HCCCl_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/HCCCl_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/HCCCl_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/HCCCl_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHS_B97-2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHS_HFLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHS_M06_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHS_N12_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHS_SOGGA11_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHS_TPSSh_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHS_hmGGA_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHS_wM05-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SPW92_aug-pc-4.i

In [481]:
#use this cell block for electronic component calculation

input_path = Path.home() / "summer/research/geometries/geometries"
ang_to_bohr = 1.88973
ang2_to_bohr2 = 3.571079
debye_to_e = 0.3934303
ea02_to_debye_ang = 1.345033669
debye_ang_to_ea02 = 0.743477

def get_electronic_dipole(string, dipole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    x = y = z = 0
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        if len(line) == 1:
            line += [0, 0, 0]
        x += charge * float(line[1])
        y += charge * float(line[2])
        z += charge * float(line[3])
    x_elec = dipole[0] * debye_to_e - x * ang_to_bohr
    y_elec = dipole[1] * debye_to_e - y * ang_to_bohr
    z_elec = dipole[2] * debye_to_e - z * ang_to_bohr
    total_elec = np.sqrt(x_elec ** 2 + y_elec ** 2 + z_elec ** 2)
    return [x_elec, y_elec, z_elec, total_elec]

def get_electronic_quadrupole(string, quadrupole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    xx = yy = zz = 0
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        if len(line) == 1:
            line += [0, 0, 0]
        xx += charge * float(line[1]) ** 2
        yy += charge * float(line[2]) ** 2
        zz += charge * float(line[3]) ** 2
    xx_elec = quadrupole[0] * debye_ang_to_ea02 - xx * ang2_to_bohr2
    yy_elec = quadrupole[1] * debye_ang_to_ea02 - yy * ang2_to_bohr2
    zz_elec = quadrupole[2] * debye_ang_to_ea02 - zz * ang2_to_bohr2
    return [xx_elec, yy_elec, zz_elec]

def get_stddev(string, dipole, quadrupole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    tote = int(re.search('molecule\s*(\d\s\d\s)', string).group(1).splitlines()[0].split()[0])
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        tote += Element(re.sub('\d+', '', line[0])).Z
    xx_std = np.sqrt((quadrupole[0]/-tote) - (dipole[0]/-tote) ** 2)
    yy_std = np.sqrt((quadrupole[1]/-tote) - (dipole[1]/-tote) ** 2)
    zz_std = np.sqrt((quadrupole[2]/-tote) - (dipole[2]/-tote) ** 2)
    return [xx_std, yy_std, zz_std]

def get_electronic_for_wft(molecule, method, basis):
    filename = input_path / "{}.xyz".format(molecule)
    with open(filename, 'r') as file:
        string = file.read()
    d = retrieve(molecule, method, basis)
    if d == {}:
        print('WFT method has not been calculated for {0} of basis {1}!'.format(molecule, basis))
        return
    add(molecule, method, basis, 'dipoles_elec_hf', get_electronic_dipole(string, d['dipoles_hf']))
    add(molecule, method, basis, 'dipoles_elec_mp2', get_electronic_dipole(string, d['dipoles_mp2']))
    add(molecule, method, basis, 'dipoles_elec_ccsd', get_electronic_dipole(string, d['dipoles_ccsd']))
    add(molecule, method, basis, 'dipoles_elec_ccsdt', get_electronic_dipole(string, d['dipoles_ccsdt']))
    add(molecule, method, basis, 'quadrupoles_elec_hf', get_electronic_quadrupole(string, d['quadrupoles_hf']))
    add(molecule, method, basis, 'quadrupoles_elec_mp2', get_electronic_quadrupole(string, d['quadrupoles_mp2']))
    add(molecule, method, basis, 'quadrupoles_elec_ccsd', get_electronic_quadrupole(string, d['quadrupoles_ccsd']))
    add(molecule, method, basis, 'quadrupoles_elec_ccsdt', get_electronic_quadrupole(string, d['quadrupoles_ccsdt']))
    add(molecule, method, basis, 'std_dev_hf', get_stddev(string, d['dipoles_elec_hf'], d['quadrupoles_elec_hf']))
    add(molecule, method, basis, 'std_dev_mp2', get_stddev(string, d['dipoles_elec_mp2'], d['quadrupoles_elec_mp2']))
    add(molecule, method, basis, 'std_dev_ccsd', get_stddev(string, d['dipoles_elec_ccsd'], d['quadrupoles_elec_ccsd']))
    add(molecule, method, basis, 'std_dev_ccsdt', get_stddev(string, d['dipoles_elec_ccsdt'], d['quadrupoles_elec_ccsdt']))
    print('Electronic part successfully calculated for {0} of basis {1}!'.format(molecule, basis))

def get_electronic_for_hf(molecule, method, basis):
    filename = input_path / "{}.xyz".format(molecule)
    with open(filename, 'r') as file:
        string = file.read()
    d = retrieve(molecule, method, basis)
    if d == {}:
        print('HF method has not been calculated for {0} of basis {1}!'.format(molecule, basis))
        return
    add(molecule, method, basis, 'dipoles_elec_hf', get_electronic_dipole(string, d['dipoles_hf']))
    add(molecule, method, basis, 'dipoles_elec_mp2', [0, 0, 0])
    add(molecule, method, basis, 'dipoles_elec_ccsd', [0, 0, 0])
    add(molecule, method, basis, 'dipoles_elec_ccsdt', [0, 0, 0])
    add(molecule, method, basis, 'quadrupoles_elec_hf', get_electronic_quadrupole(string, d['quadrupoles_hf']))
    add(molecule, method, basis, 'quadrupoles_elec_mp2', [0, 0, 0])
    add(molecule, method, basis, 'quadrupoles_elec_ccsd', [0, 0, 0])
    add(molecule, method, basis, 'quadrupoles_elec_ccsdt', [0, 0, 0])
    add(molecule, method, basis, 'std_dev_hf', get_stddev(string, d['dipoles_elec_hf'], d['quadrupoles_elec_hf']))
    add(molecule, method, basis, 'std_dev_mp2', [0, 0, 0])
    add(molecule, method, basis, 'std_dev_ccsd', [0, 0, 0])
    add(molecule, method, basis, 'std_dev_ccsdt', [0, 0, 0])
    print('Electronic part successfully calculated for {0} of basis {1}!'.format(molecule, basis))
    
def get_electronic_for_dft(molecule, method, basis):
    filename = input_path / "{}.xyz".format(molecule)
    with open(filename, 'r') as file:
        string = file.read()
    d = retrieve(molecule, method, basis)
    if d == {}:
        print('DFT method has not been calculated for {0} of method {1}!'.format(molecule, method))
        return
    add(molecule, method, basis, 'dipoles_elec', get_electronic_dipole(string, d['dipoles']))
    add(molecule, method, basis, 'quadrupoles_elec', get_electronic_quadrupole(string, d['quadrupoles']))
    add(molecule, method, basis, 'std_dev', get_stddev(string, d['dipoles_elec'], d['quadrupoles_elec']))
    print('Electronic part successfully calculated for {0} of method {1}!'.format(molecule, method))

In [205]:
get_electronic_for_wft('NH', 'ccsdT', 'aug-cc-pcV5Zp')

Electronic part successfully calculated for NH of basis aug-cc-pcV5Zp!

In [453]:
mols = data.keys()

In [460]:
bases = ['aug-cc-pcV5Zp', 'aug-cc-pcVQZp', 'aug-cc-pcVTZp']
for m in mols:
    for b in bases:
        get_electronic_for_wft(m, 'ccsdT', b)

WFT method has not been calculated for AlF of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for AlF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for AlF of basis aug-cc-pcVTZp!
Electronic part successfully calculated for Ar of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Ar of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Ar of basis aug-cc-pcVTZp!
WFT method has not been calculated for BeH of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BeH of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BeH of basis aug-cc-pcVTZp!
WFT method has not been calculated for BeH2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BeH2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BeH2 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for BF of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BF of basis aug-cc-pcVTZp!
Electronic part successfully calculated for BH2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BH2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BH2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for BH2F of basis aug-cc-pcV5Zp!
WFT method has not been calculated for BH2F of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BH2F of basis aug-cc-pcVTZp!
Electronic part successfully calculated for BH3 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BH3 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BH3 of basis aug-cc-pcVTZp!
WFT method has not been calculated for BO of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BO of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BO of basis aug-cc-pcVTZp!
Electronic part successfully calculated for BS of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BS of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BS of basis aug-cc-pcVTZp!
Electronic part successfully calculated for C2H of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for C2H of basis aug-cc-pcVQZp!
Electronic part successfully calculated for C2H of basis aug-cc-pcVTZp!
WFT method has not been calculated for C2H2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for C2H2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for C2H2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for CH2BH of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CH2BH of basis aug-cc-pcVQZp!
WFT method has not been calculated for CH2BH of basis aug-cc-pcVTZp!
Electronic part successfully calculated for CH2-t of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CH2-t of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CH2-t of basis aug-cc-pcVTZp!
WFT method has not been calculated for CH3 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CH3 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CH3 of basis aug-cc-pcVTZp!
WFT method has not been calculated for CH4 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CH4 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CH4 of basis aug-cc-pcVTZp!
WFT method has not been calculated for ClF of basis aug-cc-pcV5Zp!
WFT method has not been calculated for ClF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for ClF of basis aug-cc-pcVTZp!
Electronic part successfully calculated for CN of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CN of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CN of basis aug-cc-pcVTZp!
WFT method has not been calculated for CO of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CO of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CO of basis aug-cc-pcVTZp!
WFT method has not been calculated for CO2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CO2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CO2 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for F2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for F2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for F2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for FCN of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for FCN of basis aug-cc-pcVQZp!
Electronic part successfully calculated for FCN of basis aug-cc-pcVTZp!
Electronic part successfully calculated for H of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for H of basis aug-cc-pcVQZp!
Electronic part successfully calculated for H of basis aug-cc-pcVTZp!
Electronic part successfully calculated for H2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for H2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for H2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for H2CN of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for H2CN of basis aug-cc-pcVQZp!
Electronic part successfully calculated for H2CN of basis aug-cc-pcVTZp!
Electronic part successfully calculated for H2O of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for H2O of basis aug-cc-pcVQZp!
Electronic part successfully calculated for H2O of basis aug-cc-pcVTZp!
WFT method has not been calculated for HBO of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HBO of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HBO of basis aug-cc-pcVTZp!
WFT method has not been calculated for HCCF of basis aug-cc-pcV5Zp!
WFT method has not been calculated for HCCF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HCCF of basis aug-cc-pcVTZp!
WFT method has not been calculated for HCN of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HCN of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HCN of basis aug-cc-pcVTZp!
Electronic part successfully calculated for He of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for He of basis aug-cc-pcVQZp!
Electronic part successfully calculated for He of basis aug-cc-pcVTZp!
Electronic part successfully calculated for HF of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HF of basis aug-cc-pcVTZp!
WFT method has not been calculated for HNC of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HNC of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HNC of basis aug-cc-pcVTZp!
WFT method has not been calculated for LiBH4 of basis aug-cc-pcV5Zp!
WFT method has not been calculated for LiBH4 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for LiBH4 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for Mg of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Mg of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Mg of basis aug-cc-pcVTZp!
WFT method has not been calculated for Mg2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Mg2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Mg2 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for N of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for N of basis aug-cc-pcVQZp!
Electronic part successfully calculated for N of basis aug-cc-pcVTZp!
Electronic part successfully calculated for N2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for N2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for N2 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for Na of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Na of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Na of basis aug-cc-pcVTZp!
WFT method has not been calculated for Na2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Na2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Na2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for NaCl of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for NaCl of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NaCl of basis aug-cc-pcVTZp!
Electronic part successfully calculated for Ne of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Ne of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Ne of basis aug-cc-pcVTZp!
Electronic part successfully calculated for NH2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for NH2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NH2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for NH3 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for NH3 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NH3 of basis aug-cc-pcVTZp!
WFT method has not been calculated for NH3O of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for NH3O of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NH3O of basis aug-cc-pcVTZp!
Electronic part successfully calculated for O2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for O2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for O2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for O3 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for O3 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for O3 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for P of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for P of basis aug-cc-pcVQZp!
Electronic part successfully calculated for P of basis aug-cc-pcVTZp!
Electronic part successfully calculated for HCl of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HCl of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HCl of basis aug-cc-pcVTZp!
Electronic part successfully calculated for NH of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for NH of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NH of basis aug-cc-pcVTZp!
Electronic part successfully calculated for PH of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for PH of basis aug-cc-pcVQZp!
Electronic part successfully calculated for PH of basis aug-cc-pcVTZp!
Electronic part successfully calculated for SiO of basis aug-cc-pcV5Zp!
WFT method has not been calculated for SiO of basis aug-cc-pcVQZp!
WFT method has not been calculated for SiO of basis aug-cc-pcVTZp!
WFT method has not been calculated for LiH of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for LiH of basis aug-cc-pcVQZp!
Electronic part successfully calculated for LiH of basis aug-cc-pcVTZp!

In [504]:
bases = ['aug-cc-pcV5Zp', 'aug-cc-pcVQZp', 'aug-cc-pcVTZp']
for m in mols:
    for b in bases:
        get_electronic_for_hf(m, 'hf', b)

HF method has not been calculated for AlF of basis aug-cc-pcV5Zp!
HF method has not been calculated for AlF of basis aug-cc-pcVQZp!
HF method has not been calculated for AlF of basis aug-cc-pcVTZp!
HF method has not been calculated for Ar of basis aug-cc-pcV5Zp!
HF method has not been calculated for Ar of basis aug-cc-pcVQZp!
HF method has not been calculated for Ar of basis aug-cc-pcVTZp!
HF method has not been calculated for BeH of basis aug-cc-pcV5Zp!
HF method has not been calculated for BeH of basis aug-cc-pcVQZp!
HF method has not been calculated for BeH of basis aug-cc-pcVTZp!
HF method has not been calculated for BeH2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for BeH2 of basis aug-cc-pcVQZp!
HF method has not been calculated for BeH2 of basis aug-cc-pcVTZp!
HF method has not been calculated for BF of basis aug-cc-pcV5Zp!
HF method has not been calculated for BF of basis aug-cc-pcVQZp!
HF method has not been calculated for BF of basis aug-cc-pcVTZp!
HF method has not been calculated for BH2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for BH2 of basis aug-cc-pcVQZp!
HF method has not been calculated for BH2 of basis aug-cc-pcVTZp!
HF method has not been calculated for BH2F of basis aug-cc-pcV5Zp!
HF method has not been calculated for BH2F of basis aug-cc-pcVQZp!
HF method has not been calculated for BH2F of basis aug-cc-pcVTZp!
HF method has not been calculated for BH3 of basis aug-cc-pcV5Zp!
HF method has not been calculated for BH3 of basis aug-cc-pcVQZp!
HF method has not been calculated for BH3 of basis aug-cc-pcVTZp!
HF method has not been calculated for BO of basis aug-cc-pcV5Zp!
HF method has not been calculated for BO of basis aug-cc-pcVQZp!
HF method has not been calculated for BO of basis aug-cc-pcVTZp!
HF method has not been calculated for BS of basis aug-cc-pcV5Zp!
HF method has not been calculated for BS of basis aug-cc-pcVQZp!
HF method has not been calculated for BS of basis aug-cc-pcVTZp!
Electronic part successfully calculated for C2H of basis aug-cc-pcV5Zp!
HF method has not been calculated for C2H of basis aug-cc-pcVQZp!
HF method has not been calculated for C2H of basis aug-cc-pcVTZp!
Electronic part successfully calculated for C2H2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for C2H2 of basis aug-cc-pcVQZp!
HF method has not been calculated for C2H2 of basis aug-cc-pcVTZp!
HF method has not been calculated for CH2BH of basis aug-cc-pcV5Zp!
HF method has not been calculated for CH2BH of basis aug-cc-pcVQZp!
HF method has not been calculated for CH2BH of basis aug-cc-pcVTZp!
HF method has not been calculated for CH2-t of basis aug-cc-pcV5Zp!
HF method has not been calculated for CH2-t of basis aug-cc-pcVQZp!
HF method has not been calculated for CH2-t of basis aug-cc-pcVTZp!
HF method has not been calculated for CH3 of basis aug-cc-pcV5Zp!
HF method has not been calculated for CH3 of basis aug-cc-pcVQZp!
HF method has not been calculated for CH3 of basis aug-cc-pcVTZp!
HF method has not been calculated for CH4 of basis aug-cc-pcV5Zp!
HF method has not been calculated for CH4 of basis aug-cc-pcVQZp!
HF method has not been calculated for CH4 of basis aug-cc-pcVTZp!
HF method has not been calculated for ClF of basis aug-cc-pcV5Zp!
HF method has not been calculated for ClF of basis aug-cc-pcVQZp!
HF method has not been calculated for ClF of basis aug-cc-pcVTZp!
HF method has not been calculated for CN of basis aug-cc-pcV5Zp!
HF method has not been calculated for CN of basis aug-cc-pcVQZp!
HF method has not been calculated for CN of basis aug-cc-pcVTZp!
HF method has not been calculated for CO of basis aug-cc-pcV5Zp!
HF method has not been calculated for CO of basis aug-cc-pcVQZp!
HF method has not been calculated for CO of basis aug-cc-pcVTZp!
HF method has not been calculated for CO2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for CO2 of basis aug-cc-pcVQZp!
HF method has not been calculated for CO2 of basis aug-cc-pcVTZp!
HF method has not been calculated for F2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for F2 of basis aug-cc-pcVQZp!
HF method has not been calculated for F2 of basis aug-cc-pcVTZp!
HF method has not been calculated for FCN of basis aug-cc-pcV5Zp!
HF method has not been calculated for FCN of basis aug-cc-pcVQZp!
HF method has not been calculated for FCN of basis aug-cc-pcVTZp!
HF method has not been calculated for H of basis aug-cc-pcV5Zp!
HF method has not been calculated for H of basis aug-cc-pcVQZp!
HF method has not been calculated for H of basis aug-cc-pcVTZp!
HF method has not been calculated for H2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for H2 of basis aug-cc-pcVQZp!
HF method has not been calculated for H2 of basis aug-cc-pcVTZp!
HF method has not been calculated for H2CN of basis aug-cc-pcV5Zp!
HF method has not been calculated for H2CN of basis aug-cc-pcVQZp!
HF method has not been calculated for H2CN of basis aug-cc-pcVTZp!
HF method has not been calculated for H2O of basis aug-cc-pcV5Zp!
HF method has not been calculated for H2O of basis aug-cc-pcVQZp!
HF method has not been calculated for H2O of basis aug-cc-pcVTZp!
Electronic part successfully calculated for HBO of basis aug-cc-pcV5Zp!
HF method has not been calculated for HBO of basis aug-cc-pcVQZp!
HF method has not been calculated for HBO of basis aug-cc-pcVTZp!
HF method has not been calculated for HCCF of basis aug-cc-pcV5Zp!
HF method has not been calculated for HCCF of basis aug-cc-pcVQZp!
HF method has not been calculated for HCCF of basis aug-cc-pcVTZp!
Electronic part successfully calculated for HCN of basis aug-cc-pcV5Zp!
HF method has not been calculated for HCN of basis aug-cc-pcVQZp!
HF method has not been calculated for HCN of basis aug-cc-pcVTZp!
HF method has not been calculated for He of basis aug-cc-pcV5Zp!
HF method has not been calculated for He of basis aug-cc-pcVQZp!
HF method has not been calculated for He of basis aug-cc-pcVTZp!
HF method has not been calculated for HF of basis aug-cc-pcV5Zp!
HF method has not been calculated for HF of basis aug-cc-pcVQZp!
HF method has not been calculated for HF of basis aug-cc-pcVTZp!
Electronic part successfully calculated for HNC of basis aug-cc-pcV5Zp!
HF method has not been calculated for HNC of basis aug-cc-pcVQZp!
HF method has not been calculated for HNC of basis aug-cc-pcVTZp!
HF method has not been calculated for LiBH4 of basis aug-cc-pcV5Zp!
HF method has not been calculated for LiBH4 of basis aug-cc-pcVQZp!
HF method has not been calculated for LiBH4 of basis aug-cc-pcVTZp!
HF method has not been calculated for Mg of basis aug-cc-pcV5Zp!
HF method has not been calculated for Mg of basis aug-cc-pcVQZp!
HF method has not been calculated for Mg of basis aug-cc-pcVTZp!
HF method has not been calculated for Mg2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for Mg2 of basis aug-cc-pcVQZp!
HF method has not been calculated for Mg2 of basis aug-cc-pcVTZp!
HF method has not been calculated for N of basis aug-cc-pcV5Zp!
HF method has not been calculated for N of basis aug-cc-pcVQZp!
HF method has not been calculated for N of basis aug-cc-pcVTZp!
HF method has not been calculated for N2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for N2 of basis aug-cc-pcVQZp!
HF method has not been calculated for N2 of basis aug-cc-pcVTZp!
HF method has not been calculated for Na of basis aug-cc-pcV5Zp!
HF method has not been calculated for Na of basis aug-cc-pcVQZp!
HF method has not been calculated for Na of basis aug-cc-pcVTZp!
HF method has not been calculated for Na2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for Na2 of basis aug-cc-pcVQZp!
HF method has not been calculated for Na2 of basis aug-cc-pcVTZp!
HF method has not been calculated for NaCl of basis aug-cc-pcV5Zp!
HF method has not been calculated for NaCl of basis aug-cc-pcVQZp!
HF method has not been calculated for NaCl of basis aug-cc-pcVTZp!
HF method has not been calculated for Ne of basis aug-cc-pcV5Zp!
HF method has not been calculated for Ne of basis aug-cc-pcVQZp!
HF method has not been calculated for Ne of basis aug-cc-pcVTZp!
HF method has not been calculated for NH2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for NH2 of basis aug-cc-pcVQZp!
HF method has not been calculated for NH2 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for NH3 of basis aug-cc-pcV5Zp!
HF method has not been calculated for NH3 of basis aug-cc-pcVQZp!
HF method has not been calculated for NH3 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for NH3O of basis aug-cc-pcV5Zp!
HF method has not been calculated for NH3O of basis aug-cc-pcVQZp!
HF method has not been calculated for NH3O of basis aug-cc-pcVTZp!
HF method has not been calculated for O2 of basis aug-cc-pcV5Zp!
HF method has not been calculated for O2 of basis aug-cc-pcVQZp!
HF method has not been calculated for O2 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for O3 of basis aug-cc-pcV5Zp!
HF method has not been calculated for O3 of basis aug-cc-pcVQZp!
HF method has not been calculated for O3 of basis aug-cc-pcVTZp!
HF method has not been calculated for P of basis aug-cc-pcV5Zp!
HF method has not been calculated for P of basis aug-cc-pcVQZp!
HF method has not been calculated for P of basis aug-cc-pcVTZp!
HF method has not been calculated for HCl of basis aug-cc-pcV5Zp!
HF method has not been calculated for HCl of basis aug-cc-pcVQZp!
HF method has not been calculated for HCl of basis aug-cc-pcVTZp!
HF method has not been calculated for NH of basis aug-cc-pcV5Zp!
HF method has not been calculated for NH of basis aug-cc-pcVQZp!
HF method has not been calculated for NH of basis aug-cc-pcVTZp!
HF method has not been calculated for PH of basis aug-cc-pcV5Zp!
HF method has not been calculated for PH of basis aug-cc-pcVQZp!
HF method has not been calculated for PH of basis aug-cc-pcVTZp!
HF method has not been calculated for SiO of basis aug-cc-pcV5Zp!
HF method has not been calculated for SiO of basis aug-cc-pcVQZp!
HF method has not been calculated for SiO of basis aug-cc-pcVTZp!
HF method has not been calculated for LiH of basis aug-cc-pcV5Zp!
HF method has not been calculated for LiH of basis aug-cc-pcVQZp!
HF method has not been calculated for LiH of basis aug-cc-pcVTZp!

In [461]:
functionals = get_functionals()
for m in mols:
    for f in functionals:
        get_electronic_for_dft(m, f, 'aug-pc-4p')

Electronic part successfully calculated for AlF of method B3LYP!
Electronic part successfully calculated for AlF of method B97-D3!
Electronic part successfully calculated for AlF of method B97M-V!
Electronic part successfully calculated for AlF of method BLYP!
Electronic part successfully calculated for AlF of method BPBE!
Electronic part successfully calculated for AlF of method CAM-B3LYP!
Electronic part successfully calculated for AlF of method M06-2X!
Electronic part successfully calculated for AlF of method M06-L!
Electronic part successfully calculated for AlF of method M08-HX!
Electronic part successfully calculated for AlF of method MGGA_MS2!
Electronic part successfully calculated for AlF of method MN15!
Electronic part successfully calculated for AlF of method MN15-L!
Electronic part successfully calculated for AlF of method PBE!
Electronic part successfully calculated for AlF of method PBE0!
Electronic part successfully calculated for AlF of method SCAN!
Electronic part successfully calculated for AlF of method SCAN0!
Electronic part successfully calculated for AlF of method SPW92!
Electronic part successfully calculated for AlF of method Slater!
Electronic part successfully calculated for AlF of method TPSS!
Electronic part successfully calculated for AlF of method mBEEF!
Electronic part successfully calculated for AlF of method mPW91!
Electronic part successfully calculated for AlF of method revM06-L!
Electronic part successfully calculated for AlF of method wB97M-V!
DFT method has not been calculated for AlF of method wB97X-D!
Electronic part successfully calculated for AlF of method wB97X-V!
Electronic part successfully calculated for Ar of method B3LYP!
Electronic part successfully calculated for Ar of method B97-D3!
Electronic part successfully calculated for Ar of method B97M-V!
Electronic part successfully calculated for Ar of method BLYP!
Electronic part successfully calculated for Ar of method BPBE!
Electronic part successfully calculated for Ar of method CAM-B3LYP!
Electronic part successfully calculated for Ar of method M06-2X!
Electronic part successfully calculated for Ar of method M06-L!
Electronic part successfully calculated for Ar of method M08-HX!
Electronic part successfully calculated for Ar of method MGGA_MS2!
Electronic part successfully calculated for Ar of method MN15!
Electronic part successfully calculated for Ar of method MN15-L!
Electronic part successfully calculated for Ar of method PBE!
Electronic part successfully calculated for Ar of method PBE0!
Electronic part successfully calculated for Ar of method SCAN!
Electronic part successfully calculated for Ar of method SCAN0!
Electronic part successfully calculated for Ar of method SPW92!
Electronic part successfully calculated for Ar of method Slater!
Electronic part successfully calculated for Ar of method TPSS!
Electronic part successfully calculated for Ar of method mBEEF!
Electronic part successfully calculated for Ar of method mPW91!
Electronic part successfully calculated for Ar of method revM06-L!
Electronic part successfully calculated for Ar of method wB97M-V!
Electronic part successfully calculated for Ar of method wB97X-D!
Electronic part successfully calculated for Ar of method wB97X-V!
Electronic part successfully calculated for BeH of method B3LYP!
Electronic part successfully calculated for BeH of method B97-D3!
Electronic part successfully calculated for BeH of method B97M-V!
Electronic part successfully calculated for BeH of method BLYP!
Electronic part successfully calculated for BeH of method BPBE!
Electronic part successfully calculated for BeH of method CAM-B3LYP!
Electronic part successfully calculated for BeH of method M06-2X!
Electronic part successfully calculated for BeH of method M06-L!
Electronic part successfully calculated for BeH of method M08-HX!
Electronic part successfully calculated for BeH of method MGGA_MS2!
Electronic part successfully calculated for BeH of method MN15!
Electronic part successfully calculated for BeH of method MN15-L!
Electronic part successfully calculated for BeH of method PBE!
Electronic part successfully calculated for BeH of method PBE0!
Electronic part successfully calculated for BeH of method SCAN!
Electronic part successfully calculated for BeH of method SCAN0!
Electronic part successfully calculated for BeH of method SPW92!
Electronic part successfully calculated for BeH of method Slater!
Electronic part successfully calculated for BeH of method TPSS!
Electronic part successfully calculated for BeH of method mBEEF!
Electronic part successfully calculated for BeH of method mPW91!
Electronic part successfully calculated for BeH of method revM06-L!
Electronic part successfully calculated for BeH of method wB97M-V!
Electronic part successfully calculated for BeH of method wB97X-D!
Electronic part successfully calculated for BeH of method wB97X-V!
Electronic part successfully calculated for BeH2 of method B3LYP!
Electronic part successfully calculated for BeH2 of method B97-D3!
Electronic part successfully calculated for BeH2 of method B97M-V!
Electronic part successfully calculated for BeH2 of method BLYP!
Electronic part successfully calculated for BeH2 of method BPBE!
Electronic part successfully calculated for BeH2 of method CAM-B3LYP!
Electronic part successfully calculated for BeH2 of method M06-2X!
Electronic part successfully calculated for BeH2 of method M06-L!
Electronic part successfully calculated for BeH2 of method M08-HX!
Electronic part successfully calculated for BeH2 of method MGGA_MS2!
Electronic part successfully calculated for BeH2 of method MN15!
Electronic part successfully calculated for BeH2 of method MN15-L!
Electronic part successfully calculated for BeH2 of method PBE!
Electronic part successfully calculated for BeH2 of method PBE0!
Electronic part successfully calculated for BeH2 of method SCAN!
Electronic part successfully calculated for BeH2 of method SCAN0!
Electronic part successfully calculated for BeH2 of method SPW92!
Electronic part successfully calculated for BeH2 of method Slater!
Electronic part successfully calculated for BeH2 of method TPSS!
Electronic part successfully calculated for BeH2 of method mBEEF!
Electronic part successfully calculated for BeH2 of method mPW91!
Electronic part successfully calculated for BeH2 of method revM06-L!
Electronic part successfully calculated for BeH2 of method wB97M-V!
Electronic part successfully calculated for BeH2 of method wB97X-D!
Electronic part successfully calculated for BeH2 of method wB97X-V!
Electronic part successfully calculated for BF of method B3LYP!
Electronic part successfully calculated for BF of method B97-D3!
Electronic part successfully calculated for BF of method B97M-V!
Electronic part successfully calculated for BF of method BLYP!
Electronic part successfully calculated for BF of method BPBE!
Electronic part successfully calculated for BF of method CAM-B3LYP!
Electronic part successfully calculated for BF of method M06-2X!
Electronic part successfully calculated for BF of method M06-L!
Electronic part successfully calculated for BF of method M08-HX!
Electronic part successfully calculated for BF of method MGGA_MS2!
Electronic part successfully calculated for BF of method MN15!
Electronic part successfully calculated for BF of method MN15-L!
Electronic part successfully calculated for BF of method PBE!
Electronic part successfully calculated for BF of method PBE0!
Electronic part successfully calculated for BF of method SCAN!
Electronic part successfully calculated for BF of method SCAN0!
Electronic part successfully calculated for BF of method SPW92!
Electronic part successfully calculated for BF of method Slater!
Electronic part successfully calculated for BF of method TPSS!
Electronic part successfully calculated for BF of method mBEEF!
Electronic part successfully calculated for BF of method mPW91!
Electronic part successfully calculated for BF of method revM06-L!
Electronic part successfully calculated for BF of method wB97M-V!
Electronic part successfully calculated for BF of method wB97X-D!
Electronic part successfully calculated for BF of method wB97X-V!
Electronic part successfully calculated for BH2 of method B3LYP!
Electronic part successfully calculated for BH2 of method B97-D3!
DFT method has not been calculated for BH2 of method B97M-V!
Electronic part successfully calculated for BH2 of method BLYP!
Electronic part successfully calculated for BH2 of method BPBE!
Electronic part successfully calculated for BH2 of method CAM-B3LYP!
Electronic part successfully calculated for BH2 of method M06-2X!
Electronic part successfully calculated for BH2 of method M06-L!
Electronic part successfully calculated for BH2 of method M08-HX!
Electronic part successfully calculated for BH2 of method MGGA_MS2!
Electronic part successfully calculated for BH2 of method MN15!
Electronic part successfully calculated for BH2 of method MN15-L!
Electronic part successfully calculated for BH2 of method PBE!
Electronic part successfully calculated for BH2 of method PBE0!
DFT method has not been calculated for BH2 of method SCAN!
DFT method has not been calculated for BH2 of method SCAN0!
Electronic part successfully calculated for BH2 of method SPW92!
Electronic part successfully calculated for BH2 of method Slater!
Electronic part successfully calculated for BH2 of method TPSS!
DFT method has not been calculated for BH2 of method mBEEF!
Electronic part successfully calculated for BH2 of method mPW91!
Electronic part successfully calculated for BH2 of method revM06-L!
Electronic part successfully calculated for BH2 of method wB97M-V!
Electronic part successfully calculated for BH2 of method wB97X-D!
Electronic part successfully calculated for BH2 of method wB97X-V!
Electronic part successfully calculated for BH2F of method B3LYP!
Electronic part successfully calculated for BH2F of method B97-D3!
Electronic part successfully calculated for BH2F of method B97M-V!
Electronic part successfully calculated for BH2F of method BLYP!
Electronic part successfully calculated for BH2F of method BPBE!
Electronic part successfully calculated for BH2F of method CAM-B3LYP!
Electronic part successfully calculated for BH2F of method M06-2X!
Electronic part successfully calculated for BH2F of method M06-L!
Electronic part successfully calculated for BH2F of method M08-HX!
Electronic part successfully calculated for BH2F of method MGGA_MS2!
Electronic part successfully calculated for BH2F of method MN15!
Electronic part successfully calculated for BH2F of method MN15-L!
Electronic part successfully calculated for BH2F of method PBE!
Electronic part successfully calculated for BH2F of method PBE0!
Electronic part successfully calculated for BH2F of method SCAN!
Electronic part successfully calculated for BH2F of method SCAN0!
Electronic part successfully calculated for BH2F of method SPW92!
Electronic part successfully calculated for BH2F of method Slater!
Electronic part successfully calculated for BH2F of method TPSS!
Electronic part successfully calculated for BH2F of method mBEEF!
Electronic part successfully calculated for BH2F of method mPW91!
Electronic part successfully calculated for BH2F of method revM06-L!
DFT method has not been calculated for BH2F of method wB97M-V!
Electronic part successfully calculated for BH2F of method wB97X-D!
DFT method has not been calculated for BH2F of method wB97X-V!
Electronic part successfully calculated for BH3 of method B3LYP!
Electronic part successfully calculated for BH3 of method B97-D3!
Electronic part successfully calculated for BH3 of method B97M-V!
Electronic part successfully calculated for BH3 of method BLYP!
Electronic part successfully calculated for BH3 of method BPBE!
Electronic part successfully calculated for BH3 of method CAM-B3LYP!
Electronic part successfully calculated for BH3 of method M06-2X!
Electronic part successfully calculated for BH3 of method M06-L!
Electronic part successfully calculated for BH3 of method M08-HX!
Electronic part successfully calculated for BH3 of method MGGA_MS2!
Electronic part successfully calculated for BH3 of method MN15!
Electronic part successfully calculated for BH3 of method MN15-L!
Electronic part successfully calculated for BH3 of method PBE!
Electronic part successfully calculated for BH3 of method PBE0!
Electronic part successfully calculated for BH3 of method SCAN!
Electronic part successfully calculated for BH3 of method SCAN0!
Electronic part successfully calculated for BH3 of method SPW92!
Electronic part successfully calculated for BH3 of method Slater!
Electronic part successfully calculated for BH3 of method TPSS!
Electronic part successfully calculated for BH3 of method mBEEF!
Electronic part successfully calculated for BH3 of method mPW91!
Electronic part successfully calculated for BH3 of method revM06-L!
Electronic part successfully calculated for BH3 of method wB97M-V!
Electronic part successfully calculated for BH3 of method wB97X-D!
DFT method has not been calculated for BH3 of method wB97X-V!
Electronic part successfully calculated for BO of method B3LYP!
Electronic part successfully calculated for BO of method B97-D3!
Electronic part successfully calculated for BO of method B97M-V!
Electronic part successfully calculated for BO of method BLYP!
Electronic part successfully calculated for BO of method BPBE!
Electronic part successfully calculated for BO of method CAM-B3LYP!
Electronic part successfully calculated for BO of method M06-2X!
Electronic part successfully calculated for BO of method M06-L!
Electronic part successfully calculated for BO of method M08-HX!
Electronic part successfully calculated for BO of method MGGA_MS2!
Electronic part successfully calculated for BO of method MN15!
Electronic part successfully calculated for BO of method MN15-L!
Electronic part successfully calculated for BO of method PBE!
Electronic part successfully calculated for BO of method PBE0!
Electronic part successfully calculated for BO of method SCAN!
Electronic part successfully calculated for BO of method SCAN0!
Electronic part successfully calculated for BO of method SPW92!
Electronic part successfully calculated for BO of method Slater!
Electronic part successfully calculated for BO of method TPSS!
Electronic part successfully calculated for BO of method mBEEF!
Electronic part successfully calculated for BO of method mPW91!
Electronic part successfully calculated for BO of method revM06-L!
Electronic part successfully calculated for BO of method wB97M-V!
Electronic part successfully calculated for BO of method wB97X-D!
Electronic part successfully calculated for BO of method wB97X-V!
Electronic part successfully calculated for BS of method B3LYP!
Electronic part successfully calculated for BS of method B97-D3!
Electronic part successfully calculated for BS of method B97M-V!
Electronic part successfully calculated for BS of method BLYP!
Electronic part successfully calculated for BS of method BPBE!
Electronic part successfully calculated for BS of method CAM-B3LYP!
Electronic part successfully calculated for BS of method M06-2X!
Electronic part successfully calculated for BS of method M06-L!
Electronic part successfully calculated for BS of method M08-HX!
Electronic part successfully calculated for BS of method MGGA_MS2!
Electronic part successfully calculated for BS of method MN15!
Electronic part successfully calculated for BS of method MN15-L!
Electronic part successfully calculated for BS of method PBE!
Electronic part successfully calculated for BS of method PBE0!
Electronic part successfully calculated for BS of method SCAN!
Electronic part successfully calculated for BS of method SCAN0!
Electronic part successfully calculated for BS of method SPW92!
Electronic part successfully calculated for BS of method Slater!
Electronic part successfully calculated for BS of method TPSS!
Electronic part successfully calculated for BS of method mBEEF!
Electronic part successfully calculated for BS of method mPW91!
Electronic part successfully calculated for BS of method revM06-L!
Electronic part successfully calculated for BS of method wB97M-V!
Electronic part successfully calculated for BS of method wB97X-D!
Electronic part successfully calculated for BS of method wB97X-V!
Electronic part successfully calculated for C2H of method B3LYP!
Electronic part successfully calculated for C2H of method B97-D3!
Electronic part successfully calculated for C2H of method B97M-V!
Electronic part successfully calculated for C2H of method BLYP!
Electronic part successfully calculated for C2H of method BPBE!
Electronic part successfully calculated for C2H of method CAM-B3LYP!
Electronic part successfully calculated for C2H of method M06-2X!
Electronic part successfully calculated for C2H of method M06-L!
Electronic part successfully calculated for C2H of method M08-HX!
Electronic part successfully calculated for C2H of method MGGA_MS2!
Electronic part successfully calculated for C2H of method MN15!
Electronic part successfully calculated for C2H of method MN15-L!
Electronic part successfully calculated for C2H of method PBE!
Electronic part successfully calculated for C2H of method PBE0!
Electronic part successfully calculated for C2H of method SCAN!
Electronic part successfully calculated for C2H of method SCAN0!
Electronic part successfully calculated for C2H of method SPW92!
Electronic part successfully calculated for C2H of method Slater!
Electronic part successfully calculated for C2H of method TPSS!
Electronic part successfully calculated for C2H of method mBEEF!
Electronic part successfully calculated for C2H of method mPW91!
Electronic part successfully calculated for C2H of method revM06-L!
Electronic part successfully calculated for C2H of method wB97M-V!
Electronic part successfully calculated for C2H of method wB97X-D!
Electronic part successfully calculated for C2H of method wB97X-V!
Electronic part successfully calculated for C2H2 of method B3LYP!
Electronic part successfully calculated for C2H2 of method B97-D3!
Electronic part successfully calculated for C2H2 of method B97M-V!
Electronic part successfully calculated for C2H2 of method BLYP!
Electronic part successfully calculated for C2H2 of method BPBE!
Electronic part successfully calculated for C2H2 of method CAM-B3LYP!
Electronic part successfully calculated for C2H2 of method M06-2X!
Electronic part successfully calculated for C2H2 of method M06-L!
DFT method has not been calculated for C2H2 of method M08-HX!
Electronic part successfully calculated for C2H2 of method MGGA_MS2!
Electronic part successfully calculated for C2H2 of method MN15!
Electronic part successfully calculated for C2H2 of method MN15-L!
Electronic part successfully calculated for C2H2 of method PBE!
Electronic part successfully calculated for C2H2 of method PBE0!
Electronic part successfully calculated for C2H2 of method SCAN!
Electronic part successfully calculated for C2H2 of method SCAN0!
Electronic part successfully calculated for C2H2 of method SPW92!
Electronic part successfully calculated for C2H2 of method Slater!
Electronic part successfully calculated for C2H2 of method TPSS!
Electronic part successfully calculated for C2H2 of method mBEEF!
Electronic part successfully calculated for C2H2 of method mPW91!
Electronic part successfully calculated for C2H2 of method revM06-L!
Electronic part successfully calculated for C2H2 of method wB97M-V!
Electronic part successfully calculated for C2H2 of method wB97X-D!
Electronic part successfully calculated for C2H2 of method wB97X-V!
Electronic part successfully calculated for CH2BH of method B3LYP!
Electronic part successfully calculated for CH2BH of method B97-D3!
Electronic part successfully calculated for CH2BH of method B97M-V!
Electronic part successfully calculated for CH2BH of method BLYP!
Electronic part successfully calculated for CH2BH of method BPBE!

Electronic part successfully calculated for H of method MGGA_MS2!
Electronic part successfully calculated for H of method MN15!
Electronic part successfully calculated for H of method MN15-L!
Electronic part successfully calculated for H of method PBE!
Electronic part successfully calculated for H of method PBE0!
Electronic part successfully calculated for H of method SCAN!
Electronic part successfully calculated for H of method SCAN0!
Electronic part successfully calculated for H of method SPW92!
Electronic part successfully calculated for H of method Slater!
Electronic part successfully calculated for H of method TPSS!
Electronic part successfully calculated for H of method mBEEF!
Electronic part successfully calculated for H of method mPW91!
Electronic part successfully calculated for H of method revM06-L!
Electronic part successfully calculated for H of method wB97M-V!
Electronic part successfully calculated for H of method wB97X-D!
Electronic part successfully calculated for H of method wB97X-V!
Electronic part successfully calculated for H2 of method B3LYP!
Electronic part successfully calculated for H2 of method B97-D3!
Electronic part successfully calculated for H2 of method B97M-V!
Electronic part successfully calculated for H2 of method BLYP!
Electronic part successfully calculated for H2 of method BPBE!
Electronic part successfully calculated for H2 of method CAM-B3LYP!
Electronic part successfully calculated for H2 of method M06-2X!
Electronic part successfully calculated for H2 of method M06-L!
Electronic part successfully calculated for H2 of method M08-HX!
Electronic part successfully calculated for H2 of method MGGA_MS2!
Electronic part successfully calculated for H2 of method MN15!
Electronic part successfully calculated for H2 of method MN15-L!
Electronic part successfully calculated for H2 of method PBE!
Electronic part successfully calculated for H2 of method PBE0!
Electronic part successfully calculated for H2 of method SCAN!
Electronic part successfully calculated for H2 of method SCAN0!
Electronic part successfully calculated for H2 of method SPW92!
Electronic part successfully calculated for H2 of method Slater!
Electronic part successfully calculated for H2 of method TPSS!
DFT method has not been calculated for H2 of method mBEEF!
Electronic part successfully calculated for H2 of method mPW91!
Electronic part successfully calculated for H2 of method revM06-L!
Electronic part successfully calculated for H2 of method wB97M-V!
Electronic part successfully calculated for H2 of method wB97X-D!
Electronic part successfully calculated for H2 of method wB97X-V!
Electronic part successfully calculated for H2CN of method B3LYP!
Electronic part successfully calculated for H2CN of method B97-D3!
Electronic part successfully calculated for H2CN of method B97M-V!
Electronic part successfully calculated for H2CN of method BLYP!
Electronic part successfully calculated for H2CN of method BPBE!
Electronic part successfully calculated for H2CN of method CAM-B3LYP!
Electronic part successfully calculated for H2CN of method M06-2X!
Electronic part successfully calculated for H2CN of method M06-L!
Electronic part successfully calculated for H2CN of method M08-HX!
Electronic part successfully calculated for H2CN of method MGGA_MS2!
Electronic part successfully calculated for H2CN of method MN15!
Electronic part successfully calculated for H2CN of method MN15-L!
Electronic part successfully calculated for H2CN of method PBE!
Electronic part successfully calculated for H2CN of method PBE0!
Electronic part successfully calculated for H2CN of method SCAN!
Electronic part successfully calculated for H2CN of method SCAN0!
Electronic part successfully calculated for H2CN of method SPW92!
Electronic part successfully calculated for H2CN of method Slater!
Electronic part successfully calculated for H2CN of method TPSS!
Electronic part successfully calculated for H2CN of method mBEEF!
Electronic part successfully calculated for H2CN of method mPW91!
Electronic part successfully calculated for H2CN of method revM06-L!
DFT method has not been calculated for H2CN of method wB97M-V!
Electronic part successfully calculated for H2CN of method wB97X-D!
DFT method has not been calculated for H2CN of method wB97X-V!
Electronic part successfully calculated for H2O of method B3LYP!
Electronic part successfully calculated for H2O of method B97-D3!
Electronic part successfully calculated for H2O of method B97M-V!
Electronic part successfully calculated for H2O of method BLYP!
Electronic part successfully calculated for H2O of method BPBE!
Electronic part successfully calculated for H2O of method CAM-B3LYP!
Electronic part successfully calculated for H2O of method M06-2X!
Electronic part successfully calculated for H2O of method M06-L!
Electronic part successfully calculated for H2O of method M08-HX!
Electronic part successfully calculated for H2O of method MGGA_MS2!
Electronic part successfully calculated for H2O of method MN15!
Electronic part successfully calculated for H2O of method MN15-L!
Electronic part successfully calculated for H2O of method PBE!
Electronic part successfully calculated for H2O of method PBE0!
Electronic part successfully calculated for H2O of method SCAN!
Electronic part successfully calculated for H2O of method SCAN0!
Electronic part successfully calculated for H2O of method SPW92!
Electronic part successfully calculated for H2O of method Slater!
Electronic part successfully calculated for H2O of method TPSS!
Electronic part successfully calculated for H2O of method mBEEF!
Electronic part successfully calculated for H2O of method mPW91!
Electronic part successfully calculated for H2O of method revM06-L!
Electronic part successfully calculated for H2O of method wB97M-V!
Electronic part successfully calculated for H2O of method wB97X-D!
Electronic part successfully calculated for H2O of method wB97X-V!
Electronic part successfully calculated for HBO of method B3LYP!
Electronic part successfully calculated for HBO of method B97-D3!
Electronic part successfully calculated for HBO of method B97M-V!
Electronic part successfully calculated for HBO of method BLYP!
Electronic part successfully calculated for HBO of method BPBE!
Electronic part successfully calculated for HBO of method CAM-B3LYP!
Electronic part successfully calculated for HBO of method M06-2X!
Electronic part successfully calculated for HBO of method M06-L!
Electronic part successfully calculated for HBO of method M08-HX!
Electronic part successfully calculated for HBO of method MGGA_MS2!
Electronic part successfully calculated for HBO of method MN15!
Electronic part successfully calculated for HBO of method MN15-L!
Electronic part successfully calculated for HBO of method PBE!
Electronic part successfully calculated for HBO of method PBE0!
Electronic part successfully calculated for HBO of method SCAN!
Electronic part successfully calculated for HBO of method SCAN0!
Electronic part successfully calculated for HBO of method SPW92!
Electronic part successfully calculated for HBO of method Slater!
Electronic part successfully calculated for HBO of method TPSS!
Electronic part successfully calculated for HBO of method mBEEF!
Electronic part successfully calculated for HBO of method mPW91!
Electronic part successfully calculated for HBO of method revM06-L!
Electronic part successfully calculated for HBO of method wB97M-V!
Electronic part successfully calculated for HBO of method wB97X-D!
Electronic part successfully calculated for HBO of method wB97X-V!
Electronic part successfully calculated for HCCF of method B3LYP!
Electronic part successfully calculated for HCCF of method B97-D3!
Electronic part successfully calculated for HCCF of method B97M-V!
Electronic part successfully calculated for HCCF of method BLYP!
Electronic part successfully calculated for HCCF of method BPBE!
Electronic part successfully calculated for HCCF of method CAM-B3LYP!
Electronic part successfully calculated for HCCF of method M06-2X!
Electronic part successfully calculated for HCCF of method M06-L!
Electronic part successfully calculated for HCCF of method M08-HX!
Electronic part successfully calculated for HCCF of method MGGA_MS2!
Electronic part successfully calculated for HCCF of method MN15!
Electronic part successfully calculated for HCCF of method MN15-L!
Electronic part successfully calculated for HCCF of method PBE!
Electronic part successfully calculated for HCCF of method PBE0!
Electronic part successfully calculated for HCCF of method SCAN!
Electronic part successfully calculated for HCCF of method SCAN0!
Electronic part successfully calculated for HCCF of method SPW92!
Electronic part successfully calculated for HCCF of method Slater!
Electronic part successfully calculated for HCCF of method TPSS!
Electronic part successfully calculated for HCCF of method mBEEF!
Electronic part successfully calculated for HCCF of method mPW91!
Electronic part successfully calculated for HCCF of method revM06-L!
Electronic part successfully calculated for HCCF of method wB97M-V!
Electronic part successfully calculated for HCCF of method wB97X-D!
Electronic part successfully calculated for HCCF of method wB97X-V!
Electronic part successfully calculated for HCN of method B3LYP!
Electronic part successfully calculated for HCN of method B97-D3!
Electronic part successfully calculated for HCN of method B97M-V!
Electronic part successfully calculated for HCN of method BLYP!
Electronic part successfully calculated for HCN of method BPBE!
Electronic part successfully calculated for HCN of method CAM-B3LYP!
Electronic part successfully calculated for HCN of method M06-2X!
Electronic part successfully calculated for HCN of method M06-L!
Electronic part successfully calculated for HCN of method M08-HX!
Electronic part successfully calculated for HCN of method MGGA_MS2!
Electronic part successfully calculated for HCN of method MN15!
Electronic part successfully calculated for HCN of method MN15-L!
Electronic part successfully calculated for HCN of method PBE!
Electronic part successfully calculated for HCN of method PBE0!
Electronic part successfully calculated for HCN of method SCAN!
Electronic part successfully calculated for HCN of method SCAN0!
Electronic part successfully calculated for HCN of method SPW92!
Electronic part successfully calculated for HCN of method Slater!
Electronic part successfully calculated for HCN of method TPSS!
Electronic part successfully calculated for HCN of method mBEEF!
Electronic part successfully calculated for HCN of method mPW91!
Electronic part successfully calculated for HCN of method revM06-L!
Electronic part successfully calculated for HCN of method wB97M-V!
Electronic part successfully calculated for HCN of method wB97X-D!
Electronic part successfully calculated for HCN of method wB97X-V!
Electronic part successfully calculated for He of method B3LYP!
Electronic part successfully calculated for He of method B97-D3!
Electronic part successfully calculated for He of method B97M-V!
Electronic part successfully calculated for He of method BLYP!
Electronic part successfully calculated for He of method BPBE!
Electronic part successfully calculated for He of method CAM-B3LYP!
Electronic part successfully calculated for He of method M06-2X!
Electronic part successfully calculated for He of method M06-L!
Electronic part successfully calculated for He of method M08-HX!
Electronic part successfully calculated for He of method MGGA_MS2!
Electronic part successfully calculated for He of method MN15!
Electronic part successfully calculated for He of method MN15-L!
Electronic part successfully calculated for He of method PBE!
Electronic part successfully calculated for He of method PBE0!
Electronic part successfully calculated for He of method SCAN!
Electronic part successfully calculated for He of method SCAN0!
Electronic part successfully calculated for He of method SPW92!
Electronic part successfully calculated for He of method Slater!
Electronic part successfully calculated for He of method TPSS!
Electronic part successfully calculated for He of method mBEEF!
Electronic part successfully calculated for He of method mPW91!
Electronic part successfully calculated for He of method revM06-L!
Electronic part successfully calculated for He of method wB97M-V!
Electronic part successfully calculated for He of method wB97X-D!
Electronic part successfully calculated for He of method wB97X-V!
Electronic part successfully calculated for HF of method B3LYP!
Electronic part successfully calculated for HF of method B97-D3!
Electronic part successfully calculated for HF of method B97M-V!
Electronic part successfully calculated for HF of method BLYP!
Electronic part successfully calculated for HF of method BPBE!
Electronic part successfully calculated for HF of method CAM-B3LYP!
Electronic part successfully calculated for HF of method M06-2X!
Electronic part successfully calculated for HF of method M06-L!
Electronic part successfully calculated for HF of method M08-HX!
Electronic part successfully calculated for HF of method MGGA_MS2!
Electronic part successfully calculated for HF of method MN15!
Electronic part successfully calculated for HF of method MN15-L!
Electronic part successfully calculated for HF of method PBE!
Electronic part successfully calculated for HF of method PBE0!
Electronic part successfully calculated for HF of method SCAN!
Electronic part successfully calculated for HF of method SCAN0!
Electronic part successfully calculated for HF of method SPW92!
Electronic part successfully calculated for HF of method Slater!
Electronic part successfully calculated for HF of method TPSS!
Electronic part successfully calculated for HF of method mBEEF!
Electronic part successfully calculated for HF of method mPW91!
Electronic part successfully calculated for HF of method revM06-L!
Electronic part successfully calculated for HF of method wB97M-V!
Electronic part successfully calculated for HF of method wB97X-D!
Electronic part successfully calculated for HF of method wB97X-V!
Electronic part successfully calculated for HNC of method B3LYP!
Electronic part successfully calculated for HNC of method B97-D3!
Electronic part successfully calculated for HNC of method B97M-V!
Electronic part successfully calculated for HNC of method BLYP!
Electronic part successfully calculated for HNC of method BPBE!
Electronic part successfully calculated for HNC of method CAM-B3LYP!
Electronic part successfully calculated for HNC of method M06-2X!
Electronic part successfully calculated for HNC of method M06-L!
Electronic part successfully calculated for HNC of method M08-HX!
Electronic part successfully calculated for HNC of method MGGA_MS2!
Electronic part successfully calculated for HNC of method MN15!
Electronic part successfully calculated for HNC of method MN15-L!
Electronic part successfully calculated for HNC of method PBE!
Electronic part successfully calculated for HNC of method PBE0!
Electronic part successfully calculated for HNC of method SCAN!
Electronic part successfully calculated for HNC of method SCAN0!
Electronic part successfully calculated for HNC of method SPW92!
Electronic part successfully calculated for HNC of method Slater!
Electronic part successfully calculated for HNC of method TPSS!
Electronic part successfully calculated for HNC of method mBEEF!
Electronic part successfully calculated for HNC of method mPW91!
Electronic part successfully calculated for HNC of method revM06-L!
Electronic part successfully calculated for HNC of method wB97M-V!
Electronic part successfully calculated for HNC of method wB97X-D!
Electronic part successfully calculated for HNC of method wB97X-V!
Electronic part successfully calculated for LiBH4 of method B3LYP!
Electronic part successfully calculated for LiBH4 of method B97-D3!
Electronic part successfully calculated for LiBH4 of method B97M-V!
Electronic part successfully calculated for LiBH4 of method BLYP!
Electronic part successfully calculated for LiBH4 of method BPBE!
Electronic part successfully calculated for LiBH4 of method CAM-B3LYP!
Electronic part successfully calculated for LiBH4 of method M06-2X!
Electronic part successfully calculated for LiBH4 of method M06-L!
Electronic part successfully calculated for LiBH4 of method M08-HX!
Electronic part successfully calculated for LiBH4 of method MGGA_MS2!
Electronic part successfully calculated for LiBH4 of method MN15!
Electronic part successfully calculated for LiBH4 of method MN15-L!
Electronic part successfully calculated for LiBH4 of method PBE!
Electronic part successfully calculated for LiBH4 of method PBE0!
Electronic part successfully calculated for LiBH4 of method SCAN!
Electronic part successfully calculated for LiBH4 of method SCAN0!
Electronic part successfully calculated for LiBH4 of method SPW92!
Electronic part successfully calculated for LiBH4 of method Slater!
Electronic part successfully calculated for LiBH4 of method TPSS!
Electronic part successfully calculated for LiBH4 of method mBEEF!
Electronic part successfully calculated for LiBH4 of method mPW91!
Electronic part successfully calculated for LiBH4 of method revM06-L!
Electronic part successfully calculated for LiBH4 of method wB97M-V!
Electronic part successfully calculated for LiBH4 of method wB97X-D!
Electronic part successfully calculated for LiBH4 of method wB97X-V!
Electronic part successfully calculated for Mg of method B3LYP!
Electronic part successfully calculated for Mg of method B97-D3!
Electronic part successfully calculated for Mg of method B97M-V!
Electronic part successfully calculated for Mg of method BLYP!
Electronic part successfully calculated for Mg of method BPBE!
Electronic part successfully calculated for Mg of method CAM-B3LYP!
Electronic part successfully calculated for Mg of method M06-2X!
Electronic part successfully calculated for Mg of method M06-L!
Electronic part successfully calculated for Mg of method M08-HX!
Electronic part successfully calculated for Mg of method MGGA_MS2!
Electronic part successfully calculated for Mg of method MN15!
Electronic part successfully calculated for Mg of method MN15-L!
Electronic part successfully calculated for Mg of method PBE!
Electronic part successfully calculated for Mg of method PBE0!
Electronic part successfully calculated for Mg of method SCAN!
Electronic part successfully calculated for Mg of method SCAN0!
Electronic part successfully calculated for Mg of method SPW92!
Electronic part successfully calculated for Mg of method Slater!
Electronic part successfully calculated for Mg of method TPSS!
Electronic part successfully calculated for Mg of method mBEEF!
Electronic part successfully calculated for Mg of method mPW91!
Electronic part successfully calculated for Mg of method revM06-L!
Electronic part successfully calculated for Mg of method wB97M-V!
Electronic part successfully calculated for Mg of method wB97X-D!
Electronic part successfully calculated for Mg of method wB97X-V!
Electronic part successfully calculated for Mg2 of method B3LYP!
Electronic part successfully calculated for Mg2 of method B97-D3!
Electronic part successfully calculated for Mg2 of method B97M-V!
Electronic part successfully calculated for Mg2 of method BLYP!
Electronic part successfully calculated for Mg2 of method BPBE!
Electronic part successfully calculated for Mg2 of method CAM-B3LYP!
Electronic part successfully calculated for Mg2 of method M06-2X!
Electronic part successfully calculated for Mg2 of method M06-L!
Electronic part successfully calculated for Mg2 of method M08-HX!
Electronic part successfully calculated for Mg2 of method MGGA_MS2!
Electronic part successfully calculated for Mg2 of method MN15!
Electronic part successfully calculated for Mg2 of method MN15-L!
Electronic part successfully calculated for Mg2 of method PBE!
Electronic part successfully calculated for Mg2 of method PBE0!

Electronic part successfully calculated for O3 of method CAM-B3LYP!
Electronic part successfully calculated for O3 of method M06-2X!
Electronic part successfully calculated for O3 of method M06-L!
Electronic part successfully calculated for O3 of method M08-HX!
Electronic part successfully calculated for O3 of method MGGA_MS2!
Electronic part successfully calculated for O3 of method MN15!
Electronic part successfully calculated for O3 of method MN15-L!
Electronic part successfully calculated for O3 of method PBE!
Electronic part successfully calculated for O3 of method PBE0!
Electronic part successfully calculated for O3 of method SCAN!
Electronic part successfully calculated for O3 of method SCAN0!
Electronic part successfully calculated for O3 of method SPW92!
Electronic part successfully calculated for O3 of method Slater!
Electronic part successfully calculated for O3 of method TPSS!
Electronic part successfully calculated for O3 of method mBEEF!
Electronic part successfully calculated for O3 of method mPW91!
Electronic part successfully calculated for O3 of method revM06-L!
Electronic part successfully calculated for O3 of method wB97M-V!
Electronic part successfully calculated for O3 of method wB97X-D!
Electronic part successfully calculated for O3 of method wB97X-V!
Electronic part successfully calculated for P of method B3LYP!
Electronic part successfully calculated for P of method B97-D3!
Electronic part successfully calculated for P of method B97M-V!
Electronic part successfully calculated for P of method BLYP!
Electronic part successfully calculated for P of method BPBE!
Electronic part successfully calculated for P of method CAM-B3LYP!
Electronic part successfully calculated for P of method M06-2X!
Electronic part successfully calculated for P of method M06-L!
Electronic part successfully calculated for P of method M08-HX!
Electronic part successfully calculated for P of method MGGA_MS2!
Electronic part successfully calculated for P of method MN15!
Electronic part successfully calculated for P of method MN15-L!
Electronic part successfully calculated for P of method PBE!
Electronic part successfully calculated for P of method PBE0!
Electronic part successfully calculated for P of method SCAN!
Electronic part successfully calculated for P of method SCAN0!
Electronic part successfully calculated for P of method SPW92!
Electronic part successfully calculated for P of method Slater!
Electronic part successfully calculated for P of method TPSS!
Electronic part successfully calculated for P of method mBEEF!
Electronic part successfully calculated for P of method mPW91!
Electronic part successfully calculated for P of method revM06-L!
Electronic part successfully calculated for P of method wB97M-V!
Electronic part successfully calculated for P of method wB97X-D!
Electronic part successfully calculated for P of method wB97X-V!
Electronic part successfully calculated for HCl of method B3LYP!
Electronic part successfully calculated for HCl of method B97-D3!
Electronic part successfully calculated for HCl of method B97M-V!
Electronic part successfully calculated for HCl of method BLYP!
Electronic part successfully calculated for HCl of method BPBE!
Electronic part successfully calculated for HCl of method CAM-B3LYP!
Electronic part successfully calculated for HCl of method M06-2X!
Electronic part successfully calculated for HCl of method M06-L!
Electronic part successfully calculated for HCl of method M08-HX!
Electronic part successfully calculated for HCl of method MGGA_MS2!
Electronic part successfully calculated for HCl of method MN15!
Electronic part successfully calculated for HCl of method MN15-L!
Electronic part successfully calculated for HCl of method PBE!
Electronic part successfully calculated for HCl of method PBE0!
Electronic part successfully calculated for HCl of method SCAN!
Electronic part successfully calculated for HCl of method SCAN0!
Electronic part successfully calculated for HCl of method SPW92!
Electronic part successfully calculated for HCl of method Slater!
Electronic part successfully calculated for HCl of method TPSS!
Electronic part successfully calculated for HCl of method mBEEF!
Electronic part successfully calculated for HCl of method mPW91!
Electronic part successfully calculated for HCl of method revM06-L!
Electronic part successfully calculated for HCl of method wB97M-V!
Electronic part successfully calculated for HCl of method wB97X-D!
Electronic part successfully calculated for HCl of method wB97X-V!
Electronic part successfully calculated for NH of method B3LYP!
Electronic part successfully calculated for NH of method B97-D3!
Electronic part successfully calculated for NH of method B97M-V!
Electronic part successfully calculated for NH of method BLYP!
Electronic part successfully calculated for NH of method BPBE!
Electronic part successfully calculated for NH of method CAM-B3LYP!
Electronic part successfully calculated for NH of method M06-2X!
Electronic part successfully calculated for NH of method M06-L!
Electronic part successfully calculated for NH of method M08-HX!
Electronic part successfully calculated for NH of method MGGA_MS2!
Electronic part successfully calculated for NH of method MN15!
Electronic part successfully calculated for NH of method MN15-L!
Electronic part successfully calculated for NH of method PBE!
Electronic part successfully calculated for NH of method PBE0!
Electronic part successfully calculated for NH of method SCAN!
Electronic part successfully calculated for NH of method SCAN0!
Electronic part successfully calculated for NH of method SPW92!
Electronic part successfully calculated for NH of method Slater!
Electronic part successfully calculated for NH of method TPSS!
Electronic part successfully calculated for NH of method mBEEF!
Electronic part successfully calculated for NH of method mPW91!
Electronic part successfully calculated for NH of method revM06-L!
Electronic part successfully calculated for NH of method wB97M-V!
Electronic part successfully calculated for NH of method wB97X-D!
Electronic part successfully calculated for NH of method wB97X-V!
Electronic part successfully calculated for PH of method B3LYP!
Electronic part successfully calculated for PH of method B97-D3!
Electronic part successfully calculated for PH of method B97M-V!
Electronic part successfully calculated for PH of method BLYP!
Electronic part successfully calculated for PH of method BPBE!
Electronic part successfully calculated for PH of method CAM-B3LYP!
Electronic part successfully calculated for PH of method M06-2X!
Electronic part successfully calculated for PH of method M06-L!
Electronic part successfully calculated for PH of method M08-HX!
Electronic part successfully calculated for PH of method MGGA_MS2!
Electronic part successfully calculated for PH of method MN15!
Electronic part successfully calculated for PH of method MN15-L!
Electronic part successfully calculated for PH of method PBE!
Electronic part successfully calculated for PH of method PBE0!
Electronic part successfully calculated for PH of method SCAN!
Electronic part successfully calculated for PH of method SCAN0!
Electronic part successfully calculated for PH of method SPW92!
Electronic part successfully calculated for PH of method Slater!
Electronic part successfully calculated for PH of method TPSS!
Electronic part successfully calculated for PH of method mBEEF!
Electronic part successfully calculated for PH of method mPW91!
Electronic part successfully calculated for PH of method revM06-L!
Electronic part successfully calculated for PH of method wB97M-V!
Electronic part successfully calculated for PH of method wB97X-D!
Electronic part successfully calculated for PH of method wB97X-V!
DFT method has not been calculated for SiO of method B3LYP!
DFT method has not been calculated for SiO of method B97-D3!
DFT method has not been calculated for SiO of method B97M-V!
DFT method has not been calculated for SiO of method BLYP!
DFT method has not been calculated for SiO of method BPBE!
DFT method has not been calculated for SiO of method CAM-B3LYP!
DFT method has not been calculated for SiO of method M06-2X!
DFT method has not been calculated for SiO of method M06-L!
DFT method has not been calculated for SiO of method M08-HX!
DFT method has not been calculated for SiO of method MGGA_MS2!
DFT method has not been calculated for SiO of method MN15!
DFT method has not been calculated for SiO of method MN15-L!
DFT method has not been calculated for SiO of method PBE!
DFT method has not been calculated for SiO of method PBE0!
DFT method has not been calculated for SiO of method SCAN!
DFT method has not been calculated for SiO of method SCAN0!
DFT method has not been calculated for SiO of method SPW92!
DFT method has not been calculated for SiO of method Slater!
DFT method has not been calculated for SiO of method TPSS!
DFT method has not been calculated for SiO of method mBEEF!
DFT method has not been calculated for SiO of method mPW91!
DFT method has not been calculated for SiO of method revM06-L!
DFT method has not been calculated for SiO of method wB97M-V!
DFT method has not been calculated for SiO of method wB97X-D!
DFT method has not been calculated for SiO of method wB97X-V!
Electronic part successfully calculated for LiH of method B3LYP!
Electronic part successfully calculated for LiH of method B97-D3!
Electronic part successfully calculated for LiH of method B97M-V!
Electronic part successfully calculated for LiH of method BLYP!
Electronic part successfully calculated for LiH of method BPBE!
Electronic part successfully calculated for LiH of method CAM-B3LYP!
Electronic part successfully calculated for LiH of method M06-2X!
Electronic part successfully calculated for LiH of method M06-L!
Electronic part successfully calculated for LiH of method M08-HX!
Electronic part successfully calculated for LiH of method MGGA_MS2!
Electronic part successfully calculated for LiH of method MN15!
Electronic part successfully calculated for LiH of method MN15-L!
Electronic part successfully calculated for LiH of method PBE!
Electronic part successfully calculated for LiH of method PBE0!
Electronic part successfully calculated for LiH of method SCAN!
Electronic part successfully calculated for LiH of method SCAN0!
Electronic part successfully calculated for LiH of method SPW92!
Electronic part successfully calculated for LiH of method Slater!
Electronic part successfully calculated for LiH of method TPSS!
DFT method has not been calculated for LiH of method mBEEF!
Electronic part successfully calculated for LiH of method mPW91!
Electronic part successfully calculated for LiH of method revM06-L!
Electronic part successfully calculated for LiH of method wB97M-V!
Electronic part successfully calculated for LiH of method wB97X-D!
Electronic part successfully calculated for LiH of method wB97X-V!

In [32]:
data['BF']

[{'name': 'BF',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.8268, -10.8268, -12.6137],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 1.0097, 1.0097],
  'quadrupoles_elec': [-8.049476783600001,
   -8.049476783600001,
   -60.9633764850087],
  'dipoles_elec': [-0.0, -0.0, -21.14964385909, 21.14964385909],
  'std_dev': [0.7582629012420429, 0.7582629012420429, 1.4395645519048152],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.6846, -10.6846, -12.5204],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.0262, 1.0262],
  'quadrupoles_elec': [-7.9437543542, -7.9437543542, -60.89401008090871],
  'dipoles_elec': [0.0, -0.0, -21.14315225914, 21.14315225914],
  'std_dev': [0.7532669017685564, 0.7532669017685564, 1.4383296251589635],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-10.6829, -10.6829, -12.7801],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.9444, 0.9444],
  'quadrupoles_elec': [-7.9424904433000005,
   -7.9424904433000005,
   -61.087091057808706],
  'dipoles_elec': [-0.0, 0.0, -21.17533485768, 21.17533485768],
  'std_dev': [0.7532069741777488, 0.7532069741777488, 1.440706438951725],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.5852, -10.5852, -12.7224],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.8462, 0.8462],
  'quadrupoles_elec': [-7.869852740400001,
   -7.869852740400001,
   -61.04419243490871],
  'dipoles_elec': [0.0, 0.0, -21.21396971314, 21.21396971314],
  'std_dev': [0.7497548523350815, 0.7497548523350815, 1.4367377004489479],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.4172, -10.4172, -12.3321],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, 1.0888, 1.0888],
  'quadrupoles_elec': [-7.7449486044, -7.7449486044, -60.7540133618087],
  'dipoles_elec': [0.0, -0.0, -21.118523522359997, 21.118523522359997],
  'std_dev': [0.7437812948710124, 0.7437812948710124, 1.4366985810389856],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.579, -10.579, -12.4222],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, 1.0998, 1.0998],
  'quadrupoles_elec': [-7.865243183000001,
   -7.865243183000001,
   -60.8210006395087],
  'dipoles_elec': [0.0, 0.0, -21.11419578906, 21.11419578906],
  'std_dev': [0.7495352456689413, 0.7495352456689413, 1.4386869458768805],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-10.6652, -10.6652, -12.6677],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.0, 0.9241, 0.9241],
  'quadrupoles_elec': [-7.929330900400001,
   -7.929330900400001,
   -61.003524243008705],
  'dipoles_elec': [0.0, 0.0, -21.18332149277, 21.18332149277],
  'std_dev': [0.7525827387071803, 0.7525827387071803, 1.4380333614535588],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.8039, -10.8039, -12.8623],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 1.0803, 1.0803],
  'quadrupoles_elec': [-8.0324511603, -8.0324511603, -61.148204867208705],
  'dipoles_elec': [0.0, 0.0, -21.121867679909997, 21.121867679909997],
  'std_dev': [0.7574605675875148, 0.7574605675875148, 1.4462152820754766],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.4446, -10.4446, -12.651],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 1.1604, 1.1604],
  'quadrupoles_elec': [-7.7653198742, -7.7653198742, -60.9911081771087],
  'dipoles_elec': [-0.0, 0.0, -21.090353912879998, 21.090353912879998],
  'std_dev': [0.7447588235798217, 0.7447588235798217, 1.4446814603865583],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-11.2366, -11.2366, -12.7018],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, 1.1196, 1.1196],
  'quadrupoles_elec': [-8.3541536582, -8.3541536582, -61.0288768087087],
  'dipoles_elec': [0.0, -0.0, -21.10640586912, 21.10640586912],
  'std_dev': [0.7724799423286017, 0.7724799423286017, 1.4444190743324463],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-10.52939432275025,
   -10.52939432275025,
   -12.59967014601273],
  'quadrupoles_mp2': [-10.618301048268405,
   -10.618301048268405,
   -12.680237662762089],
  'quadrupoles_ccsd': [-10.478753805079696,
   -10.478753805079696,
   -12.709828403539177],
  'quadrupoles_hf': [-10.4126, -10.4126, -13.2925],
  'dipoles_ccsdt': [0.0, 0.0, 0.8217, 0.8217],
  'dipoles_mp2': [0.0, 0.0, 0.953, 0.953],
  'dipoles_ccsd': [0.0, 0.0, 0.7959, 0.7959],
  'dipoles_hf': [0.0, -0.0, 0.8468, 0.8468],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -21.21373365496, 21.21373365496],
  'dipoles_elec_mp2': [0.0, 0.0, -21.1719513571, 21.1719513571],
  'dipoles_elec_ccsd': [0.0, 0.0, -21.23375925723, 21.23375925723],
  'dipoles_elec_ccsdt': [0.0, 0.0, -21.223608755489998, 21.223608755489998],
  'quadrupoles_elec_hf': [-7.7415286102000005,
   -7.7415286102000005,
   -61.4680486726087],
  'quadrupoles_elec_mp2': [-7.894462608463449,
   -7.894462608463449,
   -61.01284570690608],
  'quadrupoles_elec_ccsd': [-7.790712442739238,
   -7.790712442739238,
   -61.0348457420868],
  'quadrupoles_elec_ccsdt': [-7.828362502895388,
   -7.828362502895388,
   -60.952945611255814],
  'std_dev_hf': [0.7436170582362941, 0.7436170582362941, 1.4472531791133751],
  'std_dev_mp2': [0.7509262189581729, 0.7509262189581729, 1.4391187702351909],
  'std_dev_ccsd': [0.7459755091125042, 0.7459755091125042, 1.4350128140564449],
  'std_dev_ccsdt': [0.7477758689653027,
   0.7477758689653027,
   1.4337400604631532]},
 {'name': 'BF',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-10.572166393427322,
   -10.572166393427322,
   -12.64493052903998],
  'quadrupoles_mp2': [-10.659324575222243,
   -10.659324575222243,
   -12.72993665688201],
  'quadrupoles_ccsd': [-10.521727630776027,
   -10.521727630776027,
   -12.750112161866072],
  'quadrupoles_hf': [-10.4234, -10.4234, -13.3092],
  'dipoles_ccsdt': [0.0, 0.0, 0.8254, 0.8254],
  'dipoles_mp2': [0.0, 0.0, 0.9541, 0.9541],
  'dipoles_ccsd': [0.0, 0.0, 0.7983, 0.7983],
  'dipoles_hf': [0.0, -0.0, 0.8451, 0.8451],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -21.214402486469996, 21.214402486469996],
  'dipoles_elec_mp2': [0.0, 0.0, -21.17151858377, 21.17151858377],
  'dipoles_elec_ccsd': [0.0, 0.0, -21.232815024509996, 21.232815024509996],
  'dipoles_elec_ccsdt': [0.0, 0.0, -21.22215306338, 21.22215306338],
  'quadrupoles_elec_hf': [-7.749558161800001,
   -7.749558161800001,
   -61.4804647385087],
  'quadrupoles_elec_mp2': [-7.924962657212508,
   -7.924962657212508,
   -61.04979576595737],
  'quadrupoles_elec_ccsd': [-7.822662493746469,
   -7.822662493746469,
   -61.064795789876406],
  'quadrupoles_elec_ccsdt': [-7.860162553686165,
   -7.860162553686165,
   -60.98659566504776],
  'std_dev_hf': [0.744002599928253, 0.744002599928253, 1.4475095316756021],
  'std_dev_mp2': [0.7523754124301677, 0.7523754124301677, 1.4400679221163828],
  'std_dev_ccsd': [0.7475035830657779, 0.7475035830657779, 1.4358292548018936],
  'std_dev_ccsdt': [0.7492931218195952,
   0.7492931218195952,
   1.4346879036726383]},
 {'name': 'BF',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.6763, -10.6763, -12.7085],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, 0.9499, 0.9499],
  'quadrupoles_elec': [-7.9375834951, -7.9375834951, -61.033858104608704],
  'dipoles_elec': [0.0, -0.0, -21.17317099103, 21.17317099103],
  'std_dev': [0.7529742689162757, 0.7529742689162757, 1.4395486176922372],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'B97M-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.6481, -10.6481, -12.6917],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 1.0059, 1.0059],
  'quadrupoles_elec': [-7.9166174437, -7.9166174437, -61.021367691008706],
  'dipoles_elec': [-0.0, -0.0, -21.151138894229998, 21.151138894229998],
  'std_dev': [0.7519791716197995, 0.7519791716197995, 1.440890581945184],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'BPBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.6827, -10.6827, -12.383],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, 1.0651, 1.0651],
  'quadrupoles_elec': [-7.942341747900001,
   -7.942341747900001,
   -60.791856341108705],
  'dipoles_elec': [0.0, -0.0, -21.12784782047, 21.12784782047],
  'std_dev': [0.7531999235594757, 0.7531999235594757, 1.4369398380646494],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'M08-HX',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-10.5817, -10.5817, -12.9043],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.8602, 0.8602],
  'quadrupoles_elec': [-7.8672505709000005,
   -7.8672505709000005,
   -61.179430901208704],
  'dipoles_elec': [-0.0, -0.0, -21.208461688939998, 21.208461688939998],
  'std_dev': [0.7496308887379175, 0.7496308887379175, 1.4405093795175339],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'mBEEF',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.5541, -10.5541, -12.4896],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 1.0184, 1.0184],
  'quadrupoles_elec': [-7.8467306057, -7.8467306057, -60.871110989308704],
  'dipoles_elec': [-0.0, 0.0, -21.14622101548, 21.14622101548],
  'std_dev': [0.7486526280926289, 0.7486526280926289, 1.437530639628734],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'mPW91',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.7316, -10.7316, -12.4425],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, 1.0436, 1.0436],
  'quadrupoles_elec': [-7.9786977732, -7.9786977732, -60.8360932226087],
  'dipoles_elec': [0.0, -0.0, -21.13630657192, 21.13630657192],
  'std_dev': [0.7549218395304246, 0.7549218395304246, 1.4374045658016446],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.7818, -10.7818, -12.4576],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, 1.0485, 1.0485],
  'quadrupoles_elec': [-8.0160203186, -8.0160203186, -60.84731972530871],
  'dipoles_elec': [0.0, -0.0, -21.134378763449998, 21.134378763449998],
  'std_dev': [0.7566854563819765, 0.7566854563819765, 1.437828064494407],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'PBE0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.6087, -10.6087, -12.6047],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.9755, 0.9755],
  'quadrupoles_elec': [-7.887324449900001,
   -7.887324449900001,
   -60.956685192008706],
  'dipoles_elec': [-0.0, -0.0, -21.16309917535, 21.16309917535],
  'std_dev': [0.7505866491285333, 0.7505866491285333, 1.438389167739211],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'SCAN',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.6164, -10.6164, -12.4753],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, 1.0522, 1.0522],
  'quadrupoles_elec': [-7.893049222800001,
   -7.893049222800001,
   -60.86047926820871],
  'dipoles_elec': [0.0, -0.0, -21.13292307134, 21.13292307134],
  'std_dev': [0.7508589948851915, 0.7508589948851915, 1.438264033365286],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'SCAN0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-10.5303, -10.5303, -12.6353],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.968, 0.968],
  'quadrupoles_elec': [-7.829035853100001,
   -7.829035853100001,
   -60.9794355882087],
  'dipoles_elec': [0.0, 0.0, -21.166049902599998, 21.166049902599998],
  'std_dev': [0.7478080279389892, 0.7478080279389892, 1.4387324880679828],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'SPW92',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-10.8668, -10.8668, -12.4504],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.0451, 1.0451],
  'quadrupoles_elec': [-8.0792158636, -8.0792158636, -60.841966690908706],
  'dipoles_elec': [0.0, -0.0, -21.135716426469997, 21.135716426469997],
  'std_dev': [0.7596623245890243, 0.7596623245890243, 1.437594761406464],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.6357, -10.6357, -12.476],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, 1.0612, 1.0612],
  'quadrupoles_elec': [-7.9073983289, -7.9073983289, -60.86099970210871],
  'dipoles_elec': [0.0, -0.0, -21.12938219864, 21.12938219864],
  'std_dev': [0.7515411940472725, 0.7515411940472725, 1.4385423527585792],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'wB97M-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 7,
  'quadrupoles': [-10.7472, -10.7472, -12.7342],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, 0.9207, 0.9207],
  'quadrupoles_elec': [-7.9902960144, -7.9902960144, -61.052965463508706],
  'dipoles_elec': [0.0, 0.0, -21.184659155789998, 21.184659155789998],
  'std_dev': [0.7554703366777547, 0.7554703366777547, 1.4391602797913818],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'wB97X-D',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-10.5751, -10.5751, -12.6201],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.0087, 1.0087],
  'quadrupoles_elec': [-7.862343622700001,
   -7.862343622700001,
   -60.968134737808704],
  'dipoles_elec': [0.0, -0.0, -21.15003728939, 21.15003728939],
  'std_dev': [0.7493970730193708, 0.7493970730193708, 1.4396531062234572],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-10.6414, -10.6414, -12.7185],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, 0.993, 0.993],
  'quadrupoles_elec': [-7.911636147800001,
   -7.911636147800001,
   -61.0412928746087],
  'dipoles_elec': [0.0, 0.0, -21.156214145099998, 21.156214145099998],
  'std_dev': [0.7517425541367205, 0.7517425541367205, 1.4410042970576935],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcV5Zp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-10.514531700672691,
   -10.514531700672691,
   -12.588842624989326],
  'quadrupoles_mp2': [-10.602496902640215,
   -10.602496902640215,
   -12.667258087881363],
  'quadrupoles_ccsd': [-10.463891183002138,
   -10.463891183002138,
   -12.700682174597778],
  'quadrupoles_hf': [-10.4082, -10.4082, -13.2911],
  'dipoles_ccsdt': [0, 0, 0.8208, 0.8208],
  'dipoles_mp2': [0, 0, 0.9531, 0.9531],
  'dipoles_ccsd': [0, 0, 0.7954, 0.7954],
  'dipoles_hf': [0.0, -0.0, 0.8471, 0.8471],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -21.21361562587, 21.21361562587],
  'dipoles_elec_mp2': [0.0, 0.0, -21.17191201407, 21.17191201407],
  'dipoles_elec_ccsd': [0.0, 0.0, -21.23395597238, 21.23395597238],
  'dipoles_elec_ccsdt': [0.0, 0.0, -21.22396284276, 21.22396284276],
  'quadrupoles_elec_hf': [-7.738257311400001,
   -7.738257311400001,
   -61.4670078048087],
  'quadrupoles_elec_mp2': [-7.88271258968424,
   -7.88271258968424,
   -61.003195691512474],
  'quadrupoles_elec_ccsd': [-7.779662425064881,
   -7.779662425064881,
   -61.02804573123214],
  'quadrupoles_elec_ccsdt': [-7.817312485221031,
   -7.817312485221031,
   -60.944895598407896],
  'std_dev_hf': [0.7434599283754304, 0.7434599283754304, 1.447236320041328],
  'std_dev_mp2': [0.7503671762964849, 0.7503671762964849, 1.4388822216228512],
  'std_dev_ccsd': [0.7454462913040215, 0.7454462913040215, 1.4348287140899176],
  'std_dev_ccsdt': [0.7472479262132974,
   0.7472479262132974,
   1.433512774846186]}]

In [35]:
save(data)

b'\x1b[0;32mSaving updates to GitHub...\x1b[0m\n[master 6320558] save Mon, Aug  3, 2020  9:38:26 PM\n 672 files changed, 440695 insertions(+), 11108 deletions(-)\n create mode 100644 output/dft/20-07-28/BO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B97M-rV_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4

In [508]:
wft_table.to_csv('wft_table_2.csv')

In [478]:
std_dev_dft = make_dft_table('std_dev', get_wft_species())

In [479]:
std_dev_dft.to_csv('dft_table.csv')

In [447]:
quadrupoles_table.loc['HCl']

method      Slater                      SPW92                   B97-D3       \
component       XX       YY       ZZ       XX       YY       ZZ     XX   YY
molecule
HCl       -14.4753 -14.4753 -10.7091 -14.1432 -14.1432 -10.4192    0.0  0.0

method         BLYP  ... CAM-B3LYP wB97X-D           wB97X-V            \
component   ZZ   XX  ...        ZZ      XX   YY   ZZ      XX   YY   ZZ
molecule             ...
HCl        0.0  0.0  ...       0.0     0.0  0.0  0.0     0.0  0.0  0.0

method    wB97M-V
component      XX   YY   ZZ
molecule
HCl           0.0  0.0  0.0

[1 rows x 81 columns]

In [488]:
data['HBO']

[{'name': 'HBO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0978, -11.0978, -19.9502],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-8.2509590506, -8.2509590506, -199.033869166212],
  'dipoles_elec': [-0.0, 0.0, -47.803149380650005, 47.803149380650005],
  'std_dev': [0.7676940913541018, 0.7676940913541018, 1.599319175331429],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0084, -11.0084, -20.1871],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -2.6504, 2.6504],
  'quadrupoles_elec': [-8.1844922068, -8.1844922068, -199.209998867512],
  'dipoles_elec': [-0.0, -0.0, -47.82868300712, 47.82868300712],
  'std_dev': [0.7645957011388437, 0.7645957011388437, 1.599357437857018],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-11.0795, -11.0795, -20.9574],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.8692, 2.8692],
  'quadrupoles_elec': [-8.2373534215, -8.2373534215, -199.78269920061203],
  'dipoles_elec': [-0.0, 0.0, -47.91476555676, 47.91476555676],
  'std_dev': [0.7670608758436321, 0.7670608758436321, 1.5990000549598815],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.9943, -10.9943, -20.9452],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.9066, 2.9066],
  'quadrupoles_elec': [-8.1740091811, -8.1740091811, -199.773628781212],
  'dipoles_elec': [0.0, 0.0, -47.929479849980005, 47.929479849980005],
  'std_dev': [0.764105881831831, 0.764105881831831, 1.5965456400785158],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.7705, -10.7705, -19.8658],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-8.0076190285, -8.0076190285, -198.97111970741202],
  'dipoles_elec': [0.0, -0.0, -47.803149380650005, 47.803149380650005],
  'std_dev': [0.7562888256149234, 0.7562888256149234, 1.597917307116611],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.9448, -10.9448, -20.0411],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, -2.6413, 2.6413],
  'quadrupoles_elec': [-8.1372070696, -8.1372070696, -199.10145122551202],
  'dipoles_elec': [0.0, -0.0, -47.82510279139, 47.82510279139],
  'std_dev': [0.7623838117378936, 0.7623838117378936, 1.5974786577574538],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-10.9999, -10.9999, -20.7016],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.7898, 2.7898],
  'quadrupoles_elec': [-8.1781726523, -8.1781726523, -199.59251778401202],
  'dipoles_elec': [-0.0, 0.0, -47.88352719094, 47.88352719094],
  'std_dev': [0.7643004575754223, 0.7643004575754223, 1.5995265127382026],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-11.1407, -11.1407, -20.7911],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -2.7518, 2.7518],
  'quadrupoles_elec': [-8.2828542139, -8.2828542139, -199.659058975512],
  'dipoles_elec': [0.0, -0.0, -47.868576839540005, 47.868576839540005],
  'std_dev': [0.7691764712015052, 0.7691764712015052, 1.6032909029431675],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.8551, -10.8551, -20.3839],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.6621, 2.6621],
  'quadrupoles_elec': [-8.070517182700002,
   -8.070517182700002,
   -199.35631514111202],
  'dipoles_elec': [0.0, 0.0, -47.833286141630005, 47.833286141630005],
  'std_dev': [0.7592532601510514, 0.7592532601510514, 1.6019203222123481],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-11.4667, -11.4667, -20.1273],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, -2.5652, 2.5652],
  'quadrupoles_elec': [-8.5252277159, -8.5252277159, -199.165538942912],
  'dipoles_elec': [0.0, -0.0, -47.79516274556, 47.79516274556],
  'std_dev': [0.780349176234588, 0.780349176234588, 1.6034719398444037],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-10.99948358996839,
   -10.99948358996839,
   -20.338388612318287],
  'quadrupoles_mp2': [-11.074939978926075,
   -11.074939978926075,
   -20.21229170588119],
  'quadrupoles_ccsd': [-10.967135530276206,
   -10.967135530276206,
   -20.70746585104695],
  'quadrupoles_hf': [-10.9055, -10.9055, -22.4865],
  'dipoles_ccsdt': [0.0, 0.0, -2.7215, 2.7215],
  'dipoles_mp2': [0.0, 0.0, -2.6652, 2.6652],
  'dipoles_ccsd': [0.0, 0.0, -2.8384, 2.8384],
  'dipoles_hf': [0.0, -0.0, -3.3361, 3.3361],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -48.09845816383, 48.09845816383],
  'dipoles_elec_mp2': [-0.0, -0.0, -45.73736490444, 45.73736490444],
  'dipoles_elec_ccsd': [-0.0, -0.0, -45.66922277648, 45.66922277648],
  'dipoles_elec_ccsdt': [-0.0, -0.0, -45.71521477855, 45.71521477855],
  'quadrupoles_elec_hf': [-8.1079884235, -8.1079884235, -200.919549881312],
  'quadrupoles_elec_mp2': [-8.233963150712022,
   -8.233963150712022,
   -199.22872832142545],
  'quadrupoles_elec_ccsd': [-8.153813022643163,
   -8.153813022643163,
   -199.59687890935086],
  'quadrupoles_elec_ccsdt': [-8.177863061018929,
   -8.177863061018929,
   -199.32247847113257],
  'std_dev_hf': [0.7610138173844152, 0.7610138173844152, 1.59625202059972],
  'std_dev_mp2': [0.7669030088941227, 0.7669030088941227, 1.8861683004554883],
  'std_dev_ccsd': [0.7631613301937429, 0.7631613301937429, 1.9015010125236143],
  'std_dev_ccsdt': [0.7642859908352804,
   0.7642859908352804,
   1.8906777700976238]},
 {'name': 'HBO',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-11.044071456105497,
   -11.044071456105497,
   -20.348476364810317],
  'quadrupoles_mp2': [-11.11408045858751,
   -11.11408045858751,
   -20.24161343990222],
  'quadrupoles_ccsd': [-11.010849124503912,
   -11.010849124503912,
   -20.70531379718963],
  'quadrupoles_hf': [-10.9126, -10.9126, -22.4967],
  'dipoles_ccsdt': [0.0, 0.0, -2.7075, 2.7075],
  'dipoles_mp2': [0.0, 0.0, -2.6584, 2.6584],
  'dipoles_ccsd': [0.0, 0.0, -2.8218, 2.8218],
  'dipoles_hf': [0.0, -0.0, -3.3371, 3.3371],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -48.098851594130004, 48.098851594130004],
  'dipoles_elec_mp2': [-0.0, -0.0, -45.740040230480005, 45.740040230480005],
  'dipoles_elec_ccsd': [-0.0, -0.0, -45.675753719460005, 45.675753719460005],
  'dipoles_elec_ccsdt': [-0.0, -0.0, -45.720722802750004, 45.720722802750004],
  'quadrupoles_elec_hf': [-8.1132671102, -8.1132671102, -200.92713334671203],
  'quadrupoles_elec_mp2': [-8.263063197109267,
   -8.263063197109267,
   -199.2505283562702],
  'quadrupoles_elec_ccsd': [-8.186313074538795,
   -8.186313074538795,
   -199.59527890680516],
  'quadrupoles_elec_ccsdt': [-8.211013113970948,
   -8.211013113970948,
   -199.3299784830921],
  'std_dev_hf': [0.761261505200414, 0.761261505200414, 1.5963612037237105],
  'std_dev_mp2': [0.768256988118897, 0.768256988118897, 1.8862500817568768],
  'std_dev_ccsd': [0.7646807491897142, 0.7646807491897142, 1.90067043334621],
  'std_dev_ccsdt': [0.7658334915059608,
   0.7658334915059608,
   1.890139835499417]}]

In [507]:
save(data)

b'\x1b[0;32mSaving updates to GitHub...\x1b[0m\n[master 8bc6862] save\n 1 file changed, 1 insertion(+), 1 deletion(-)\n'
File saved!

In [557]:
wft_table.loc[('Ar', 'CBS'), ('hf', 'XX')] = 0.694399

In [567]:
wft_table.index[wft_table.index.get_level_values('basis') == 'CBS']

MultiIndex([(   'Ar', 'CBS'),
            (   'Be', 'CBS'),
            (  'BeH', 'CBS'),
            ( 'BeH2', 'CBS'),
            (   'BF', 'CBS'),
            (  'BH3', 'CBS'),
            (   'BO', 'CBS'),
            (   'BS', 'CBS'),
            (  'C2H', 'CBS'),
            ( 'C2H2', 'CBS'),
            (  'CH3', 'CBS'),
            (  'CH4', 'CBS'),
            (   'CN', 'CBS'),
            (   'CO', 'CBS'),
            (   'F2', 'CBS'),
            (    'H', 'CBS'),
            (   'H2', 'CBS'),
            (  'H2O', 'CBS'),
            (  'HBO', 'CBS'),
            (  'HCN', 'CBS'),
            (   'He', 'CBS'),
            (   'HF', 'CBS'),
            (  'HNC', 'CBS'),
            ('LiBH4', 'CBS'),
            (   'Mg', 'CBS'),
            (    'N', 'CBS'),
            (   'N2', 'CBS'),
            (   'Na', 'CBS'),
            (   'Ne', 'CBS'),
            (  'NH3', 'CBS'),
            ( 'NH3O', 'CBS'),
            (   'O2', 'CBS'),
            (   'OF', 'CBS'),
            (   'OH', 'CBS'),
            (    'P', 'CBS'),
            (   'SF', 'CBS'),
            (  'HCl', 'CBS'),
            (   'NH', 'CBS'),
            (   'PH', 'CBS'),
            (  'SiO', 'CBS')],
           names=['molecule', 'basis'])

In [192]:
#make extrapolation in this cell
def extrapolate(dataframe):
    molecules = wft_table.index[wft_table.index.get_level_values('basis') == 'CBS']
    columns = wft_table.columns
    for m in molecules:
        for c in columns:
            if c[0] == 'hf':
                if dataframe.loc[(m[0], '5Z'), c] != 0:
                    dataframe.loc[m, c] = dataframe.loc[(m[0], '5Z'), c]
                else:
                    dataframe.loc[m, c] = dataframe.loc[(m[0], 'QZ'), c]
            if dataframe.loc[(m[0], '5Z'), c] != 0:
                dataframe.loc[m, c] = ((dataframe.loc[(m[0], '5Z'), c] - dataframe.loc[(m[0], '5Z'), ('hf', c[1])]) * 125
                                       - (dataframe.loc[(m[0], 'QZ'), c] - dataframe.loc[(m[0], 'QZ'), ('hf', c[1])]) * 64) \
                                       / (125 - 64) + dataframe.loc[(m[0], 'CBS'), ('hf', c[1])]
            else:
                dataframe.loc[m, c] = ((dataframe.loc[(m[0], 'QZ'), c] - dataframe.loc[(m[0], 'QZ'), ('hf', c[1])]) * 64
                                       - (dataframe.loc[(m[0], 'TZ'), c] - dataframe.loc[(m[0], 'TZ'), ('hf', c[1])]) * 27) \
                                       / (64 - 27) + dataframe.loc[(m[0], 'CBS'), ('hf', c[1])]
    display(dataframe)

In [506]:
extrapolate(wft_table)

method                hf                           MP2                      \
component             XX        YY        ZZ        XX        YY        ZZ
molecule basis
AlF      5Z     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         QZ     0.728620  0.728620  1.762230  0.731470  0.731470  1.752314
         TZ     0.729178  0.729178  1.762396  0.733437  0.733437  1.753416
         CBS    0.728620  0.728620  1.762230  0.730442  0.730442  1.751630
Ar       5Z     0.694399  0.694399  0.694399  0.693865  0.693865  0.693865
...                  ...       ...       ...       ...       ...       ...
SiO      CBS    0.737226  0.737226  1.611787  0.759922  0.759922  1.664609
LiH      5Z     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         QZ     0.987146  0.987146  1.651777  0.988522  0.988522  1.646651
         TZ     0.988021  0.988021  1.651583  0.991225  0.991225  1.546393
         CBS    0.987146  0.987146  1.651777  0.987189  0.987189  1.719672

method              CCSD                     CCSD\(T\)
component             XX        YY        ZZ        XX        YY        ZZ
molecule basis
AlF      5Z     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         QZ     0.728352  0.728352  1.752450  0.729932  0.729932  1.751065
         TZ     0.730298  0.730298  1.753317  0.731928  0.731928  1.752099
         CBS    0.727339  0.727339  1.751938  0.728883  0.728883  1.750432
Ar       5Z     0.692929  0.692929  0.692929  0.693342  0.693342  0.693342
...                  ...       ...       ...       ...       ...       ...
SiO      CBS    0.745493  0.745493  1.673833  0.751225  0.751225  1.666390
LiH      5Z     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         QZ     0.996375  0.996375  1.645965  0.996507  0.996507  1.645823
         TZ     0.999088  0.999088  1.536849  0.999238  0.999238  1.540299
         CBS    0.995035  0.995035  1.725448  0.995153  0.995153  1.722685

[208 rows x 12 columns]

In [507]:
wft_table.loc['C2H']

method           hf                           MP2                      \
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.860498  0.860498  1.545005  0.000000  0.000000  0.000000
QZ         0.860668  0.860668  1.545016  0.870421  0.870421  1.547620
TZ         0.861166  0.861166  1.544931  0.871710  0.871710  1.548739
CBS        0.860498  0.860498  1.545005  0.869674  0.869674  1.546731

method         CCSD                     CCSD\(T\)
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
QZ         0.855555  0.855555  1.557354  0.855798  0.855798  1.558396
TZ         0.857163  0.857163  1.558318  0.857549  0.857549  1.559362
CBS        0.854576  0.854576  1.556578  0.854714  0.854714  1.557618

In [197]:
save(data)

b"\x1b[0;32mSaving updates to GitHub...\x1b[0m\nOn branch master\nYour branch is up to date with 'origin/master'.\n\nChanges not staged for commit:\n\tmodified:   ../geometries/cbs_limit/make_input.py\n\tmodified:   .ipynb_checkpoints/ouput-checkpoint.ipynb\n\tmodified:   ouput.ipynb\n\tmodified:   output.json\n\tmodified:   wft_table_2.csv\n\nUntracked files:\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2BH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2BH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2NH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2NH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3O_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH3O_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/FCO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/FCO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/H2CN_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/H2CN_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HCCF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HCCF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HCO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HCO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HNS_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HNS_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2Cl_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2Cl_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2OH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2OH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/O3_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/O3_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/hf/C2H2_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/C2H_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HBO_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HCN_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HF_ccsdT_aug-cc-pc-V5Z.inp\n\t../geometries/cbs_limit/hf/HNC_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/LiBH4_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/NH3O_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/NH3_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/O3_hf_aug-cc-pcV5Z.inp\n\t../geometries/inputs/HF_MP2_aug-cc-pcVDZ.inp\n\t../geometries/inputs/NH3-F2_TDDFT_aug-pc-2.inp\n\t../geometries/inputs/dft/CH3OH_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/to_delete.txt\n\t../geometries/inputs/rerun.sh\n\tcbs_limit/20-08-03/NH_ccsdT_aug-cc-pcV5Zp.out\n\twft_table (version 1).xlsx\n\t~$wft_table (version 1).xlsx\n\nno changes added to commit\n"
File saved!

In [231]:
len(get_dft_species())

53

In [210]:
get_functionals()

array(['B3LYP', 'B3LYP5', 'B97-D3', 'B97M-V', 'B97M-rV', 'BLYP', 'BPBE',
       'CAM-B3LYP', 'M06-2X', 'M06-L', 'M08-HX', 'MGGA_MS2', 'MN15',
       'MN15-L', 'PBE', 'PBE0', 'SCAN', 'SCAN0', 'SPW92', 'Slater',
       'TPSS', 'mBEEF', 'mPW91', 'revM06-L', 'wB97M-V', 'wB97X-D',
       'wB97X-V'], dtype='<U9')

In [469]:
wft_table.loc['BeH2']

method           hf                           MP2                      \
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
QZ         0.901702  0.901702  1.900126  0.900672  0.900672  1.891046
TZ         0.902052  0.902052  1.900504  0.902234  0.902234  1.893160
CBS        0.901702  0.901702  1.900126  0.899787  0.899787  1.889779

method         CCSD                     CCSD\(T\)
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
QZ         0.901476  0.901476  1.888265  0.902072  0.902072  1.887460
TZ         0.903037  0.903037  1.890233  0.903637  0.903637  1.889498
CBS        0.900593  0.900593  1.887106  0.901186  0.901186  1.886248

In [245]:
make_dft_table('std_dev').loc['CH3']

method       Slater                         SPW92                     B97-D3  \
component        XX        YY        ZZ        XX        YY        ZZ     XX
molecule
CH3        1.150866  1.150846  0.895335  1.140646  1.140626  0.879825    0.0

method                   BLYP  ... CAM-B3LYP   wB97X-D                     \
component   YY   ZZ        XX  ...        ZZ        XX        YY       ZZ
molecule                       ...
CH3        0.0  0.0  1.142953  ...       0.0  1.134273  1.134253  0.86577

method    wB97X-V           wB97M-V
component      XX   YY   ZZ      XX   YY   ZZ
molecule
CH3           0.0  0.0  0.0     0.0  0.0  0.0

[1 rows x 81 columns]

In [248]:
len(['BHF2', 'BN', 'C2H4', 'CH3Cl', 'Cl2', 'ClCN', 'CS', 'CSO', 'HBS', 'HCCCl', 'HCHS', 'HCP', 'Li', 'Li2', 'LiCl', 'LiCN', 'NaH', 'NaLi', 'NOCl', 'NP', 'OCl2', 'P2', 'PH2', 'PH3', 'PH3O', 'S2', 'SCl2', 'SiH3', 'SiH3Cl', 'SiH3F', 'SiH4', 'SO2', 'SO-trip', 'OF2', 'SH2']
)

35

In [249]:
save(data)

b"\x1b[0;32mSaving updates to GitHub...\x1b[0m\nOn branch master\nYour branch is up to date with 'origin/master'.\n\nChanges not staged for commit:\n\tmodified:   ../geometries/cbs_limit/make_input.py\n\tdeleted:    ../geometries/inputs/dft/Be_B3LYP5_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B3LYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B97-D3_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B97M-V_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_BLYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_BPBE_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_CAM-B3LYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M06-2X_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M06-L_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M08-HX_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MGGA_MS2_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MN15-L_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MN15_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_PBE0_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_PBE_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SCAN0_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SCAN_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SPW92_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_Slater_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_TPSS_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_mBEEF_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_mPW91_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_revM06-L_aug-pc-4.inp\n\tmodified:   .ipynb_checkpoints/ouput-checkpoint.ipynb\n\tmodified:   mp2/HF.ipynb\n\tmodified:   ouput.ipynb\n\tmodified:   output.json\n\tmodified:   wft_table_2.csv\n\nUntracked files:\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2BH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2BH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2NH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2NH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3O_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH3O_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/FCO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/FCO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/H2CN_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/H2CN_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HCCF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HCCF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HCO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HCO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HNS_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HNS_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2Cl_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2Cl_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2OH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2OH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/O3_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/O3_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/hf/C2H2_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/C2H_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HBO_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HCN_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HF_ccsdT_aug-cc-pc-V5Z.inp\n\t../geometries/cbs_limit/hf/HNC_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/LiBH4_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/NH3O_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/NH3_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/O3_hf_aug-cc-pcV5Z.inp\n\t../geometries/inputs/HF_MP2_aug-cc-pcVDZ.inp\n\t../geometries/inputs/NH3-F2_TDDFT_aug-pc-2.inp\n\t../geometries/inputs/dft/BO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/He_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/He_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/He_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/He_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/N2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/Ne_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/Ne_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/Ne_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/Ne_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/to_delete.txt\n\t../geometries/inputs/rerun.sh\n\tcbs_limit/20-08-03/NH_ccsdT_aug-cc-pcV5Zp.out\n\tdft/20-07-28/second_half/FCO_B97-D3_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_CAM-B3LYP_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_M06-2X_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_M06-L_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_MGGA_MS2_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_MN15-L_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_MN15_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_PBE0_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_PBE_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_SCAN0_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_SCAN_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_SPW92_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_Slater_aug-pc-4p.out\n\tdft/20-07-28/second_half/FCO_revM06-L_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_B3LYP5_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_B3LYP_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_B97-D3_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_B97M-V_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_BLYP_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_BPBE_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_CAM-B3LYP_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_M06-2X_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_M06-L_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_M08-HX_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_MGGA_MS2_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_MN15-L_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_MN15_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_PBE0_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2CN_SCAN0_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2_B97M-V_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2_M08-HX_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2_wB97M-V_aug-pc-4p.out\n\tdft/20-07-28/second_half/H2_wB97X-D_aug-pc-4p.out\n\tdft/20-07-28/second_half/H_B97M-V_aug-pc-4p.out\n\tdft/20-07-28/second_half/H_M08-HX_aug-pc-4p.out\n\tdft/20-07-28/second_half/H_SCAN0_aug-pc-4p.out\n\tdft/20-07-28/second_half/H_wB97M-V_aug-pc-4p.out\n\tdft/20-07-28/second_half/H_wB97X-D_aug-pc-4p.out\n\tdft/20-07-28/second_half/Mg2_Slater_aug-pc-4p.out\n\tdft/20-07-28/second_half/Mg2_revM06-L_aug-pc-4p.out\n\tdft/20-07-28/second_half/Mg2_wB97M-V_aug-pc-4p.out\n\tdft/20-07-28/second_half/Mg2_wB97X-D_aug-pc-4p.out\n\tdft/20-07-28/second_half/Mg_B97-D3_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H2_wB97X-D_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_B97-D3_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_B97M-V_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_M08-HX_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_MGGA_MS2_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_PBE0_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_SCAN_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_SPW92_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_Slater_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_TPSS_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_mBEEF_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_mPW91_aug-pc-4p.out\n\tdft/20-07-28/second_half/N2H4_revM06-L_aug-pc-4p.out\n\tdft/20-07-28/second_half/N

In [254]:
data['NH']

[{'name': 'NH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVDZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.450983231570466,
   -5.719957432479677,
   0.798411985892379],
  'quadrupoles_mp2': [-6.443585546400087,
   -5.659430917384136,
   0.8269939513820369],
  'quadrupoles_ccsd': [-6.435649847765377,
   -5.693460269206112,
   0.8047336441340982],
  'quadrupoles_hf': [-6.2876, -6.2876, -5.5205],
  'dipoles_ccsdt': [],
  'dipoles_mp2': [],
  'dipoles_ccsd': [],
  'dipoles_hf': [0.0, 0.0, 1.6421, 1.6421],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.373374788851031,
   -6.373374788851031,
   -5.517529865318849],
  'quadrupoles_mp2': [-6.380570719002153,
   -6.380570719002153,
   -5.48289524834353],
  'quadrupoles_ccsd': [-6.355284086035276,
   -6.355284086035276,
   -5.493252007591618],
  'quadrupoles_hf': [-6.2725, -6.2725, -5.4586],
  'dipoles_ccsdt': [0, 0, 1.5363, 1.5363],
  'dipoles_mp2': [0, 0, 1.5768, 1.5768],
  'dipoles_ccsd': [0, 0, 1.5499, 1.5499],
  'dipoles_hf': [0.0, -0.0, 1.6326, 1.6326],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, -0.0, -1.31582391822, 1.31582391822],
  'dipoles_elec_mp2': [0.0, 0.0, -1.3377773289600001, 1.3377773289600001],
  'dipoles_elec_ccsd': [0.0, 0.0, -1.3483606040299998, 1.3483606040299998],
  'dipoles_elec_ccsdt': [0.0, 0.0, -1.35371125611, 1.35371125611],
  'quadrupoles_elec_hf': [-4.6634594825, -4.6634594825, -7.89264835656476],
  'quadrupoles_elec_mp2': [-4.743807576451564,
   -4.743807576451564,
   -7.910711314917463],
  'quadrupoles_elec_ccsd': [-4.7250075464332495,
   -4.7250075464332495,
   -7.9184113272129535],
  'quadrupoles_elec_ccsdt': [-4.738457567890598,
   -4.738457567890598,
   -7.936461356042423],
  'std_dev_hf': [0.7635001213572268, 0.7635001213572268, 0.9795550191027289],
  'std_dev_mp2': [0.7700493146912382, 0.7700493146912382, 0.980242654409008],
  'std_dev_ccsd': [0.7685219211604547, 0.7685219211604547, 0.9805069981520043],
  'std_dev_ccsdt': [0.7696149660618125,
   0.7696149660618125,
   0.9815418091851436]},
 {'name': 'NH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.393550293930663,
   -6.393550293930663,
   -5.55364401930913],
  'quadrupoles_mp2': [-6.398325163468406,
   -6.398325163468406,
   -5.516790096787475],
  'quadrupoles_ccsd': [-6.375526842708352,
   -6.375526842708352,
   -5.5286263930505255],
  'quadrupoles_hf': [-6.2787, -6.2787, -5.464],
  'dipoles_ccsdt': [0, 0, 1.5276, 1.5276],
  'dipoles_mp2': [0, 0, 1.57, 1.57],
  'dipoles_ccsd': [0, 0, 1.5411, 1.5411],
  'dipoles_hf': [0.0, -0.0, 1.634, 1.634],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, -0.0, -1.3152731158000002, 1.3152731158000002],
  'dipoles_elec_mp2': [0.0, 0.0, -1.340452655, 1.340452655],
  'dipoles_elec_ccsd': [0.0, 0.0, -1.35182279067, 1.35182279067],
  'dipoles_elec_ccsdt': [0.0, 0.0, -1.35713409972, 1.35713409972],
  'quadrupoles_elec_hf': [-4.6680690399, -4.6680690399, -7.89666313236476],
  'quadrupoles_elec_mp2': [-4.75700759756, -4.75700759756, -7.935911355154022],
  'quadrupoles_elec_ccsd': [-4.740057570436278,
   -4.740057570436278,
   -7.944711369190786],
  'quadrupoles_elec_ccsdt': [-4.753457591880688,
   -4.753457591880688,
   -7.963311398908655],
  'std_dev_hf': [0.7638773658038965, 0.7638773658038965, 0.979822701514251],
  'std_dev_mp2': [0.7711199321084886, 0.7711199321084886, 0.9817910731233093],
  'std_dev_ccsd': [0.7697448904049541, 0.7697448904049541, 0.9821076355228925],
  'std_dev_ccsdt': [0.7708321470885123,
   0.7708321470885123,
   0.9831762798661033]},
 {'name': 'NH',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.5052, -6.5052, -5.6728],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, 1.4819, 1.4819],
  'quadrupoles_elec': [-4.836466580400001,
   -4.836466580400001,
   -8.05190112996476],
  'dipoles_elec': [0.0, 0.0, -1.3751138644299998, 1.3751138644299998],
  'std_dev': [0.7775334864492977, 0.7775334864492977, 0.9884036284867577],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'mBEEF',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.3293, -6.3293, -5.5613],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 1.4847, 1.4847],
  'quadrupoles_elec': [-4.7056889761, -4.7056889761, -7.969003444464761],
  'dipoles_elec': [-0.0, 0.0, -1.37401225959, 1.37401225959],
  'std_dev': [0.7669492304008786, 0.7669492304008786, 0.9831718271287075],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'PBE0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.403, -6.403, -5.5468],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 1.5315, 1.5315],
  'quadrupoles_elec': [-4.760483231, -4.760483231, -7.9582230279647606],
  'dipoles_elec': [-0.0, -0.0, -1.35559972155, 1.35559972155],
  'std_dev': [0.7714015840500977, 0.7714015840500977, 0.9828858467754188],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'SCAN',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.3618, -6.3618, -5.5565],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.5264, 1.5264],
  'quadrupoles_elec': [-4.7298519786, -4.7298519786, -7.96543475486476],
  'dipoles_elec': [0.0, -0.0, -1.35760621608, 1.35760621608],
  'std_dev': [0.7689157933902776, 0.7689157933902776, 0.9833010681578137],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'SCAN0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-6.3235, -6.3235, -5.4918],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 1.5584, 1.5584],
  'quadrupoles_elec': [-4.7013768095, -4.7013768095, -7.91733179296476],
  'dipoles_elec': [-0.0, 0.0, -1.3450164464799998, 1.3450164464799998],
  'std_dev': [0.766597744053229, 0.766597744053229, 0.9805099526395723],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-6.7239, -6.7239, -5.9331],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 1.5179, 1.5179],
  'quadrupoles_elec': [-4.999065000300001,
   -4.999065000300001,
   -8.245428193064761],
  'dipoles_elec': [-0.0, -0.0, -1.36095037363, 1.36095037363],
  'std_dev': [0.7904954933695069, 0.7904954933695069, 1.000868682266142],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'SPW92',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-6.5579, -6.5579, -5.6807],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 1.5305, 1.5305],
  'quadrupoles_elec': [-4.8756478183, -4.8756478183, -8.05777459826476],
  'dipoles_elec': [-0.0, -0.0, -1.35599315185, 1.35599315185],
  'std_dev': [0.7806766150510082, 0.7806766150510082, 0.9891874771612905],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.42, -6.42, -5.5955],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.5074, 1.5074],
  'quadrupoles_elec': [-4.7731223400000005,
   -4.7731223400000005,
   -7.99443035786476],
  'dipoles_elec': [0.0, -0.0, -1.36508139178, 1.36508139178],
  'std_dev': [0.7724249429556247, 0.7724249429556247, 0.9849809298339078],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.4464, -6.4464, -5.6151],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, 0.0, 1.5221, 1.5221],
  'quadrupoles_elec': [-4.7927501328, -4.7927501328, -8.00900250706476],
  'dipoles_elec': [-0.0, 0.0, -1.35929796637, 1.35929796637],
  'std_dev': [0.7740114770466908, 0.7740114770466908, 0.9860299904726884],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'B3LYP5',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.4498, -6.4498, -5.6208],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.5219, 1.5219],
  'quadrupoles_elec': [-4.7952779546, -4.7952779546, -8.01324032596476],
  'dipoles_elec': [0.0, -0.0, -1.35937665243, 1.35937665243],
  'std_dev': [0.7742155670903292, 0.7742155670903292, 0.9862968756647442],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.3784, -6.3784, -5.6159],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 1.4879, 1.4879],
  'quadrupoles_elec': [-4.7421936968, -4.7421936968, -8.00959728866476],
  'dipoles_elec': [-0.0, -0.0, -1.37275328263, 1.37275328263],
  'std_dev': [0.7699183152127244, 0.7699183152127244, 0.9857763971733987],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'B97M-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.4071, -6.4071, -5.6454],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 1.4728, 1.4728],
  'quadrupoles_elec': [-4.7635314867, -4.7635314867, -8.03152986016476],
  'dipoles_elec': [-0.0, -0.0, -1.3786940801599998, 1.3786940801599998],
  'std_dev': [0.771648518327807, 0.771648518327807, 0.9870366121205454],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.5316, -6.5316, -5.7313],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.4771, 1.4771],
  'quadrupoles_elec': [-4.8560943732, -4.8560943732, -8.09539453446476],
  'dipoles_elec': [0.0, -0.0, -1.3770023298699998, 1.3770023298699998],
  'std_dev': [0.7791096178651629, 0.7791096178651629, 0.9911090761998861],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'BPBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.4486, -6.4486, -5.6243],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 1.4796, 1.4796],
  'quadrupoles_elec': [-4.7943857822, -4.7943857822, -8.01584249546476],
  'dipoles_elec': [-0.0, -0.0, -1.37601875412, 1.37601875412],
  'std_dev': [0.7741435414540381, 0.7741435414540381, 0.9861011639281435],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.4663, -6.4663, -5.5984],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 1.5624, 1.5624],
  'quadrupoles_elec': [-4.8075453251, -4.8075453251, -7.9965864411647605],
  'dipoles_elec': [-0.0, -0.0, -1.34344272528, 1.34344272528],
  'std_dev': [0.775205240976543, 0.775205240976543, 0.9855824196034604],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.4236, -6.4236, -5.5407],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, 0.0, 1.5478, 1.5478],
  'quadrupoles_elec': [-4.775798857200001,
   -4.775798857200001,
   -7.95368781826476],
  'dipoles_elec': [-0.0, 0.0, -1.34918680766, 1.34918680766],
  'std_dev': [0.7726414803451858, 0.7726414803451858, 0.9827353209295018],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.2415, -6.2415, -5.4661],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.0, 1.5002, 1.5002],
  'quadrupoles_elec': [-4.6404116955, -4.6404116955, -7.89822443406476],
  'dipoles_elec': [0.0, 0.0, -1.36791408994, 1.36791408994],
  'std_dev': [0.7616110962541841, 0.7616110962541841, 0.9787955490284164],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'M08-HX',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-6.462, -6.462, -5.5439],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, 1.5711, 1.5711],
  'quadrupoles_elec': [-4.804348374, -4.804348374, -7.9560669446647605],
  'dipoles_elec': [0.0, -0.0, -1.34001988167, 1.34001988167],
  'std_dev': [0.7749474477343609, 0.7749474477343609, 0.9830825425832703],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.3704, -6.3704, -5.5664],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 1.4832, 1.4832],
  'quadrupoles_elec': [-4.7362458808, -4.7362458808, -7.97279517716476],
  'dipoles_elec': [-0.0, -0.0, -1.37460240504, 1.37460240504],
  'std_dev': [0.7694353352296734, 0.7694353352296734, 0.983399950787575],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-6.4544, -6.4544, -5.5508],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.0, 1.5501, 1.5501],
  'quadrupoles_elec': [-4.7986979488, -4.7986979488, -7.96119693596476],
  'dipoles_elec': [0.0, 0.0, -1.34828191797, 1.34828191797],
  'std_dev': [0.7744916033114885, 0.7744916033114885, 0.9832321648315158],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.4878, -6.4878, -5.7468],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 1.4809, 1.4809],
  'quadrupoles_elec': [-4.8235300806, -4.8235300806, -8.10691842796476],
  'dipoles_elec': [0.0, 0.0, -1.3755072947299998, 1.3755072947299998],
  'std_dev': [0.7764929233901621, 0.7764929233901621, 0.9918679277147254],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'mPW91',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.4757, -6.4757, -5.6485],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 1.4827, 1.4827],
  'quadrupoles_elec': [-4.8145340089, -4.8145340089, -8.03383463886476],
  'dipoles_elec': [-0.0, 0.0, -1.37479912019, 1.37479912019],
  'std_dev': [0.77576849066748, 0.77576849066748, 0.9872674131950878],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.2817, -6.2817, -5.5341],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.5584, 1.5584],
  'quadrupoles_elec': [-4.6702994709, -4.6702994709, -7.94878087006476],
  'dipoles_elec': [0.0, -0.0, -1.3450164464799998, 1.3450164464799998],
  'std_dev': [0.7640598365720449, 0.7640598365720449, 0.9825125453971344],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'wB97M-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 7,
  'quadrupoles': [-6.5128, -6.5128, -5.6196],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 1.5412, 1.5412],
  'quadrupoles_elec': [-4.8421170056000005,
   -4.8421170056000005,
   -8.01234815356476],
  'dipoles_elec': [-0.0, 0.0, -1.35178344764, 1.35178344764],
  'std_dev': [0.7779875485507465, 0.7779875485507465, 0.9864034001361065],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'wB97X-D',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.3652, -6.3652, -5.4979],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, 1.5552, 1.5552],
  'quadrupoles_elec': [-4.7323798004, -4.7323798004, -7.92186700266476],
  'dipoles_elec': [-0.0, -0.0, -1.3462754234399998, 1.3462754234399998],
  'std_dev': [0.769121235599434, 0.769121235599434, 0.9807720054372309],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.4544, -6.4544, -5.5735],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, 0.0, 1.5456, 1.5456],
  'quadrupoles_elec': [-4.7986979488, -4.7986979488, -7.97807386386476],
  'dipoles_elec': [-0.0, 0.0, -1.3500523543199998, 1.3500523543199998],
  'std_dev': [0.7744916033114885, 0.7744916033114885, 0.984266458710441],
  'spin_polarized': 1},
 {'name': 'NH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcV5Zp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.365237335149278,
   -6.365237335149278,
   -5.50656784086963],
  'quadrupoles_mp2': [-6.372836775386701,
   -6.372836775386701,
   -5.470655441898607],
  'quadrupoles_ccsd': [-6.347012128955494,
   -6.347012128955494,
   -5.482626241539687],
  'quadrupoles_hf': [-6.269, -6.269, -5.4578],
  'dipoles_ccsdt': [0, 0, 1.5398, 1.5398],
  'dipoles_mp2': [0, 0, 1.5805, 1.5805],
  'dipoles_ccsd': [0, 0, 1.5534, 1.5534],
  'dipoles_hf': [0.0, -0.0, 1.6329, 1.6329],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, -0.0, -1.31570588913, 1.31570588913],
  'dipoles_elec_mp2': [0.0, 0.0, -1.33632163685, 1.33632163685],
  'dipoles_elec_ccsd': [0.0, 0.0, -1.34698359798, 1.34698359798],
  'dipoles_elec_ccsdt': [0.0, 0.0, -1.35233425006, 1.35233425006],
  'quadrupoles_elec_hf': [-4.660857313, -4.660857313, -7.89205357496476],
  'quadrupoles_elec_mp2': [-4.738057567254178,
   -4.738057567254178,
   -7.901611300341211],
  'quadrupoles_elec_ccsd': [-4.718857536599444,
   -4.718857536599444,
   -7.910511314545962],
  'quadrupoles_elec_ccsdt': [-4.7324075582247795,
   -4.7324075582247795,
   -7.92831134299099],
  'std_dev_hf': [0.7632870784475524, 0.7632870784475524, 0.979519545914497],
  'std_dev_mp2': [0.7695824815487761, 0.7695824815487761, 0.9796933104741267],
  'std_dev_ccsd': [0.7680216091197763, 0.7680216091197763, 0.9800328893009516],
  'std_dev_ccsdt': [0.7691234912405793,
   0.7691234912405793,
   0.9810523910898772]}]

In [261]:
data['C2H']

[{'name': 'C2H',
  'method': 'B97M-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.9108, -12.9108, -9.0109],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.762, 0.762],
  'quadrupoles_elec': [-9.5988828516, -9.5988828516, -42.31875209981425],
  'dipoles_elec': [-0.0, 0.0, 12.115330713599999, 12.115330713599999],
  'std_dev': [0.8592878469809933, 0.8592878469809933, 1.5449144266868384],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'M08-HX',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-12.9854, -12.9854, -8.9589],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.7373, 0.7373],
  'quadrupoles_elec': [-9.6543462358, -9.6543462358, -42.28009129581425],
  'dipoles_elec': [-0.0, -0.0, 12.10561298519, 12.10561298519],
  'std_dev': [0.8617668003227216, 0.8617668003227216, 1.5444026077365125],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'mBEEF',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.722, -12.722, -8.8877],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.7509, 0.7509],
  'quadrupoles_elec': [-9.458514394, -9.458514394, -42.22715573341425],
  'dipoles_elec': [-0.0, -0.0, 12.110963637269998, 12.110963637269998],
  'std_dev': [0.8529818464115706, 0.8529818464115706, 1.5428352911340513],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'mPW91',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.8451, -12.8451, -9.1125],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.7564, 0.7564],
  'quadrupoles_elec': [-9.5500364127, -9.5500364127, -42.39428936301425],
  'dipoles_elec': [-0.0, 0.0, 12.11312750392, 12.11312750392],
  'std_dev': [0.857098702362982, 0.857098702362982, 1.5468959256175199],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.89, -12.89, -9.1526],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.7625, 0.7625],
  'quadrupoles_elec': [-9.583418530000001,
   -9.583418530000001,
   -42.42410279071425],
  'dipoles_elec': [-0.0, 0.0, 12.11552742875, 12.11552742875],
  'std_dev': [0.858595388276242, 0.858595388276242, 1.5475258577768956],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'PBE0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-12.8732, -12.8732, -8.9147],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.7525, 0.7525],
  'quadrupoles_elec': [-9.570928116400001,
   -9.570928116400001,
   -42.24722961241425],
  'dipoles_elec': [-0.0, -0.0, 12.111593125749998, 12.111593125749998],
  'std_dev': [0.8580356867421524, 0.8580356867421524, 1.5433064038996205],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'SCAN',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.8161, -12.8161, -8.8891],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.0, 0.7496, 0.7496],
  'quadrupoles_elec': [-9.5284755797, -9.5284755797, -42.22819660121425],
  'dipoles_elec': [0.0, 0.0, 12.11045217788, 12.11045217788],
  'std_dev': [0.8561306325420923, 0.8561306325420923, 1.5428849943202572],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'SCAN0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-12.8492, -12.8492, -8.7912],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, 0.7433, 0.7433],
  'quadrupoles_elec': [-9.5530846684, -9.5530846684, -42.15541020291425],
  'dipoles_elec': [0.0, 0.0, 12.10797356699, 12.10797356699],
  'std_dev': [0.8572354792004354, 0.8572354792004354, 1.5411847220783728],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'SPW92',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-12.9556, -12.9556, -9.1745],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.7795, 0.7795],
  'quadrupoles_elec': [-9.632190621200001,
   -9.632190621200001,
   -42.44038493701425],
  'dipoles_elec': [-0.0, 0.0, 12.12221574385, 12.12221574385],
  'std_dev': [0.8607774044968349, 0.8607774044968349, 1.547620600955358],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.8267, -12.8267, -9.0617],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.7762, 0.7762],
  'quadrupoles_elec': [-9.536356435900002,
   -9.536356435900002,
   -42.35652073141425],
  'dipoles_elec': [-0.0, -0.0, 12.120917423859998, 12.120917423859998],
  'std_dev': [0.8564846056320076, 0.8564846056320076, 1.5455952498647412],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'wB97M-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 7,
  'quadrupoles': [-13.0659, -13.0659, -9.1022],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.771, 0.771],
  'quadrupoles_elec': [-9.7141961343, -9.7141961343, -42.38663154991425],
  'dipoles_elec': [-0.0, -0.0, 12.1188715863, 12.1188715863],
  'std_dev': [0.8644338358050403, 0.8644338358050403, 1.5464392419794764],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'wB97X-D',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-12.8571, -12.8571, -8.8602],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.7638, 0.7638],
  'quadrupoles_elec': [-9.558958136700001,
   -9.558958136700001,
   -42.20671011591425],
  'dipoles_elec': [-0.0, 0.0, 12.116038888139999, 12.116038888139999],
  'std_dev': [0.8574989632960767, 0.8574989632960767, 1.5420896319431423],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-12.9553, -12.9553, -8.9946],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.7819, 0.7819],
  'quadrupoles_elec': [-9.6319675781, -9.6319675781, -42.30663342471425],
  'dipoles_elec': [-0.0, 0.0, 12.12315997657, 12.12315997657],
  'std_dev': [0.8607674383541523, 0.8607674383541523, 1.5442491649517895],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.8255, -12.8255, -9.138],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, 0.8036, 0.8036],
  'quadrupoles_elec': [-9.5354642635, -9.5354642635, -42.41324802651425],
  'dipoles_elec': [0.0, 0.0, 12.13169741408, 12.13169741408],
  'std_dev': [0.8564445405503275, 0.8564445405503275, 1.5465061638352477],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-12.9782, -12.9782, -9.0487],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.7629, 0.7629],
  'quadrupoles_elec': [-9.6489932014, -9.6489932014, -42.34685553041425],
  'dipoles_elec': [-0.0, 0.0, 12.11568480087, 12.11568480087],
  'std_dev': [0.8615278557664507, 0.8615278557664507, 1.5455974959654384],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-12.9496, -12.9496, -8.9473],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.7449, 0.7449],
  'quadrupoles_elec': [-9.627729759200001,
   -9.627729759200001,
   -42.27146696261425],
  'dipoles_elec': [-0.0, 0.0, 12.108603055469999, 12.108603055469999],
  'std_dev': [0.8605780597142473, 0.8605780597142473, 1.5440490889563039],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.5643, -12.5643, -8.9161],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.7825, 0.7825],
  'quadrupoles_elec': [-9.3412680711, -9.3412680711, -42.24827048021425],
  'dipoles_elec': [-0.0, -0.0, 12.123396034749998, 12.123396034749998],
  'std_dev': [0.8476786433503605, 0.8476786433503605, 1.5427838989119547],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.7758, -12.7758, -8.9708],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.7921, 0.7921],
  'quadrupoles_elec': [-9.498513456600001,
   -9.498513456600001,
   -42.28893867211425],
  'dipoles_elec': [-0.0, -0.0, 12.127172965629999, 12.127172965629999],
  'std_dev': [0.8547835288989389, 0.8547835288989389, 1.5436218812977396],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-12.9154, -12.9154, -9.0327],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.7079, 0.7079],
  'quadrupoles_elec': [-9.6023028458, -9.6023028458, -42.33495989841425],
  'dipoles_elec': [-0.0, 0.0, 12.094046134369998, 12.094046134369998],
  'std_dev': [0.8594409115501507, 0.8594409115501507, 1.5463041005811422],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-13.1932, -13.1932, -9.0568],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.6701, 0.6701],
  'quadrupoles_elec': [-9.8088407564, -9.8088407564, -42.35287769411425],
  'dipoles_elec': [-0.0, 0.0, 12.079174469029999, 12.079174469029999],
  'std_dev': [0.8686346827238534, 0.8686346827238534, 1.5474371906463213],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.7089, -12.7089, -8.8289],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.71, 0.71],
  'quadrupoles_elec': [-9.448774845300001,
   -9.448774845300001,
   -42.18343928581425],
  'dipoles_elec': [-0.0, 0.0, 12.094872337999998, 12.094872337999998],
  'std_dev': [0.8525425703469864, 0.8525425703469864, 1.5424923615570807],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-13.3165, -13.3165, -9.4623],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.7075, 0.7075],
  'quadrupoles_elec': [-9.9005114705, -9.9005114705, -42.65435761761425],
  'dipoles_elec': [0.0, 0.0, 12.093888762249998, 12.093888762249998],
  'std_dev': [0.8726842529936454, 0.8726842529936454, 1.5542354874679654],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-12.806132814275498,
   -12.806132814275498,
   -9.000158292834126],
  'quadrupoles_mp2': [-13.247505612721524,
   -13.247505612721524,
   -8.41493414338918],
  'quadrupoles_ccsd': [-12.798869632339791,
   -12.798869632339791,
   -8.943397871893326],
  'quadrupoles_hf': [-12.9523, -12.9523, -8.9741],
  'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
  'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
  'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
  'dipoles_hf': [-0.0, -0.0, 0.7191, 0.7191],
  'spin_polarized': 1,
  'dipoles_elec_hf': [-0.0, -0.0, 12.098452553729999, 12.098452553729999],
  'dipoles_elec_mp2': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'dipoles_elec_ccsd': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'dipoles_elec_ccsdt': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'quadrupoles_elec_hf': [-9.6297371471, -9.6297371471, -42.29139214621425],
  'quadrupoles_elec_mp2': [-9.84921573042936,
   -9.84921573042936,
   -41.875665192638806],
  'quadrupoles_elec_ccsd': [-9.515665197643091,
   -9.515665197643091,
   -42.26856582011588],
  'quadrupoles_elec_ccsdt': [-9.521065206359106,
   -9.521065206359106,
   -42.310765887595686],
  'std_dev_hf': [0.8606677705801378, 0.8606677705801378, 1.5450159297275894],
  'std_dev_mp2': [0.8704205760802056, 0.8704205760802056, 1.5476203092317535],
  'std_dev_ccsd': [0.8555549345147543, 0.8555549345147543, 1.557354085215412],
  'std_dev_ccsdt': [0.8557976578948979,
   0.8557976578948979,
   1.558395939988949]},
 {'name': 'C2H',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-12.858589127406086,
   -12.858589127406086,
   -9.0528163608884],
  'quadrupoles_mp2': [-13.286780595856555,
   -13.286780595856555,
   -8.475527910173735],
  'quadrupoles_ccsd': [-12.847021837755737,
   -12.847021837755737,
   -8.995921436665142],
  'quadrupoles_hf': [-12.9673, -12.9673, -8.9709],
  'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
  'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
  'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
  'dipoles_hf': [-0.0, 0.0, 0.7205, 0.7205],
  'spin_polarized': 1,
  'dipoles_elec_hf': [-0.0, 0.0, 12.099003356149998, 12.099003356149998],
  'dipoles_elec_mp2': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'dipoles_elec_ccsd': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'dipoles_elec_ccsdt': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'quadrupoles_elec_hf': [-9.6408893021, -9.6408893021, -42.28901301981425],
  'quadrupoles_elec_mp2': [-9.878415777065644,
   -9.878415777065644,
   -41.92071526458649],
  'quadrupoles_elec_ccsd': [-9.551465254869122,
   -9.551465254869122,
   -42.30761588248174],
  'quadrupoles_elec_ccsdt': [-9.560065268676496,
   -9.560065268676496,
   -42.349915950058474],
  'std_dev_hf': [0.8611659940988774, 0.8611659940988774, 1.544931179496808],
  'std_dev_mp2': [0.8717098925086013, 0.8717098925086013, 1.5487394912303394],
  'std_dev_ccsd': [0.8571628179805713, 0.8571628179805713, 1.5583181952631986],
  'std_dev_ccsdt': [0.8575486202263042,
   0.8575486202263042,
   1.5593618723825489]},
 {'name': 'C2H',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcV5Zp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [0, 0, 0],
  'quadrupoles_mp2': [0, 0, 0],
  'quadrupoles_ccsd': [0, 0, 0],
  'quadrupoles_hf': [-12.9472, -12.9472, -8.9732],
  'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
  'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
  'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
  'dipoles_hf': [-0.0, 0.0, 0.7188, 0.7188],
  'spin_polarized': 1,
  'dipoles_elec_hf': [-0.0, 0.0, 12.099003356149998, 12.099003356149998],
  'dipoles_elec_mp2': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'dipoles_elec_ccsd': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'dipoles_elec_ccsdt': [0.0, 0.0, 11.815536824999999, 11.815536824999999],
  'quadrupoles_elec_hf': [-9.6408893021, -9.6408893021, -42.28901301981425],
  'quadrupoles_elec_mp2': [-9.878415777065644,
   -9.878415777065644,
   -41.92071526458649],
  'quadrupoles_elec_ccsd': [-9.551465254869122,
   -9.551465254869122,
   -42.30761588248174],
  'quadrupoles_elec_ccsdt': [-9.560065268676496,
   -9.560065268676496,
   -42.349915950058474],
  'std_dev_hf': [0.8611659940988774, 0.8611659940988774, 1.544931179496808],
  'std_dev_mp2': [0.8717098925086013, 0.8717098925086013, 1.5487394912303394],
  'std_dev_ccsd': [0.8571628179805713, 0.8571628179805713, 1.5583181952631986],
  'std_dev_ccsdt': [0.8575486202263042,
   0.8575486202263042,
   1.5593618723825489]}]

In [264]:
forbidden_species =  ['CH2F', 'CH2NH', 'CH3BH2', 'CH3O', 'FCO', 'HCO', 'HNO', 'HNS', 'HO2', 'N2H2','N2H4', 'NH2Cl', 'NH2F', 'NH2OH', 'S2H2', 'FH-OH', 'CH3OH', 'HCOOH', 'C2H3', 'CH3NH2', 'CH3SH', 'HCONH2', 'HOCl', 'HOF', 'HOOH', 'NaCN', 'P2H4', 'Ph2OH', 'HCHO', 'FNO'] + ['Be', 'OH', 'SH', 'OF', 'SF', 'NCO', 'NO', 'OCl', 'PS', 'SCl']

In [285]:
for f in forbidden_species:
    data.pop(f, None)

In [276]:
#Check for uncompleted calculations:
get_functionals()

array(['B3LYP', 'B97-D3', 'B97M-V', 'BLYP', 'BPBE', 'CAM-B3LYP', 'M06-2X',
       'M06-L', 'M08-HX', 'MGGA_MS2', 'MN15', 'MN15-L', 'PBE', 'PBE0',
       'SCAN', 'SCAN0', 'SPW92', 'Slater', 'TPSS', 'mBEEF', 'mPW91',
       'revM06-L', 'wB97M-V', 'wB97X-D', 'wB97X-V'], dtype='<U9')

In [29]:
missing = []
for m in get_dft_species():
    for f in get_functionals():
        temp = retrieve(m, f, 'aug-pc-4p')
        if temp == {}:
            missing.append((m, f))

In [30]:
missing

[('AlF', 'B97-2'),
 ('AlF', 'HFLYP'),
 ('AlF', 'M06'),
 ('AlF', 'N12'),
 ('AlF', 'SOGGA11'),
 ('AlF', 'TPSSh'),
 ('AlF', 'wB97X-D'),
 ('AlF', 'wM05-D'),
 ('Ar', 'B97-2'),
 ('Ar', 'HFLYP'),
 ('Ar', 'M06'),
 ('Ar', 'N12'),
 ('Ar', 'SOGGA11'),
 ('Ar', 'TPSSh'),
 ('Ar', 'wM05-D'),
 ('BeH', 'B97-2'),
 ('BeH', 'HFLYP'),
 ('BeH', 'M06'),
 ('BeH', 'N12'),
 ('BeH', 'SOGGA11'),
 ('BeH', 'TPSSh'),
 ('BeH', 'wM05-D'),
 ('BeH2', 'B97-2'),
 ('BeH2', 'HFLYP'),
 ('BeH2', 'M06'),
 ('BeH2', 'N12'),
 ('BeH2', 'SOGGA11'),
 ('BeH2', 'TPSSh'),
 ('BeH2', 'wM05-D'),
 ('BF', 'B97-2'),
 ('BF', 'HFLYP'),
 ('BF', 'M06'),
 ('BF', 'N12'),
 ('BF', 'SOGGA11'),
 ('BF', 'TPSSh'),
 ('BF', 'wM05-D'),
 ('BH2', 'B97-2'),
 ('BH2', 'B97M-V'),
 ('BH2', 'HFLYP'),
 ('BH2', 'M06'),
 ('BH2', 'N12'),
 ('BH2', 'SOGGA11'),
 ('BH2', 'TPSSh'),
 ('BH2', 'wM05-D'),
 ('BH2F', 'B97-2'),
 ('BH2F', 'HFLYP'),
 ('BH2F', 'M06'),
 ('BH2F', 'N12'),
 ('BH2F', 'SOGGA11'),
 ('BH2F', 'TPSSh'),
 ('BH2F', 'wB97M-V'),
 ('BH2F', 'wB97X-V'),
 ('BH2F', 'wM05-D'),
 ('BH3', 'B97-2'),
 ('BH3', 'HFLYP'),
 ('BH3', 'M06'),
 ('BH3', 'N12'),
 ('BH3', 'SOGGA11'),
 ('BH3', 'TPSSh'),
 ('BH3', 'wB97X-V'),
 ('BH3', 'wM05-D'),
 ('BO', 'B97-2'),
 ('BO', 'HFLYP'),
 ('BO', 'M06'),
 ('BO', 'N12'),
 ('BO', 'SOGGA11'),
 ('BO', 'TPSSh'),
 ('BO', 'wM05-D'),
 ('BS', 'B97-2'),
 ('BS', 'HFLYP'),
 ('BS', 'M06'),
 ('BS', 'N12'),
 ('BS', 'SOGGA11'),
 ('BS', 'TPSSh'),
 ('BS', 'wM05-D'),
 ('C2H', 'B97-2'),
 ('C2H', 'HFLYP'),
 ('C2H', 'M06'),
 ('C2H', 'N12'),
 ('C2H', 'SOGGA11'),
 ('C2H', 'TPSSh'),
 ('C2H', 'wM05-D'),
 ('C2H2', 'B97-2'),
 ('C2H2', 'HFLYP'),
 ('C2H2', 'M06'),
 ('C2H2', 'M08-HX'),
 ('C2H2', 'N12'),
 ('C2H2', 'SOGGA11'),
 ('C2H2', 'TPSSh'),
 ('C2H2', 'wM05-D'),
 ('CH2BH', 'B97-2'),
 ('CH2BH', 'HFLYP'),
 ('CH2BH', 'M06'),
 ('CH2BH', 'M08-HX'),
 ('CH2BH', 'N12'),
 ('CH2BH', 'SOGGA11'),
 ('CH2BH', 'TPSSh'),
 ('CH2BH', 'wM05-D'),
 ('CH2-t', 'B97-2'),
 ('CH2-t', 'HFLYP'),
 ('CH2-t', 'M06'),
 ('CH2-t', 'N12'),
 ('CH2-t', 'SOGGA11'),
 ('CH2-t', 'TPSSh'),
 ('CH2-t', 'wB97X-V'),
 ('CH2-t', 'wM05-D'),
 ('CH3', 'B97-2'),
 ('CH3', 'B97M-V'),
 ('CH3', 'HFLYP'),
 ('CH3', 'M06'),
 ('CH3', 'N12'),
 ('CH3', 'SOGGA11'),
 ('CH3', 'TPSSh'),
 ('CH3', 'wB97M-V'),
 ('CH3', 'wM05-D'),
 ('CH4', 'B97-2'),
 ('CH4', 'HFLYP'),
 ('CH4', 'M06'),
 ('CH4', 'N12'),
 ('CH4', 'SOGGA11'),
 ('CH4', 'TPSSh'),
 ('CH4', 'wM05-D'),
 ('ClF', 'B97-2'),
 ('ClF', 'HFLYP'),
 ('ClF', 'M06'),
 ('ClF', 'N12'),
 ('ClF', 'SOGGA11'),
 ('ClF', 'TPSSh'),
 ('ClF', 'wM05-D'),
 ('CN', 'B97-2'),
 ('CN', 'HFLYP'),
 ('CN', 'M06'),
 ('CN', 'N12'),
 ('CN', 'SOGGA11'),
 ('CN', 'TPSSh'),
 ('CN', 'wM05-D'),
 ('CO', 'B97-2'),
 ('CO', 'HFLYP'),
 ('CO', 'M06'),
 ('CO', 'N12'),
 ('CO', 'SOGGA11'),
 ('CO', 'TPSSh'),
 ('CO', 'wM05-D'),
 ('CO2', 'B97-2'),
 ('CO2', 'HFLYP'),
 ('CO2', 'M06'),
 ('CO2', 'N12'),
 ('CO2', 'SOGGA11'),
 ('CO2', 'TPSSh'),
 ('CO2', 'wM05-D'),
 ('F2', 'B97-2'),
 ('F2', 'HFLYP'),
 ('F2', 'M06'),
 ('F2', 'N12'),
 ('F2', 'SOGGA11'),
 ('F2', 'TPSSh'),
 ('F2', 'wM05-D'),
 ('FCN', 'B97-2'),
 ('FCN', 'HFLYP'),
 ('FCN', 'M06'),
 ('FCN', 'N12'),
 ('FCN', 'SOGGA11'),
 ('FCN', 'TPSSh'),
 ('FCN', 'wM05-D'),
 ('H', 'B97-2'),
 ('H', 'HFLYP'),
 ('H', 'M06'),
 ('H', 'N12'),
 ('H', 'SOGGA11'),
 ('H', 'TPSSh'),
 ('H', 'wM05-D'),
 ('H2', 'B97-2'),
 ('H2', 'HFLYP'),
 ('H2', 'M06'),
 ('H2', 'N12'),
 ('H2', 'SOGGA11'),
 ('H2', 'TPSSh'),
 ('H2', 'mBEEF'),
 ('H2', 'wM05-D'),
 ('H2CN', 'B97-2'),
 ('H2CN', 'HFLYP'),
 ('H2CN', 'M06'),
 ('H2CN', 'N12'),
 ('H2CN', 'SOGGA11'),
 ('H2CN', 'TPSSh'),
 ('H2CN', 'wB97M-V'),
 ('H2CN', 'wM05-D'),
 ('H2O', 'B97-2'),
 ('H2O', 'HFLYP'),
 ('H2O', 'M06'),
 ('H2O', 'N12'),
 ('H2O', 'SOGGA11'),
 ('H2O', 'TPSSh'),
 ('H2O', 'wM05-D'),
 ('HBO', 'B97-2'),
 ('HBO', 'HFLYP'),
 ('HBO', 'M06'),
 ('HBO', 'N12'),
 ('HBO', 'SOGGA11'),
 ('HBO', 'TPSSh'),
 ('HBO', 'wM05-D'),
 ('HCCF', 'B97-2'),
 ('HCCF', 'HFLYP'),
 ('HCCF', 'M06'),
 ('HCCF', 'N12'),
 ('HCCF', 'SOGGA11'),
 ('HCCF', 'TPSSh'),
 ('HCCF', 'wM05-D'),
 ('HCN', 'B97-2'),
 ('HCN', 'HFLYP'),
 ('HCN', 'M06'),
 ('HCN', 'N12'),
 ('HCN', 'SOGGA11'),
 ('HCN', 'TPSSh'),
 ('HCN', 'wM05-D'),
 ('He', 'B97-2'),
 ('He', 'HFLYP'),
 ('He', 'M06'),
 ('He', 'N12'),
 ('He', 'SOGGA11'),
 ('He', 'TPSSh'),
 ('He', 'wM05-D'),
 ('HF', 'B97-2'),
 ('HF', 'HFLYP'),
 ('HF', 'M06'),
 ('HF', 'N12'),
 ('HF', 'SOGGA11'),
 ('HF', 'TPSSh'),
 ('HF', 'wM05-D'),
 ('HNC', 'B97-2'),
 ('HNC', 'HFLYP'),
 ('HNC', 'M06'),
 ('HNC', 'N12'),
 ('HNC', 'SOGGA11'),
 ('HNC', 'TPSSh'),
 ('HNC', 'wM05-D'),
 ('LiBH4', 'B97-2'),
 ('LiBH4', 'HFLYP'),
 ('LiBH4', 'M06'),
 ('LiBH4', 'N12'),
 ('LiBH4', 'SOGGA11'),
 ('LiBH4', 'TPSSh'),
 ('LiBH4', 'wM05-D'),
 ('Mg', 'B97-2'),
 ('Mg', 'HFLYP'),
 ('Mg', 'M06'),
 ('Mg', 'N12'),
 ('Mg', 'SOGGA11'),
 ('Mg', 'TPSSh'),
 ('Mg', 'wM05-D'),
 ('Mg2', 'B97-2'),
 ('Mg2', 'HFLYP'),
 ('Mg2', 'M06'),
 ('Mg2', 'N12'),
 ('Mg2', 'SOGGA11'),
 ('Mg2', 'TPSSh'),
 ('Mg2', 'wM05-D'),
 ('N', 'B97-2'),
 ('N', 'HFLYP'),
 ('N', 'M06'),
 ('N', 'N12'),
 ('N', 'SOGGA11'),
 ('N', 'TPSSh'),
 ('N', 'wM05-D'),
 ('N2', 'B97-2'),
 ('N2', 'HFLYP'),
 ('N2', 'M06'),
 ('N2', 'N12'),
 ('N2', 'SOGGA11'),
 ('N2', 'TPSSh'),
 ('N2', 'wM05-D'),
 ('Na', 'B97-2'),
 ('Na', 'HFLYP'),
 ('Na', 'M06'),
 ('Na', 'M06-2X'),
 ('Na', 'N12'),
 ('Na', 'SOGGA11'),
 ('Na', 'TPSSh'),
 ('Na', 'wM05-D'),
 ('Na2', 'B97-2'),
 ('Na2', 'HFLYP'),
 ('Na2', 'M06'),
 ('Na2', 'N12'),
 ('Na2', 'SOGGA11'),
 ('Na2', 'TPSSh'),
 ('Na2', 'wM05-D'),
 ('NaCl', 'B97-2'),
 ('NaCl', 'HFLYP'),
 ('NaCl', 'M06'),
 ('NaCl', 'N12'),
 ('NaCl', 'SOGGA11'),
 ('NaCl', 'TPSSh'),
 ('NaCl', 'wM05-D'),
 ('Ne', 'B97-2'),
 ('Ne', 'HFLYP'),
 ('Ne', 'M06'),
 ('Ne', 'N12'),
 ('Ne', 'SOGGA11'),
 ('Ne', 'TPSSh'),
 ('Ne', 'wM05-D'),
 ('NH2', 'B97-2'),
 ('NH2', 'HFLYP'),
 ('NH2', 'M06'),
 ('NH2', 'N12'),
 ('NH2', 'SOGGA11'),
 ('NH2', 'TPSSh'),
 ('NH2', 'wM05-D'),
 ('NH3', 'B97-2'),
 ('NH3', 'HFLYP'),
 ('NH3', 'M06'),
 ('NH3', 'N12'),
 ('NH3', 'SOGGA11'),
 ('NH3', 'TPSSh'),
 ('NH3', 'wM05-D'),
 ('NH3O', 'B97-2'),
 ('NH3O', 'HFLYP'),
 ('NH3O', 'M06'),
 ('NH3O', 'N12'),
 ('NH3O', 'SOGGA11'),
 ('NH3O', 'TPSSh'),
 ('NH3O', 'wB97X-V'),
 ('NH3O', 'wM05-D'),
 ('O2', 'B97-2'),
 ('O2', 'HFLYP'),
 ('O2', 'M06'),
 ('O2', 'N12'),
 ('O2', 'SOGGA11'),
 ('O2', 'TPSSh'),
 ('O2', 'wM05-D'),
 ('O3', 'B97-2'),
 ('O3', 'HFLYP'),
 ('O3', 'M06'),
 ('O3', 'N12'),
 ('O3', 'SOGGA11'),
 ('O3', 'TPSSh'),
 ('O3', 'wM05-D'),
 ('P', 'B97-2'),
 ('P', 'HFLYP'),
 ('P', 'M06'),
 ('P', 'N12'),
 ('P', 'SOGGA11'),
 ('P', 'TPSSh'),
 ('P', 'wM05-D'),
 ('HCl', 'B97-2'),
 ('HCl', 'HFLYP'),
 ('HCl', 'M06'),
 ('HCl', 'N12'),
 ('HCl', 'SOGGA11'),
 ('HCl', 'TPSSh'),
 ('HCl', 'wM05-D'),
 ('NH', 'B97-2'),
 ('NH', 'HFLYP'),
 ('NH', 'M06'),
 ('NH', 'N12'),
 ('NH', 'SOGGA11'),
 ('NH', 'TPSSh'),
 ('NH', 'wM05-D'),
 ('PH', 'B97-2'),
 ('PH', 'HFLYP'),
 ('PH', 'M06'),
 ('PH', 'N12'),
 ('PH', 'SOGGA11'),
 ('PH', 'TPSSh'),
 ('PH', 'wM05-D'),
 ('LiH', 'B97-2'),
 ('LiH', 'HFLYP'),
 ('LiH', 'M06'),
 ('LiH', 'N12'),
 ('LiH', 'SOGGA11'),
 ('LiH', 'TPSSh'),
 ('LiH', 'mBEEF'),
 ('LiH', 'wM05-D'),
 ('BHF2', 'B3LYP'),
 ('BHF2', 'B97-D3'),
 ('BHF2', 'B97M-V'),
 ('BHF2', 'BLYP'),
 ('BHF2', 'BPBE'),
 ('BHF2', 'CAM-B3LYP'),
 ('BHF2', 'M06-2X'),
 ('BHF2', 'M06-L'),
 ('BHF2', 'M08-HX'),
 ('BHF2', 'MGGA_MS2'),
 ('BHF2', 'MN15'),
 ('BHF2', 'MN15-L'),
 ('BHF2', 'PBE'),
 ('BHF2', 'PBE0'),
 ('BHF2', 'SCAN'),
 ('BHF2', 'SCAN0'),
 ('BHF2', 'SPW92'),
 ('BHF2', 'Slater'),
 ('BHF2', 'TPSS'),
 ('BHF2', 'mBEEF'),
 ('BHF2', 'mPW91'),
 ('BHF2', 'revM06-L'),
 ('BHF2', 'wB97M-V'),
 ('BHF2', 'wB97X-D'),
 ('BHF2', 'wB97X-V'),
 ('C2H4', 'B3LYP'),
 ('C2H4', 'B97-D3'),
 ('C2H4', 'B97M-V'),
 ('C2H4', 'BLYP'),
 ('C2H4', 'BPBE'),
 ('C2H4', 'CAM-B3LYP'),
 ('C2H4', 'M06-2X'),
 ('C2H4', 'M06-L'),
 ('C2H4', 'M08-HX'),
 ('C2H4', 'MGGA_MS2'),
 ('C2H4', 'MN15'),
 ('C2H4', 'MN15-L'),
 ('C2H4', 'PBE'),
 ('C2H4', 'PBE0'),
 ('C2H4', 'SCAN'),
 ('C2H4', 'SCAN0'),
 ('C2H4', 'SPW92'),
 ('C2H4', 'Slater'),
 ('C2H4', 'TPSS'),
 ('C2H4', 'mBEEF'),
 ('C2H4', 'mPW91'),
 ('C2H4', 'revM06-L'),
 ('C2H4', 'wB97M-V'),
 ('C2H4', 'wB97X-D'),
 ('C2H4', 'wB97X-V'),
 ('CH3Cl', 'B3LYP'),
 ('CH3Cl', 'B97-D3'),
 ('CH3Cl', 'B97M-V'),
 ('CH3Cl', 'BLYP'),
 ('CH3Cl', 'BPBE'),
 ('CH3Cl', 'CAM-B3LYP'),
 ('CH3Cl', 'M06-2X'),
 ('CH3Cl', 'M06-L'),
 ('CH3Cl', 'M08-HX'),
 ('CH3Cl', 'MGGA_MS2'),
 ('CH3Cl', 'MN15'),
 ('CH3Cl', 'MN15-L'),
 ('CH3Cl', 'PBE'),
 ('CH3Cl', 'PBE0'),
 ('CH3Cl', 'SCAN'),
 ('CH3Cl', 'SCAN0'),
 ('CH3Cl', 'SPW92'),
 ('CH3Cl', 'Slater'),
 ('CH3Cl', 'TPSS'),
 ('CH3Cl', 'mBEEF'),
 ('CH3Cl', 'mPW91'),
 ('CH3Cl', 'revM06-L'),
 ('CH3Cl', 'wB97M-V'),
 ('CH3Cl', 'wB97X-D'),
 ('CH3Cl', 'wB97X-V'),
 ('Cl2', 'B3LYP'),
 ('Cl2', 'B97-D3'),
 ('Cl2', 'B97M-V'),
 ('Cl2', 'BLYP'),
 ('Cl2', 'BPBE'),
 ('Cl2', 'CAM-B3LYP'),
 ('Cl2', 'M06-2X'),
 ('Cl2', 'M06-L'),
 ('Cl2', 'M08-HX'),
 ('Cl2', 'MGGA_MS2'),
 ('Cl2', 'MN15'),
 ('Cl2', 'MN15-L'),
 ('Cl2', 'PBE'),
 ('Cl2', 'PBE0'),
 ('Cl2', 'SCAN'),
 ('Cl2', 'SCAN0'),
 ('Cl2', 'SPW92'),
 ('Cl2', 'Slater'),
 ('Cl2', 'TPSS'),
 ('Cl2', 'mBEEF'),
 ('Cl2', 'mPW91'),
 ('Cl2', 'revM06-L'),
 ('Cl2', 'wB97M-V'),
 ('Cl2', 'wB97X-D'),
 ('Cl2', 'wB97X-V'),
 ('ClCN', 'B3LYP'),
 ('ClCN', 'B97-D3'),
 ('ClCN', 'B97M-V'),
 ('ClCN', 'BLYP'),
 ('ClCN', 'BPBE'),
 ('ClCN', 'CAM-B3LYP'),
 ('ClCN', 'M06-2X'),
 ('ClCN', 'M06-L'),
 ('ClCN', 'M08-HX'),
 ('ClCN', 'MGGA_MS2'),
 ('ClCN', 'MN15'),
 ('ClCN', 'MN15-L'),
 ('ClCN', 'PBE'),
 ('ClCN', 'PBE0'),
 ('ClCN', 'SCAN'),
 ('ClCN', 'SCAN0'),
 ('ClCN', 'SPW92'),
 ('ClCN', 'Slater'),
 ('ClCN', 'TPSS'),
 ('ClCN', 'mBEEF'),
 ('ClCN', 'mPW91'),
 ('ClCN', 'revM06-L'),
 ('ClCN', 'wB97M-V'),
 ('ClCN', 'wB97X-D'),
 ('ClCN', 'wB97X-V'),
 ('CS', 'B3LYP'),
 ('CS', 'B97-D3'),
 ('CS', 'B97M-V'),
 ('CS', 'BLYP'),
 ('CS', 'BPBE'),
 ('CS', 'CAM-B3LYP'),
 ('CS', 'M06-2X'),
 ('CS', 'M06-L'),
 ('CS', 'M08-HX'),
 ('CS', 'MGGA_MS2'),
 ('CS', 'MN15'),
 ('CS', 'MN15-L'),
 ('CS', 'PBE'),
 ('CS', 'PBE0'),
 ('CS', 'SCAN'),
 ('CS', 'SCAN0'),
 ('CS', 'SPW92'),
 ('CS', 'Slater'),
 ('CS', 'TPSS'),
 ('CS', 'mBEEF'),
 ('CS', 'mPW91'),
 ('CS', 'revM06-L'),
 ('CS', 'wB97M-V'),
 ('CS', 'wB97X-D'),
 ('CS', 'wB97X-V'),
 ('CSO', 'B3LYP'),
 ('CSO', 'B97-D3'),
 ('CSO', 'B97M-V'),
 ('CSO', 'BLYP'),
 ('CSO', 'BPBE'),
 ('CSO', 'CAM-B3LYP'),
 ('CSO', 'M06-2X'),
 ('CSO', 'M06-L'),
 ('CSO', 'M08-HX'),
 ('CSO', 'MGGA_MS2'),
 ('CSO', 'MN15'),
 ('CSO', 'MN15-L'),
 ('CSO', 'PBE'),
 ('CSO', 'PBE0'),
 ('CSO', 'SCAN'),
 ('CSO', 'SCAN0'),
 ('CSO', 'SPW92'),
 ('CSO', 'Slater'),
 ('CSO', 'TPSS'),
 ('CSO', 'mBEEF'),
 ('CSO', 'mPW91'),
 ('CSO', 'revM06-L'),
 ('CSO', 'wB97M-V'),
 ('CSO', 'wB97X-D'),
 ('CSO', 'wB97X-V'),
 ('HBS', 'B3LYP'),
 ('HBS', 'B97-D3'),
 ('HBS', 'B97M-V'),
 ('HBS', 'BLYP'),
 ('HBS', 'BPBE'),
 ('HBS', 'CAM-B3LYP'),
 ('HBS', 'M06-2X'),
 ('HBS', 'M06-L'),
 ('HBS', 'M08-HX'),
 ('HBS', 'MGGA_MS2'),
 ('HBS', 'MN15'),
 ('HBS', 'MN15-L'),
 ('HBS', 'PBE'),
 ('HBS', 'PBE0'),
 ('HBS', 'SCAN'),
 ('HBS', 'SCAN0'),
 ('HBS', 'SPW92'),
 ('HBS', 'Slater'),
 ('HBS', 'TPSS'),
 ('HBS', 'mBEEF'),
 ('HBS', 'mPW91'),
 ('HBS', 'revM06-L'),
 ('HBS', 'wB97M-V'),
 ('HBS', 'wB97X-D'),
 ('HBS', 'wB97X-V'),
 ('HCCCl', 'B3LYP'),
 ('HCCCl', 'B97-D3'),
 ('HCCCl', 'B97M-V'),
 ('HCCCl', 'BLYP'),
 ('HCCCl', 'BPBE'),
 ('HCCCl', 'CAM-B3LYP'),
 ('HCCCl', 'M06-2X'),
 ('HCCCl', 'M06-L'),
 ('HCCCl', 'M08-HX'),
 ('HCCCl', 'MGGA_MS2'),
 ('HCCCl', 'MN15'),
 ('HCCCl', 'MN15-L'),
 ('HCCCl', 'PBE'),
 ('HCCCl', 'PBE0'),
 ('HCCCl', 'SCAN'),
 ('HCCCl', 'SCAN0'),
 ('HCCCl', 'SPW92'),
 ('HCCCl', 'Slater'),
 ('HCCCl', 'TPSS'),
 ('HCCCl', 'mBEEF'),
 ('HCCCl', 'mPW91'),
 ('HCCCl', 'revM06-L'),
 ('HCCCl', 'wB97M-V'),
 ('HCCCl', 'wB97X-D'),
 ('HCCCl', 'wB97X-V'),
 ('HCHS', 'B3LYP'),
 ('HCHS', 'B97-D3'),
 ('HCHS', 'B97M-V'),
 ('HCHS', 'BLYP'),
 ('HCHS', 'BPBE'),
 ('HCHS', 'CAM-B3LYP'),
 ('HCHS', 'M06-2X'),
 ('HCHS', 'M06-L'),
 ('HCHS', 'M08-HX'),
 ('HCHS', 'MGGA_MS2'),
 ('HCHS', 'MN15'),
 ('HCHS', 'MN15-L'),
 ('HCHS', 'PBE'),
 ('HCHS', 'PBE0'),
 ('HCHS', 'SCAN'),
 ('HCHS', 'SCAN0'),
 ('HCHS', 'SPW92'),
 ('HCHS', 'Slater'),
 ('HCHS', 'TPSS'),
 ('HCHS', 'mBEEF'),
 ('HCHS', 'mPW91'),
 ('HCHS', 'revM06-L'),
 ('HCHS', 'wB97M-V'),
 ('HCHS', 'wB97X-D'),
 ('HCHS', 'wB97X-V'),
 ('HCP', 'B3LYP'),
 ('HCP', 'B97-D3'),
 ('HCP', 'B97M-V'),
 ('HCP', 'BLYP'),
 ('HCP', 'BPBE'),
 ('HCP', 'CAM-B3LYP'),
 ('HCP', 'M06-2X'),
 ('HCP', 'M06-L'),
 ('HCP', 'M08-HX'),
 ('HCP', 'MGGA_MS2'),
 ('HCP', 'MN15'),
 ('HCP', 'MN15-L'),
 ('HCP', 'PBE'),
 ('HCP', 'PBE0'),
 ('HCP', 'SCAN'),
 ('HCP', 'SCAN0'),
 ('HCP', 'SPW92'),
 ('HCP', 'Slater'),
 ('HCP', 'TPSS'),
 ('HCP', 'mBEEF'),
 ('HCP', 'mPW91'),
 ('HCP', 'revM06-L'),
 ('HCP', 'wB97M-V'),
 ('HCP', 'wB97X-D'),
 ('HCP', 'wB97X-V'),
 ('Li', 'B3LYP'),
 ('Li', 'B97-D3'),
 ('Li', 'B97M-V'),
 ('Li', 'BLYP'),
 ('Li', 'BPBE'),
 ('Li', 'CAM-B3LYP'),
 ('Li', 'M06-2X'),
 ('Li', 'M06-L'),
 ('Li', 'M08-HX'),
 ('Li', 'MGGA_MS2'),
 ('Li', 'MN15'),
 ('Li', 'MN15-L'),
 ('Li', 'PBE'),
 ('Li', 'PBE0'),
 ('Li', 'SCAN'),
 ('Li', 'SCAN0'),
 ('Li', 'SPW92'),
 ('Li', 'Slater'),
 ('Li', 'TPSS'),
 ('Li', 'mBEEF'),
 ('Li', 'mPW91'),
 ('Li', 'revM06-L'),
 ('Li', 'wB97M-V'),
 ('Li', 'wB97X-D'),
 ('Li', 'wB97X-V'),
 ('Li2', 'B3LYP'),
 ('Li2', 'B97-D3'),
 ('Li2', 'B97M-V'),
 ('Li2', 'BLYP'),
 ('Li2', 'BPBE'),
 ('Li2', 'CAM-B3LYP'),
 ('Li2', 'M06-2X'),
 ('Li2', 'M06-L'),
 ('Li2', 'M08-HX'),
 ('Li2', 'MGGA_MS2'),
 ('Li2', 'MN15'),
 ('Li2', 'MN15-L'),
 ('Li2', 'PBE'),
 ('Li2', 'PBE0'),
 ('Li2', 'SCAN'),
 ('Li2', 'SCAN0'),
 ('Li2', 'SPW92'),
 ('Li2', 'Slater'),
 ('Li2', 'TPSS'),
 ('Li2', 'mBEEF'),
 ('Li2', 'mPW91'),
 ('Li2', 'revM06-L'),
 ('Li2', 'wB97M-V'),
 ('Li2', 'wB97X-D'),
 ('Li2', 'wB97X-V'),
 ('LiCl', 'B3LYP'),
 ('LiCl', 'B97-D3'),
 ('LiCl', 'B97M-V'),
 ('LiCl', 'BLYP'),
 ('LiCl', 'BPBE'),
 ('LiCl', 'CAM-B3LYP'),
 ('LiCl', 'M06-2X'),
 ('LiCl', 'M06-L'),
 ('LiCl', 'M08-HX'),
 ('LiCl', 'MGGA_MS2'),
 ('LiCl', 'MN15'),
 ('LiCl', 'MN15-L'),
 ('LiCl', 'PBE'),
 ('LiCl', 'PBE0'),
 ('LiCl', 'SCAN'),
 ('LiCl', 'SCAN0'),
 ('LiCl', 'SPW92'),
 ('LiCl', 'Slater'),
 ('LiCl', 'TPSS'),
 ('LiCl', 'mBEEF'),
 ('LiCl', 'mPW91'),
 ('LiCl', 'revM06-L'),
 ('LiCl', 'wB97M-V'),
 ('LiCl', 'wB97X-D'),
 ('LiCl', 'wB97X-V'),
 ('LiCN', 'B3LYP'),
 ('LiCN', 'B97-D3'),
 ('LiCN', 'B97M-V'),
 ('LiCN', 'BLYP'),
 ('LiCN', 'BPBE'),
 ('LiCN', 'CAM-B3LYP'),
 ('LiCN', 'M06-2X'),
 ('LiCN', 'M06-L'),
 ('LiCN', 'M08-HX'),
 ('LiCN', 'MGGA_MS2'),
 ('LiCN', 'MN15'),
 ('LiCN', 'MN15-L'),
 ('LiCN', 'PBE'),
 ('LiCN', 'PBE0'),
 ('LiCN', 'SCAN'),
 ('LiCN', 'SCAN0'),
 ('LiCN', 'SPW92'),
 ('LiCN', 'Slater'),
 ('LiCN', 'TPSS'),
 ('LiCN', 'mBEEF'),
 ('LiCN', 'mPW91'),
 ('LiCN', 'revM06-L'),
 ('LiCN', 'wB97M-V'),
 ('LiCN', 'wB97X-D'),
 ('LiCN', 'wB97X-V'),
 ('NaH', 'B3LYP'),
 ('NaH', 'B97-D3'),
 ('NaH', 'B97M-V'),
 ('NaH', 'BLYP'),
 ('NaH', 'BPBE'),
 ('NaH', 'CAM-B3LYP'),
 ('NaH', 'M06-2X'),
 ('NaH', 'M06-L'),
 ('NaH', 'M08-HX'),
 ('NaH', 'MGGA_MS2'),
 ('NaH', 'MN15'),
 ('NaH', 'MN15-L'),
 ('NaH', 'PBE'),
 ('NaH', 'PBE0'),
 ('NaH', 'SCAN'),
 ('NaH', 'SCAN0'),
 ('NaH', 'SPW92'),
 ('NaH', 'Slater'),
 ('NaH', 'TPSS'),
 ('NaH', 'mBEEF'),
 ('NaH', 'mPW91'),
 ('NaH', 'revM06-L'),
 ('NaH', 'wB97M-V'),
 ('NaH', 'wB97X-D'),
 ('NaH', 'wB97X-V'),
 ('NaLi', 'B3LYP'),
 ('NaLi', 'B97-D3'),
 ('NaLi', 'B97M-V'),
 ('NaLi', 'BLYP'),
 ('NaLi', 'BPBE'),
 ('NaLi', 'CAM-B3LYP'),
 ('NaLi', 'M06-2X'),
 ('NaLi', 'M06-L'),
 ('NaLi', 'M08-HX'),
 ('NaLi', 'MGGA_MS2'),
 ('NaLi', 'MN15'),
 ('NaLi', 'MN15-L'),
 ('NaLi', 'PBE'),
 ('NaLi', 'PBE0'),
 ('NaLi', 'SCAN'),
 ('NaLi', 'SCAN0'),
 ('NaLi', 'SPW92'),
 ('NaLi', 'Slater'),
 ('NaLi', 'TPSS'),
 ('NaLi', 'mBEEF'),
 ('NaLi', 'mPW91'),
 ('NaLi', 'revM06-L'),
 ('NaLi', 'wB97M-V'),
 ('NaLi', 'wB97X-D'),
 ('NaLi', 'wB97X-V'),
 ('NOCl', 'B3LYP'),
 ('NOCl', 'B97-D3'),
 ('NOCl', 'B97M-V'),
 ('NOCl', 'BLYP'),
 ('NOCl', 'BPBE'),
 ('NOCl', 'CAM-B3LYP'),
 ('NOCl', 'M06-2X'),
 ('NOCl', 'M06-L'),
 ('NOCl', 'M08-HX'),
 ('NOCl', 'MGGA_MS2'),
 ('NOCl', 'MN15'),
 ('NOCl', 'MN15-L'),
 ('NOCl', 'PBE'),
 ('NOCl', 'PBE0'),
 ('NOCl', 'SCAN'),
 ('NOCl', 'SCAN0'),
 ('NOCl', 'SPW92'),
 ('NOCl', 'Slater'),
 ('NOCl', 'TPSS'),
 ('NOCl', 'mBEEF'),
 ('NOCl', 'mPW91'),
 ('NOCl', 'revM06-L'),
 ('NOCl', 'wB97M-V'),
 ('NOCl', 'wB97X-D'),
 ('NOCl', 'wB97X-V'),
 ('NP', 'B3LYP'),
 ('NP', 'B97-D3'),
 ('NP', 'B97M-V'),
 ('NP', 'BLYP'),
 ('NP', 'BPBE'),
 ('NP', 'CAM-B3LYP'),
 ('NP', 'M06-2X'),
 ('NP', 'M06-L'),
 ('NP', 'M08-HX'),
 ('NP', 'MGGA_MS2'),
 ('NP', 'MN15'),
 ('NP', 'MN15-L'),
 ('NP', 'PBE'),
 ('NP', 'PBE0'),
 ('NP', 'SCAN'),
 ('NP', 'SCAN0'),
 ('NP', 'SPW92'),
 ('NP', 'Slater'),
 ('NP', 'TPSS'),
 ('NP', 'mBEEF'),
 ('NP', 'mPW91'),
 ('NP', 'revM06-L'),
 ('NP', 'wB97M-V'),
 ('NP', 'wB97X-D'),
 ('NP', 'wB97X-V'),
 ('OCl2', 'B3LYP'),
 ('OCl2', 'B97-D3'),
 ('OCl2', 'B97M-V'),
 ('OCl2', 'BLYP'),
 ('OCl2', 'BPBE'),
 ('OCl2', 'CAM-B3LYP'),
 ('OCl2', 'M06-2X'),
 ('OCl2', 'M06-L'),
 ('OCl2', 'M08-HX'),
 ('OCl2', 'MGGA_MS2'),
 ('OCl2', 'MN15'),
 ('OCl2', 'MN15-L'),
 ('OCl2', 'PBE'),
 ('OCl2', 'PBE0'),
 ('OCl2', 'SCAN'),
 ('OCl2', 'SCAN0'),
 ('OCl2', 'SPW92'),
 ('OCl2', 'Slater'),
 ('OCl2', 'TPSS'),
 ('OCl2', 'mBEEF'),
 ('OCl2', 'mPW91'),
 ('OCl2', 'revM06-L'),
 ('OCl2', 'wB97M-V'),
 ('OCl2', 'wB97X-D'),
 ('OCl2', 'wB97X-V'),
 ('OF2', 'B3LYP'),
 ('OF2', 'B97-D3'),
 ('OF2', 'B97M-V'),
 ('OF2', 'BLYP'),
 ('OF2', 'BPBE'),
 ('OF2', 'CAM-B3LYP'),
 ('OF2', 'M06-2X'),
 ('OF2', 'M06-L'),
 ('OF2', 'M08-HX'),
 ('OF2', 'MGGA_MS2'),
 ('OF2', 'MN15'),
 ('OF2', 'MN15-L'),
 ('OF2', 'PBE'),
 ('OF2', 'PBE0'),
 ('OF2', 'SCAN'),
 ('OF2', 'SCAN0'),
 ('OF2', 'SPW92'),
 ('OF2', 'Slater'),
 ('OF2', 'TPSS'),
 ('OF2', 'mBEEF'),
 ('OF2', 'mPW91'),
 ('OF2', 'revM06-L'),
 ('OF2', 'wB97M-V'),
 ('OF2', 'wB97X-D'),
 ('OF2', 'wB97X-V'),
 ('P2', 'B3LYP'),
 ('P2', 'B97-D3'),
 ('P2', 'B97M-V'),
 ('P2', 'BLYP'),
 ('P2', 'BPBE'),
 ('P2', 'CAM-B3LYP'),
 ('P2', 'M06-2X'),
 ('P2', 'M06-L'),
 ('P2', 'M08-HX'),
 ('P2', 'MGGA_MS2'),
 ('P2', 'MN15'),
 ('P2', 'MN15-L'),
 ('P2', 'PBE'),
 ('P2', 'PBE0'),
 ('P2', 'SCAN'),
 ('P2', 'SCAN0'),
 ('P2', 'SPW92'),
 ('P2', 'Slater'),
 ('P2', 'TPSS'),
 ('P2', 'mBEEF'),
 ('P2', 'mPW91'),
 ('P2', 'revM06-L'),
 ('P2', 'wB97M-V'),
 ('P2', 'wB97X-D'),
 ('P2', 'wB97X-V'),
 ('PH2', 'B3LYP'),
 ('PH2', 'B97-D3'),
 ('PH2', 'B97M-V'),
 ('PH2', 'BLYP'),
 ('PH2', 'BPBE'),
 ('PH2', 'CAM-B3LYP'),
 ('PH2', 'M06-2X'),
 ('PH2', 'M06-L'),
 ('PH2', 'M08-HX'),
 ('PH2', 'MGGA_MS2'),
 ('PH2', 'MN15'),
 ('PH2', 'MN15-L'),
 ('PH2', 'PBE'),
 ('PH2', 'PBE0'),
 ('PH2', 'SCAN'),
 ('PH2', 'SCAN0'),
 ('PH2', 'SPW92'),
 ('PH2', 'Slater'),
 ('PH2', 'TPSS'),
 ('PH2', 'mBEEF'),
 ('PH2', 'mPW91'),
 ('PH2', 'revM06-L'),
 ('PH2', 'wB97M-V'),
 ('PH2', 'wB97X-D'),
 ('PH2', 'wB97X-V'),
 ('PH3', 'B3LYP'),
 ('PH3', 'B97-D3'),
 ('PH3', 'B97M-V'),
 ('PH3', 'BLYP'),
 ('PH3', 'BPBE'),
 ('PH3', 'CAM-B3LYP'),
 ('PH3', 'M06-2X'),
 ('PH3', 'M06-L'),
 ('PH3', 'M08-HX'),
 ('PH3', 'MGGA_MS2'),
 ('PH3', 'MN15'),
 ('PH3', 'MN15-L'),
 ('PH3', 'PBE'),
 ('PH3', 'PBE0'),
 ('PH3', 'SCAN'),
 ('PH3', 'SCAN0'),
 ('PH3', 'SPW92'),
 ('PH3', 'Slater'),
 ('PH3', 'TPSS'),
 ('PH3', 'mBEEF'),
 ('PH3', 'mPW91'),
 ('PH3', 'revM06-L'),
 ('PH3', 'wB97M-V'),
 ('PH3', 'wB97X-D'),
 ('PH3', 'wB97X-V'),
 ('PH3O', 'B3LYP'),
 ('PH3O', 'B97-D3'),
 ('PH3O', 'B97M-V'),
 ('PH3O', 'BLYP'),
 ('PH3O', 'BPBE'),
 ('PH3O', 'CAM-B3LYP'),
 ('PH3O', 'M06-2X'),
 ('PH3O', 'M06-L'),
 ('PH3O', 'M08-HX'),
 ('PH3O', 'MGGA_MS2'),
 ('PH3O', 'MN15'),
 ('PH3O', 'MN15-L'),
 ('PH3O', 'PBE'),
 ('PH3O', 'PBE0'),
 ('PH3O', 'SCAN'),
 ('PH3O', 'SCAN0'),
 ('PH3O', 'SOGGA11'),
 ('PH3O', 'SPW92'),
 ('PH3O', 'Slater'),
 ('PH3O', 'TPSS'),
 ('PH3O', 'mBEEF'),
 ('PH3O', 'mPW91'),
 ('PH3O', 'revM06-L'),
 ('PH3O', 'wB97M-V'),
 ('PH3O', 'wB97X-D'),
 ('PH3O', 'wB97X-V'),
 ('S2', 'B3LYP'),
 ('S2', 'B97-D3'),
 ...]

In [24]:
data['PH']

[{'name': 'PH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVDZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-14.561267248715938,
   -15.338024192513723,
   -0.2209217803018111],
  'quadrupoles_mp2': [-14.571018742906253,
   -15.438699962605915,
   -0.24714993662817875],
  'quadrupoles_ccsd': [-14.543109294306738,
   -15.335603132282627,
   -0.22462062276753794],
  'quadrupoles_hf': [-14.4571, -14.4571, -15.6531],
  'dipoles_ccsdt': [],
  'dipoles_mp2': [],
  'dipoles_ccsd': [],
  'dipoles_hf': [-0.0, 0.0, -0.5511, 0.5511],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-14.333822055296505,
   -14.333822055296505,
   -15.009566971082664],
  'quadrupoles_mp2': [-14.382714029339395,
   -14.382714029339395,
   -15.064915106506376],
  'quadrupoles_ccsd': [-14.320640725587662,
   -14.320640725587662,
   -15.03263429807314],
  'quadrupoles_hf': [-14.4047, -14.4047, -15.4891],
  'dipoles_ccsdt': [0, 0, -0.429, 0.429],
  'dipoles_mp2': [0, 0, -0.4413, 0.4413],
  'dipoles_ccsd': [0, 0, -0.4374, 0.4374],
  'dipoles_hf': [0.0, -0.0, -0.513, 0.513],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, -0.0, -40.51827442889999, 40.51827442889999],
  'dipoles_elec_mp2': [0.0, 0.0, -40.490065476389994, 40.490065476389994],
  'dipoles_elec_ccsd': [0.0, 0.0, -40.488531098219994, 40.488531098219994],
  'dipoles_elec_ccsdt': [0.0, 0.0, -40.485226283699994, 40.485226283699994],
  'quadrupoles_elec_hf': [-10.7095631419, -10.7095631419, -119.87682272023864],
  'quadrupoles_elec_mp2': [-10.693217078391166,
   -10.693217078391166,
   -119.56145100817868],
  'quadrupoles_elec_ccsd': [-10.647067004737739,
   -10.647067004737739,
   -119.53745096956716],
  'quadrupoles_elec_ccsdt': [-10.65686702020568,
   -10.65686702020568,
   -119.52030094249827],
  'std_dev_hf': [0.8181367222956992, 0.8181367222956992, 1.038889507832776],
  'std_dev_mp2': [0.817512120643754, 0.817512120643754, 1.0336861638552304],
  'std_dev_ccsd': [0.8157460927250026, 0.8157460927250026, 1.0331952581629564],
  'std_dev_ccsdt': [0.8161214301578259,
   0.8161214301578259,
   1.0331824088661907]},
 {'name': 'PH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-14.397576651321383,
   -14.397576651321383,
   -15.054558347067147],
  'quadrupoles_mp2': [-14.441828259347915,
   -14.441828259347915,
   -15.117774929579909],
  'quadrupoles_ccsd': [-14.382310519300878,
   -14.382310519300878,
   -15.072111036609712],
  'quadrupoles_hf': [-14.4267, -14.4267, -15.5055],
  'dipoles_ccsdt': [0, 0, -0.4192, 0.4192],
  'dipoles_mp2': [0, 0, -0.4359, 0.4359],
  'dipoles_ccsd': [0, 0, -0.4276, 0.4276],
  'dipoles_hf': [0.0, 0.0, -0.5189, 0.5189],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, 0.0, -40.520595667669994, 40.520595667669994],
  'dipoles_elec_mp2': [0.0, 0.0, -40.487940952769996, 40.487940952769996],
  'dipoles_elec_ccsd': [0.0, 0.0, -40.48467548127999, 40.48467548127999],
  'dipoles_elec_ccsdt': [0.0, 0.0, -40.48137066675999, 40.48137066675999],
  'quadrupoles_elec_hf': [-10.7259196359, -10.7259196359, -119.88901574303863],
  'quadrupoles_elec_mp2': [-10.73716714877521,
   -10.73716714877521,
   -119.60075107085791],
  'quadrupoles_elec_ccsd': [-10.69291707795826,
   -10.69291707795826,
   -119.56680101670412],
  'quadrupoles_elec_ccsdt': [-10.704267095994469,
   -10.704267095994469,
   -119.55375099574107],
  'std_dev_hf': [0.818761245567809, 0.818761245567809, 1.0389026260950138],
  'std_dev_mp2': [0.8191904215739163, 0.8191904215739163, 1.0351982270521625],
  'std_dev_ccsd': [0.81750065282689, 0.81750065282689, 1.0346721012949442],
  'std_dev_ccsdt': [0.8179344065997312,
   0.8179344065997312,
   1.0347830480502618]},
 {'name': 'PH',
  'method': 'mBEEF',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.1594, -14.1594, -15.0691],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.45, 0.45],
  'quadrupoles_elec': [-10.5271882338, -10.5271882338, -119.56456238023864],
  'dipoles_elec': [0.0, -0.0, -40.49348831999999, 40.49348831999999],
  'std_dev': [0.8111407181324952, 0.8111407181324952, 1.033256384873666],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.2986, -14.2986, -15.1374],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.4538, 0.4538],
  'quadrupoles_elec': [-10.630680232200001,
   -10.630680232200001,
   -119.61534185933863],
  'dipoles_elec': [-0.0, -0.0, -40.49498335513999, 40.49498335513999],
  'std_dev': [0.815118098506284, 0.815118098506284, 1.034562469447292],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-14.4131, -14.4131, -15.123],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -0.4008, 0.4008],
  'quadrupoles_elec': [-10.715808348700001,
   -10.715808348700001,
   -119.60463579053864],
  'dipoles_elec': [0.0, 0.0, -40.47413154923999, 40.47413154923999],
  'std_dev': [0.8183752328814393, 0.8183752328814393, 1.0374225271967492],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-14.1858, -14.1858, -15.0879],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.4342, 0.4342],
  'quadrupoles_elec': [-10.546816026600002,
   -10.546816026600002,
   -119.57853974783863],
  'dipoles_elec': [0.0, -0.0, -40.48727212125999, 40.48727212125999],
  'std_dev': [0.8118965461575139, 0.8118965461575139, 1.0346297498691517],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'B97M-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.4032, -14.4032, -15.2128],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.3957, 0.3957],
  'quadrupoles_elec': [-10.708447926400002,
   -10.708447926400002,
   -119.67140002513864],
  'dipoles_elec': [-0.0, -0.0, -40.47212505470999, 40.47212505470999],
  'std_dev': [0.8180941238023899, 0.8180941238023899, 1.0397368468867307],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-14.5049, -14.5049, -15.1397],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.3681, 0.3681],
  'quadrupoles_elec': [-10.784059537300001,
   -10.784059537300001,
   -119.61705185643864],
  'dipoles_elec': [-0.0, -0.0, -40.46126637843, 40.46126637843],
  'std_dev': [0.8209772963250872, 0.8209772963250872, 1.0397542392104244],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'BPBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-14.3308, -14.3308, -15.0294],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.4216, 0.4216],
  'quadrupoles_elec': [-10.654620191600001,
   -10.654620191600001,
   -119.53504634333864],
  'dipoles_elec': [-0.0, -0.0, -40.482314899479995, 40.482314899479995],
  'std_dev': [0.8160353925994878, 0.8160353925994878, 1.0340736378834254],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-14.4151, -14.4151, -15.1985],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.4366, 0.4366],
  'quadrupoles_elec': [-10.717295302700002,
   -10.717295302700002,
   -119.66076830403864],
  'dipoles_elec': [-0.0, 0.0, -40.48821635397999, 40.48821635397999],
  'std_dev': [0.8184320108712453, 0.8184320108712453, 1.0369664089792254],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-14.3942, -14.3942, -15.1471],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.4185, 0.4185],
  'quadrupoles_elec': [-10.7017566334, -10.7017566334, -119.62255358623864],
  'dipoles_elec': [-0.0, 0.0, -40.481095265549996, 40.481095265549996],
  'std_dev': [0.8178384862474375, 0.8178384862474375, 1.0369007747724779],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.0305, -14.0305, -14.9077],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.4488, 0.4488],
  'quadrupoles_elec': [-10.431354048500001,
   -10.431354048500001,
   -119.44456519243863],
  'dipoles_elec': [-0.0, -0.0, -40.493016203639996, 40.493016203639996],
  'std_dev': [0.8074401699390799, 0.8074401699390799, 1.029693298183157],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'M08-HX',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-14.4185, -14.4185, -15.1291],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.4113, 0.4113],
  'quadrupoles_elec': [-10.719823124500001,
   -10.719823124500001,
   -119.60917100023863],
  'dipoles_elec': [-0.0, -0.0, -40.47826256738999, 40.47826256738999],
  'std_dev': [0.8185285244151544, 0.8185285244151544, 1.036929428064486],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.2447, -14.2447, -15.1102],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.4691, 0.4691],
  'quadrupoles_elec': [-10.590606821900002,
   -10.590606821900002,
   -119.59511928493863],
  'dipoles_elec': [-0.0, -0.0, -40.501002838729995, 40.501002838729995],
  'std_dev': [0.8135803134102682, 0.8135803134102682, 1.0330300501138836],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-14.3864, -14.3864, -15.219],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.4172, 0.4172],
  'quadrupoles_elec': [-10.695957512800002,
   -10.695957512800002,
   -119.67600958253863],
  'dipoles_elec': [0.0, -0.0, -40.48058380615999, 40.48058380615999],
  'std_dev': [0.817616869046866, 0.817616869046866, 1.0385884501953606],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.5772, -14.5772, -15.7456],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.4866, 0.4866],
  'quadrupoles_elec': [-10.8378129244, -10.8378129244, -120.06752457073863],
  'dipoles_elec': [-0.0, 0.0, -40.50788786897999, 40.50788786897999],
  'std_dev': [0.8230208428557566, 0.8230208428557566, 1.0461824454108317],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'mPW91',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-14.383, -14.383, -15.0695],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.4149, 0.4149],
  'quadrupoles_elec': [-10.693429691, -10.693429691, -119.56485977103863],
  'dipoles_elec': [-0.0, 0.0, -40.47967891646999, 40.47967891646999],
  'std_dev': [0.8175202478761612, 0.8175202478761612, 1.0353768772546381],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-14.4357, -14.4357, -15.1213],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, 0.0, -0.4203, 0.4203],
  'quadrupoles_elec': [-10.732610928900002,
   -10.732610928900002,
   -119.60337187963863],
  'dipoles_elec': [-0.0, 0.0, -40.48180344008999, 40.48180344008999],
  'std_dev': [0.8190165951043056, 0.8190165951043056, 1.0362144526324086],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'PBE0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-14.3381, -14.3381, -15.1208],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.4553, 0.4553],
  'quadrupoles_elec': [-10.660047573700002,
   -10.660047573700002,
   -119.60300014113864],
  'dipoles_elec': [0.0, -0.0, -40.49557350058999, 40.49557350058999],
  'std_dev': [0.8162432072343696, 0.8162432072343696, 1.0340993384880648],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.1261, -14.1261, -15.2953],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.4632, 0.4632],
  'quadrupoles_elec': [-10.5024304497, -10.5024304497, -119.73273687763863],
  'dipoles_elec': [-0.0, 0.0, -40.498681599959994, 40.498681599959994],
  'std_dev': [0.8101863385087718, 0.8101863385087718, 1.0375387393130497],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'SCAN',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.2713, -14.2713, -15.1431],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.4723, 0.4723],
  'quadrupoles_elec': [-10.610383310100001,
   -10.610383310100001,
   -119.61957967823864],
  'dipoles_elec': [-0.0, 0.0, -40.50226181568999, 40.50226181568999],
  'std_dev': [0.8143395832705482, 0.8143395832705482, 1.03357703863119],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'SCAN0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-14.259, -14.259, -15.1402],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.4748, 0.4748],
  'quadrupoles_elec': [-10.601238543000001,
   -10.601238543000001,
   -119.61742359493863],
  'dipoles_elec': [0.0, -0.0, -40.50324539144, 40.50324539144],
  'std_dev': [0.8139885803483363, 0.8139885803483363, 1.0333612673724124],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-14.944, -14.944, -15.639],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.4592, 0.4592],
  'quadrupoles_elec': [-11.110520288000002,
   -11.110520288000002,
   -119.98826992253863],
  'dipoles_elec': [0.0, -0.0, -40.49710787875999, 40.49710787875999],
  'std_dev': [0.8333111771721294, 0.8333111771721294, 1.045445053659665],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'SPW92',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-14.5275, -14.5275, -15.1881],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, -0.4472, 0.4472],
  'quadrupoles_elec': [-10.800862117500001,
   -10.800862117500001,
   -119.65303614323864],
  'dipoles_elec': [-0.0, 0.0, -40.492386715159995, 40.492386715159995],
  'std_dev': [0.821616627353506, 0.821616627353506, 1.0360969360751655],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'wB97M-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 7,
  'quadrupoles': [-14.5772, -14.5772, -15.1889],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.3911, 0.3911],
  'quadrupoles_elec': [-10.8378129244, -10.8378129244, -119.65363092483864],
  'dipoles_elec': [-0.0, 0.0, -40.470315275329995, 40.470315275329995],
  'std_dev': [0.8230208428557566, 0.8230208428557566, 1.0394779269406897],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'wB97X-D',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-14.2718, -14.2718, -15.129],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.4818, 0.4818],
  'quadrupoles_elec': [-10.610755048600002,
   -10.610755048600002,
   -119.60909665253862],
  'dipoles_elec': [-0.0, 0.0, -40.505999403539995, 40.505999403539995],
  'std_dev': [0.8143538484820343, 0.8143538484820343, 1.0326875562871354],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-14.3906, -14.3906, -15.2325],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.4843, 0.4843],
  'quadrupoles_elec': [-10.6990801162, -10.6990801162, -119.68604652203864],
  'dipoles_elec': [-0.0, -0.0, -40.506982979289994, 40.506982979289994],
  'std_dev': [0.8177362088488561, 0.8177362088488561, 1.0348631292880612],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcV5Zp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-14.31526059084879,
   -14.31526059084879,
   -14.995914878833943],
  'quadrupoles_mp2': [-14.363614551379564,
   -14.363614551379564,
   -15.049447219275471],
  'quadrupoles_ccsd': [-14.30295353295378,
   -14.30295353295378,
   -15.020932505427043],
  'quadrupoles_hf': [-14.4015, -14.4015, -15.4878],
  'dipoles_ccsdt': [0, 0, -0.4331, 0.4331],
  'dipoles_mp2': [0, 0, -0.4463, 0.4463],
  'dipoles_ccsd': [0, 0, -0.4415, 0.4415],
  'dipoles_hf': [0.0, 0.0, -0.5129, 0.5129],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, 0.0, -40.518235085869996, 40.518235085869996],
  'dipoles_elec_mp2': [0.0, 0.0, -40.49203262788999, 40.49203262788999],
  'dipoles_elec_ccsd': [0.0, 0.0, -40.490144162449994, 40.490144162449994],
  'dipoles_elec_ccsdt': [0.0, 0.0, -40.486839347929994, 40.486839347929994],
  'quadrupoles_elec_hf': [-10.707184015500001,
   -10.707184015500001,
   -119.87585620013863],
  'quadrupoles_elec_mp2': [-10.679017055816026,
   -10.679017055816026,
   -119.5499509897839],
  'quadrupoles_elec_ccsd': [-10.633916983819878,
   -10.633916983819878,
   -119.52875095587602],
  'quadrupoles_elec_ccsdt': [-10.643066998302487,
   -10.643066998302487,
   -119.51015092590946],
  'std_dev_hf': [0.8180458428283528, 0.8180458428283528, 1.038866428358468],
  'std_dev_mp2': [0.816969134048834, 0.816969134048834, 1.0330372949357929],
  'std_dev_ccsd': [0.8152421796550656, 0.8152421796550656, 1.0326850639951013],
  'std_dev_ccsdt': [0.8155928441286776,
   0.8155928441286776,
   1.0326283486158387]}]

In [287]:
save(data)

b"\x1b[0;32mSaving updates to GitHub...\x1b[0m\nOn branch master\nYour branch is up to date with 'origin/master'.\n\nChanges not staged for commit:\n\tmodified:   ../geometries/cbs_limit/make_input.py\n\tdeleted:    ../geometries/inputs/dft/Be_B3LYP5_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B3LYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B97-D3_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_B97M-V_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_BLYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_BPBE_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_CAM-B3LYP_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M06-2X_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M06-L_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_M08-HX_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MGGA_MS2_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MN15-L_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_MN15_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_PBE0_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_PBE_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SCAN0_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SCAN_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_SPW92_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_Slater_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_TPSS_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_mBEEF_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_mPW91_aug-pc-4.inp\n\tdeleted:    ../geometries/inputs/dft/Be_revM06-L_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_B3LYP_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_B97-D3_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_B97M-V_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_M06-2X_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_M06-L_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_M08-HX_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_MGGA_MS2_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_MN15-L_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_MN15_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_revM06-L_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_wB97M-V_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_wB97X-D_aug-pc-4.inp\n\tmodified:   ../geometries/inputs/dft/LiH_wB97X-V_aug-pc-4.inp\n\tmodified:   .ipynb_checkpoints/ouput-checkpoint.ipynb\n\tmodified:   mp2/HF.ipynb\n\tmodified:   ouput.ipynb\n\tmodified:   output.json\n\tmodified:   wft_table_2.csv\n\nUntracked files:\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/AlF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/BH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/BH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/C2H3_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2-t_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2BH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2BH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH2NH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH2NH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH3BH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CH3O_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CH3O_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/CO2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/ClF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/FCN_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/FCO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/FCO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/H2CN_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/H2CN_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HCCF_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HCCF_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HCO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HCO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HNO_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HNS_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HNS_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/HO2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/Mg2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/N2H2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/N2H4_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2Cl_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2Cl_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2F_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2OH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2OH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/Na2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/NaCl_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/O3_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/O3_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/PH_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcVQZ.inp\n\t../geometries/cbs_limit/S2H2_ccsdT_aug-cc-pcVTZ.inp\n\t../geometries/cbs_limit/hf/C2H2_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/C2H_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HBO_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HCN_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/HF_ccsdT_aug-cc-pc-V5Z.inp\n\t../geometries/cbs_limit/hf/HNC_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/LiBH4_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/NH3O_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/NH3_hf_aug-cc-pcV5Z.inp\n\t../geometries/cbs_limit/hf/O3_hf_aug-cc-pcV5Z.inp\n\t../geometries/inputs/HF_MP2_aug-cc-pcVDZ.inp\n\t../geometries/inputs/NH3-F2_TDDFT_aug-pc-2.inp\n\t../geometries/inputs/dft/BO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/BO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3OH_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/CH3_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/FH-OH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/H2O_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/H2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCHO_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCN_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B3LYP5_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B97-D3_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_B97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_BLYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_BPBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_CAM-B3LYP_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M06-2X_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_M08-HX_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MGGA_MS2_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MN15-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_MN15_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_TPSS_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_mPW91_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_revM06-L_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97M-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97X-D_aug-pc-4.inp\n\t../geometries/inputs/dft/HCOOH_wB97X-V_aug-pc-4.inp\n\t../geometries/inputs/dft/HCO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HCO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HCO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HCO_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HF_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HNC_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HNO_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HNO_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HNO_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HNO_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HNO_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HNS_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HNS_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HNS_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HNS_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HNS_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HNS_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/HO2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/HO2_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/HO2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/HO2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/HO2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/HO2_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/He_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/He_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/He_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/He_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/LiBH4_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/LiH_mBEEF_aug-pc-4.inp\n\t../geometries/inputs/dft/N2H2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/N2H2_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/N2H2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/N2H2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/N2H2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/N2H2_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/N2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2Cl_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2Cl_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2Cl_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2F_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2F_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2F_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2F_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2F_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2F_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2OH_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2OH_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2OH_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2OH_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2OH_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NH2_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3O_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NH3_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/NaCl_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/Na_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/Ne_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/Ne_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/Ne_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/Ne_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/O2_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_PBE_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_SCAN0_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_SCAN_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_SPW92_aug-pc-4.inp\n\t../geometries/inputs/dft/O3_Slater_aug-pc-4.inp\n\t../geometries/inputs/dft/S2H2_PBE0_aug-pc-4.inp\n\t../geometries/inputs/dft/missing-

In [74]:
missing_wft = []
for m in get_dft_species():
    temp = retrieve(m, 'ccsdT', 'aug-cc-pcV5Zp')
    if temp == {}:
        missing_wft.append(m)

In [75]:
missing_wft

['AlF',
 'BH2F',
 'BO',
 'C2H',
 'C2H2',
 'CH2BH',
 'CH3',
 'CH4',
 'ClF',
 'CO',
 'CO2',
 'FCN',
 'H2CN',
 'HBO',
 'HCCF',
 'HCN',
 'HNC',
 'LiBH4',
 'NaCl',
 'NH3',
 'NH3O',
 'O3',
 'LiH',
 'BHF2',
 'C2H4',
 'CH3Cl',
 'Cl2',
 'ClCN',
 'CS',
 'CSO',
 'HBS',
 'HCCCl',
 'HCHS',
 'HCP',
 'Li',
 'Li2',
 'LiCl',
 'LiCN',
 'NaH',
 'NaLi',
 'NOCl',
 'NP',
 'OCl2',
 'OF2',
 'P2',
 'PH2',
 'PH3',
 'PH3O',
 'S2',
 'SCl2',
 'SH2',
 'SiH3',
 'SiH3Cl',
 'SiH3F',
 'SiH4',
 'SO2',
 'SO-trip']

In [28]:
len(get_functionals())

32

In [39]:
save(data)

b'\x1b[0;32mSaving updates to GitHub...\x1b[0m\n[master 7dfc79d] save Tue, Aug 18, 2020  1:39:58 PM\n 920 files changed, 885563 insertions(+), 20622 deletions(-)\n create mode 100644 output/Na2_B97M-V_aug-pc-4p.out\n create mode 100644 output/Na_M06-2X_aug-pc-4p.out\n create mode 100644 output/OF2_ccsdT_aug-cc-pcVTZp.err\n create mode 100644 output/cbs_limit/20-08-03/BH2F_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/CH2-t_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/20-08-03/CH2BH_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/20-08-03/CN_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/20-08-03/CO2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/ClF_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/20-08-03/ClF_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/F2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/20-08-03/FCN_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/FCN_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/20-08-03/H2CN_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/HCCF_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/HCCF_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/20-08-03/Mg2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/N2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/20-08-03/NH2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/20-08-03/NH3O_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/NH_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/20-08-03/Na2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/NaCl_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/O2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/20-08-03/O3_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/20-08-03/O3_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/BF_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/BH2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/BH2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/BH3_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/C2H2_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/CH2-t_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/CH2-t_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/CH2-t_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/CH2BH_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/CN_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/CO2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/F2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/FCN_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/FCN_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/H2CN_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/HBO_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/HCCF_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/HCN_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/HNC_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/LiH_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/LiH_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/Mg2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/Mg_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/N2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/NH2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/NH3O_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/NH3O_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/NH3_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/Na2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/NaCl_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/Na_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/O2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/O3_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/O3_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/O3_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-11/PH_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/AlF_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/BH2F_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/BH2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/BHF2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/BHF2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/BO_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/BeH2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/BeH_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/C2H2_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/C2H4_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/C2H4_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CH2-t_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CH2BH_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CH2BH_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CH3Cl_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CH3_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CH4_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CO2_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CO_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CSO_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/CSO_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Cl2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Cl2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/ClCN_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/ClCN_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/ClF_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/ClF_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/FCN_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/H2CN_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HBO_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HBS_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HBS_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HCCCl_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HCCF_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HCCF_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HCHS_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HCN_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HCP_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HCP_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/HNC_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Li2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Li2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/LiBH4_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/LiBH4_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/LiCN_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/LiH_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Li_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Li_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Mg2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Mg_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/NOCl_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/NOCl_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/NP_ccsdT_aug-cc-pcVQZp.out\n rename output/cbs_limit/{20-08-03/AlF_ccsdT_aug-cc-pcVTZp.out => missing/20-08-14/NP_ccsdT_aug-cc-pcVTZp.out} (59%)\n create mode 100644 output/cbs_limit/missing/20-08-14/Na2_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/NaCl_hf_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/NaH_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/NaH_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/NaLi_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/NaLi_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/Na_ccsdT_aug-cc-pcV5Zp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/OF2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/P2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/P2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/PH2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/PH2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/PH3O_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/PH3_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/PH3_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/S2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/S2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SCl2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SH2_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SH2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SO-trip_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SO-trip_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SO2_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SiH3Cl_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SiH3F_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SiH3_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SiH3_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SiH4_ccsdT_aug-cc-pcVQZp.out\n create mode 100644 output/cbs_limit/missing/20-08-14/SiH4_ccsdT_aug-cc-pcVTZp.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/FCO_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2CN_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H2_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/H_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/LiBH4_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/LiH_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/LiH_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/LiH_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/LiH_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/LiH_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/LiH_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Mg2_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Mg2_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Mg2_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Mg2_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Mg_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H2_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2H4_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N2_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2Cl_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2F_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2F_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2F_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2OH_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH2_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH3O_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH3_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH3_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH3_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/NH_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/N_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Na2_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Na2_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Na2_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Na2_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/second_half/Na2_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/s