In [1]:
import json, re
import pandas as pd
import numpy as np
from get_electronic import get_electronic_dipole, get_electronic_quadrupole, get_stddev
from os import path
from pathlib import Path
from numpy import sign
import subprocess
from IPython.display import display

In [43]:
with open('output.json') as f:
    data = json.load(f)

In [3]:
with open('jacob_ladder.json') as f:
    ladder = json.load(f)

In [4]:
data

{'AlF': [{'name': 'AlF',
   'method': 'BLYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-16.0501, -16.0501, -22.7295],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [-0.0, 0.0, -1.4687, 1.4687],
   'quadrupoles_elec': [-11.932880197700001,
    -11.932880197700001,
    -104.86651449752497],
   'dipoles_elec': [-0.0, 0.0, -28.71515488961, 28.71515488961],
   'std_dev': [0.736480580429654, 0.736480580429654, 1.7501494615108055],
   'spin_polarized': 0}],
 'Ar': [{'name': 'Ar',
   'method': 'B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-11.7543, -11.7543, -11.7543],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.739051701100001,
    -8.739051701100001,
    -8.739051701100001],
   'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
   'std_dev': [0.6967803615798406, 0.6967803615798406, 0.6967803615798406],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'B3LYP5',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-11.7593, -11.7593, -11.7593],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.742769086100001,
    -8.742769086100001,
    -8.742769086100001],
   'dipoles_elec': [-0.0, 0.0, -0.0, 0.0],
   'std_dev': [0.6969285427303307, 0.6969285427303307, 0.6969285427303307],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'BLYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.8321, -11.8321, -11.8321],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-8.796894211700002,
    -8.796894211700002,
    -8.796894211700002],
   'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.6990825023517929, 0.6990825023517929, 0.6990825023517929],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'BPBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.695, -11.695, -11.695],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.694963515000001,
    -8.694963515000001,
    -8.694963515000001],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [0.6950205238776127, 0.6950205238776127, 0.6950205238776127],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'mBEEF',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-11.5602, -11.5602, -11.5602],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-8.5947428154, -8.5947428154, -8.5947428154],
   'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.6910034095188436, 0.6910034095188436, 0.6910034095188436],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'mPW91',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-11.7286, -11.7286, -11.7286],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [-0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-8.719944342200002,
    -8.719944342200002,
    -8.719944342200002],
   'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
   'std_dev': [0.6960182126528331, 0.6960182126528331, 0.6960182126528331],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'TPSS',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-11.6976, -11.6976, -11.6976],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.6968965552, -8.6968965552, -8.6968965552],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [0.6950977771028573, 0.6950977771028573, 0.6950977771028573],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'wB97X-V',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-11.7107, -11.7107, -11.7107],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-8.7066361039, -8.7066361039, -8.7066361039],
   'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
   'std_dev': [0.695486883968506, 0.695486883968506, 0.695486883968506],
   'spin_polarized': 0},
  {'name': 'Ar',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcV5Zp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-11.63857633767873,
    -11.63857633767873,
    -11.63857633767873],
   'quadrupoles_mp2': [-11.656129027221297,
    -11.656129027221297,
    -11.656129027221297],
   'quadrupoles_ccsd': [-11.624722491366455,
    -11.624722491366455,
    -11.624722491366455],
   'quadrupoles_hf': [-11.6741, -11.6741, -11.6741],
   'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_hf': [0.0, -0.0, -0.0, 0.0],
   'spin_polarized': 0,
   'dipoles_elec_hf': [0.0, -0.0, -0.0, 0.0],
   'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec_hf': [-8.6794248457, -8.6794248457, -8.6794248457],
   'quadrupoles_elec_mp2': [-8.66606384077141,
    -8.66606384077141,
    -8.66606384077141],
   'quadrupoles_elec_ccsd': [-8.642713803713658,
    -8.642713803713658,
    -8.642713803713658],
   'quadrupoles_elec_ccsdt': [-8.65301381980837,
    -8.65301381980837,
    -8.65301381980837],
   'std_dev_hf': [0.6943992145772888, 0.6943992145772888, 0.6943992145772888],
   'std_dev_mp2': [0.6938645337196355, 0.6938645337196355, 0.6938645337196355],
   'std_dev_ccsd': [0.6929291211032922,
    0.6929291211032922,
    0.6929291211032922],
   'std_dev_ccsdt': [0.693341899779145, 0.693341899779145, 0.693341899779145]},
  {'name': 'Ar',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVQZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-11.656801543824729,
    -11.656801543824729,
    -11.656801543824729],
   'quadrupoles_mp2': [-11.673547213290263,
    -11.673547213290263,
    -11.673547213290263],
   'quadrupoles_ccsd': [-11.64200617319726,
    -11.64200617319726,
    -11.64200617319726],
   'quadrupoles_hf': [-11.6767, -11.6767, -11.6767],
   'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_hf': [0.0, -0.0, -0.0, 0.0],
   'spin_polarized': 0,
   'dipoles_elec_hf': [0.0, -0.0, -0.0, 0.0],
   'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec_hf': [-8.6813578859, -8.6813578859, -8.6813578859],
   'quadrupoles_elec_mp2': [-8.679013861495406,
    -8.679013861495406,
    -8.679013861495406],
   'quadrupoles_elec_ccsd': [-8.65556382363018,
    -8.65556382363018,
    -8.65556382363018],
   'quadrupoles_elec_ccsdt': [-8.666563841398178,
    -8.666563841398178,
    -8.666563841398178],
   'std_dev_hf': [0.694476536916675, 0.694476536916675, 0.694476536916675],
   'std_dev_mp2': [0.694382773943698, 0.694382773943698, 0.694382773943698],
   'std_dev_ccsd': [0.6934440546059526,
    0.6934440546059526,
    0.6934440546059526],
   'std_dev_ccsdt': [0.6938845501713995,
    0.6938845501713995,
    0.6938845501713995]},
  {'name': 'Ar',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVTZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-11.709997625582261,
    -11.709997625582261,
    -11.709997625582261],
   'quadrupoles_mp2': [-11.715445011675651,
    -11.715445011675651,
    -11.715445011675651],
   'quadrupoles_ccsd': [-11.694327983905522,
    -11.694327983905522,
    -11.694327983905522],
   'quadrupoles_hf': [-11.6875, -11.6875, -11.6875],
   'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_hf': [0.0, 0.0, 0.0, 0.0],
   'spin_polarized': 0,
   'dipoles_elec_hf': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec_hf': [-8.6893874375, -8.6893874375, -8.6893874375],
   'quadrupoles_elec_mp2': [-8.710163910945578,
    -8.710163910945578,
    -8.710163910945578],
   'quadrupoles_elec_ccsd': [-8.694463886490126,
    -8.694463886490126,
    -8.694463886490126],
   'quadrupoles_elec_ccsdt': [-8.706113904675023,
    -8.706113904675023,
    -8.706113904675023],
   'std_dev_hf': [0.6947976299094419, 0.6947976299094419, 0.6947976299094419],
   'std_dev_mp2': [0.6956277704724935, 0.6956277704724935, 0.6956277704724935],
   'std_dev_ccsd': [0.695000555015371, 0.695000555015371, 0.695000555015371],
   'std_dev_ccsdt': [0.6954660269949697,
    0.6954660269949697,
    0.6954660269949697]}],
 'Be': [{'name': 'Be',
   'method': 'PBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-7.5237, -7.5237, -7.5237],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-5.5936979049, -5.5936979049, -5.5936979049],
   'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
   'std_dev': [1.182549988890533, 1.182549988890533, 1.182549988890533],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'B97-D3',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-7.6035, -7.6035, -7.6035],
   'quadrupoles_off_diag': [0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-5.653027369500001,
    -5.653027369500001,
    -5.653027369500001],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [1.1888047957402428, 1.1888047957402428, 1.1888047957402428],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'CAM-B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 6,
   'quadrupoles': [-7.5393, -7.5393, -7.5393],
   'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec': [-5.605296146100001,
    -5.605296146100001,
    -5.605296146100001],
   'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
   'std_dev': [1.1837753319464805, 1.1837753319464805, 1.1837753319464805],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'M06-2X',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-7.454, -7.454, -7.454],
   'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
   'dipoles': [0.0, 0.0, -0.0, 0.0],
   'quadrupoles_elec': [-5.541877558, -5.541877558, -5.541877558],
   'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
   'std_dev': [1.1770596371892124, 1.1770596371892124, 1.1770596371892124],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'M06-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.4636, -7.4636, -7.4636],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.0, 0.0],
   'quadrupoles_elec': [-5.5490149372, -5.5490149372, -5.5490149372],
   'dipoles_elec': [0.0, -0.0, 0.0, 0.0],
   'std_dev': [1.1778173603322375, 1.1778173603322375, 1.1778173603322375],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'MGGA_MS2',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.4472, -7.4472, -7.4472],
   'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-5.5368219144, -5.5368219144, -5.5368219144],
   'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
   'std_dev': [1.176522621371982, 1.176522621371982, 1.176522621371982],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'MN15',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 5,
   'quadrupoles': [-7.7815, -7.7815, -7.7815],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [-0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-5.7853662755, -5.7853662755, -5.7853662755],
   'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
   'std_dev': [1.2026394176456217, 1.2026394176456217, 1.2026394176456217],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'MN15-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.9746, -7.9746, -7.9746],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, 0.0, 0.0],
   'quadrupoles_elec': [-5.9289316842, -5.9289316842, -5.9289316842],
   'dipoles_elec': [-0.0, -0.0, 0.0, 0.0],
   'std_dev': [1.2174698850690313, 1.2174698850690313, 1.2174698850690313],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'revM06-L',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-7.5653, -7.5653, -7.5653],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, -0.0, 0.0],
   'quadrupoles_elec': [-5.6246265481, -5.6246265481, -5.6246265481],
   'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
   'std_dev': [1.185814756623057, 1.185814756623057, 1.185814756623057],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'Slater',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 1,
   'quadrupoles': [-8.0362, -8.0362, -8.0362],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, 0.0, 0.0],
   'quadrupoles_elec': [-5.9747298674, -5.9747298674, -5.9747298674],
   'dipoles_elec': [-0.0, -0.0, 0.0, 0.0],
   'std_dev': [1.2221630279344895, 1.2221630279344895, 1.2221630279344895],
   'spin_polarized': 0},
  {'name': 'Be',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVQZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-7.291763778065563,
    -7.292032784797728,
    -7.292032784797728],
   'quadrupoles_mp2': [-6.1426342629446555,
    -8.443919618941246,
    -8.443919618941246],
   'quadrupoles_ccsd': [-7.288132187157441,
    -7.308173188823205,
    -7.308173188823205],
   'quadrupoles_hf': [-7.5774, -8.0435, -7.5774],
   'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_hf': [0.0, 0.0, -0.0, 0.0],
   'spin_polarized': 1,
   'dipoles_elec_hf': [0.0, 0.0, -0.0, 0.0],
   'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec_hf': [-5.633622619800001,
    -5.9801572495,
    -5.633622619800001],
   'quadrupoles_elec_mp2': [-4.566907293911304,
    -6.277860026531581,
    -6.277860026531581],
   'quadrupoles_elec_ccsd': [-5.418558654111253,
    -5.43345867790671,
    -5.43345867790671],
   'quadrupoles_elec_ccsdt': [-5.4212586584248506,
    -5.42145865874306,
    -5.42145865874306],
   'std_dev_hf': [1.186762678445021, 1.2227180019836954, 1.186762678445021],
   'std_dev_mp2': [1.0685161783884352, 1.252782904829442, 1.252782904829442],
   'std_dev_ccsd': [1.1638898846230314,
    1.1654890258928556,
    1.1654890258928556],
   'std_dev_ccsdt': [1.164179824857918,
    1.1642012990397173,
    1.1642012990397173]},
  {'name': 'Be',
   'method': 'ccsdT',
   'basis': 'aug-cc-pcVTZp',
   'method_type': 'wft',
   'quadrupoles_ccsdt': [-7.309854480917156,
    -7.310526997747569,
    -7.310526997747569],
   'quadrupoles_mp2': [-6.190181203147525,
    -8.450981045702394,
    -8.450981045702394],
   'quadrupoles_ccsd': [-7.305348618123525,
    -7.323035810876871,
    -7.323035810876871],
   'quadrupoles_hf': [-7.9957, -7.5817, -7.6276],
   'dipoles_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'dipoles_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_hf': [0.0, 0.0, -0.0, 0.0],
   'spin_polarized': 1,
   'dipoles_elec_hf': [0.0, 0.0, -0.0, 0.0],
   'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
   'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
   'quadrupoles_elec_hf': [-5.944619048900001,
    -5.6368195709,
    -5.670945165200001],
   'quadrupoles_elec_mp2': [-4.602257350372513,
    -6.283110034915679,
    -6.283110034915679],
   'quadrupoles_elec_ccsd': [-5.431358674556624,
    -5.444508695563304,
    -5.444508695563304],
   'quadrupoles_elec_ccsdt': [-5.434708679908845,
    -5.43520868070437,
    -5.43520868070437],
   'std_dev_hf': [1.2190794733014745, 1.1870993609319314, 1.1906873188625131],
   'std_dev_mp2': [1.0726436209632388, 1.2533066299708622, 1.2533066299708622],
   'std_dev_ccsd': [1.165263776421097, 1.166673550694806, 1.166673550694806],
   'std_dev_ccsdt': [1.1656230822942772,
    1.1656767005375428,
    1.1656767005375428]}],
 'BeH': [{'name': 'BeH',
   'method': 'B3LYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-6.7621, -6.7621, -10.1264],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.3051, 0.3051],
   'quadrupoles_elec': [-5.027465821700001,
    -5.027465821700001,
    -33.277292978264164],
   'dipoles_elec': [-0.0, 0.0, -10.028570407470001, 10.028570407470001],
   'std_dev': [1.0027428206374756, 1.0027428206374756, 1.62251952806415],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'B3LYP5',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 4,
   'quadrupoles': [-6.7758, -6.7758, -10.1462],
   'quadrupoles_off_diag': [0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.3008, 0.3008],
   'quadrupoles_elec': [-5.037651456600001,
    -5.037651456600001,
    -33.29201382286416],
   'dipoles_elec': [0.0, -0.0, -10.030262157760001, 10.030262157760001],
   'std_dev': [1.0037580840620912, 1.0037580840620912, 1.6230084431194867],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'BLYP',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-6.8576, -6.8576, -10.1165],
   'quadrupoles_off_diag': [0.0, -0.0, -0.0],
   'dipoles': [-0.0, -0.0, 0.3047, 0.3047],
   'quadrupoles_elec': [-5.0984678752, -5.0984678752, -33.26993255596416],
   'dipoles_elec': [-0.0, -0.0, -10.02872777959, 10.02872777959],
   'std_dev': [1.0097987794803478, 1.0097987794803478, 1.6220269036326205],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'BPBE',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-6.7704, -6.7704, -10.0953],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [0.0, 0.0, 0.2743, 0.2743],
   'quadrupoles_elec': [-5.033636680800001,
    -5.033636680800001,
    -33.25417084356416],
   'dipoles_elec': [0.0, 0.0, -10.04068806071, 10.04068806071],
   'std_dev': [1.0033580298976035, 1.0033580298976035, 1.6180906956698868],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'mBEEF',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-6.6953, -6.6953, -10.1219],
   'quadrupoles_off_diag': [0.0, 0.0, 0.0],
   'dipoles': [-0.0, -0.0, 0.3205, 0.3205],
   'quadrupoles_elec': [-4.9778015581, -4.9778015581, -33.27394733176416],
   'dipoles_elec': [-0.0, -0.0, -10.02251158085, 10.02251158085],
   'std_dev': [0.9977776864712901, 0.9977776864712901, 1.6238103124509151],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'mPW91',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 2,
   'quadrupoles': [-6.8165, -6.8165, -10.1366],
   'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
   'dipoles': [0.0, -0.0, 0.2666, 0.2666],
   'quadrupoles_elec': [-5.0679109705, -5.0679109705, -33.28487644366416],
   'dipoles_elec': [0.0, -0.0, -10.043717474020001, 10.043717474020001],
   'std_dev': [1.0067681928328884, 1.0067681928328884, 1.6192358879469795],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'TPSS',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',
   'method_level': 3,
   'quadrupoles': [-6.7357, -6.7357, -10.2449],
   'quadrupoles_off_diag': [0.0, -0.0, 0.0],
   'dipoles': [-0.0, 0.0, 0.1885, 0.1885],
   'quadrupoles_elec': [-5.0078380289, -5.0078380289, -33.36539500276416],
   'dipoles_elec': [-0.0, 0.0, -10.07444438045, 10.07444438045],
   'std_dev': [1.0007834959570427, 1.0007834959570427, 1.6165710060376588],
   'spin_polarized': 1},
  {'name': 'BeH',
   'method': 'wB97X-V',
   'basis': 'aug-pc-4p',
   'method_type': 'dft',

In [5]:
def search(key, value, molecule):
    result = []
    for d in data[molecule]:
        if d[key] == value:
            result.append(d)
    return result

In [6]:
def load():
    global data
    with open('output.json') as f:
        data = json.load(f)

In [7]:
def save(data):
    with open("output.json", 'w') as outfile:
        json.dump(data, outfile)
    result = subprocess.run(['sh', 'commit.sh'], stdout=subprocess.PIPE)
    print(result.stdout)
    print('File saved!')

In [8]:
def save_as(data, name):
    with open(name, 'w') as outfile:
        json.dump(data, outfile)
    print('File saved as {0}!'.format(name))

In [9]:
def retrieve(molecule, method, basis):
    d = data[molecule]
    for m in d:
        if m['method'] == method and m['basis'] == basis:
            return m
    return {}

In [10]:
def get_dft_species():
    result = []
    for v in data.values():
        for d in v:
            if d['method_type'] == 'dft':
                result.append(d['name'])
                break
    return result
def get_wft_species():
    result = []
    for v in data.values():
        for d in v:
            if d['method_type'] == 'wft':
                result.append(d['name'])
                break
    return result

In [16]:
def get_functionals():
    functionals = []
    for v in data.values():
        for n in v:
            if n['method_type'] == 'dft':
                functionals.append(n['method'])
    functionals = np.unique(functionals)
    return functionals

In [11]:
def delete(molecule, method, basis):
    for c, d in enumerate(data[molecule]):
        if d.get('method') == method and d.get('basis') == basis:
            data[molecule].pop(c)
    return

def pop(molecule, method, basis, key):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d.pop(key, None)
    return

def modify(molecule, method, basis, old, new):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d[old] = new
    return

def add(molecule, method, basis, key, value):
    for d in data[molecule]:
        if d.get('method') == method and d.get('basis') == basis:
            d[key] = value

In [12]:
from pymatgen.core.periodic_table import Element

In [13]:
def count_e(name):
    if name == 'CH2-t':
        return 8
    l = [a for a in re.split(r'([A-Z][a-z]*)', name) if a]
    c = 0
    e = 0
    prev = ''
    while c < len(l):
        if l[c].isnumeric():
            e -= Element(prev).Z
            e += Element(prev).Z * int(l[c])
        else:
            e += Element(l[c]).Z
            prev = l[c]
        c += 1
    return e

In [14]:
def get_leq20():
    leq_20 = []
    for k in data.keys():
        if count_e(k) <= 20:
            if data[k][0]['method_type'] == 'dft':
                leq_20.append(data[k][0])
    return leq_20

In [29]:
#find electron count less than 20:
leq_20 = get_leq20()

In [30]:
leq_20

[{'name': 'Ar',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-11.7543, -11.7543, -11.7543],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-15.8099292555267,
   -15.8099292555267,
   -15.8099292555267],
  'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
  'std_dev': [0.9371922978155639, 0.9371922978155639, 0.9371922978155639],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.5237, -7.5237, -7.5237],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.1196298154553,
   -10.1196298154553,
   -10.1196298154553],
  'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
  'std_dev': [1.5905682801639875, 1.5905682801639875, 1.5905682801639875],
  'spin_polarized': 0},
 {'name': 'BeH',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.7621, -6.7621, -10.1264],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.3051, 0.3051],
  'quadrupoles_elec': [-9.0952521731449, -9.0952521731449, -20.8306479857616],
  'dipoles_elec': [-0.0, 0.0, -5.25036441547, 5.25036441547],
  'std_dev': [1.3487217780658025, 1.3487217780658025, 1.75027898843098],
  'spin_polarized': 1},
 {'name': 'BeH2',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.7659, -6.7659, -11.9572],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-9.1003633010871, -9.1003633010871, -19.6015105069668],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.231554796526671, 1.231554796526671, 1.8074618717493878],
  'spin_polarized': 0},
 {'name': 'BF',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.8268, -10.8268, -12.6137],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 1.0097, 1.0097],
  'quadrupoles_elec': [-14.5624105275292,
   -14.5624105275292,
   -31.411171680665298],
  'dipoles_elec': [-0.0, -0.0, -11.00485342609, 11.00485342609],
  'std_dev': [1.0198883176788527, 1.0198883176788527, 1.275054229738255],
  'spin_polarized': 0},
 {'name': 'BH2',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8136, -9.5373, -8.4481],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.4878, -0.0, 0.4878],
  'quadrupoles_elec': [-9.1645214070984, -13.3062316113537, -13.6699309390789],
  'dipoles_elec': [0.0, -0.7860846996599999, -0.0, 0.7860846996599999],
  'std_dev': [1.144210358225794, 1.3741468011500613, 1.397443121207898],
  'spin_polarized': 1},
 {'name': 'BH2F',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0907, -12.8078, -14.0274],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.6118, 0.6118],
  'quadrupoles_elec': [-14.9173649127783,
   -19.4736982458182,
   -35.06719891853061],
  'dipoles_elec': [-0.0, -0.0, -10.968200657539999, 10.968200657539999],
  'std_dev': [0.9655751172480802, 1.1032253352618573, 1.3121632857262564],
  'spin_polarized': 0},
 {'name': 'BH3',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-9.3862, -9.3862, -7.2026],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec': [-14.749027743967801,
   -14.7489050239678,
   -9.687739504339401],
  'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
  'std_dev': [1.357802808951276, 1.3577971601074939, 1.1004396567020043],
  'spin_polarized': 0},
 {'name': 'BO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.5253, -10.5253, -13.6658],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.1838, 2.1838],
  'quadrupoles_elec': [-14.1568828763257,
   -14.1568828763257,
   -29.987523113820203],
  'dipoles_elec': [0.0, 0.0, -10.49517308914, 10.49517308914],
  'std_dev': [1.04354731109164, 1.04354731109164, 1.2864545616167182],
  'spin_polarized': 1},
 {'name': 'C2H',
  'method': 'B97M-rV',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-12.9131, -12.9131, -9.012],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, 0.7621, 0.7621],
  'quadrupoles_elec': [-17.3685542711639,
   -17.3685542711639,
   -22.095839175027997],
  'dipoles_elec': [0.0, 0.0, 6.55233323163, 6.55233323163],
  'std_dev': [1.1558731055973994, 1.1558731055973994, 1.2023469123408719],
  'spin_polarized': 1},
 {'name': 'C2H2',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-13.7879, -13.7879, -7.4406],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-18.545189724805102,
   -18.545189724805102,
   -19.8870525175614],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.150937187215119, 1.150937187215119, 1.191848879369522],
  'spin_polarized': 0},
 {'name': 'C2H3',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.648, -11.7986, -15.0047],
  'quadrupoles_off_diag': [-1.1888, -0.0, 0.0],
  'dipoles': [-0.6115, -0.3728, -0.0, 0.7162],
  'quadrupoles_elec': [-19.224254985512, -26.1068616070634, -20.1818266932443],
  'dipoles_elec': [-0.24018262845000007,
   -0.1460708158400001,
   -0.0,
   0.2811127500653679],
  'std_dev': [1.1319720002184406, 1.3192280359238897, 1.1599375469752469],
  'spin_polarized': 1},
 {'name': 'CH2BH',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-16.2715, -11.8421, -11.7112],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, -0.509, 0.509],
  'quadrupoles_elec': [-21.885715345133498,
   -17.6109017916649,
   -27.5462574443928],
  'dipoles_elec': [0.0, 0.0, -0.2000560227000007, 0.2000560227000007],
  'std_dev': [1.2503061152354848, 1.1215710216243522, 1.4026352417773915],
  'spin_polarized': 0},
 {'name': 'CH2F',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.7679, -11.9532, -10.9089],
  'quadrupoles_off_diag': [0.4934, -0.0, 0.0],
  'dipoles': [0.4286, 1.0942, 0.0, 1.1752],
  'quadrupoles_elec': [-17.278060732425097,
   -25.2723608622908,
   -16.4679713117541],
  'dipoles_elec': [0.16912422658, 0.4303914342599994, 0.0, 0.4624281465272876],
  'std_dev': [1.0080959980774788, 1.2190030782357777, 0.9842277149161492],
  'spin_polarized': 1},
 {'name': 'CH2NH',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.8913, -13.7771, -13.007],
  'quadrupoles_off_diag': [0.0, 2.1021, -0.0],
  'dipoles': [-1.3146, -0.0, 1.4334, 1.9449],
  'quadrupoles_elec': [-18.5868675381797, -18.5306633611799, -26.633103392683],
  'dipoles_elec': [-0.51770347238,
   -0.0,
   0.5635429920199994,
   0.7652434835849061],
  'std_dev': [1.0773264501431181, 1.0761814252595814, 1.2897009003711886],
  'spin_polarized': 0},
 {'name': 'CH2-t',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-8.4761, -5.9565, -7.9487],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.5897, 0.5897],
  'quadrupoles_elec': [-11.400639881810902,
   -10.028528329398501,
   -10.9444040847803],
  'dipoles_elec': [-0.0, -0.0, -0.23200584791, 0.23200584791],
  'std_dev': [1.1937671402858945, 1.119627635053196, 1.169277327326437],
  'spin_polarized': 1},
 {'name': 'CH3',
  'method': 'B3LYP5',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-7.3267, -7.3268, -9.1826],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-11.601019682662299,
   -11.600999406029201,
   -12.350906168959401],
  'dipoles_elec': [-0.0, 0.0, -0.0, 0.0],
  'std_dev': [1.1353423214883156, 1.1353413292940782, 1.1714618677798077],
  'spin_polarized': 1},
 {'name': 'CH3BH2',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-13.837, -16.559, -15.7637],
  'quadrupoles_off_diag': [-0.1929, -0.0, -0.0],
  'dipoles': [0.0997, -0.7191, 0.0, 0.726],
  'quadrupoles_elec': [-20.101880243046285,
   -36.791836181041774,
   -24.88929674448142],
  'dipoles_elec': [0.048500556209999914,
   -0.28182743123000026,
   6.819000000213293e-07,
   0.2859702868251261],
  'std_dev': [1.1208739119557907, 1.51630455409339, 1.2472293480070484],
  'spin_polarized': 0},
 {'name': 'CH3O',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-13.1049, -11.732, -13.7156],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.288],
  'dipoles': [0.0, 0.1715, -2.1155, 2.1225],
  'quadrupoles_elec': [-19.2364674088781, -17.389879004708, -28.8138552505364],
  'dipoles_elec': [0.0,
   0.06747329645000001,
   -0.8323017996500006,
   0.8350322936476525],
  'std_dev': [1.06374663637757, 1.0113942386631662, 1.3009748979242945],
  'spin_polarized': 1},
 {'name': 'CH4',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-8.4815, -8.4815, -8.4815],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-12.983430103623501,
   -12.983430103623501,
   -12.983430103623501],
  'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
  'std_dev': [1.139448555382098, 1.139448555382098, 1.139448555382098],
  'spin_polarized': 0},
 {'name': 'CN',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-11.0789, -11.0789, -9.0071],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 1.3668, 1.3668],
  'quadrupoles_elec': [-14.9014935154841,
   -14.9014935154841,
   -20.3535442000499],
  'dipoles_elec': [0.0, -0.0, -6.493059465959999, 6.493059465959999],
  'std_dev': [1.0706394033288311, 1.0706394033288311, 1.147253611175817],
  'spin_polarized': 1},
 {'name': 'CO',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.3071, -10.3071, -12.222],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0872, 0.0872],
  'quadrupoles_elec': [-13.8633965297499,
   -13.8633965297499,
   -26.621683422518004],
  'dipoles_elec': [0.0, 0.0, -8.991292877840001, 8.991292877840001],
  'std_dev': [0.9951093453826318, 0.9951093453826318, 1.2202797862102968],
  'spin_polarized': 0},
 {'name': 'F2',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-9.8209, -9.8209, -8.9373],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-13.2094411598821,
   -13.2094411598821,
   -29.9621238999537],
  'dipoles_elec': [-0.0, 0.0, -12.707099999999999, 12.707099999999999],
  'std_dev': [0.8566550310455617, 0.8566550310455617, 1.0799060312760165],
  'spin_polarized': 0},
 {'name': 'H',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-1.4216, -1.4216, -1.4216],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-1.9120998638503999,
   -1.9120998638503999,
   -1.9120998638503999],
  'dipoles_elec': [0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.3827869914959425, 1.3827869914959425, 1.3827869914959425],
  'spin_polarized': 1},
 {'name': 'H2',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-2.1053, -2.1053, -1.514],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-2.8316993833457,
   -2.8316993833457,
   -2.5860549348659996],
  'dipoles_elec': [0.0, -0.0, -0.7414, 0.7414],
  'std_dev': [1.1898948237860563, 1.1898948237860563, 1.074992547617424],
  'spin_polarized': 0},
 {'name': 'H2CN',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-12.8266, -11.1734, -13.1315],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, -2.4665, 2.4665],
  'quadrupoles_elec': [-17.2522088587954,
   -16.7740584772046,
   -24.9968387844735],
  'dipoles_elec': [0.0, 0.0, -0.9705958349500005, 0.9705958349500005],
  'std_dev': [1.0724491863268053, 1.0574831275944658, 1.2892901156015708],
  'spin_polarized': 1},
 {'name': 'H2O',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.8655, -4.5551, -6.5422],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, -1.7955, 1.7955],
  'quadrupoles_elec': [-10.5793623235195,
   -7.2734665456619005,
   -9.3498508693318],
  'dipoles_elec': [-0.0, 0.0, -0.7064041036500001, 0.7064041036500001],
  'std_dev': [1.0285602716185134, 0.8528462080388176, 0.9643624937525538],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0978, -11.0978, -19.9502],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-14.926914651828199,
   -14.926914651828199,
   -78.41511870328381],
  'dipoles_elec': [-0.0, 0.0, -25.775214040650003, 25.775214040650003],
  'std_dev': [1.0325735757883308, 1.0325735757883308, 1.4871044372089655],
  'spin_polarized': 0},
 {'name': 'HCN',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.8099, -11.8099, -12.8787],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, 2.9427, 2.9427],
  'quadrupoles_elec': [-15.884713127523101,
   -15.884713127523101,
   -27.8087331129503],
  'dipoles_elec': [0.0, 0.0, 8.185747343809998, 8.185747343809998],
  'std_dev': [1.0651865405888539, 1.0651865405888539, 1.2823682730708177],
  'spin_polarized': 0},
 {'name': 'HCO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.3297, -13.407, -11.0841],
  'quadrupoles_off_diag': [0.5232, -0.0, -0.0],
  'dipoles': [1.4642, -0.52, -0.0, 1.5538],
  'quadrupoles_elec': [-19.1890840396693,
   -26.730652720282997,
   -14.908487690562898],
  'dipoles_elec': [4.21526064526, -8.546183756, -0.0, 9.52920138830091],
  'std_dev': [1.0955827232574793, 1.2072420985460606, 0.996944922937501],
  'spin_polarized': 1},
 {'name': 'He',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-1.125, -1.125, -1.125],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-1.513162877625, -1.513162877625, -1.513162877625],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [0.8698168995900804, 0.8698168995900804, 0.8698168995900804],
  'spin_polarized': 0},
 {'name': 'HF',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-5.9524, -5.9524, -3.5354],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 1.7456, 1.7456],
  'quadrupoles_elec': [-8.0061784113556, -8.0061784113556, -5.5957542733826],
  'dipoles_elec': [0.0, 0.0, -0.2300280683199999, 0.2300280683199999],
  'std_dev': [0.8947725080351765, 0.8947725080351765, 0.7476939870134771],
  'spin_polarized': 0},
 {'name': 'HNC',
  'method': 'B3LYP5',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-12.1493, -12.1493, -10.5746],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 3.0058, 3.0058],
  'quadrupoles_elec': [-16.3412175547817,
   -16.3412175547817,
   -20.8317822962074],
  'dipoles_elec': [-0.0, 0.0, 1.1825727957400007, 1.1825727957400007],
  'std_dev': [1.0803841100930494, 1.0803841100930494, 1.2169015390587974],
  'spin_polarized': 0},
 {'name': 'HNO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.806, -11.2922, -12.1186],
  'quadrupoles_off_diag': [0.0, 0.0, -1.2948],
  'dipoles': [0.0, -1.2816, 0.7755, 1.4979],
  'quadrupoles_elec': [-14.534433827213999,
   -16.1957700370818,
   -22.6618420311434],
  'dipoles_elec': [0.0,
   -0.50442027248,
   0.3050051976500002,
   0.5894641480890191],
  'std_dev': [0.9531013137127001, 1.0056051520376998, 1.1899587117438493],
  'spin_polarized': 1},
 {'name': 'HO2',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.0634, -11.1131, -11.1327],
  'quadrupoles_off_diag': [1.6368, 0.0, 0.0],
  'dipoles': [-1.6687, -1.4033, -0.0, 2.1803],
  'quadrupoles_elec': [-14.3682973546146,
   -22.827771746963897,
   -14.9738563268763],
  'dipoles_elec': [-0.6560171416100001,
   -0.5521007399900002,
   -0.0,
   0.8574227179073697],
  'std_dev': [0.9185340670397977, 1.15834165028863, 0.9385174894755809],
  'spin_polarized': 1},
 {'name': 'LiBH4',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-14.1406, -14.1408, -4.5924],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0001, -6.0899, 6.0899],
  'quadrupoles_elec': [-20.9706856798614,
   -20.9708484365952,
   -16.4736666015156],
  'dipoles_elec': [0.0,
   -0.00013934302999998898,
   -2.3959511839700007,
   2.3959511880219364],
  'std_dev': [1.3219520187920777, 1.3219571486681267, 1.1545303793408694],
  'spin_polarized': 0},
 {'name': 'Mg',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-12.6256, -12.6256, -12.6256],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-16.9818570913264,
   -16.9818570913264,
   -16.9818570913264],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.1896027730341474, 1.1896027730341474, 1.1896027730341474],
  'spin_polarized': 0},
 {'name': 'N',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-5.5748, -5.5748, -5.5748],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-7.498293697941199,
   -7.498293697941199,
   -7.498293697941199],
  'dipoles_elec': [0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.0349805862872983, 1.0349805862872983, 1.0349805862872983],
  'spin_polarized': 1},
 {'name': 'N2',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-10.3096, -10.3096, -11.8471],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-13.866759113922399,
   -13.866759113922399,
   -20.151288540009897],
  'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
  'std_dev': [0.9952300205739374, 0.9952300205739374, 1.1997407023427396],
  'spin_polarized': 0},
 {'name': 'N2H2',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-11.3241, -12.364, -12.6142],
  'quadrupoles_off_diag': [-0.0, 1.836, 0.0],
  'dipoles': [1.0445, -0.0, 2.6466, 2.8452],
  'quadrupoles_elec': [-28.231719421032725,
   -16.629996283516,
   -19.6021075435635],
  'dipoles_elec': [-9.61474216605,
   -0.0,
   2.9303808381800005,
   10.051387902990928],
  'std_dev': [1.1846416979026952, 1.0194973112861798, 1.0915989362660632],
  'spin_polarized': 0},
 {'name': 'N2H4',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.7179, -14.2517, -14.5796],
  'quadrupoles_off_diag': [1.9827, 0.0, -0.0],
  'dipoles': [-0.0, 0.0, 2.6368, 2.6368],
  'quadrupoles_elec': [-18.0280594099751,
   -30.512060780487303,
   -20.932099840552397],

In [31]:
asymmetrics = []
symmetrics = []
for m in leq_20:
    if abs(m['quadrupoles'][0] - m['quadrupoles'][1]) > 0.001:
        asymmetrics.append(m)
    elif all([v == 0 for v in m['quadrupoles_off_diag']]):
        symmetrics.append(m)

In [32]:
[x['name'] for x in asymmetrics]

['BH2',
 'BH2F',
 'C2H3',
 'CH2BH',
 'CH2F',
 'CH2NH',
 'CH2-t',
 'CH3BH2',
 'CH3O',
 'H2CN',
 'H2O',
 'HCO',
 'HNO',
 'HO2',
 'N2H2',
 'N2H4',
 'NH2',
 'NH2F',
 'NH2OH',
 'OF',
 'OH',
 'SH']

In [33]:
[x['name'] for x in leq_20]

['Ar',
 'Be',
 'BeH',
 'BeH2',
 'BF',
 'BH2',
 'BH2F',
 'BH3',
 'BO',
 'C2H',
 'C2H2',
 'C2H3',
 'CH2BH',
 'CH2F',
 'CH2NH',
 'CH2-t',
 'CH3',
 'CH3BH2',
 'CH3O',
 'CH4',
 'CN',
 'CO',
 'F2',
 'H',
 'H2',
 'H2CN',
 'H2O',
 'HBO',
 'HCN',
 'HCO',
 'He',
 'HF',
 'HNC',
 'HNO',
 'HO2',
 'LiBH4',
 'Mg',
 'N',
 'N2',
 'N2H2',
 'N2H4',
 'Na',
 'Ne',
 'NH2',
 'NH2F',
 'NH2OH',
 'NH3',
 'NH3O',
 'O2',
 'OF',
 'OH',
 'P',
 'SH',
 'LiH']

In [34]:
[x['name'] for x in symmetrics]

['Ar',
 'Be',
 'BeH',
 'BeH2',
 'BF',
 'BH3',
 'BO',
 'C2H',
 'C2H2',
 'CH3',
 'CH4',
 'CN',
 'CO',
 'F2',
 'H',
 'H2',
 'HBO',
 'HCN',
 'He',
 'HF',
 'HNC',
 'LiBH4',
 'Mg',
 'N',
 'N2',
 'Na',
 'Ne',
 'NH3',
 'NH3O',
 'O2',
 'P',
 'LiH']

In [17]:
functionals_sorted = sorted(sorted(get_functionals(), key=lambda v: v.upper()), key=lambda x: ladder[x])
functionals_sorted

['Slater',
 'SPW92',
 'B97-D3',
 'BLYP',
 'BPBE',
 'mPW91',
 'PBE',
 'B97M-rV',
 'B97M-V',
 'M06-L',
 'mBEEF',
 'MGGA_MS2',
 'MN15-L',
 'revM06-L',
 'SCAN',
 'TPSS',
 'B3LYP',
 'B3LYP5',
 'M06-2X',
 'PBE0',
 'M08-HX',
 'MN15',
 'SCAN0',
 'CAM-B3LYP',
 'wB97X-D',
 'wB97X-V',
 'wB97M-V']

In [18]:
def make_dft_table(key, domain=data.keys()):
    """
    Makes a table of molecules in DOMAIN of desired KEY.
    """
    values = []
    index = pd.MultiIndex.from_product([domain], names=['molecule'])
    columns = pd.MultiIndex.from_product([functionals_sorted, ['XX','YY','ZZ']], names=['method', 'component'])
    for d in domain:
        value = data[d]
        temp = [[0, 0, 0] for i in range(len(functionals_sorted))]
        for i in value:
            if i['method_type'] == 'dft':
                method = i['method']
                ind = functionals_sorted.index(method)
                temp[ind] = i[key]
        values.append(np.ravel(temp).tolist())
    df = pd.DataFrame(values, index=index, columns=columns)
    return df

In [19]:
quadrupoles_table = make_dft_table('quadrupoles')

In [20]:
make_dft_table('std_dev').loc['He']

method       Slater                        SPW92                      B97-D3  \
component        XX        YY        ZZ       XX       YY       ZZ        XX
molecule
He         0.665192  0.665192  0.665192  0.65497  0.65497  0.65497  0.641059

method                             BLYP  ... CAM-B3LYP   wB97X-D            \
component        YY        ZZ        XX  ...        ZZ        XX        YY
molecule                                 ...
He         0.641059  0.641059  0.647148  ...  0.645538  0.635556  0.635556

method                wB97X-V                       wB97M-V            \
component        ZZ        XX        YY        ZZ        XX        YY
molecule
He         0.635556  0.642392  0.642392  0.642392  0.643086  0.643086

method
component        ZZ
molecule
He         0.643086

[1 rows x 81 columns]

In [21]:
make_dft_table('std_dev').loc['BeH2']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
BeH2       0.947195  0.947195  1.893168   0.0  0.0  0.0  0.911522  0.911522

method                  BLYP  ... CAM-B3LYP wB97X-D           wB97X-V       \
component       ZZ        XX  ...        ZZ      XX   YY   ZZ      XX   YY
molecule                      ...
BeH2       1.89122  0.915632  ...  1.891089     0.0  0.0  0.0     0.0  0.0

method         wB97M-V
component   ZZ      XX   YY   ZZ
molecule
BeH2       0.0     0.0  0.0  0.0

[1 rows x 81 columns]

In [22]:
make_dft_table('std_dev').loc['Ne']

method      Slater                      SPW92                      B97-D3  \
component       XX       YY       ZZ       XX       YY       ZZ        XX
molecule
Ne         0.57839  0.57839  0.57839  0.57307  0.57307  0.57307  0.567968

method                             BLYP  ... CAM-B3LYP   wB97X-D            \
component        YY        ZZ        XX  ...        ZZ        XX        YY
molecule                                 ...
Ne         0.567968  0.567968  0.573919  ...   0.57041  0.565304  0.565304

method                wB97X-V                       wB97M-V            \
component        ZZ        XX        YY        ZZ        XX        YY
molecule
Ne         0.565304  0.569412  0.569412  0.569412  0.569934  0.569934

method
component        ZZ
molecule
Ne         0.569934

[1 rows x 81 columns]

In [23]:
make_dft_table('std_dev').loc['Be']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
Be         1.222163  1.222163  1.222163   0.0  0.0  0.0  1.188805  1.188805

method              BLYP  ... CAM-B3LYP wB97X-D           wB97X-V            \
component        ZZ   XX  ...        ZZ      XX   YY   ZZ      XX   YY   ZZ
molecule                  ...
Be         1.188805  0.0  ...  1.183775     0.0  0.0  0.0     0.0  0.0  0.0

method    wB97M-V
component      XX   YY   ZZ
molecule
Be            0.0  0.0  0.0

[1 rows x 81 columns]

In [24]:
make_dft_table('std_dev').loc['N']

method       Slater                     SPW92              B97-D3            \
component        XX        YY        ZZ    XX   YY   ZZ        XX        YY
molecule
N          0.784452  0.784452  0.784452   0.0  0.0  0.0  0.765283  0.765283

method                   BLYP  ... CAM-B3LYP   wB97X-D                      \
component        ZZ        XX  ...        ZZ        XX        YY        ZZ
molecule                       ...
N          0.765283  0.775054  ...  0.770291  0.764623  0.764623  0.764623

method      wB97X-V                       wB97M-V
component        XX        YY        ZZ        XX        YY        ZZ
molecule
N          0.770153  0.770153  0.770153  0.773229  0.773229  0.773229

[1 rows x 81 columns]

In [25]:
wft_method = ['hf', 'MP2', 'CCSD', 'CCSD\(T\)']
wft_basis = ['aug-cc-pcV5Zp', 'aug-cc-pcVQZp', 'aug-cc-pcVTZp', 'CBS']

In [26]:
def make_table_wft_extrap(domain=data.keys()):
    """
    Makes a table of DOMAIN of wft method of desired KEY.
    """
    values = np.array([])
    index = pd.MultiIndex.from_product([domain, ['5Z', 'QZ', 'TZ', 'CBS']], names=['molecule', 'basis'])
    columns = pd.MultiIndex.from_product([wft_method, ['XX','YY','ZZ']], names=['method', 'component'])
    for d in domain:
        m_name = d
        for b in wft_basis:
            temp = [[0, 0, 0] for k in range(len(wft_method))]
            info = search('basis', b, m_name)
            if info != []:
                temp[0] = info[0]['std_dev_hf']
                temp[1] = info[0]['std_dev_mp2']
                temp[2] = info[0]['std_dev_ccsd']
                temp[3] = info[0]['std_dev_ccsdt']
            temp = np.ravel(temp)
            values = np.vstack((values, temp)) if values.size else temp
    df = pd.DataFrame(values, index=index, columns=columns)
    return df

In [44]:
wft_table = make_table_wft_extrap(get_wft_species())

KeyError: 'std_dev_hf'

In [28]:
wft_table.loc['HBO']

method           hf                           MP2                      \
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
QZ         0.761014  0.761014  1.596252  0.766903  0.766903  1.598887
TZ         0.761262  0.761262  1.596361  0.768257  0.768257  1.599782
CBS        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

method         CCSD                     CCSD\(T\)
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
QZ         0.763161  0.763161  1.596700  0.764286  0.764286  1.597599
TZ         0.764681  0.764681  1.597664  0.765833  0.765833  1.598608
CBS        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

In [44]:
wft_table[wft_table.index.get_level_values('basis') == '5Z']

method               hf                          MP2                        \
component            XX       YY       ZZ         XX         YY         ZZ
molecule basis
AlF      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
Ar       5Z    -11.6741 -11.6741 -11.6741 -11.656129 -11.656129 -11.656129
Be       5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
BeH      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
BeH2     5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000
...                 ...      ...      ...        ...        ...        ...
HCl      5Z    -14.0726 -14.0726 -10.2180 -14.012628 -14.012628 -10.243776
NH       5Z     -6.2690  -6.2690  -5.4578  -6.372837  -5.470655   0.836409
PH       5Z    -14.4015 -14.4015 -15.4878 -14.363615 -15.049447  -0.236188
SiO      5Z    -16.0826 -16.0826 -25.3663 -16.569470 -16.569470 -23.618388
LiH      5Z      0.0000   0.0000   0.0000   0.000000   0.000000   0.000000

method               CCSD                        CCSD\(T\)             \
component              XX         YY         ZZ         XX         YY
molecule basis
AlF      5Z      0.000000   0.000000   0.000000   0.000000   0.000000
Ar       5Z    -11.624722 -11.624722 -11.624722 -11.638576 -11.638576
Be       5Z      0.000000   0.000000   0.000000   0.000000   0.000000
BeH      5Z      0.000000   0.000000   0.000000   0.000000   0.000000
BeH2     5Z      0.000000   0.000000   0.000000   0.000000   0.000000
...                   ...        ...        ...        ...        ...
HCl      5Z    -13.947865 -13.947865 -10.236849 -13.963534 -13.963534
NH       5Z     -6.347012  -5.482626   0.822085  -6.365237  -5.506568
PH       5Z    -14.302954 -15.020933  -0.233700 -14.315261 -14.995915
SiO      5Z    -16.259103 -16.259103 -24.055255 -16.382039 -16.382039
LiH      5Z      0.000000   0.000000   0.000000   0.000000   0.000000

method
component              ZZ
molecule basis
AlF      5Z      0.000000
Ar       5Z    -11.638576
Be       5Z      0.000000
BeH      5Z      0.000000
BeH2     5Z      0.000000
...                   ...
HCl      5Z    -10.266440
NH       5Z      0.814889
PH       5Z     -0.229194
SiO      5Z    -23.702654
LiH      5Z      0.000000

[73 rows x 12 columns]

In [340]:
data['Be']

[{'name': 'Be',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.5237, -7.5237, -7.5237],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.1196298154553,
   -10.1196298154553,
   -10.1196298154553],
  'dipoles_elec': [0.0, 0.0, 0.0, 0.0],
  'std_dev': [1.5905682801639875, 1.5905682801639875, 1.5905682801639875],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-7.6035, -7.6035, -7.6035],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.2269635022415,
   -10.2269635022415,
   -10.2269635022415],
  'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.5989811992516907, 1.5989811992516907, 1.5989811992516907],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-7.5393, -7.5393, -7.5393],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.1406123406917,
   -10.1406123406917,
   -10.1406123406917],
  'dipoles_elec': [-0.0, 0.0, 0.0, 0.0],
  'std_dev': [1.5922164065141788, 1.5922164065141788, 1.5922164065141788],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-7.454, -7.454, -7.454],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, 0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.025880968726, -10.025880968726, -10.025880968726],
  'dipoles_elec': [0.0, 0.0, -0.0, 0.0],
  'std_dev': [1.583183578168211, 1.583183578168211, 1.583183578168211],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.4636, -7.4636, -7.4636],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.0387932919484,
   -10.0387932919484,
   -10.0387932919484],
  'dipoles_elec': [0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.584202740493495, 1.584202740493495, 1.584202740493495],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.4472, -7.4472, -7.4472],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.0167347397768,
   -10.0167347397768,
   -10.0167347397768],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.582461274390056, 1.582461274390056, 1.582461274390056],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-7.7815, -7.7815, -7.7815],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.4663794953235,
   -10.4663794953235,
   -10.4663794953235],
  'dipoles_elec': [-0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.6175892166526318, 1.6175892166526318, 1.6175892166526318],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.9746, -7.9746, -7.9746],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.7261054968074,
   -10.7261054968074,
   -10.7261054968074],
  'dipoles_elec': [-0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.6375366787348153, 1.6375366787348153, 1.6375366787348153],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.5653, -7.5653, -7.5653],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.0, 0.0],
  'quadrupoles_elec': [-10.1755832160857,
   -10.1755832160857,
   -10.1755832160857],
  'dipoles_elec': [0.0, -0.0, -0.0, 0.0],
  'std_dev': [1.5949594991790308, 1.5949594991790308, 1.5949594991790308],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-8.0362, -8.0362, -8.0362],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.0, 0.0],
  'quadrupoles_elec': [-10.808959570817798,
   -10.808959570817798,
   -10.808959570817798],
  'dipoles_elec': [-0.0, -0.0, 0.0, 0.0],
  'std_dev': [1.6438491088614093, 1.6438491088614093, 1.6438491088614093],
  'spin_polarized': 0},
 {'name': 'Be',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-7.291763778065563,
   -7.292032784797728,
   -7.292032784797728],
  'quadrupoles_mp2': [-6.1426342629446555,
   -8.443919618941246,
   -8.443919618941246],
  'quadrupoles_ccsd': [-7.288132187157441,
   -7.308173188823205,
   -7.308173188823205],
  'quadrupoles_hf': [-7.5774, -8.0435, -7.5774],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [0.0, 0.0, -0.0, 0.0],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, 0.0, -0.0, 0.0],
  'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
  'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
  'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec_hf': [-10.1918581234806,
   -10.8187783166015,
   -10.1918581234806],
  'quadrupoles_elec_mp2': [-8.26204990001356,
   -11.357356185805626,
   -11.357356185805626],
  'quadrupoles_elec_ccsd': [-9.802783175849367,
   -9.829738997850304,
   -9.829738997850304],
  'quadrupoles_elec_ccsdt': [-9.807667787892825,
   -9.808029611004775,
   -9.808029611004775],
  'std_dev_hf': [1.5962344849269954, 1.6445955670469183, 1.5962344849269954],
  'std_dev_mp2': [1.437189088117284, 1.6850338413371426, 1.6850338413371426],
  'std_dev_ccsd': [1.5654698316998452, 1.5676207288316188, 1.5676207288316188],
  'std_dev_ccsdt': [1.5658598107663426,
   1.5658886942408115,
   1.5658886942408115]},
 {'name': 'Be',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-7.309854480917156,
   -7.310526997747569,
   -7.310526997747569],
  'quadrupoles_mp2': [-6.190181203147525,
   -8.450981045702394,
   -8.450981045702394],
  'quadrupoles_ccsd': [-7.305348618123525,
   -7.323035810876871,
   -7.323035810876871],
  'quadrupoles_hf': [-7.9957, -7.5817, -7.6276],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [0.0, 0.0, -0.0, 0.0],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, 0.0, -0.0, 0.0],
  'dipoles_elec_mp2': [0.0, 0.0, 0.0, 0.0],
  'dipoles_elec_ccsd': [0.0, 0.0, 0.0, 0.0],
  'dipoles_elec_ccsdt': [0.0, 0.0, 0.0, 0.0],
  'quadrupoles_elec_hf': [-10.754485707223301,
   -10.197641768257299,
   -10.2593788136644],
  'quadrupoles_elec_mp2': [-8.32600213544435,
   -11.366854042550546,
   -11.366854042550546],
  'quadrupoles_elec_ccsd': [-9.825939855158765,
   -9.849729724922108,
   -9.849729724922108],
  'quadrupoles_elec_ccsdt': [-9.832000392324094,
   -9.832904950103968,
   -9.832904950103968],
  'std_dev_hf': [1.6397016273718292, 1.5966873338460241, 1.6015132542118096],
  'std_dev_mp2': [1.4427406329139993, 1.6857382687231244, 1.6857382687231244],
  'std_dev_ccsd': [1.567317760950118, 1.5692139532997171, 1.5692139532997171],
  'std_dev_ccsdt': [1.5678010390610868,
   1.5678731573459608,
   1.5678731573459608]}]

In [341]:
save(data)

File saved!

In [45]:
data['BeH']

[{'name': 'BeH',
  'method': 'B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.7621, -6.7621, -10.1264],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.3051, 0.3051],
  'quadrupoles_elec': [-9.0952521731449, -9.0952521731449, -20.8306479857616],
  'dipoles_elec': [-0.0, 0.0, -5.25036441547, 5.25036441547],
  'std_dev': [1.3487217780658025, 1.3487217780658025, 1.75027898843098],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'B3LYP5',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.7758, -6.7758, -10.1462],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.3008, 0.3008],
  'quadrupoles_elec': [-9.1136791344102, -9.1136791344102, -20.8572796524078],
  'dipoles_elec': [0.0, -0.0, -5.25205616576, 5.25205616576],
  'std_dev': [1.3500873404643272, 1.3500873404643272, 1.7515970346371494],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8576, -6.8576, -10.1165],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.3047, 0.3047],
  'quadrupoles_elec': [-9.2237028885344, -9.2237028885344, -20.8173321524385],
  'dipoles_elec': [-0.0, -0.0, -5.25052178759, 5.25052178759],
  'std_dev': [1.358212272697784, 1.358212272697784, 1.74949914798762],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'BPBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.7704, -6.7704, -10.0953],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.2743, 0.2743],
  'quadrupoles_elec': [-9.106415952597601,
   -9.106415952597601,
   -20.7888174386557],
  'dipoles_elec': [0.0, 0.0, -5.26248206871, 5.26248206871],
  'std_dev': [1.3495492545733632, 1.3495492545733632, 1.7464291530982208],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'mBEEF',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.6953, -6.6953, -10.1219],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.3205, 0.3205],
  'quadrupoles_elec': [-9.005403924055699,
   -9.005403924055699,
   -20.8245953342511],
  'dipoles_elec': [-0.0, -0.0, -5.24430558885, 5.24430558885],
  'std_dev': [1.3420435107742, 1.3420435107742, 1.7506597106463855],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'mPW91',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8165, -6.8165, -10.1366],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.2666, 0.2666],
  'quadrupoles_elec': [-9.168422004738499,
   -9.168422004738499,
   -20.8443673291854],
  'dipoles_elec': [0.0, -0.0, -5.26551148202, 5.26551148202],
  'std_dev': [1.3541360348752631, 1.3541360348752631, 1.7492424129164321],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.7357, -6.7357, -10.2449],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.1885, 0.1885],
  'quadrupoles_elec': [-9.0597432842833, -9.0597432842833, -20.9900344755381],
  'dipoles_elec': [-0.0, 0.0, -5.29623838845, 5.29623838845],
  'std_dev': [1.346086422506616, 1.346086422506616, 1.7538532585185003],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'wB97X-V',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.7379, -6.7379, -10.52],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, 0.2334, 0.2334],
  'quadrupoles_elec': [-9.0627023583551, -9.0627023583551, -21.36005323788],
  'dipoles_elec': [-0.0, 0.0, -5.27857336798, 5.27857336798],
  'std_dev': [1.3463062325009938, 1.3463062325009938, 1.776929141955326],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-6.8874, -6.8874, -10.6129],
  'quadrupoles_off_diag': [-0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, 0.0744, 0.0744],
  'quadrupoles_elec': [-9.2637848918706, -9.2637848918706, -21.4850068657301],
  'dipoles_elec': [0.0, 0.0, -5.3411287856800005, 5.3411287856800005],
  'std_dev': [1.3611601589725288, 1.3611601589725288, 1.7764839163181971],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-6.7598, -6.7598, -10.2436],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, 0.2799, 0.2799],
  'quadrupoles_elec': [-9.0921585957062,
   -9.0921585957062,
   -20.988285931768402],
  'dipoles_elec': [-0.0, -0.0, -5.2602788590300005, 5.2602788590300005],
  'std_dev': [1.348492387498439, 1.348492387498439, 1.758077313249722],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-6.8179, -6.8179, -10.1027],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.2513, 0.2513],
  'quadrupoles_elec': [-9.1703050518751, -9.1703050518751, -20.7987706878063],
  'dipoles_elec': [-0.0, -0.0, -5.27153096561, 5.27153096561],
  'std_dev': [1.3542750866699942, 1.3542750866699942, 1.7459073826253944],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.5112, -6.5112, -10.4318],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.0918, 0.0918],
  'quadrupoles_elec': [-8.7577832255928,
   -8.7577832255928,
   -21.241421268274202],
  'dipoles_elec': [0.0, -0.0, -5.33428309846, 5.33428309846],
  'std_dev': [1.3234638813048734, 1.3234638813048734, 1.763547903141335],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.6589, -6.6589, -10.1564],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, 0.2607, 0.2607],
  'quadrupoles_elec': [-8.9564446985041, -8.9564446985041, -20.8709989958316],
  'dipoles_elec': [0.0, -0.0, -5.26783272079, 5.26783272079],
  'std_dev': [1.3383904287243016, 1.3383904287243016, 1.7504848860236666],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-7.1747, -7.1747, -9.8023],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.5052, 0.5052],
  'quadrupoles_elec': [-9.650213064974299,
   -9.650213064974299,
   -20.3947225736387],
  'dipoles_elec': [0.0, -0.0, -5.17163901244, 5.17163901244],
  'std_dev': [1.3892597356127687, 1.3892597356127687, 1.7346787920903641],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-7.0314, -7.0314, -10.5284],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.4055, 0.4055],
  'quadrupoles_elec': [-9.4574697402066,
   -9.4574697402066,
   -21.371351520699598],
  'dipoles_elec': [0.0, -0.0, -5.21086401335, 5.21086401335],
  'std_dev': [1.3753159448073449, 1.3753159448073449, 1.785538057145486],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-6.7011, -6.7011, -10.5707],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, 0.2853, 0.2853],
  'quadrupoles_elec': [-9.0132051193359, -9.0132051193359, -21.4282464448983],
  'dipoles_elec': [0.0, -0.0, -5.25815433541, 5.25815433541],
  'std_dev': [1.342624677215185, 1.342624677215185, 1.783177447249718],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-7.269, -7.269, -11.0095],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, 0.1611, 0.1611],
  'quadrupoles_elec': [-9.777049739961, -9.777049739961, -22.0184472188555],
  'dipoles_elec': [-0.0, -0.0, -5.3070183786700005, 5.3070183786700005],
  'std_dev': [1.398359734829418, 1.398359734829418, 1.8102794482922941],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.647223643879551,
   -6.647223643879551,
   -10.375522470984151],
  'quadrupoles_mp2': [-6.596583126244836,
   -6.596583126244836,
   -10.484066688069824],
  'quadrupoles_ccsd': [-6.635387347604554,
   -6.635387347604554,
   -10.393613173835746],
  'quadrupoles_hf': [-6.5797, -6.5797, -10.7231],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [0.0, 0.0, 0.2749, 0.2749],
  'spin_polarized': 1},
 {'name': 'BeH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-6.669752957835762,
   -6.669752957835762,
   -10.425624975154536],
  'quadrupoles_mp2': [-6.617094889697863,
   -6.617094889697863,
   -10.537061014628902],
  'quadrupoles_ccsd': [-6.657983913225887,
   -6.657983913225887,
   -10.441294617392751],
  'quadrupoles_hf': [-6.5849, -6.5849, -10.7454],
  'dipoles_ccsdt': [0, 0, 0, 0],
  'dipoles_mp2': [0, 0, 0, 0],
  'dipoles_ccsd': [0, 0, 0, 0],
  'dipoles_hf': [-0.0, -0.0, 0.2712, 0.2712],
  'spin_polarized': 1}]

In [162]:
quadrupoles_table.loc['CO', 'Slater']

component       XX       YY       ZZ
molecule
CO        -10.6552 -10.6552 -12.3091

In [163]:
data['PH']

[{'name': 'PH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcV5Zp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-14.31526059084879,
   -14.995914878833943,
   -0.22919373704709678],
  'quadrupoles_mp2': [-14.363614551379564,
   -15.049447219275471,
   -0.23618791232231587],
  'quadrupoles_ccsd': [-14.30295353295378,
   -15.020932505427043,
   -0.23369959997213757],
  'quadrupoles_hf': [-14.4015, -14.4015, -15.4878],
  'dipoles_ccsdt': [-0.0, -0.0, -0.0, -0.0],
  'dipoles_mp2': [-0.0, -0.0, -0.0, -0.0],
  'dipoles_ccsd': [-0.0, -0.0, -0.0, -0.0],
  'dipoles_hf': [0.0, -0.0, -0.5129, 0.5129],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, -0.0, -40.518235085869996, 40.518235085869996],
  'dipoles_elec_mp2': [-0.0, -0.0, -40.31644468499999, 40.31644468499999],
  'dipoles_elec_ccsd': [-0.0, -0.0, -40.31644468499999, 40.31644468499999],
  'dipoles_elec_ccsdt': [-0.0, -0.0, -40.31644468499999, 40.31644468499999],
  'quadrupoles_elec_hf': [-10.707184015500001,
   -10.707184015500001,
   -119.87585620013863],
  'quadrupoles_elec_mp2': [-10.679017055816026,
   -11.18891787024527,
   -108.5366334000283],
  'quadrupoles_elec_ccsd': [-10.633916983819878,
   -11.167717836337383,
   -108.53478339702711],
  'quadrupoles_elec_ccsdt': [-10.643066998302487,
   -11.149117806370825,
   -108.5314333915772],
  'std_dev_hf': [0.8180458428283528, 0.8180458428283528, 1.038866428358468],
  'std_dev_mp2': [0.816969134048834, 0.8362459966363542, 0.6589836586370987],
  'std_dev_ccsd': [0.8152421796550656, 0.8354533887483409, 0.658895922861238],
  'std_dev_ccsdt': [0.8155928441286776,
   0.8347573676812782,
   0.6587370202307918]},
 {'name': 'PH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVDZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-14.561267248715938,
   -15.338024192513723,
   -0.2209217803018111],
  'quadrupoles_mp2': [-14.571018742906253,
   -15.438699962605915,
   -0.24714993662817875],
  'quadrupoles_ccsd': [-14.543109294306738,
   -15.335603132282627,
   -0.22462062276753794],
  'quadrupoles_hf': [-14.4571, -14.4571, -15.6531],
  'dipoles_ccsdt': [],
  'dipoles_mp2': [],
  'dipoles_ccsd': [],
  'dipoles_hf': [-0.0, 0.0, -0.5511, 0.5511],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-14.333822055296505,
   -14.333822055296505,
   -15.009566971082664],
  'quadrupoles_mp2': [-14.382714029339395,
   -14.382714029339395,
   -15.064915106506376],
  'quadrupoles_ccsd': [-14.320640725587662,
   -14.320640725587662,
   -15.03263429807314],
  'quadrupoles_hf': [-14.4047, -14.4047, -15.4891],
  'dipoles_ccsdt': [],
  'dipoles_mp2': [0, 0, -0.4413, 0.4413],
  'dipoles_ccsd': [0, 0, -0.429, 0.429],
  'dipoles_hf': [0.0, -0.0, -0.513, 0.513],
  'spin_polarized': 1,
  'dipoles_elec_hf': [0.0, -0.0, -40.51827442889999, 40.51827442889999],
  'dipoles_elec_mp2': [0.0, 0.0, -40.490065476389994, 40.490065476389994],
  'dipoles_elec_ccsd': [0.0, 0.0, -40.485226283699994, 40.485226283699994]},
 {'name': 'PH',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-14.397576651321383,
   -14.397576651321383,
   -15.054558347067147],
  'quadrupoles_mp2': [-14.441828259347915,
   -14.441828259347915,
   -15.117774929579909],
  'quadrupoles_ccsd': [-14.382310519300878,
   -14.382310519300878,
   -15.072111036609712],
  'quadrupoles_hf': [-14.4267, -14.4267, -15.5055],
  'dipoles_ccsdt': [0, 0, -0.4192, 0.4192],
  'dipoles_mp2': [0, 0, -0.4359, 0.4359],
  'dipoles_ccsd': [0, 0, -0.4276, 0.4276],
  'dipoles_hf': [0.0, 0.0, -0.5189, 0.5189],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'mBEEF',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.1594, -14.1594, -15.0691],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, -0.45, 0.45],
  'quadrupoles_elec': [-10.5271882338, -10.5271882338, -119.56456238023864],
  'dipoles_elec': [0.0, -0.0, -40.49348831999999, 40.49348831999999],
  'std_dev': [0.8111407181324952, 0.8111407181324952, 1.033256384873666],
  'spin_polarized': 1},
 {'name': 'PH',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-14.2986, -14.2986, -15.1374],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -0.4538, 0.4538],
  'quadrupoles_elec': [-10.630680232200001,
   -10.630680232200001,
   -119.61534185933863],
  'dipoles_elec': [-0.0, -0.0, -40.49498335513999, 40.49498335513999],
  'std_dev': [0.815118098506284, 0.815118098506284, 1.034562469447292],
  'spin_polarized': 1}]

In [164]:
#this cell block is used to modify dipole values
modify('PH', 'ccsdT', 'aug-cc-pcVQZp', 'dipoles_ccsd', [0, 0, -0.429, 0.429])

In [158]:
save(data)

b'\x1b[0;32mSaving updates to GitHub...\x1b[0m\n[master 2fd98b4] save Tue, Aug  4, 2020  4:40:42 PM\n 2 files changed, 96 insertions(+), 479 deletions(-)\n'
File saved!

In [159]:
#use this cell block for electronic component calculation

input_path = Path.home() / "summer/research/geometries/geometries"
ang_to_bohr = 1.88973
ang2_to_bohr2 = 3.571079
debye_to_e = 0.3934303
ea02_to_debye_ang = 1.345033669
debye_ang_to_ea02 = 0.743477

def get_electronic_dipole(string, dipole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    x = y = z = 0
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        if len(line) == 1:
            line += [0, 0, 0]
        x += charge * float(line[1])
        y += charge * float(line[2])
        z += charge * float(line[3])
    x_elec = dipole[0] * debye_to_e - x * ang_to_bohr
    y_elec = dipole[1] * debye_to_e - y * ang_to_bohr
    z_elec = dipole[2] * debye_to_e - z * ang_to_bohr
    total_elec = np.sqrt(x_elec ** 2 + y_elec ** 2 + z_elec ** 2)
    return [x_elec, y_elec, z_elec, total_elec]

def get_electronic_quadrupole(string, quadrupole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    xx = yy = zz = 0
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        if len(line) == 1:
            line += [0, 0, 0]
        xx += charge * float(line[1]) ** 2
        yy += charge * float(line[2]) ** 2
        zz += charge * float(line[3]) ** 2
    xx_elec = quadrupole[0] * debye_ang_to_ea02 - xx * ang2_to_bohr2
    yy_elec = quadrupole[1] * debye_ang_to_ea02 - yy * ang2_to_bohr2
    zz_elec = quadrupole[2] * debye_ang_to_ea02 - zz * ang2_to_bohr2
    return [xx_elec, yy_elec, zz_elec]

def get_stddev(string, dipole, quadrupole):
    info = re.search('molecule\s*\d\s\d\s([\s\S]*?)\$end', string).group(1)
    tote = int(re.search('molecule\s*(\d\s\d\s)', string).group(1).splitlines()[0].split()[0])
    for l in info.splitlines():
        line = l.split()
        charge = Element(re.sub('\d+', '', line[0])).Z
        tote += Element(re.sub('\d+', '', line[0])).Z
    xx_std = np.sqrt((quadrupole[0]/-tote) - (dipole[0]/-tote) ** 2)
    yy_std = np.sqrt((quadrupole[1]/-tote) - (dipole[1]/-tote) ** 2)
    zz_std = np.sqrt((quadrupole[2]/-tote) - (dipole[2]/-tote) ** 2)
    return [xx_std, yy_std, zz_std]

def get_electronic_for_wft(molecule, method, basis):
    filename = input_path / "{}.xyz".format(molecule)
    with open(filename, 'r') as file:
        string = file.read()
    d = retrieve(molecule, method, basis)
    if d == {}:
        print('WFT method has not been calculated for {0} of basis {1}!'.format(molecule, basis))
        return
    add(molecule, method, basis, 'dipoles_elec_hf', get_electronic_dipole(string, d['dipoles_hf']))
    add(molecule, method, basis, 'dipoles_elec_mp2', get_electronic_dipole(string, d['dipoles_mp2']))
    add(molecule, method, basis, 'dipoles_elec_ccsd', get_electronic_dipole(string, d['dipoles_ccsd']))
    add(molecule, method, basis, 'dipoles_elec_ccsdt', get_electronic_dipole(string, d['dipoles_ccsdt']))
    add(molecule, method, basis, 'quadrupoles_elec_hf', get_electronic_quadrupole(string, d['quadrupoles_hf']))
    add(molecule, method, basis, 'quadrupoles_elec_mp2', get_electronic_quadrupole(string, d['quadrupoles_mp2']))
    add(molecule, method, basis, 'quadrupoles_elec_ccsd', get_electronic_quadrupole(string, d['quadrupoles_ccsd']))
    add(molecule, method, basis, 'quadrupoles_elec_ccsdt', get_electronic_quadrupole(string, d['quadrupoles_ccsdt']))
    add(molecule, method, basis, 'std_dev_hf', get_stddev(string, d['dipoles_elec_hf'], d['quadrupoles_elec_hf']))
    add(molecule, method, basis, 'std_dev_mp2', get_stddev(string, d['dipoles_elec_mp2'], d['quadrupoles_elec_mp2']))
    add(molecule, method, basis, 'std_dev_ccsd', get_stddev(string, d['dipoles_elec_ccsd'], d['quadrupoles_elec_ccsd']))
    add(molecule, method, basis, 'std_dev_ccsdt', get_stddev(string, d['dipoles_elec_ccsdt'], d['quadrupoles_elec_ccsdt']))
    print('Electronic part successfully calculated for {0} of basis {1}!'.format(molecule, basis))
    
def get_electronic_for_dft(molecule, method, basis):
    filename = input_path / "{}.xyz".format(molecule)
    with open(filename, 'r') as file:
        string = file.read()
    d = retrieve(molecule, method, basis)
    if d == {}:
        print('DFT method has not been calculated for {0} of method {1}!'.format(molecule, method))
        return
    add(molecule, method, basis, 'dipoles_elec', get_electronic_dipole(string, d['dipoles']))
    add(molecule, method, basis, 'quadrupoles_elec', get_electronic_quadrupole(string, d['quadrupoles']))
    add(molecule, method, basis, 'std_dev', get_stddev(string, d['dipoles_elec'], d['quadrupoles_elec']))
    print('Electronic part successfully calculated for {0} of method {1}!'.format(molecule, method))

In [432]:
get_electronic_for_wft('HBO', 'ccsdT', 'aug-cc-pcVTZp')

Electronic part successfully calculated!

In [161]:
mols = data.keys()

In [162]:
bases = ['aug-cc-pcV5Zp', 'aug-cc-pcVQZp', 'aug-cc-pcVTZp']
for m in mols:
    for b in bases:
        get_electronic_for_wft(m, 'ccsdT', b)

WFT method has not been calculated for AlF of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for AlF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for AlF of basis aug-cc-pcVTZp!
Electronic part successfully calculated for Ar of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Ar of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Ar of basis aug-cc-pcVTZp!
WFT method has not been calculated for Be of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Be of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Be of basis aug-cc-pcVTZp!
WFT method has not been calculated for BeH of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BeH of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BeH of basis aug-cc-pcVTZp!
WFT method has not been calculated for BeH2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BeH2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BeH2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for BF of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BF of basis aug-cc-pcVTZp!
WFT method has not been calculated for BH2 of basis aug-cc-pcV5Zp!
WFT method has not been calculated for BH2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BH2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for BH2F of basis aug-cc-pcV5Zp!
WFT method has not been calculated for BH2F of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BH2F of basis aug-cc-pcVTZp!
WFT method has not been calculated for BH3 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BH3 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BH3 of basis aug-cc-pcVTZp!
WFT method has not been calculated for BO of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BO of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BO of basis aug-cc-pcVTZp!
Electronic part successfully calculated for BS of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for BS of basis aug-cc-pcVQZp!
Electronic part successfully calculated for BS of basis aug-cc-pcVTZp!
WFT method has not been calculated for C2H of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for C2H of basis aug-cc-pcVQZp!
Electronic part successfully calculated for C2H of basis aug-cc-pcVTZp!
WFT method has not been calculated for C2H2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for C2H2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for C2H2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for CH2BH of basis aug-cc-pcV5Zp!
WFT method has not been calculated for CH2BH of basis aug-cc-pcVQZp!
WFT method has not been calculated for CH2BH of basis aug-cc-pcVTZp!
WFT method has not been calculated for CH2-t of basis aug-cc-pcV5Zp!
WFT method has not been calculated for CH2-t of basis aug-cc-pcVQZp!
WFT method has not been calculated for CH2-t of basis aug-cc-pcVTZp!
WFT method has not been calculated for CH3 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CH3 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CH3 of basis aug-cc-pcVTZp!
WFT method has not been calculated for CH4 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CH4 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CH4 of basis aug-cc-pcVTZp!
WFT method has not been calculated for ClF of basis aug-cc-pcV5Zp!
WFT method has not been calculated for ClF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for ClF of basis aug-cc-pcVTZp!
WFT method has not been calculated for CN of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CN of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CN of basis aug-cc-pcVTZp!
WFT method has not been calculated for CO of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for CO of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CO of basis aug-cc-pcVTZp!
WFT method has not been calculated for CO2 of basis aug-cc-pcV5Zp!
WFT method has not been calculated for CO2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for CO2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for F2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for F2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for F2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for FCN of basis aug-cc-pcV5Zp!
WFT method has not been calculated for FCN of basis aug-cc-pcVQZp!
WFT method has not been calculated for FCN of basis aug-cc-pcVTZp!
Electronic part successfully calculated for H of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for H of basis aug-cc-pcVQZp!
Electronic part successfully calculated for H of basis aug-cc-pcVTZp!
Electronic part successfully calculated for H2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for H2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for H2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for H2CN of basis aug-cc-pcV5Zp!
WFT method has not been calculated for H2CN of basis aug-cc-pcVQZp!
Electronic part successfully calculated for H2CN of basis aug-cc-pcVTZp!
Electronic part successfully calculated for H2O of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for H2O of basis aug-cc-pcVQZp!
Electronic part successfully calculated for H2O of basis aug-cc-pcVTZp!
WFT method has not been calculated for HBO of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HBO of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HBO of basis aug-cc-pcVTZp!
WFT method has not been calculated for HCCF of basis aug-cc-pcV5Zp!
WFT method has not been calculated for HCCF of basis aug-cc-pcVQZp!
WFT method has not been calculated for HCCF of basis aug-cc-pcVTZp!
WFT method has not been calculated for HCN of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HCN of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HCN of basis aug-cc-pcVTZp!
Electronic part successfully calculated for He of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for He of basis aug-cc-pcVQZp!
Electronic part successfully calculated for He of basis aug-cc-pcVTZp!
Electronic part successfully calculated for HF of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HF of basis aug-cc-pcVTZp!
WFT method has not been calculated for HNC of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HNC of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HNC of basis aug-cc-pcVTZp!
WFT method has not been calculated for LiBH4 of basis aug-cc-pcV5Zp!
WFT method has not been calculated for LiBH4 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for LiBH4 of basis aug-cc-pcVTZp!
WFT method has not been calculated for Mg of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Mg of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Mg of basis aug-cc-pcVTZp!
WFT method has not been calculated for Mg2 of basis aug-cc-pcV5Zp!
WFT method has not been calculated for Mg2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Mg2 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for N of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for N of basis aug-cc-pcVQZp!
Electronic part successfully calculated for N of basis aug-cc-pcVTZp!
WFT method has not been calculated for N2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for N2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for N2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for Na of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Na of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Na of basis aug-cc-pcVTZp!
WFT method has not been calculated for Na2 of basis aug-cc-pcV5Zp!
WFT method has not been calculated for Na2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Na2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for NaCl of basis aug-cc-pcV5Zp!
WFT method has not been calculated for NaCl of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NaCl of basis aug-cc-pcVTZp!
Electronic part successfully calculated for Ne of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for Ne of basis aug-cc-pcVQZp!
Electronic part successfully calculated for Ne of basis aug-cc-pcVTZp!
WFT method has not been calculated for NH2 of basis aug-cc-pcV5Zp!

Electronic part successfully calculated for NH2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NH2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for NH3 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for NH3 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NH3 of basis aug-cc-pcVTZp!
WFT method has not been calculated for NH3O of basis aug-cc-pcV5Zp!
WFT method has not been calculated for NH3O of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NH3O of basis aug-cc-pcVTZp!
WFT method has not been calculated for O2 of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for O2 of basis aug-cc-pcVQZp!
Electronic part successfully calculated for O2 of basis aug-cc-pcVTZp!
WFT method has not been calculated for O3 of basis aug-cc-pcV5Zp!
WFT method has not been calculated for O3 of basis aug-cc-pcVQZp!
WFT method has not been calculated for O3 of basis aug-cc-pcVTZp!
Electronic part successfully calculated for OF of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for OF of basis aug-cc-pcVQZp!
Electronic part successfully calculated for OF of basis aug-cc-pcVTZp!
Electronic part successfully calculated for OH of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for OH of basis aug-cc-pcVQZp!
Electronic part successfully calculated for OH of basis aug-cc-pcVTZp!
Electronic part successfully calculated for P of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for P of basis aug-cc-pcVQZp!
Electronic part successfully calculated for P of basis aug-cc-pcVTZp!
Electronic part successfully calculated for SF of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for SF of basis aug-cc-pcVQZp!
WFT method has not been calculated for SF of basis aug-cc-pcVTZp!
Electronic part successfully calculated for HCl of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for HCl of basis aug-cc-pcVQZp!
Electronic part successfully calculated for HCl of basis aug-cc-pcVTZp!
Electronic part successfully calculated for NH of basis aug-cc-pcV5Zp!
Electronic part successfully calculated for NH of basis aug-cc-pcVQZp!
Electronic part successfully calculated for NH of basis aug-cc-pcVTZp!
Electronic part successfully calculated for PH of basis aug-cc-pcV5Zp!

IndexError: list index out of range

In [33]:
functionals = get_functionals()
for m in mols:
    for f in functionals:
        get_electronic_for_dft(m, f, 'aug-pc-4p')

DFT method has not been calculated for AlF of method B3LYP!
DFT method has not been calculated for AlF of method B3LYP5!
DFT method has not been calculated for AlF of method B97-D3!
DFT method has not been calculated for AlF of method B97M-V!
DFT method has not been calculated for AlF of method B97M-rV!
Electronic part successfully calculated for AlF of method BLYP!
DFT method has not been calculated for AlF of method BPBE!
DFT method has not been calculated for AlF of method CAM-B3LYP!
DFT method has not been calculated for AlF of method M06-2X!
DFT method has not been calculated for AlF of method M06-L!
DFT method has not been calculated for AlF of method M08-HX!
DFT method has not been calculated for AlF of method MGGA_MS2!
DFT method has not been calculated for AlF of method MN15!
DFT method has not been calculated for AlF of method MN15-L!
DFT method has not been calculated for AlF of method PBE!
DFT method has not been calculated for AlF of method PBE0!
DFT method has not been calculated for AlF of method SCAN!
DFT method has not been calculated for AlF of method SCAN0!
DFT method has not been calculated for AlF of method SPW92!
DFT method has not been calculated for AlF of method Slater!
DFT method has not been calculated for AlF of method TPSS!
DFT method has not been calculated for AlF of method mBEEF!
DFT method has not been calculated for AlF of method mPW91!
DFT method has not been calculated for AlF of method revM06-L!
DFT method has not been calculated for AlF of method wB97M-V!
DFT method has not been calculated for AlF of method wB97X-D!
DFT method has not been calculated for AlF of method wB97X-V!
Electronic part successfully calculated for Ar of method B3LYP!
Electronic part successfully calculated for Ar of method B3LYP5!
DFT method has not been calculated for Ar of method B97-D3!
DFT method has not been calculated for Ar of method B97M-V!
DFT method has not been calculated for Ar of method B97M-rV!
Electronic part successfully calculated for Ar of method BLYP!
Electronic part successfully calculated for Ar of method BPBE!
DFT method has not been calculated for Ar of method CAM-B3LYP!
DFT method has not been calculated for Ar of method M06-2X!
DFT method has not been calculated for Ar of method M06-L!
DFT method has not been calculated for Ar of method M08-HX!
DFT method has not been calculated for Ar of method MGGA_MS2!
DFT method has not been calculated for Ar of method MN15!
DFT method has not been calculated for Ar of method MN15-L!
DFT method has not been calculated for Ar of method PBE!
DFT method has not been calculated for Ar of method PBE0!
DFT method has not been calculated for Ar of method SCAN!
DFT method has not been calculated for Ar of method SCAN0!
DFT method has not been calculated for Ar of method SPW92!
DFT method has not been calculated for Ar of method Slater!
Electronic part successfully calculated for Ar of method TPSS!
Electronic part successfully calculated for Ar of method mBEEF!
Electronic part successfully calculated for Ar of method mPW91!
DFT method has not been calculated for Ar of method revM06-L!
DFT method has not been calculated for Ar of method wB97M-V!
DFT method has not been calculated for Ar of method wB97X-D!
Electronic part successfully calculated for Ar of method wB97X-V!
DFT method has not been calculated for Be of method B3LYP!
DFT method has not been calculated for Be of method B3LYP5!
Electronic part successfully calculated for Be of method B97-D3!
DFT method has not been calculated for Be of method B97M-V!
DFT method has not been calculated for Be of method B97M-rV!
DFT method has not been calculated for Be of method BLYP!
DFT method has not been calculated for Be of method BPBE!
Electronic part successfully calculated for Be of method CAM-B3LYP!
Electronic part successfully calculated for Be of method M06-2X!
Electronic part successfully calculated for Be of method M06-L!
DFT method has not been calculated for Be of method M08-HX!
Electronic part successfully calculated for Be of method MGGA_MS2!
Electronic part successfully calculated for Be of method MN15!
Electronic part successfully calculated for Be of method MN15-L!
Electronic part successfully calculated for Be of method PBE!
DFT method has not been calculated for Be of method PBE0!
DFT method has not been calculated for Be of method SCAN!
DFT method has not been calculated for Be of method SCAN0!
DFT method has not been calculated for Be of method SPW92!
Electronic part successfully calculated for Be of method Slater!
DFT method has not been calculated for Be of method TPSS!
DFT method has not been calculated for Be of method mBEEF!
DFT method has not been calculated for Be of method mPW91!
Electronic part successfully calculated for Be of method revM06-L!
DFT method has not been calculated for Be of method wB97M-V!
DFT method has not been calculated for Be of method wB97X-D!
DFT method has not been calculated for Be of method wB97X-V!
Electronic part successfully calculated for BeH of method B3LYP!
Electronic part successfully calculated for BeH of method B3LYP5!
Electronic part successfully calculated for BeH of method B97-D3!
DFT method has not been calculated for BeH of method B97M-V!
DFT method has not been calculated for BeH of method B97M-rV!
Electronic part successfully calculated for BeH of method BLYP!
Electronic part successfully calculated for BeH of method BPBE!
Electronic part successfully calculated for BeH of method CAM-B3LYP!
Electronic part successfully calculated for BeH of method M06-2X!
Electronic part successfully calculated for BeH of method M06-L!
DFT method has not been calculated for BeH of method M08-HX!
Electronic part successfully calculated for BeH of method MGGA_MS2!
Electronic part successfully calculated for BeH of method MN15!
Electronic part successfully calculated for BeH of method MN15-L!
DFT method has not been calculated for BeH of method PBE!
DFT method has not been calculated for BeH of method PBE0!
DFT method has not been calculated for BeH of method SCAN!
DFT method has not been calculated for BeH of method SCAN0!
DFT method has not been calculated for BeH of method SPW92!
Electronic part successfully calculated for BeH of method Slater!
Electronic part successfully calculated for BeH of method TPSS!
Electronic part successfully calculated for BeH of method mBEEF!
Electronic part successfully calculated for BeH of method mPW91!
Electronic part successfully calculated for BeH of method revM06-L!
DFT method has not been calculated for BeH of method wB97M-V!
DFT method has not been calculated for BeH of method wB97X-D!
Electronic part successfully calculated for BeH of method wB97X-V!
DFT method has not been calculated for BeH2 of method B3LYP!
DFT method has not been calculated for BeH2 of method B3LYP5!
Electronic part successfully calculated for BeH2 of method B97-D3!
DFT method has not been calculated for BeH2 of method B97M-V!
DFT method has not been calculated for BeH2 of method B97M-rV!
Electronic part successfully calculated for BeH2 of method BLYP!
DFT method has not been calculated for BeH2 of method BPBE!
Electronic part successfully calculated for BeH2 of method CAM-B3LYP!
Electronic part successfully calculated for BeH2 of method M06-2X!
Electronic part successfully calculated for BeH2 of method M06-L!
DFT method has not been calculated for BeH2 of method M08-HX!
Electronic part successfully calculated for BeH2 of method MGGA_MS2!
Electronic part successfully calculated for BeH2 of method MN15!
Electronic part successfully calculated for BeH2 of method MN15-L!
DFT method has not been calculated for BeH2 of method PBE!
DFT method has not been calculated for BeH2 of method PBE0!
DFT method has not been calculated for BeH2 of method SCAN!
DFT method has not been calculated for BeH2 of method SCAN0!
DFT method has not been calculated for BeH2 of method SPW92!
Electronic part successfully calculated for BeH2 of method Slater!
DFT method has not been calculated for BeH2 of method TPSS!
DFT method has not been calculated for BeH2 of method mBEEF!
DFT method has not been calculated for BeH2 of method mPW91!
Electronic part successfully calculated for BeH2 of method revM06-L!
DFT method has not been calculated for BeH2 of method wB97M-V!
DFT method has not been calculated for BeH2 of method wB97X-D!
DFT method has not been calculated for BeH2 of method wB97X-V!
DFT method has not been calculated for BF of method B3LYP!
DFT method has not been calculated for BF of method B3LYP5!
Electronic part successfully calculated for BF of method B97-D3!
DFT method has not been calculated for BF of method B97M-V!
DFT method has not been calculated for BF of method B97M-rV!
Electronic part successfully calculated for BF of method BLYP!
DFT method has not been calculated for BF of method BPBE!
Electronic part successfully calculated for BF of method CAM-B3LYP!
Electronic part successfully calculated for BF of method M06-2X!
Electronic part successfully calculated for BF of method M06-L!
DFT method has not been calculated for BF of method M08-HX!
Electronic part successfully calculated for BF of method MGGA_MS2!
Electronic part successfully calculated for BF of method MN15!
Electronic part successfully calculated for BF of method MN15-L!
DFT method has not been calculated for BF of method PBE!
DFT method has not been calculated for BF of method PBE0!
DFT method has not been calculated for BF of method SCAN!
DFT method has not been calculated for BF of method SCAN0!
DFT method has not been calculated for BF of method SPW92!
Electronic part successfully calculated for BF of method Slater!
DFT method has not been calculated for BF of method TPSS!
DFT method has not been calculated for BF of method mBEEF!
DFT method has not been calculated for BF of method mPW91!
Electronic part successfully calculated for BF of method revM06-L!
DFT method has not been calculated for BF of method wB97M-V!
DFT method has not been calculated for BF of method wB97X-D!
DFT method has not been calculated for BF of method wB97X-V!
DFT method has not been calculated for BH2 of method B3LYP!
DFT method has not been calculated for BH2 of method B3LYP5!
DFT method has not been calculated for BH2 of method B97-D3!
DFT method has not been calculated for BH2 of method B97M-V!
DFT method has not been calculated for BH2 of method B97M-rV!
Electronic part successfully calculated for BH2 of method BLYP!
DFT method has not been calculated for BH2 of method BPBE!
DFT method has not been calculated for BH2 of method CAM-B3LYP!
DFT method has not been calculated for BH2 of method M06-2X!
DFT method has not been calculated for BH2 of method M06-L!
DFT method has not been calculated for BH2 of method M08-HX!
DFT method has not been calculated for BH2 of method MGGA_MS2!
DFT method has not been calculated for BH2 of method MN15!
DFT method has not been calculated for BH2 of method MN15-L!
DFT method has not been calculated for BH2 of method PBE!
DFT method has not been calculated for BH2 of method PBE0!
DFT method has not been calculated for BH2 of method SCAN!
DFT method has not been calculated for BH2 of method SCAN0!
DFT method has not been calculated for BH2 of method SPW92!
DFT method has not been calculated for BH2 of method Slater!
DFT method has not been calculated for BH2 of method TPSS!
DFT method has not been calculated for BH2 of method mBEEF!
DFT method has not been calculated for BH2 of method mPW91!
DFT method has not been calculated for BH2 of method revM06-L!
DFT method has not been calculated for BH2 of method wB97M-V!
DFT method has not been calculated for BH2 of method wB97X-D!
DFT method has not been calculated for BH2 of method wB97X-V!
DFT method has not been calculated for BH2F of method B3LYP!
DFT method has not been calculated for BH2F of method B3LYP5!
DFT method has not been calculated for BH2F of method B97-D3!
DFT method has not been calculated for BH2F of method B97M-V!
DFT method has not been calculated for BH2F of method B97M-rV!
DFT method has not been calculated for BH2F of method BLYP!
DFT method has not been calculated for BH2F of method BPBE!
DFT method has not been calculated for BH2F of method CAM-B3LYP!
DFT method has not been calculated for BH2F of method M06-2X!
DFT method has not been calculated for BH2F of method M06-L!
DFT method has not been calculated for BH2F of method M08-HX!
DFT method has not been calculated for BH2F of method MGGA_MS2!
DFT method has not been calculated for BH2F of method MN15!
DFT method has not been calculated for BH2F of method MN15-L!
Electronic part successfully calculated for BH2F of method PBE!
DFT method has not been calculated for BH2F of method PBE0!
DFT method has not been calculated for BH2F of method SCAN!
DFT method has not been calculated for BH2F of method SCAN0!
DFT method has not been calculated for BH2F of method SPW92!
DFT method has not been calculated for BH2F of method Slater!
DFT method has not been calculated for BH2F of method TPSS!
DFT method has not been calculated for BH2F of method mBEEF!
DFT method has not been calculated for BH2F of method mPW91!
DFT method has not been calculated for BH2F of method revM06-L!
DFT method has not been calculated for BH2F of method wB97M-V!
DFT method has not been calculated for BH2F of method wB97X-D!
DFT method has not been calculated for BH2F of method wB97X-V!
Electronic part successfully calculated for BH3 of method B3LYP!
Electronic part successfully calculated for BH3 of method B3LYP5!
Electronic part successfully calculated for BH3 of method B97-D3!
DFT method has not been calculated for BH3 of method B97M-V!
DFT method has not been calculated for BH3 of method B97M-rV!
Electronic part successfully calculated for BH3 of method BLYP!
Electronic part successfully calculated for BH3 of method BPBE!
Electronic part successfully calculated for BH3 of method CAM-B3LYP!
Electronic part successfully calculated for BH3 of method M06-2X!
Electronic part successfully calculated for BH3 of method M06-L!
DFT method has not been calculated for BH3 of method M08-HX!
Electronic part successfully calculated for BH3 of method MGGA_MS2!
Electronic part successfully calculated for BH3 of method MN15!
Electronic part successfully calculated for BH3 of method MN15-L!
DFT method has not been calculated for BH3 of method PBE!
DFT method has not been calculated for BH3 of method PBE0!
DFT method has not been calculated for BH3 of method SCAN!
DFT method has not been calculated for BH3 of method SCAN0!
DFT method has not been calculated for BH3 of method SPW92!
Electronic part successfully calculated for BH3 of method Slater!
Electronic part successfully calculated for BH3 of method TPSS!
Electronic part successfully calculated for BH3 of method mBEEF!
Electronic part successfully calculated for BH3 of method mPW91!
Electronic part successfully calculated for BH3 of method revM06-L!
DFT method has not been calculated for BH3 of method wB97M-V!
DFT method has not been calculated for BH3 of method wB97X-D!
DFT method has not been calculated for BH3 of method wB97X-V!
DFT method has not been calculated for BO of method B3LYP!
DFT method has not been calculated for BO of method B3LYP5!
Electronic part successfully calculated for BO of method B97-D3!
DFT method has not been calculated for BO of method B97M-V!
DFT method has not been calculated for BO of method B97M-rV!
DFT method has not been calculated for BO of method BLYP!
DFT method has not been calculated for BO of method BPBE!
Electronic part successfully calculated for BO of method CAM-B3LYP!
Electronic part successfully calculated for BO of method M06-2X!
Electronic part successfully calculated for BO of method M06-L!
DFT method has not been calculated for BO of method M08-HX!
Electronic part successfully calculated for BO of method MGGA_MS2!
Electronic part successfully calculated for BO of method MN15!
Electronic part successfully calculated for BO of method MN15-L!
Electronic part successfully calculated for BO of method PBE!
Electronic part successfully calculated for BO of method PBE0!
Electronic part successfully calculated for BO of method SCAN!
Electronic part successfully calculated for BO of method SCAN0!
Electronic part successfully calculated for BO of method SPW92!
Electronic part successfully calculated for BO of method Slater!
DFT method has not been calculated for BO of method TPSS!
DFT method has not been calculated for BO of method mBEEF!
DFT method has not been calculated for BO of method mPW91!
Electronic part successfully calculated for BO of method revM06-L!
DFT method has not been calculated for BO of method wB97M-V!
DFT method has not been calculated for BO of method wB97X-D!
DFT method has not been calculated for BO of method wB97X-V!
Electronic part successfully calculated for BS of method B3LYP!
Electronic part successfully calculated for BS of method B3LYP5!
DFT method has not been calculated for BS of method B97-D3!
DFT method has not been calculated for BS of method B97M-V!
DFT method has not been calculated for BS of method B97M-rV!
Electronic part successfully calculated for BS of method BLYP!
Electronic part successfully calculated for BS of method BPBE!
DFT method has not been calculated for BS of method CAM-B3LYP!
DFT method has not been calculated for BS of method M06-2X!
DFT method has not been calculated for BS of method M06-L!
DFT method has not been calculated for BS of method M08-HX!
DFT method has not been calculated for BS of method MGGA_MS2!
DFT method has not been calculated for BS of method MN15!
DFT method has not been calculated for BS of method MN15-L!
Electronic part successfully calculated for BS of method PBE!
Electronic part successfully calculated for BS of method PBE0!
Electronic part successfully calculated for BS of method SCAN!
Electronic part successfully calculated for BS of method SCAN0!
Electronic part successfully calculated for BS of method SPW92!
Electronic part successfully calculated for BS of method Slater!
Electronic part successfully calculated for BS of method TPSS!
Electronic part successfully calculated for BS of method mBEEF!
Electronic part successfully calculated for BS of method mPW91!
DFT method has not been calculated for BS of method revM06-L!
DFT method has not been calculated for BS of method wB97M-V!
DFT method has not been calculated for BS of method wB97X-D!
Electronic part successfully calculated for BS of method wB97X-V!
DFT method has not been calculated for C2H of method B3LYP!
DFT method has not been calculated for C2H of method B3LYP5!
Electronic part successfully calculated for C2H of method B97-D3!
Electronic part successfully calculated for C2H of method B97M-V!
Electronic part successfully calculated for C2H of method B97M-rV!
DFT method has not been calculated for C2H of method BLYP!
DFT method has not been calculated for C2H of method BPBE!
Electronic part successfully calculated for C2H of method CAM-B3LYP!
Electronic part successfully calculated for C2H of method M06-2X!
Electronic part successfully calculated for C2H of method M06-L!
Electronic part successfully calculated for C2H of method M08-HX!
Electronic part successfully calculated for C2H of method MGGA_MS2!
Electronic part successfully calculated for C2H of method MN15!
Electronic part successfully calculated for C2H of method MN15-L!
Electronic part successfully calculated for C2H of method PBE!
Electronic part successfully calculated for C2H of method PBE0!
Electronic part successfully calculated for C2H of method SCAN!
Electronic part successfully calculated for C2H of method SCAN0!
Electronic part successfully calculated for C2H of method SPW92!
Electronic part successfully calculated for C2H of method Slater!
Electronic part successfully calculated for C2H of method TPSS!
Electronic part successfully calculated for C2H of method mBEEF!
Electronic part successfully calculated for C2H of method mPW91!
Electronic part successfully calculated for C2H of method revM06-L!

Electronic part successfully calculated for CO of method Slater!
Electronic part successfully calculated for CO of method TPSS!
DFT method has not been calculated for CO of method mBEEF!
Electronic part successfully calculated for CO of method mPW91!
Electronic part successfully calculated for CO of method revM06-L!
Electronic part successfully calculated for CO of method wB97M-V!
Electronic part successfully calculated for CO of method wB97X-D!
Electronic part successfully calculated for CO of method wB97X-V!
DFT method has not been calculated for CO2 of method B3LYP!
DFT method has not been calculated for CO2 of method B3LYP5!
Electronic part successfully calculated for CO2 of method B97-D3!
DFT method has not been calculated for CO2 of method B97M-V!
DFT method has not been calculated for CO2 of method B97M-rV!
DFT method has not been calculated for CO2 of method BLYP!
DFT method has not been calculated for CO2 of method BPBE!
Electronic part successfully calculated for CO2 of method CAM-B3LYP!
Electronic part successfully calculated for CO2 of method M06-2X!
Electronic part successfully calculated for CO2 of method M06-L!
DFT method has not been calculated for CO2 of method M08-HX!
Electronic part successfully calculated for CO2 of method MGGA_MS2!
Electronic part successfully calculated for CO2 of method MN15!
Electronic part successfully calculated for CO2 of method MN15-L!
Electronic part successfully calculated for CO2 of method PBE!
Electronic part successfully calculated for CO2 of method PBE0!
Electronic part successfully calculated for CO2 of method SCAN!
Electronic part successfully calculated for CO2 of method SCAN0!
Electronic part successfully calculated for CO2 of method SPW92!
Electronic part successfully calculated for CO2 of method Slater!
DFT method has not been calculated for CO2 of method TPSS!
DFT method has not been calculated for CO2 of method mBEEF!
DFT method has not been calculated for CO2 of method mPW91!
Electronic part successfully calculated for CO2 of method revM06-L!
DFT method has not been calculated for CO2 of method wB97M-V!
DFT method has not been calculated for CO2 of method wB97X-D!
DFT method has not been calculated for CO2 of method wB97X-V!
Electronic part successfully calculated for F2 of method B3LYP!
Electronic part successfully calculated for F2 of method B3LYP5!
Electronic part successfully calculated for F2 of method B97-D3!
Electronic part successfully calculated for F2 of method B97M-V!
DFT method has not been calculated for F2 of method B97M-rV!
Electronic part successfully calculated for F2 of method BLYP!
Electronic part successfully calculated for F2 of method BPBE!
Electronic part successfully calculated for F2 of method CAM-B3LYP!
Electronic part successfully calculated for F2 of method M06-2X!
Electronic part successfully calculated for F2 of method M06-L!
Electronic part successfully calculated for F2 of method M08-HX!
Electronic part successfully calculated for F2 of method MGGA_MS2!
Electronic part successfully calculated for F2 of method MN15!
Electronic part successfully calculated for F2 of method MN15-L!
Electronic part successfully calculated for F2 of method PBE!
Electronic part successfully calculated for F2 of method PBE0!
Electronic part successfully calculated for F2 of method SCAN!
Electronic part successfully calculated for F2 of method SCAN0!
Electronic part successfully calculated for F2 of method SPW92!
Electronic part successfully calculated for F2 of method Slater!
Electronic part successfully calculated for F2 of method TPSS!
Electronic part successfully calculated for F2 of method mBEEF!
Electronic part successfully calculated for F2 of method mPW91!
Electronic part successfully calculated for F2 of method revM06-L!
Electronic part successfully calculated for F2 of method wB97M-V!
Electronic part successfully calculated for F2 of method wB97X-D!
Electronic part successfully calculated for F2 of method wB97X-V!
Electronic part successfully calculated for FCN of method B3LYP!
Electronic part successfully calculated for FCN of method B3LYP5!
Electronic part successfully calculated for FCN of method B97-D3!
Electronic part successfully calculated for FCN of method B97M-V!
DFT method has not been calculated for FCN of method B97M-rV!
Electronic part successfully calculated for FCN of method BLYP!
Electronic part successfully calculated for FCN of method BPBE!
DFT method has not been calculated for FCN of method CAM-B3LYP!
Electronic part successfully calculated for FCN of method M06-2X!
Electronic part successfully calculated for FCN of method M06-L!
Electronic part successfully calculated for FCN of method M08-HX!
Electronic part successfully calculated for FCN of method MGGA_MS2!
DFT method has not been calculated for FCN of method MN15!
DFT method has not been calculated for FCN of method MN15-L!
DFT method has not been calculated for FCN of method PBE!
DFT method has not been calculated for FCN of method PBE0!
DFT method has not been calculated for FCN of method SCAN!
DFT method has not been calculated for FCN of method SCAN0!
Electronic part successfully calculated for FCN of method SPW92!
Electronic part successfully calculated for FCN of method Slater!
Electronic part successfully calculated for FCN of method TPSS!
Electronic part successfully calculated for FCN of method mBEEF!
Electronic part successfully calculated for FCN of method mPW91!
Electronic part successfully calculated for FCN of method revM06-L!
Electronic part successfully calculated for FCN of method wB97M-V!
Electronic part successfully calculated for FCN of method wB97X-D!
Electronic part successfully calculated for FCN of method wB97X-V!
Electronic part successfully calculated for FCO of method B3LYP!
DFT method has not been calculated for FCO of method B3LYP5!
DFT method has not been calculated for FCO of method B97-D3!
DFT method has not been calculated for FCO of method B97M-V!
Electronic part successfully calculated for FCO of method B97M-rV!
Electronic part successfully calculated for FCO of method BLYP!
Electronic part successfully calculated for FCO of method BPBE!
DFT method has not been calculated for FCO of method CAM-B3LYP!
DFT method has not been calculated for FCO of method M06-2X!
DFT method has not been calculated for FCO of method M06-L!
Electronic part successfully calculated for FCO of method M08-HX!
DFT method has not been calculated for FCO of method MGGA_MS2!
DFT method has not been calculated for FCO of method MN15!
DFT method has not been calculated for FCO of method MN15-L!
DFT method has not been calculated for FCO of method PBE!
DFT method has not been calculated for FCO of method PBE0!
DFT method has not been calculated for FCO of method SCAN!
DFT method has not been calculated for FCO of method SCAN0!
DFT method has not been calculated for FCO of method SPW92!
DFT method has not been calculated for FCO of method Slater!
DFT method has not been calculated for FCO of method TPSS!
DFT method has not been calculated for FCO of method mBEEF!
DFT method has not been calculated for FCO of method mPW91!
DFT method has not been calculated for FCO of method revM06-L!
DFT method has not been calculated for FCO of method wB97M-V!
DFT method has not been calculated for FCO of method wB97X-D!
DFT method has not been calculated for FCO of method wB97X-V!
Electronic part successfully calculated for H of method B3LYP!
Electronic part successfully calculated for H of method B3LYP5!
Electronic part successfully calculated for H of method B97-D3!
DFT method has not been calculated for H of method B97M-V!
DFT method has not been calculated for H of method B97M-rV!
Electronic part successfully calculated for H of method BLYP!
Electronic part successfully calculated for H of method BPBE!
Electronic part successfully calculated for H of method CAM-B3LYP!
Electronic part successfully calculated for H of method M06-2X!
Electronic part successfully calculated for H of method M06-L!
DFT method has not been calculated for H of method M08-HX!
Electronic part successfully calculated for H of method MGGA_MS2!
Electronic part successfully calculated for H of method MN15!
Electronic part successfully calculated for H of method MN15-L!
DFT method has not been calculated for H of method PBE!
DFT method has not been calculated for H of method PBE0!
DFT method has not been calculated for H of method SCAN!
DFT method has not been calculated for H of method SCAN0!
DFT method has not been calculated for H of method SPW92!
Electronic part successfully calculated for H of method Slater!
Electronic part successfully calculated for H of method TPSS!
Electronic part successfully calculated for H of method mBEEF!
Electronic part successfully calculated for H of method mPW91!
Electronic part successfully calculated for H of method revM06-L!
DFT method has not been calculated for H of method wB97M-V!
DFT method has not been calculated for H of method wB97X-D!
Electronic part successfully calculated for H of method wB97X-V!
Electronic part successfully calculated for H2 of method B3LYP!
Electronic part successfully calculated for H2 of method B3LYP5!
Electronic part successfully calculated for H2 of method B97-D3!
DFT method has not been calculated for H2 of method B97M-V!
DFT method has not been calculated for H2 of method B97M-rV!
Electronic part successfully calculated for H2 of method BLYP!
Electronic part successfully calculated for H2 of method BPBE!
Electronic part successfully calculated for H2 of method CAM-B3LYP!
Electronic part successfully calculated for H2 of method M06-2X!
Electronic part successfully calculated for H2 of method M06-L!
DFT method has not been calculated for H2 of method M08-HX!
Electronic part successfully calculated for H2 of method MGGA_MS2!
Electronic part successfully calculated for H2 of method MN15!
Electronic part successfully calculated for H2 of method MN15-L!
Electronic part successfully calculated for H2 of method PBE!
Electronic part successfully calculated for H2 of method PBE0!
Electronic part successfully calculated for H2 of method SCAN!
Electronic part successfully calculated for H2 of method SCAN0!
Electronic part successfully calculated for H2 of method SPW92!
Electronic part successfully calculated for H2 of method Slater!
Electronic part successfully calculated for H2 of method TPSS!
DFT method has not been calculated for H2 of method mBEEF!
Electronic part successfully calculated for H2 of method mPW91!
Electronic part successfully calculated for H2 of method revM06-L!
DFT method has not been calculated for H2 of method wB97M-V!
DFT method has not been calculated for H2 of method wB97X-D!
Electronic part successfully calculated for H2 of method wB97X-V!
DFT method has not been calculated for H2CN of method B3LYP!
DFT method has not been calculated for H2CN of method B3LYP5!
DFT method has not been calculated for H2CN of method B97-D3!
DFT method has not been calculated for H2CN of method B97M-V!
DFT method has not been calculated for H2CN of method B97M-rV!
DFT method has not been calculated for H2CN of method BLYP!
DFT method has not been calculated for H2CN of method BPBE!
DFT method has not been calculated for H2CN of method CAM-B3LYP!
DFT method has not been calculated for H2CN of method M06-2X!
DFT method has not been calculated for H2CN of method M06-L!
DFT method has not been calculated for H2CN of method M08-HX!
DFT method has not been calculated for H2CN of method MGGA_MS2!
DFT method has not been calculated for H2CN of method MN15!
DFT method has not been calculated for H2CN of method MN15-L!
Electronic part successfully calculated for H2CN of method PBE!
DFT method has not been calculated for H2CN of method PBE0!
DFT method has not been calculated for H2CN of method SCAN!
DFT method has not been calculated for H2CN of method SCAN0!
DFT method has not been calculated for H2CN of method SPW92!
DFT method has not been calculated for H2CN of method Slater!
DFT method has not been calculated for H2CN of method TPSS!
DFT method has not been calculated for H2CN of method mBEEF!
DFT method has not been calculated for H2CN of method mPW91!
DFT method has not been calculated for H2CN of method revM06-L!
DFT method has not been calculated for H2CN of method wB97M-V!
DFT method has not been calculated for H2CN of method wB97X-D!
DFT method has not been calculated for H2CN of method wB97X-V!
Electronic part successfully calculated for H2O of method B3LYP!
Electronic part successfully calculated for H2O of method B3LYP5!
Electronic part successfully calculated for H2O of method B97-D3!
DFT method has not been calculated for H2O of method B97M-V!
DFT method has not been calculated for H2O of method B97M-rV!
Electronic part successfully calculated for H2O of method BLYP!
Electronic part successfully calculated for H2O of method BPBE!
Electronic part successfully calculated for H2O of method CAM-B3LYP!
Electronic part successfully calculated for H2O of method M06-2X!
Electronic part successfully calculated for H2O of method M06-L!
Electronic part successfully calculated for H2O of method M08-HX!
Electronic part successfully calculated for H2O of method MGGA_MS2!
Electronic part successfully calculated for H2O of method MN15!
Electronic part successfully calculated for H2O of method MN15-L!
Electronic part successfully calculated for H2O of method PBE!
Electronic part successfully calculated for H2O of method PBE0!
Electronic part successfully calculated for H2O of method SCAN!
Electronic part successfully calculated for H2O of method SCAN0!
Electronic part successfully calculated for H2O of method SPW92!
Electronic part successfully calculated for H2O of method Slater!
Electronic part successfully calculated for H2O of method TPSS!
Electronic part successfully calculated for H2O of method mBEEF!
Electronic part successfully calculated for H2O of method mPW91!
Electronic part successfully calculated for H2O of method revM06-L!
Electronic part successfully calculated for H2O of method wB97M-V!
Electronic part successfully calculated for H2O of method wB97X-D!
Electronic part successfully calculated for H2O of method wB97X-V!
Electronic part successfully calculated for HBO of method B3LYP!
Electronic part successfully calculated for HBO of method B3LYP5!
Electronic part successfully calculated for HBO of method B97-D3!
DFT method has not been calculated for HBO of method B97M-V!
DFT method has not been calculated for HBO of method B97M-rV!
Electronic part successfully calculated for HBO of method BLYP!
Electronic part successfully calculated for HBO of method BPBE!
Electronic part successfully calculated for HBO of method CAM-B3LYP!
Electronic part successfully calculated for HBO of method M06-2X!
Electronic part successfully calculated for HBO of method M06-L!
Electronic part successfully calculated for HBO of method M08-HX!
Electronic part successfully calculated for HBO of method MGGA_MS2!
Electronic part successfully calculated for HBO of method MN15!
Electronic part successfully calculated for HBO of method MN15-L!
Electronic part successfully calculated for HBO of method PBE!
Electronic part successfully calculated for HBO of method PBE0!
Electronic part successfully calculated for HBO of method SCAN!
Electronic part successfully calculated for HBO of method SCAN0!
Electronic part successfully calculated for HBO of method SPW92!
Electronic part successfully calculated for HBO of method Slater!
Electronic part successfully calculated for HBO of method TPSS!
Electronic part successfully calculated for HBO of method mBEEF!
Electronic part successfully calculated for HBO of method mPW91!
Electronic part successfully calculated for HBO of method revM06-L!
Electronic part successfully calculated for HBO of method wB97M-V!
Electronic part successfully calculated for HBO of method wB97X-D!
Electronic part successfully calculated for HBO of method wB97X-V!
Electronic part successfully calculated for HCCF of method B3LYP!
Electronic part successfully calculated for HCCF of method B3LYP5!
Electronic part successfully calculated for HCCF of method B97-D3!
Electronic part successfully calculated for HCCF of method B97M-V!
DFT method has not been calculated for HCCF of method B97M-rV!
Electronic part successfully calculated for HCCF of method BLYP!
Electronic part successfully calculated for HCCF of method BPBE!
Electronic part successfully calculated for HCCF of method CAM-B3LYP!
Electronic part successfully calculated for HCCF of method M06-2X!
Electronic part successfully calculated for HCCF of method M06-L!
Electronic part successfully calculated for HCCF of method M08-HX!
Electronic part successfully calculated for HCCF of method MGGA_MS2!
Electronic part successfully calculated for HCCF of method MN15!
Electronic part successfully calculated for HCCF of method MN15-L!
Electronic part successfully calculated for HCCF of method PBE!
Electronic part successfully calculated for HCCF of method PBE0!
Electronic part successfully calculated for HCCF of method SCAN!
Electronic part successfully calculated for HCCF of method SCAN0!
Electronic part successfully calculated for HCCF of method SPW92!
Electronic part successfully calculated for HCCF of method Slater!
Electronic part successfully calculated for HCCF of method TPSS!
Electronic part successfully calculated for HCCF of method mBEEF!
Electronic part successfully calculated for HCCF of method mPW91!
Electronic part successfully calculated for HCCF of method revM06-L!
Electronic part successfully calculated for HCCF of method wB97M-V!
Electronic part successfully calculated for HCCF of method wB97X-D!
Electronic part successfully calculated for HCCF of method wB97X-V!
Electronic part successfully calculated for HCN of method B3LYP!
Electronic part successfully calculated for HCN of method B3LYP5!
Electronic part successfully calculated for HCN of method B97-D3!
Electronic part successfully calculated for HCN of method B97M-V!
DFT method has not been calculated for HCN of method B97M-rV!
Electronic part successfully calculated for HCN of method BLYP!
Electronic part successfully calculated for HCN of method BPBE!
Electronic part successfully calculated for HCN of method CAM-B3LYP!
Electronic part successfully calculated for HCN of method M06-2X!
DFT method has not been calculated for HCN of method M06-L!
Electronic part successfully calculated for HCN of method M08-HX!
Electronic part successfully calculated for HCN of method MGGA_MS2!
Electronic part successfully calculated for HCN of method MN15!
Electronic part successfully calculated for HCN of method MN15-L!
Electronic part successfully calculated for HCN of method PBE!
Electronic part successfully calculated for HCN of method PBE0!
Electronic part successfully calculated for HCN of method SCAN!
Electronic part successfully calculated for HCN of method SCAN0!
Electronic part successfully calculated for HCN of method SPW92!
Electronic part successfully calculated for HCN of method Slater!
Electronic part successfully calculated for HCN of method TPSS!
Electronic part successfully calculated for HCN of method mBEEF!
Electronic part successfully calculated for HCN of method mPW91!
Electronic part successfully calculated for HCN of method revM06-L!
Electronic part successfully calculated for HCN of method wB97M-V!
Electronic part successfully calculated for HCN of method wB97X-D!
Electronic part successfully calculated for HCN of method wB97X-V!
DFT method has not been calculated for HCO of method B3LYP!
Electronic part successfully calculated for HCO of method B3LYP5!
Electronic part successfully calculated for HCO of method B97-D3!
Electronic part successfully calculated for HCO of method B97M-V!
DFT method has not been calculated for HCO of method B97M-rV!
Electronic part successfully calculated for HCO of method BLYP!
Electronic part successfully calculated for HCO of method BPBE!

Electronic part successfully calculated for N2 of method mPW91!
Electronic part successfully calculated for N2 of method revM06-L!
Electronic part successfully calculated for N2 of method wB97M-V!
Electronic part successfully calculated for N2 of method wB97X-D!
Electronic part successfully calculated for N2 of method wB97X-V!
Electronic part successfully calculated for N2H2 of method B3LYP!
Electronic part successfully calculated for N2H2 of method B3LYP5!
Electronic part successfully calculated for N2H2 of method B97-D3!
Electronic part successfully calculated for N2H2 of method B97M-V!
DFT method has not been calculated for N2H2 of method B97M-rV!
Electronic part successfully calculated for N2H2 of method BLYP!
Electronic part successfully calculated for N2H2 of method BPBE!
Electronic part successfully calculated for N2H2 of method CAM-B3LYP!
Electronic part successfully calculated for N2H2 of method M06-2X!
Electronic part successfully calculated for N2H2 of method M06-L!
Electronic part successfully calculated for N2H2 of method M08-HX!
Electronic part successfully calculated for N2H2 of method MGGA_MS2!
Electronic part successfully calculated for N2H2 of method MN15!
Electronic part successfully calculated for N2H2 of method MN15-L!
Electronic part successfully calculated for N2H2 of method PBE!
Electronic part successfully calculated for N2H2 of method PBE0!
Electronic part successfully calculated for N2H2 of method SCAN!
Electronic part successfully calculated for N2H2 of method SCAN0!
Electronic part successfully calculated for N2H2 of method SPW92!
Electronic part successfully calculated for N2H2 of method Slater!
Electronic part successfully calculated for N2H2 of method TPSS!
Electronic part successfully calculated for N2H2 of method mBEEF!
Electronic part successfully calculated for N2H2 of method mPW91!
Electronic part successfully calculated for N2H2 of method revM06-L!
Electronic part successfully calculated for N2H2 of method wB97M-V!
DFT method has not been calculated for N2H2 of method wB97X-D!
Electronic part successfully calculated for N2H2 of method wB97X-V!
Electronic part successfully calculated for N2H4 of method B3LYP!
Electronic part successfully calculated for N2H4 of method B3LYP5!
Electronic part successfully calculated for N2H4 of method B97-D3!
DFT method has not been calculated for N2H4 of method B97M-V!
DFT method has not been calculated for N2H4 of method B97M-rV!
Electronic part successfully calculated for N2H4 of method BLYP!
Electronic part successfully calculated for N2H4 of method BPBE!
Electronic part successfully calculated for N2H4 of method CAM-B3LYP!
Electronic part successfully calculated for N2H4 of method M06-2X!
DFT method has not been calculated for N2H4 of method M06-L!
DFT method has not been calculated for N2H4 of method M08-HX!
DFT method has not been calculated for N2H4 of method MGGA_MS2!
DFT method has not been calculated for N2H4 of method MN15!
Electronic part successfully calculated for N2H4 of method MN15-L!
Electronic part successfully calculated for N2H4 of method PBE!
Electronic part successfully calculated for N2H4 of method PBE0!
DFT method has not been calculated for N2H4 of method SCAN!
Electronic part successfully calculated for N2H4 of method SCAN0!
Electronic part successfully calculated for N2H4 of method SPW92!
Electronic part successfully calculated for N2H4 of method Slater!
DFT method has not been calculated for N2H4 of method TPSS!
Electronic part successfully calculated for N2H4 of method mBEEF!
DFT method has not been calculated for N2H4 of method mPW91!
Electronic part successfully calculated for N2H4 of method revM06-L!
DFT method has not been calculated for N2H4 of method wB97M-V!
Electronic part successfully calculated for N2H4 of method wB97X-D!
DFT method has not been calculated for N2H4 of method wB97X-V!
Electronic part successfully calculated for Na of method B3LYP!
Electronic part successfully calculated for Na of method B3LYP5!
Electronic part successfully calculated for Na of method B97-D3!
Electronic part successfully calculated for Na of method B97M-V!
DFT method has not been calculated for Na of method B97M-rV!
Electronic part successfully calculated for Na of method BLYP!
Electronic part successfully calculated for Na of method BPBE!
Electronic part successfully calculated for Na of method CAM-B3LYP!
DFT method has not been calculated for Na of method M06-2X!
DFT method has not been calculated for Na of method M06-L!
Electronic part successfully calculated for Na of method M08-HX!
Electronic part successfully calculated for Na of method MGGA_MS2!
Electronic part successfully calculated for Na of method MN15!
Electronic part successfully calculated for Na of method MN15-L!
Electronic part successfully calculated for Na of method PBE!
Electronic part successfully calculated for Na of method PBE0!
Electronic part successfully calculated for Na of method SCAN!
Electronic part successfully calculated for Na of method SCAN0!
Electronic part successfully calculated for Na of method SPW92!
Electronic part successfully calculated for Na of method Slater!
Electronic part successfully calculated for Na of method TPSS!
Electronic part successfully calculated for Na of method mBEEF!
Electronic part successfully calculated for Na of method mPW91!
Electronic part successfully calculated for Na of method revM06-L!
Electronic part successfully calculated for Na of method wB97M-V!
DFT method has not been calculated for Na of method wB97X-D!
Electronic part successfully calculated for Na of method wB97X-V!
Electronic part successfully calculated for Na2 of method B3LYP!
Electronic part successfully calculated for Na2 of method B3LYP5!
DFT method has not been calculated for Na2 of method B97-D3!
DFT method has not been calculated for Na2 of method B97M-V!
DFT method has not been calculated for Na2 of method B97M-rV!
Electronic part successfully calculated for Na2 of method BLYP!
Electronic part successfully calculated for Na2 of method BPBE!
Electronic part successfully calculated for Na2 of method CAM-B3LYP!
Electronic part successfully calculated for Na2 of method M06-2X!
Electronic part successfully calculated for Na2 of method M06-L!
Electronic part successfully calculated for Na2 of method M08-HX!
Electronic part successfully calculated for Na2 of method MGGA_MS2!
Electronic part successfully calculated for Na2 of method MN15!
Electronic part successfully calculated for Na2 of method MN15-L!
DFT method has not been calculated for Na2 of method PBE!
DFT method has not been calculated for Na2 of method PBE0!
Electronic part successfully calculated for Na2 of method SCAN!
DFT method has not been calculated for Na2 of method SCAN0!
Electronic part successfully calculated for Na2 of method SPW92!
Electronic part successfully calculated for Na2 of method Slater!
Electronic part successfully calculated for Na2 of method TPSS!
Electronic part successfully calculated for Na2 of method mBEEF!
Electronic part successfully calculated for Na2 of method mPW91!
Electronic part successfully calculated for Na2 of method revM06-L!
Electronic part successfully calculated for Na2 of method wB97M-V!
DFT method has not been calculated for Na2 of method wB97X-D!
Electronic part successfully calculated for Na2 of method wB97X-V!
Electronic part successfully calculated for NaCl of method B3LYP!
Electronic part successfully calculated for NaCl of method B3LYP5!
Electronic part successfully calculated for NaCl of method B97-D3!
DFT method has not been calculated for NaCl of method B97M-V!
DFT method has not been calculated for NaCl of method B97M-rV!
Electronic part successfully calculated for NaCl of method BLYP!
Electronic part successfully calculated for NaCl of method BPBE!
Electronic part successfully calculated for NaCl of method CAM-B3LYP!
Electronic part successfully calculated for NaCl of method M06-2X!
DFT method has not been calculated for NaCl of method M06-L!
Electronic part successfully calculated for NaCl of method M08-HX!
DFT method has not been calculated for NaCl of method MGGA_MS2!
Electronic part successfully calculated for NaCl of method MN15!
Electronic part successfully calculated for NaCl of method MN15-L!
Electronic part successfully calculated for NaCl of method PBE!
Electronic part successfully calculated for NaCl of method PBE0!
Electronic part successfully calculated for NaCl of method SCAN!
Electronic part successfully calculated for NaCl of method SCAN0!
Electronic part successfully calculated for NaCl of method SPW92!
Electronic part successfully calculated for NaCl of method Slater!
Electronic part successfully calculated for NaCl of method TPSS!
Electronic part successfully calculated for NaCl of method mBEEF!
Electronic part successfully calculated for NaCl of method mPW91!
DFT method has not been calculated for NaCl of method revM06-L!
Electronic part successfully calculated for NaCl of method wB97M-V!
Electronic part successfully calculated for NaCl of method wB97X-D!
Electronic part successfully calculated for NaCl of method wB97X-V!
Electronic part successfully calculated for Ne of method B3LYP!
Electronic part successfully calculated for Ne of method B3LYP5!
Electronic part successfully calculated for Ne of method B97-D3!
Electronic part successfully calculated for Ne of method B97M-V!
DFT method has not been calculated for Ne of method B97M-rV!
Electronic part successfully calculated for Ne of method BLYP!
Electronic part successfully calculated for Ne of method BPBE!
Electronic part successfully calculated for Ne of method CAM-B3LYP!
Electronic part successfully calculated for Ne of method M06-2X!
Electronic part successfully calculated for Ne of method M06-L!
DFT method has not been calculated for Ne of method M08-HX!
Electronic part successfully calculated for Ne of method MGGA_MS2!
Electronic part successfully calculated for Ne of method MN15!
Electronic part successfully calculated for Ne of method MN15-L!
DFT method has not been calculated for Ne of method PBE!
Electronic part successfully calculated for Ne of method PBE0!
Electronic part successfully calculated for Ne of method SCAN!
Electronic part successfully calculated for Ne of method SCAN0!
Electronic part successfully calculated for Ne of method SPW92!
Electronic part successfully calculated for Ne of method Slater!
Electronic part successfully calculated for Ne of method TPSS!
Electronic part successfully calculated for Ne of method mBEEF!
Electronic part successfully calculated for Ne of method mPW91!
Electronic part successfully calculated for Ne of method revM06-L!
Electronic part successfully calculated for Ne of method wB97M-V!
Electronic part successfully calculated for Ne of method wB97X-D!
Electronic part successfully calculated for Ne of method wB97X-V!
Electronic part successfully calculated for NH2 of method B3LYP!
Electronic part successfully calculated for NH2 of method B3LYP5!
Electronic part successfully calculated for NH2 of method B97-D3!
Electronic part successfully calculated for NH2 of method B97M-V!
DFT method has not been calculated for NH2 of method B97M-rV!
Electronic part successfully calculated for NH2 of method BLYP!
Electronic part successfully calculated for NH2 of method BPBE!
Electronic part successfully calculated for NH2 of method CAM-B3LYP!
Electronic part successfully calculated for NH2 of method M06-2X!
Electronic part successfully calculated for NH2 of method M06-L!
Electronic part successfully calculated for NH2 of method M08-HX!
Electronic part successfully calculated for NH2 of method MGGA_MS2!
DFT method has not been calculated for NH2 of method MN15!
Electronic part successfully calculated for NH2 of method MN15-L!
Electronic part successfully calculated for NH2 of method PBE!
Electronic part successfully calculated for NH2 of method PBE0!
Electronic part successfully calculated for NH2 of method SCAN!
Electronic part successfully calculated for NH2 of method SCAN0!
Electronic part successfully calculated for NH2 of method SPW92!
Electronic part successfully calculated for NH2 of method Slater!
Electronic part successfully calculated for NH2 of method TPSS!
Electronic part successfully calculated for NH2 of method mBEEF!
Electronic part successfully calculated for NH2 of method mPW91!
Electronic part successfully calculated for NH2 of method revM06-L!
Electronic part successfully calculated for NH2 of method wB97M-V!
Electronic part successfully calculated for NH2 of method wB97X-D!
Electronic part successfully calculated for NH2 of method wB97X-V!
Electronic part successfully calculated for NH2Cl of method B3LYP!
Electronic part successfully calculated for NH2Cl of method B3LYP5!
DFT method has not been calculated for NH2Cl of method B97-D3!
DFT method has not been calculated for NH2Cl of method B97M-V!
DFT method has not been calculated for NH2Cl of method B97M-rV!
Electronic part successfully calculated for NH2Cl of method BLYP!
Electronic part successfully calculated for NH2Cl of method BPBE!
DFT method has not been calculated for NH2Cl of method CAM-B3LYP!
Electronic part successfully calculated for NH2Cl of method M06-2X!
DFT method has not been calculated for NH2Cl of method M06-L!
Electronic part successfully calculated for NH2Cl of method M08-HX!
DFT method has not been calculated for NH2Cl of method MGGA_MS2!
DFT method has not been calculated for NH2Cl of method MN15!
Electronic part successfully calculated for NH2Cl of method MN15-L!
DFT method has not been calculated for NH2Cl of method PBE!
DFT method has not been calculated for NH2Cl of method PBE0!
Electronic part successfully calculated for NH2Cl of method SCAN!
DFT method has not been calculated for NH2Cl of method SCAN0!
Electronic part successfully calculated for NH2Cl of method SPW92!
Electronic part successfully calculated for NH2Cl of method Slater!
Electronic part successfully calculated for NH2Cl of method TPSS!
Electronic part successfully calculated for NH2Cl of method mBEEF!
Electronic part successfully calculated for NH2Cl of method mPW91!
DFT method has not been calculated for NH2Cl of method revM06-L!
DFT method has not been calculated for NH2Cl of method wB97M-V!
DFT method has not been calculated for NH2Cl of method wB97X-D!
Electronic part successfully calculated for NH2Cl of method wB97X-V!
Electronic part successfully calculated for NH2F of method B3LYP!
Electronic part successfully calculated for NH2F of method B3LYP5!
Electronic part successfully calculated for NH2F of method B97-D3!
Electronic part successfully calculated for NH2F of method B97M-V!
DFT method has not been calculated for NH2F of method B97M-rV!
Electronic part successfully calculated for NH2F of method BLYP!
Electronic part successfully calculated for NH2F of method BPBE!
Electronic part successfully calculated for NH2F of method CAM-B3LYP!
Electronic part successfully calculated for NH2F of method M06-2X!
DFT method has not been calculated for NH2F of method M06-L!
Electronic part successfully calculated for NH2F of method M08-HX!
Electronic part successfully calculated for NH2F of method MGGA_MS2!
Electronic part successfully calculated for NH2F of method MN15!
Electronic part successfully calculated for NH2F of method MN15-L!
Electronic part successfully calculated for NH2F of method PBE!
Electronic part successfully calculated for NH2F of method PBE0!
Electronic part successfully calculated for NH2F of method SCAN!
Electronic part successfully calculated for NH2F of method SCAN0!
Electronic part successfully calculated for NH2F of method SPW92!
Electronic part successfully calculated for NH2F of method Slater!
Electronic part successfully calculated for NH2F of method TPSS!
Electronic part successfully calculated for NH2F of method mBEEF!
Electronic part successfully calculated for NH2F of method mPW91!
Electronic part successfully calculated for NH2F of method revM06-L!
Electronic part successfully calculated for NH2F of method wB97M-V!
Electronic part successfully calculated for NH2F of method wB97X-D!
Electronic part successfully calculated for NH2F of method wB97X-V!
Electronic part successfully calculated for NH2OH of method B3LYP!
Electronic part successfully calculated for NH2OH of method B3LYP5!
DFT method has not been calculated for NH2OH of method B97-D3!
DFT method has not been calculated for NH2OH of method B97M-V!
DFT method has not been calculated for NH2OH of method B97M-rV!
DFT method has not been calculated for NH2OH of method BLYP!
Electronic part successfully calculated for NH2OH of method BPBE!
DFT method has not been calculated for NH2OH of method CAM-B3LYP!
Electronic part successfully calculated for NH2OH of method M06-2X!
Electronic part successfully calculated for NH2OH of method M06-L!
Electronic part successfully calculated for NH2OH of method M08-HX!
Electronic part successfully calculated for NH2OH of method MGGA_MS2!
Electronic part successfully calculated for NH2OH of method MN15!
Electronic part successfully calculated for NH2OH of method MN15-L!
Electronic part successfully calculated for NH2OH of method PBE!
Electronic part successfully calculated for NH2OH of method PBE0!
Electronic part successfully calculated for NH2OH of method SCAN!
Electronic part successfully calculated for NH2OH of method SCAN0!
Electronic part successfully calculated for NH2OH of method SPW92!
Electronic part successfully calculated for NH2OH of method Slater!
Electronic part successfully calculated for NH2OH of method TPSS!
Electronic part successfully calculated for NH2OH of method mBEEF!
Electronic part successfully calculated for NH2OH of method mPW91!
Electronic part successfully calculated for NH2OH of method revM06-L!
DFT method has not been calculated for NH2OH of method wB97M-V!
Electronic part successfully calculated for NH2OH of method wB97X-D!
DFT method has not been calculated for NH2OH of method wB97X-V!
Electronic part successfully calculated for NH3 of method B3LYP!
Electronic part successfully calculated for NH3 of method B3LYP5!
Electronic part successfully calculated for NH3 of method B97-D3!
DFT method has not been calculated for NH3 of method B97M-V!
DFT method has not been calculated for NH3 of method B97M-rV!
Electronic part successfully calculated for NH3 of method BLYP!
Electronic part successfully calculated for NH3 of method BPBE!
Electronic part successfully calculated for NH3 of method CAM-B3LYP!
Electronic part successfully calculated for NH3 of method M06-2X!
Electronic part successfully calculated for NH3 of method M06-L!
Electronic part successfully calculated for NH3 of method M08-HX!
Electronic part successfully calculated for NH3 of method MGGA_MS2!
Electronic part successfully calculated for NH3 of method MN15!
Electronic part successfully calculated for NH3 of method MN15-L!
Electronic part successfully calculated for NH3 of method PBE!
Electronic part successfully calculated for NH3 of method PBE0!
Electronic part successfully calculated for NH3 of method SCAN!
Electronic part successfully calculated for NH3 of method SCAN0!
Electronic part successfully calculated for NH3 of method SPW92!
Electronic part successfully calculated for NH3 of method Slater!
Electronic part successfully calculated for NH3 of method TPSS!
Electronic part successfully calculated for NH3 of method mBEEF!
Electronic part successfully calculated for NH3 of method mPW91!
Electronic part successfully calculated for NH3 of method revM06-L!
Electronic part successfully calculated for NH3 of method wB97M-V!
Electronic part successfully calculated for NH3 of method wB97X-D!
Electronic part successfully calculated for NH3 of method wB97X-V!
Electronic part successfully calculated for NH3O of method B3LYP!
Electronic part successfully calculated for NH3O of method B3LYP5!
Electronic part successfully calculated for NH3O of method B97-D3!
Electronic part successfully calculated for NH3O of method B97M-V!

DFT method has not been calculated for SiO of method revM06-L!
DFT method has not been calculated for SiO of method wB97M-V!
DFT method has not been calculated for SiO of method wB97X-D!
DFT method has not been calculated for SiO of method wB97X-V!
DFT method has not been calculated for LiH of method B3LYP!
DFT method has not been calculated for LiH of method B3LYP5!
DFT method has not been calculated for LiH of method B97-D3!
DFT method has not been calculated for LiH of method B97M-V!
DFT method has not been calculated for LiH of method B97M-rV!
Electronic part successfully calculated for LiH of method BLYP!
Electronic part successfully calculated for LiH of method BPBE!
Electronic part successfully calculated for LiH of method CAM-B3LYP!
DFT method has not been calculated for LiH of method M06-2X!
DFT method has not been calculated for LiH of method M06-L!
DFT method has not been calculated for LiH of method M08-HX!
DFT method has not been calculated for LiH of method MGGA_MS2!
DFT method has not been calculated for LiH of method MN15!
DFT method has not been calculated for LiH of method MN15-L!
Electronic part successfully calculated for LiH of method PBE!
Electronic part successfully calculated for LiH of method PBE0!
Electronic part successfully calculated for LiH of method SCAN!
Electronic part successfully calculated for LiH of method SCAN0!
Electronic part successfully calculated for LiH of method SPW92!
Electronic part successfully calculated for LiH of method Slater!
Electronic part successfully calculated for LiH of method TPSS!
DFT method has not been calculated for LiH of method mBEEF!
Electronic part successfully calculated for LiH of method mPW91!
DFT method has not been calculated for LiH of method revM06-L!
DFT method has not been calculated for LiH of method wB97M-V!
DFT method has not been calculated for LiH of method wB97X-D!
DFT method has not been calculated for LiH of method wB97X-V!

In [34]:
data['LiH']

[{'name': 'LiH',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-5.6189, -5.6189, -11.6417],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, -5.6155, 5.6155],
  'quadrupoles_elec': [-4.1775229153, -4.1775229153, -17.73911130538479],
  'dipoles_elec': [-0.0, -0.0, -5.22323822665, 5.22323822665],
  'std_dev': [1.021949474692854, 1.021949474692854, 1.6521619860277266],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'BLYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-5.6429, -5.6429, -11.7088],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.0, -5.6037, 5.6037],
  'quadrupoles_elec': [-4.195366363300001,
   -4.195366363300001,
   -17.78899861208479],
  'dipoles_elec': [0.0, 0.0, -5.2185957491099995, 5.2185957491099995],
  'std_dev': [1.0241296748092987, 1.0241296748092987, 1.6568466445274552],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'BPBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-5.5172, -5.5172, -11.6644],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, -5.6947, 5.6947],
  'quadrupoles_elec': [-4.101911304400001,
   -4.101911304400001,
   -17.75598823328479],
  'dipoles_elec': [0.0, -0.0, -5.25439790641, 5.25439790641],
  'std_dev': [1.0126587905607694, 1.0126587905607694, 1.647256347200045],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-5.4383, -5.4383, -11.8447],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -5.7729, 5.7729],
  'quadrupoles_elec': [-4.0432509691, -4.0432509691, -17.89003713638479],
  'dipoles_elec': [0.0, -0.0, -5.2851641558699995, 5.2851641558699995],
  'std_dev': [1.0053918351941198, 1.0053918351941198, 1.651272017094816],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'mPW91',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-5.5704, -5.5704, -11.6684],
  'quadrupoles_off_diag': [-0.0, -0.0, -0.0],
  'dipoles': [-0.0, -0.0, -5.6473, 5.6473],
  'quadrupoles_elec': [-4.1414642808, -4.1414642808, -17.75896214128479],
  'dipoles_elec': [-0.0, -0.0, -5.23574931019, 5.23574931019],
  'std_dev': [1.017529395251066, 1.017529395251066, 1.6511885440112544],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'PBE0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-5.4238, -5.4238, -11.7385],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -5.7527, 5.7527],
  'quadrupoles_elec': [-4.0324705526, -4.0324705526, -17.811079878984792],
  'dipoles_elec': [-0.0, 0.0, -5.2772168638100005, 5.2772168638100005],
  'std_dev': [1.0040506153327133, 1.0040506153327133, 1.6468777597369384],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'SCAN',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-5.4331, -5.4331, -11.8887],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, -5.8403, 5.8403],
  'quadrupoles_elec': [-4.0393848887, -4.0393848887, -17.92275012438479],
  'dipoles_elec': [0.0, -0.0, -5.31168135809, 5.31168135809],
  'std_dev': [1.004911051872254, 1.004911051872254, 1.6484280703077845],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'SCAN0',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-5.3381, -5.3381, -11.9179],
  'quadrupoles_off_diag': [0.0, -0.0, -0.0],
  'dipoles': [0.0, -0.0, -5.8805, 5.8805],
  'quadrupoles_elec': [-3.9687545737, -3.9687545737, -17.94445965278479],
  'dipoles_elec': [0.0, -0.0, -5.32749725615, 5.32749725615],
  'std_dev': [0.9960866646155846, 0.9960866646155846, 1.6468836403350835],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-6.2786, -6.2786, -11.865],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -5.4571, 5.4571],
  'quadrupoles_elec': [-4.667994692200001,
   -4.667994692200001,
   -17.90512971948479],
  'dipoles_elec': [0.0, 0.0, -5.16091886713, 5.16091886713],
  'std_dev': [1.080277127893579, 1.080277127893579, 1.6767795644635424],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'SPW92',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-5.7462, -5.7462, -11.6715],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [-0.0, -0.0, -5.6093, 5.6093],
  'quadrupoles_elec': [-4.2721675374000005,
   -4.2721675374000005,
   -17.76126691998479],
  'dipoles_elec': [-0.0, -0.0, -5.2207989587900006, 5.2207989587900006],
  'std_dev': [1.033461118934815, 1.033461118934815, 1.6543187025146562],
  'spin_polarized': 0},
 {'name': 'LiH',
  'method': 'TPSS',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-5.3737, -5.3737, -11.6382],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, 0.0, -5.7265, 5.7265],
  'quadrupoles_elec': [-3.9952223549000005,
   -3.9952223549000005,
   -17.736509135884788],
  'dipoles_elec': [0.0, 0.0, -5.26690898995, 5.26690898995],
  'std_dev': [0.9994026159286357, 0.9994026159286357, 1.6432761909354094],
  'spin_polarized': 0}]

In [35]:
save(data)

b'\x1b[0;32mSaving updates to GitHub...\x1b[0m\n[master 6320558] save Mon, Aug  3, 2020  9:38:26 PM\n 672 files changed, 440695 insertions(+), 11108 deletions(-)\n create mode 100644 output/dft/20-07-28/BO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/BS_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CH3_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CN_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/CO2_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/F2_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/FCN_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2O_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/H2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HBO_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCCF_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCN_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCO_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_B97M-rV_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HCl_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HF_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNC_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNO_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HNS_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_Slater_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/HO2_revM06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_B3LYP5_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_B97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_BLYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_BPBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_M08-HX_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_TPSS_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_mBEEF_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_mPW91_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_wB97M-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_wB97X-D_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/He_wB97X-V_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_B97-D3_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_CAM-B3LYP_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_M06-2X_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_M06-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_MGGA_MS2_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_MN15-L_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_MN15_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_PBE0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_PBE_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_SCAN0_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_SCAN_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4_SPW92_aug-pc-4p.out\n create mode 100644 output/dft/20-07-28/LiBH4

In [492]:
wft_table.to_csv('wft_table_2.csv')

In [36]:
std_dev_dft = make_dft_table('std_dev', get_wft_species())

In [37]:
std_dev_dft.to_csv('dft_table.csv')

In [447]:
quadrupoles_table.loc['HCl']

method      Slater                      SPW92                   B97-D3       \
component       XX       YY       ZZ       XX       YY       ZZ     XX   YY
molecule
HCl       -14.4753 -14.4753 -10.7091 -14.1432 -14.1432 -10.4192    0.0  0.0

method         BLYP  ... CAM-B3LYP wB97X-D           wB97X-V            \
component   ZZ   XX  ...        ZZ      XX   YY   ZZ      XX   YY   ZZ
molecule             ...
HCl        0.0  0.0  ...       0.0     0.0  0.0  0.0     0.0  0.0  0.0

method    wB97M-V
component      XX   YY   ZZ
molecule
HCl           0.0  0.0  0.0

[1 rows x 81 columns]

In [488]:
data['HBO']

[{'name': 'HBO',
  'method': 'PBE',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0978, -11.0978, -19.9502],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-8.2509590506, -8.2509590506, -199.033869166212],
  'dipoles_elec': [-0.0, 0.0, -47.803149380650005, 47.803149380650005],
  'std_dev': [0.7676940913541018, 0.7676940913541018, 1.599319175331429],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'B97-D3',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 2,
  'quadrupoles': [-11.0084, -11.0084, -20.1871],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [-0.0, -0.0, -2.6504, 2.6504],
  'quadrupoles_elec': [-8.1844922068, -8.1844922068, -199.209998867512],
  'dipoles_elec': [-0.0, -0.0, -47.82868300712, 47.82868300712],
  'std_dev': [0.7645957011388437, 0.7645957011388437, 1.599357437857018],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'CAM-B3LYP',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 6,
  'quadrupoles': [-11.0795, -11.0795, -20.9574],
  'quadrupoles_off_diag': [-0.0, -0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.8692, 2.8692],
  'quadrupoles_elec': [-8.2373534215, -8.2373534215, -199.78269920061203],
  'dipoles_elec': [-0.0, 0.0, -47.91476555676, 47.91476555676],
  'std_dev': [0.7670608758436321, 0.7670608758436321, 1.5990000549598815],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'M06-2X',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 4,
  'quadrupoles': [-10.9943, -10.9943, -20.9452],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.9066, 2.9066],
  'quadrupoles_elec': [-8.1740091811, -8.1740091811, -199.773628781212],
  'dipoles_elec': [0.0, 0.0, -47.929479849980005, 47.929479849980005],
  'std_dev': [0.764105881831831, 0.764105881831831, 1.5965456400785158],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'M06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.7705, -10.7705, -19.8658],
  'quadrupoles_off_diag': [0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -2.5855, 2.5855],
  'quadrupoles_elec': [-8.0076190285, -8.0076190285, -198.97111970741202],
  'dipoles_elec': [0.0, -0.0, -47.803149380650005, 47.803149380650005],
  'std_dev': [0.7562888256149234, 0.7562888256149234, 1.597917307116611],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MGGA_MS2',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.9448, -10.9448, -20.0411],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [0.0, -0.0, -2.6413, 2.6413],
  'quadrupoles_elec': [-8.1372070696, -8.1372070696, -199.10145122551202],
  'dipoles_elec': [0.0, -0.0, -47.82510279139, 47.82510279139],
  'std_dev': [0.7623838117378936, 0.7623838117378936, 1.5974786577574538],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MN15',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 5,
  'quadrupoles': [-10.9999, -10.9999, -20.7016],
  'quadrupoles_off_diag': [0.0, 0.0, 0.0],
  'dipoles': [-0.0, 0.0, -2.7898, 2.7898],
  'quadrupoles_elec': [-8.1781726523, -8.1781726523, -199.59251778401202],
  'dipoles_elec': [-0.0, 0.0, -47.88352719094, 47.88352719094],
  'std_dev': [0.7643004575754223, 0.7643004575754223, 1.5995265127382026],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'MN15-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-11.1407, -11.1407, -20.7911],
  'quadrupoles_off_diag': [-0.0, 0.0, -0.0],
  'dipoles': [0.0, -0.0, -2.7518, 2.7518],
  'quadrupoles_elec': [-8.2828542139, -8.2828542139, -199.659058975512],
  'dipoles_elec': [0.0, -0.0, -47.868576839540005, 47.868576839540005],
  'std_dev': [0.7691764712015052, 0.7691764712015052, 1.6032909029431675],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'revM06-L',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 3,
  'quadrupoles': [-10.8551, -10.8551, -20.3839],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, 0.0, -2.6621, 2.6621],
  'quadrupoles_elec': [-8.070517182700002,
   -8.070517182700002,
   -199.35631514111202],
  'dipoles_elec': [0.0, 0.0, -47.833286141630005, 47.833286141630005],
  'std_dev': [0.7592532601510514, 0.7592532601510514, 1.6019203222123481],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'Slater',
  'basis': 'aug-pc-4p',
  'method_type': 'dft',
  'method_level': 1,
  'quadrupoles': [-11.4667, -11.4667, -20.1273],
  'quadrupoles_off_diag': [0.0, -0.0, 0.0],
  'dipoles': [0.0, -0.0, -2.5652, 2.5652],
  'quadrupoles_elec': [-8.5252277159, -8.5252277159, -199.165538942912],
  'dipoles_elec': [0.0, -0.0, -47.79516274556, 47.79516274556],
  'std_dev': [0.780349176234588, 0.780349176234588, 1.6034719398444037],
  'spin_polarized': 0},
 {'name': 'HBO',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVQZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-10.99948358996839,
   -10.99948358996839,
   -20.338388612318287],
  'quadrupoles_mp2': [-11.074939978926075,
   -11.074939978926075,
   -20.21229170588119],
  'quadrupoles_ccsd': [-10.967135530276206,
   -10.967135530276206,
   -20.70746585104695],
  'quadrupoles_hf': [-10.9055, -10.9055, -22.4865],
  'dipoles_ccsdt': [0.0, 0.0, -2.7215, 2.7215],
  'dipoles_mp2': [0.0, 0.0, -2.6652, 2.6652],
  'dipoles_ccsd': [0.0, 0.0, -2.8384, 2.8384],
  'dipoles_hf': [0.0, -0.0, -3.3361, 3.3361],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -48.09845816383, 48.09845816383],
  'dipoles_elec_mp2': [-0.0, -0.0, -45.73736490444, 45.73736490444],
  'dipoles_elec_ccsd': [-0.0, -0.0, -45.66922277648, 45.66922277648],
  'dipoles_elec_ccsdt': [-0.0, -0.0, -45.71521477855, 45.71521477855],
  'quadrupoles_elec_hf': [-8.1079884235, -8.1079884235, -200.919549881312],
  'quadrupoles_elec_mp2': [-8.233963150712022,
   -8.233963150712022,
   -199.22872832142545],
  'quadrupoles_elec_ccsd': [-8.153813022643163,
   -8.153813022643163,
   -199.59687890935086],
  'quadrupoles_elec_ccsdt': [-8.177863061018929,
   -8.177863061018929,
   -199.32247847113257],
  'std_dev_hf': [0.7610138173844152, 0.7610138173844152, 1.59625202059972],
  'std_dev_mp2': [0.7669030088941227, 0.7669030088941227, 1.8861683004554883],
  'std_dev_ccsd': [0.7631613301937429, 0.7631613301937429, 1.9015010125236143],
  'std_dev_ccsdt': [0.7642859908352804,
   0.7642859908352804,
   1.8906777700976238]},
 {'name': 'HBO',
  'method': 'ccsdT',
  'basis': 'aug-cc-pcVTZp',
  'method_type': 'wft',
  'quadrupoles_ccsdt': [-11.044071456105497,
   -11.044071456105497,
   -20.348476364810317],
  'quadrupoles_mp2': [-11.11408045858751,
   -11.11408045858751,
   -20.24161343990222],
  'quadrupoles_ccsd': [-11.010849124503912,
   -11.010849124503912,
   -20.70531379718963],
  'quadrupoles_hf': [-10.9126, -10.9126, -22.4967],
  'dipoles_ccsdt': [0.0, 0.0, -2.7075, 2.7075],
  'dipoles_mp2': [0.0, 0.0, -2.6584, 2.6584],
  'dipoles_ccsd': [0.0, 0.0, -2.8218, 2.8218],
  'dipoles_hf': [0.0, -0.0, -3.3371, 3.3371],
  'spin_polarized': 0,
  'dipoles_elec_hf': [0.0, -0.0, -48.098851594130004, 48.098851594130004],
  'dipoles_elec_mp2': [-0.0, -0.0, -45.740040230480005, 45.740040230480005],
  'dipoles_elec_ccsd': [-0.0, -0.0, -45.675753719460005, 45.675753719460005],
  'dipoles_elec_ccsdt': [-0.0, -0.0, -45.720722802750004, 45.720722802750004],
  'quadrupoles_elec_hf': [-8.1132671102, -8.1132671102, -200.92713334671203],
  'quadrupoles_elec_mp2': [-8.263063197109267,
   -8.263063197109267,
   -199.2505283562702],
  'quadrupoles_elec_ccsd': [-8.186313074538795,
   -8.186313074538795,
   -199.59527890680516],
  'quadrupoles_elec_ccsdt': [-8.211013113970948,
   -8.211013113970948,
   -199.3299784830921],
  'std_dev_hf': [0.761261505200414, 0.761261505200414, 1.5963612037237105],
  'std_dev_mp2': [0.768256988118897, 0.768256988118897, 1.8862500817568768],
  'std_dev_ccsd': [0.7646807491897142, 0.7646807491897142, 1.90067043334621],
  'std_dev_ccsdt': [0.7658334915059608,
   0.7658334915059608,
   1.890139835499417]}]

In [507]:
save(data)

b'\x1b[0;32mSaving updates to GitHub...\x1b[0m\n[master 8bc6862] save\n 1 file changed, 1 insertion(+), 1 deletion(-)\n'
File saved!

In [557]:
wft_table.loc[('Ar', 'CBS'), ('hf', 'XX')] = 0.694399

In [567]:
wft_table.index[wft_table.index.get_level_values('basis') == 'CBS']

MultiIndex([(   'Ar', 'CBS'),
            (   'Be', 'CBS'),
            (  'BeH', 'CBS'),
            ( 'BeH2', 'CBS'),
            (   'BF', 'CBS'),
            (  'BH3', 'CBS'),
            (   'BO', 'CBS'),
            (   'BS', 'CBS'),
            (  'C2H', 'CBS'),
            ( 'C2H2', 'CBS'),
            (  'CH3', 'CBS'),
            (  'CH4', 'CBS'),
            (   'CN', 'CBS'),
            (   'CO', 'CBS'),
            (   'F2', 'CBS'),
            (    'H', 'CBS'),
            (   'H2', 'CBS'),
            (  'H2O', 'CBS'),
            (  'HBO', 'CBS'),
            (  'HCN', 'CBS'),
            (   'He', 'CBS'),
            (   'HF', 'CBS'),
            (  'HNC', 'CBS'),
            ('LiBH4', 'CBS'),
            (   'Mg', 'CBS'),
            (    'N', 'CBS'),
            (   'N2', 'CBS'),
            (   'Na', 'CBS'),
            (   'Ne', 'CBS'),
            (  'NH3', 'CBS'),
            ( 'NH3O', 'CBS'),
            (   'O2', 'CBS'),
            (   'OF', 'CBS'),
            (   'OH', 'CBS'),
            (    'P', 'CBS'),
            (   'SF', 'CBS'),
            (  'HCl', 'CBS'),
            (   'NH', 'CBS'),
            (   'PH', 'CBS'),
            (  'SiO', 'CBS')],
           names=['molecule', 'basis'])

In [579]:
#make extrapolation in this cell
def extrapolate(dataframe):
    molecules = wft_table.index[wft_table.index.get_level_values('basis') == 'CBS']
    columns = wft_table.columns
    for m in molecules:
        for c in columns:
            if c[0] == 'hf':
                dataframe.loc[m, c] = dataframe.loc[(m[0], '5Z'), c]
            if dataframe.loc[(m[0], '5Z'), c] != 0:
                dataframe.loc[m, c] = ((dataframe.loc[(m[0], '5Z'), c] - dataframe.loc[(m[0], '5Z'), ('hf', c[1])]) * 125
                                       - (dataframe.loc[(m[0], 'QZ'), c] - dataframe.loc[(m[0], 'QZ'), ('hf', c[1])]) * 64) \
                                       / (125 - 64) + dataframe.loc[(m[0], 'CBS'), ('hf', c[1])]
            else:
                dataframe.loc[m, c] = ((dataframe.loc[(m[0], 'QZ'), c] - dataframe.loc[(m[0], 'QZ'), ('hf', c[1])]) * 64
                                       - (dataframe.loc[(m[0], 'TZ'), c] - dataframe.loc[(m[0], 'TZ'), ('hf', c[1])]) * 27) \
                                       / (64 - 27) + dataframe.loc[(m[0], 'CBS'), ('hf', c[1])]
    display(dataframe)

In [580]:
extrapolate(wft_table)

method                hf                           MP2                      \
component             XX        YY        ZZ        XX        YY        ZZ
molecule basis
Ar       5Z     0.694399  0.694399  0.694399  0.693865  0.693865  0.693865
         QZ     0.694477  0.694477  0.694477  0.694383  0.694383  0.694383
         TZ     0.694798  0.694798  0.694798  0.695628  0.695628  0.695628
         CBS    0.694399  0.694399  0.694399  0.693402  0.693402  0.693402
Be       5Z     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
...                  ...       ...       ...       ...       ...       ...
PH       CBS    0.818046  0.818046  1.038866  0.816495  0.835891  0.659105
SiO      5Z     0.737226  0.737226  1.611787  0.748302  0.748302  1.637564
         QZ     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         TZ     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         CBS    0.737226  0.737226  1.611787  0.759922  0.759922  1.664609

method              CCSD                     CCSD\(T\)
component             XX        YY        ZZ        XX        YY        ZZ
molecule basis
Ar       5Z     0.692929  0.692929  0.692929  0.693342  0.693342  0.693342
         QZ     0.693444  0.693444  0.693444  0.693885  0.693885  0.693885
         TZ     0.695001  0.695001  0.695001  0.695466  0.695466  0.695466
         CBS    0.692470  0.692470  0.692470  0.692854  0.692854  0.692854
Be       5Z     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
...                  ...       ...       ...       ...       ...       ...
PH       CBS    0.814809  0.835207  0.659002  0.815134  0.834454  0.658838
SiO      5Z     0.741260  0.741260  1.642066  0.744057  0.744057  1.638433
         QZ     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         TZ     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
         CBS    0.745493  0.745493  1.673833  0.751225  0.751225  1.666390

[160 rows x 12 columns]

In [582]:
wft_table.loc['H2O']

method           hf                           MP2                      \
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.749271  0.851185  0.808749  0.761483  0.858177  0.818400
QZ         0.749390  0.851298  0.808814  0.761942  0.858719  0.818847
TZ         0.749663  0.851517  0.809062  0.763070  0.859975  0.819952
CBS        0.749271  0.851185  0.808749  0.761126  0.857728  0.818000

method         CCSD                     CCSD\(T\)
component        XX        YY        ZZ        XX        YY        ZZ
basis
5Z         0.755686  0.856091  0.814369  0.757586  0.857536  0.816078
QZ         0.756221  0.856623  0.814826  0.758117  0.858078  0.816541
TZ         0.757602  0.858066  0.816155  0.759484  0.859548  0.817866
CBS        0.755249  0.855653  0.813957  0.757153  0.857086  0.815660

In [38]:
data.keys()

dict_keys(['AlF', 'Ar', 'Be', 'BeH', 'BeH2', 'BF', 'BH2', 'BH2F', 'BH3', 'BO', 'BS', 'C2H', 'C2H2', 'C2H3', 'CH2BH', 'CH2F', 'CH2NH', 'CH2-t', 'CH3', 'CH3BH2', 'CH3O', 'CH4', 'ClF', 'CN', 'CO', 'CO2', 'F2', 'FCN', 'FCO', 'H', 'H2', 'H2CN', 'H2O', 'HBO', 'HCCF', 'HCN', 'HCO', 'He', 'HF', 'HNC', 'HNO', 'HNS', 'HO2', 'LiBH4', 'Mg', 'Mg2', 'N', 'N2', 'N2H2', 'N2H4', 'Na', 'Na2', 'NaCl', 'Ne', 'NH2', 'NH2Cl', 'NH2F', 'NH2OH', 'NH3', 'NH3O', 'O2', 'O3', 'OF', 'OH', 'P', 'S2H2', 'SF', 'SH', 'HCl', 'NH', 'PH', 'SiO', 'LiH'])

In [42]:
std_dev_dft.loc['NH']

method       Slater                         SPW92                      \
component        XX        YY        ZZ        XX        YY        ZZ
molecule
NH         0.790495  0.790495  1.000869  0.780677  0.780677  0.989187

method       B97-D3                         BLYP  ... CAM-B3LYP   wB97X-D  \
component        XX        YY        ZZ       XX  ...        ZZ        XX
molecule                                          ...
NH         0.769918  0.769918  0.985776  0.77911  ...  0.985582  0.769121

method                          wB97X-V                       wB97M-V  \
component        YY        ZZ        XX        YY        ZZ        XX
molecule
NH         0.769121  0.980772  0.774492  0.774492  0.984266  0.777988

method
component        YY        ZZ
molecule
NH         0.777988  0.986403

[1 rows x 81 columns]